### ISSUE TITLE
[delegatesFocus] container with focusout handler sets focus incorrectly on child

### ISSUE THREAD

**Issue by gonzalocordero** [salesforce/lwc#1031]
### Description

Given a container with a `onblur` handler and `tabindex=0`
and 
A child component with `delegatesFocus=true` and `tabindex=-1` on the host

Changing the `tabindex` property on the container dynamically on the blur handler, will then make the child focusable. 

#### Steps to Reproduce
Go to https://playground.lwcjs.org/projects/E3OKiG1Qn/4/edit
First tab: Focus will be on the first button
Second tab: Focus will be on the div element
Third tab: 
- Actual - the button inside buttonIcon gets the focus. 
- Expected - focus on buttonIcon should be ignored since it was `tabindex=-1` 

### Version
LWC: 0.35.1

**Comment by ekashida** [comment]
This bug is no longer reproducible in 1.0.2
