### ISSUE TITLE
LightningElement.addEventListener and .removeEventListener doesn't provide consistent restrictions

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1043]
### Description

`LightningElement.addEventListener` and `LightningElement.removeEventListener` apis enforces extra restrictions with synthetic shadow DOM than with native shadow. We need to make sure the APIs enforce the same restrictions in both modes.

More details https://github.com/salesforce/lwc/pull/1025#issuecomment-461057640

### Version
- LWC: 0.35.5

**Comment by caridy** [comment]
I think this is now solved, but we will have to validate it and re-enable those tests.

**Comment by ravijayaramappa** [comment]
Tests being enabled under https://github.com/salesforce/lwc/pull/1674
