### ISSUE TITLE
ShadowRoot.cloneNode should be blocked in production mode 

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1065]
### Description

By specification `ShadowRoot` should throw when invoking `Node.CloneNode` on it, this behavior should be consistent in dev and prod mode: https://dom.spec.whatwg.org/#dom-node-clonenode

```js
const elm = createElement('x-slotted', { is: slotted });
elm.shadowRoot.cloneNode();
// dev mode - throws an Error
// prod mode - pass
```

### Version
- LWC: 0.35.7

**Comment by caridy** [comment]
I believe this is now fixed, but we should validate it.
