### ISSUE TITLE
Compiler incorrectly errors depending on the order to api decorators

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1113]
### Description

In some specific cases, the LWC compiler throws when applying an `api` decorators to getter/setters.

```js
import { LightningElement, api } from 'lwc';

export default class Test extends LightningElement {
    @api
    get two() {}
    set two(value) {}

    get three() {}
    @api
    set three(value) {}
   //  ^ LWC1112: @api get three and @api set three detected in class declaration. Only one of the two needs to be decorated with @api.
}
```

This bug appears to be related to the application order to the `api` decorator. In the above code snippet, moving the `api` decorator right before the getter definition make the compiler pass.

### Version
- LWC: 0.37.0

**Comment by AllanOricil** [comment]
Regression? https://github.com/salesforce/lwc/issues/2406
