### ISSUE TITLE
disconnectedCallback isn't invoked on components slotted into another component

### ISSUE THREAD

**Issue by midzelis** [salesforce/lwc#1118]
### Description
The LWC playground app is using lwc:dom=manual for monaco editor, and for the iframe preview component. The disconnectedCallback isn't invoked for fiddle:editor component, and it is leaking a listener on a Redux store, and a whole monaco editor, causing problems with duplicate models, and memory leaks. 

#### Steps to Reproduce
Load https://tools-playground-beta-dev.herokuapp.com/projects/edit
Click New
Notice that the disconnectedCallback() method in fiddle-editor isn't invoked. 

#### Expected Results

disconnectedCallback() is invoked
#### Actual Results

disconnectedCallback() is NOT invoked

### Version
- LWC: 37.0

**Comment by ravijayaramappa** [comment]
GUS work item: W-6025676
