### ISSUE TITLE
Composed and non-bubbling events doesn't invoke host event listeners

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1138]
### Description

When dispatching a composed and non-bubbling event in a shadow tree, the event should invoke all the host elements on its path.

More detail: https://github.com/whatwg/dom/issues/742

### Browsers Affected
All

### Version
- LWC: 0.37.0

**Comment by ravijayaramappa** [comment]
GUS work item: W-5983653

**Comment by caridy** [comment]
working on this.

**Comment by ekashida** [comment]
Note that every node returned by `composedPath()` receives the event during the capture phase, but only host elements and elements that share the same shadow tree as the original event target receive the event during the bubble phase.

**Comment by ravijayaramappa** [comment]
synthetic-shadow is in maintenance mode, this won't be fixed.
