### ISSUE TITLE
Event non dispatched from within a LWC shadow tree are not patched

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1141]
### Description

Today the engine checks if an event comes for an LWC shadow tree before patching the event. When dispatching an event on the root LWC element, the event is not patched. This is an issue in compat because invoking `composedPath()` on the dispatched event throw an exception

```js
const elm = createElement('x-foo', { is: Foo });
document.body.appendChild(elm);

elm.addEventListener('test', evt => {
    evt.composedPath();
    // ^ throws here
});
```

### Browsers Affected
IE11

### Version
- LWC: 0.37.0

**Comment by caridy** [comment]
This should be fixed by now. @pmdartus you can validate and close?

**Comment by ravijayaramappa** [comment]
GUS work item: W-5983905
