### ISSUE TITLE
[Event retargeting] event.target is retargeted when accessed aysnchronously

### ISSUE THREAD

**Issue by ravijayaramappa** [salesforce/lwc#1160]
### Description
event.target is retargeted when accessed asynchronously.
The root cause for this is that our retargeting logic relies on event.currentTarget. event.currentTarget is null when accessed asynchronously. As a side effect, our retargeting logic gets triggered.

#### Steps to Reproduce
https://playground.lwcjs.org/projects/kkLHEyzqh/3/edit

#### Expected Results
Same value for event.target whether accessed synchronously or async

https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000006SEIvIAO/view

**Comment by caridy** [comment]
@ravijayaramappa can you validate this?

**Comment by ravijayaramappa** [comment]
Yes, this is the same behavior as native shadow. Here's a snippet to test the same behavior in native shadow.
```js
(() => {
    const inTheShadow = document.createElement('span');
    inTheShadow.innerHTML = 'Click Me';
    inTheShadow.addEventListener('click', function(event){
        console.log('event target outside setTimeout', event.target);
        setTimeout(() => {
            console.log('event target inside setTimeout', event.target);
        })
        });
    const div = document.createElement('div');
    div.attachShadow({mode: 'open'});
    div.shadowRoot.appendChild(inTheShadow);
    document.body.appendChild(div);
})()
```
