### ISSUE TITLE
Remove proxy-concat polyfill from the engine

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1178]
Today the engine comes with a polyfill fixing a [safari bug](https://bugs.webkit.org/show_bug.cgi?id=184267) related to `Array.prototype.concat`. This bug has been fixed for almost a year now and has been shipped as into for Safari 11.

We should evaluate the removal of this polyfill based on internal browser usage.

**Comment by caridy** [comment]
@Gr8Gatsby can you double check the numbers for safari, to see if we can remove this polyfill now? @pmdartus can you validate that we are good on this one?

**Comment by Gr8Gatsby** [comment]
95.5% of Safari users are 11 or higher (12).

**Comment by nolanlawson** [comment]
Fixed in https://github.com/salesforce/lwc/pull/2453
