### ISSUE TITLE
NPM installation of @lwc/compiler throws subdependency warnings

### ISSUE THREAD

**Issue by muenzpraeger** [salesforce/lwc#1218]
### Description

When running an npm install/yarn install a subdependency throws warnings on the console. While this doesn't seem have to impact functionality it just doesn't look that we're using a 4 year old version (cssnano in this case, see [here](https://www.npmjs.com/package/cssnano).

#### Steps to Reproduce

1. Create new npm/yarn project.
2. Add @lwc/compiler@next (also older versions) as dependency.
3. Run `npm init/yarn install`.

#### Expected Results

No warning for dependencies is shown.

#### Actual Results

These two warnings are shown:

`@lwc/style-compiler > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.`

`@lwc/style-compiler > cssnano > postcss-merge-rules > postcss-selector-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.`

### Browsers Affected
Not applicable

### Version
Any version of @lwc/style-compiler

**Possible Solution**

Dependency upgrade

**Additional context/Screenshots**

Not applicable

**Comment by caridy** [comment]
@muenzpraeger can you double check on 1.x? I think this is gone now.

**Comment by muenzpraeger** [comment]
1.0.x or 1.x @caridy? From the latter is no version published yet.

**Comment by caridy** [comment]
try 1.0.2

**Comment by muenzpraeger** [comment]
It's fixed in the current `1.0.2.x` as well as `1.1.0-alpha`. Only the `js-yaml` dependencies are throwing warnings now.
