### ISSUE TITLE
Should compiler attempt to validation HTML attributes?

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1219]
### Description

Today the LWC compiler tries to validate attributes attached to standard HTML elements. The LWC compiler maintains a list of known attributes for all the standard elements. While this approach prevents attribute misspelling issues, it also prevents developers to experiment with emerging/unstable HTML APIs. 

IMO, the LWC compiler should not report an error on unknown HTML attributes. Standard HTML attribute validation should be delegated to a linter for example.

**Comment by jodarove** [comment]
Fixed in https://github.com/salesforce/lwc/pull/1247
