### ISSUE TITLE
`isNodeFromTemplate` return false for the shadowRoot node itself

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#1250]
### Description

This is a semantic issue: 

* shadowRoot is not accessible by querying the DOM, and it is only accessible by calling `elm.shadowRoot`, which is disabled it locker, it seems to be fine that when passing such node into `isNodeFromTemplate` method, it should return `true` instead of `false`.

/cc @jfparadis @ravijayaramappa

**Comment by ekashida** [comment]
This API will likely never change to avoid issues in legacy code. Please reopen if this is not the case.
