### ISSUE TITLE
[engine] refactor unit tests into karma integration tests

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#1295]
Many of our unit tests are sensitive to compiler changes because they rely on non-public APIs. They should be refactored to only use public APIs.

**Comment by ekashida** [comment]
@ravijayaramappa can you confirm this is no longer the case?

**Comment by ekashida** [comment]
Discussed with @ravijayaramappa and we agreed this should stay open until we refactor all tests that use `compileTemplate`.

**Comment by ravijayaramappa** [comment]
We no longer have tests that use compileTemplate.
