### ISSUE TITLE
Check that anything in `track` or `wire` is correctly defined in the prototype

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#1302]
https://github.com/salesforce/lwc/blob/37f8cf2a3461da54d8c5a9cdfe84bc949758097a/packages/%40lwc/engine/src/framework/decorators/register.ts#L108
https://github.com/salesforce/lwc/blob/37f8cf2a3461da54d8c5a9cdfe84bc949758097a/packages/%40lwc/engine/src/framework/decorators/register.ts#L120

@diervo to add context

**Comment by nolanlawson** [comment]
Closing old issues, please reopen if this is still on the docket.
