### ISSUE TITLE
[engine] add/removeEventListener should be patched on EventTarget.prototype

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#1305]
https://github.com/salesforce/lwc/blob/37f8cf2a3461da54d8c5a9cdfe84bc949758097a/packages/%40lwc/synthetic-shadow/src/polyfills/event-listener/polyfill.ts#L91

**Comment by ravijayaramappa** [comment]
This work has been completed in https://github.com/salesforce/lwc/pull/1572
