### ISSUE TITLE
Lightning-checkbox-group non trackable property warning

### ISSUE THREAD

**Issue by az-oolloow** [salesforce/lwc#1323]
### Description

In the off-the-shelf sample of lightning-checkbox-group, we get the following warnings in the console:

>  Property "_value" of [object:vm undefined (0)] is set to a non-trackable object, which means changes into that object cannot be observed.

#### Steps to Reproduce
Create a <lightning-checkbox-group> with `value` set to a `@track` annotated property:

https://developer.salesforce.com/docs/component-library/tools/playground/4ceb14a5d13175b0ed34521e347eee448ba84f45/edit

Observe warning in the console

#### Expected Results
No warning in the console

#### Actual Results
Warning in the console

### Browsers Affected
Chrome 73.0.3683.103 (Official Build) (64-bit)

### Version
- LWC: x.x.x *Unsure, using official prod playground*

**Comment by caridy** [comment]
@ekashida I believe this was solves already with 1.0. Can you confirm?

@midzelis I know you haven't update the playground yet to use 1.0, but can you link this issue to the upgrade?

**Comment by ekashida** [comment]
@az-oolloow Thanks for bringing this to our attention!

We removed this in #1003 but that change is available starting in Summer '19 (220). It looks like https://developer.salesforce.com/docs/component-library/tools/playground is still on the Spring '19 (218) version of LWC (v0.34.7).
