### ISSUE TITLE
Error: Email required

### ISSUE THREAD

**Issue by bk107** [salesforce/lwc#1324]
Cannot run lwc-create-app due to the following error:

![image](https://user-images.githubusercontent.com/22213993/58683849-5a8bc600-8376-11e9-9f26-0715438e7eb7.png)

I executed "npx lwc-create-app my-app" and it threw the mentioned error.

**Comment by FabienTaillon** [comment]
You should try posting in the [lwc-create-app repo](https://github.com/muenzpraeger/lwc-create-app) directly.

**Comment by Gr8Gatsby** [comment]
https://github.com/muenzpraeger/lwc-create-app/issues/5 - duplicate issue opened in lwc-create-app repo.
