### ISSUE TITLE
[delegatesFocus] Shadow DOM semantics for focus method

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#1327]
- Which internal element should be focused? Is it enough to implement something that's "good enough" like we did for sequential focus navigation? If the behavior eventually changes, would that be considered as a breaking change?
- Elements that aren’t rendered should not be attempted to focus() (e.g., [hidden], display:none, visibility:hidden, etc)
- Elements with the `hidden` attribute have a computed style attribute of `display:none` so we can just use that check to filter
- Bug? Chrome doesn’t transfer focus to `span[tabindex=0]` but it does transfer focus to `span[tabindex=-1]`
- Safari doesn’t even attempt to transfer focus

**Comment by caridy** [comment]
Is this really on LightningElement or on the bridge?

**Comment by ekashida** [comment]
I guess it should be part of our patch for HTMLElement?

**Comment by caridy** [comment]
Yes, that's the BridgeElement. Thanks for clarifying.

**Comment by sfdciuie** [comment]
>>> Which internal element should be focused? Is it enough to implement something that's "good enough" like we did for sequential focus navigation? If the behavior eventually changes, would that be considered as a breaking change?

Perhaps it should be the first element that's not hidden or disabled, has [1]: tabindex of either -1 or 0, and [2] has the `autofocus` attribute on it, and otherwise focus on the first one that has [1].

**Comment by ekashida** [comment]
@sfdciuie that sounds like a good start but my concern is that what is and isn't focusable isn't well defined so I'd rather let component authors explicitly define what their focus method does today so that we don't break any existing functionality tomorrow.

**Comment by ekashida** [comment]
Notes from a recent spike

- There are two settings that affect sequential focus navigation in MacOS: 1) enabling full keyboard access in the keyboard system preferences and 2) toggling "press tab to highlight each item on a webpage" in Safari preferences.
- Enabling full keyboard access in the keyboard system preferences allows the user to focus on non-editable form controls like buttons and checkboxes during sequential focus navigation. Note that this does not include links.
- Enabling "press tab to highlight each item on a webpage" in Safari preferences allows the user to focus on non-editable form controls as well as links.
- By default, links with href attributes are not sequentially focusable in Safari, even if it has tabindex=0.
- Non-editable form controls (checkbox, button) are not click focusable in Safari
	- Interestingly, clicking a such a form control that already has focus, it will lose focus.
- What is click focusable depends on the UA.


Programmatic Focus

A programmatically focusable element is either click focusable or sequentially focusable. We cannot know what is click focusable or sequentially focusable a priori, so it is impossible to correctly polyfill programmatic focus delegation without knowing which UA and how the user's system is configured.

Click Focus

Correctly polyfilling the click focus delegation when the user clicks on the host element is impossible since we lack the ability to determine where to forward the focus. Even if we test all the elements using focus() in the shadow, we would need to differentiate between Chrome and Safari if the candidate element is a non-editable form control. This does, however, seem like an edge case. If we really need to do this, it seems the best we could do is to invoke focus() on the host element, assuming we get programmatic focus to be good enough.
