### ISSUE TITLE
Enable default tabIndex test

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#1330]
These tests currently fail for Chrome and IE11: https://github.com/salesforce/lwc/commit/5e2678c345fb947d010bf1b489c2b5856b09f292#diff-a114ad0a33ab52546686d320d3393d39

- Chrome returns `0` when delegating focus and `-1` otherwise
- IE11 seems to have a `tabIndex` value of `0` in all cases (tested `x-foo`, `span`, `a`, `div`)

**Comment by ekashida** [comment]
These tests don't seem useful, maybe we can just remove them?

**Comment by caridy** [comment]
ok
