### ISSUE TITLE
Broken Link in several Readme files

### ISSUE THREAD

**Issue by girishla** [salesforce/lwc#1333]
Several Readme files have broken docs links - for example the wire-service package readme has a broken link to"docs/proposals/data-service.md". If those docs are public, can they be re-pointed please ?

**Comment by caridy** [comment]
thanks @girishla, yes, we moved all RFCs into its own repo very recently (https://github.com/salesforce/lwc-rfcs/tree/master/text)... and I suspect that there will be quite few broken links pointing to those docs.

The one in question is here: https://github.com/salesforce/lwc-rfcs/blob/master/text/0000-data-service.md

We will fix the links.
