### ISSUE TITLE
docs missing link bug

### ISSUE THREAD

**Issue by xgqfrms** [salesforce/lwc#1338]
# docs missing link bug

![image](https://user-images.githubusercontent.com/7291672/58844436-c9845a00-86a9-11e9-82ab-a248f61ec3aa.png)

https://lwc.dev/guide/html_templates

![image](https://user-images.githubusercontent.com/7291672/58844417-ae194f00-86a9-11e9-8d8d-eab99fe941b1.png)

https://lwc.dev/guide/reference_directives

**Comment by xgqfrms** [comment]
# the right link

https://lwc.dev/guide/reference#html-template-directives

**Comment by caridy** [comment]
docs issues should go here: https://github.com/salesforce/lwc-docs/issues/new

**Comment by diervo** [comment]
We haven't open sourced the docs yet where this issue should go (fyi @caridy), give us a week
@xgqfrms we will be merging your changes shortly, FYI @jbleyleSF
