### ISSUE TITLE
Docs say "npm install lwc" but NPM's lwc is something else

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce/lwc#1345]
The docs show:

![image](https://user-images.githubusercontent.com/415690/59113438-e4bac800-893c-11e9-917d-664cce925a36.png)

but after installing I realized this is NOT lwc but something from someone else: https://www.npmjs.com/package/lwc points to https://github.com/neo/npm-lwc

**Comment by mattgoldspink** [comment]
It's also worth noting the comment here: https://www.npmjs.com/package/@lwc/engine says 

```
@lwc/engine is a private package that handles the runtime for LWC. Don't use this package directly; instead, use lwc.
```
which should probably also be corrected to point to something else (I'm not sure what though).

**Comment by diervo** [comment]
@mattgoldspink thanks matt a PR was merged yesterday, will land in the doc site shortly.
For the other issue, I'm working on making lwc the package with all the things so @caridy  is happy :)

Thanks a lot for the feedback.
Will close this once we fix this items.

**Comment by caridy** [comment]
yes @diervo, make my happy!

**Comment by diervo** [comment]
We should be good now.
