### ISSUE TITLE
npx lwc-create-app my-app 

### ISSUE THREAD

**Issue by testosteronicV** [salesforce/lwc#1347]
I get error when i run - $npx lwc-create-app my-app

Node - 10.12.0
OS -Ubuntu 18.04

npx: installed 372 in 51.707s
Error: Cannot find module './generators/CreateGenerator'
    at Create.run (~/.npm/_npx/15696/lib/node_modules/lwc-create-app/lib/index.js:12:30)
    at Create._run (~/.npm/_npx/15696/lib/node_modules/lwc-create-app/node_modules/@oclif/command/lib/command.js:44:31)

**Comment by caridy** [comment]
cc @muenzpraeger, this one probably belongs to https://github.com/muenzpraeger/lwc-create-app/issues/new/choose

**Comment by muenzpraeger** [comment]
This has been already fixed and will be released latest tomorrow.

https://github.com/muenzpraeger/lwc-create-app/pull/49

**Comment by muenzpraeger** [comment]
Just released with https://github.com/muenzpraeger/lwc-create-app/pull/52
