### ISSUE TITLE
implement adopted stylesheet

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#1364]
as today, we have a forking logic between native shadow and synthetic shadow.

for native, the engine insert a cloned StyleElement as the first node of the shadow.
for synthetic, the engine insert a StyleElement in the header.

## Proposal

once adopted stylesheet is available in all modern browsers, we should add the polyfill into synthetic shadow to pipe it as StyleElement in the header, and remove all the logic from engine.

**Comment by nolanlawson** [comment]
This is done.
