### ISSUE TITLE
SVG Linear Gradient Tag throwing error - 1078: has no matching closing tag

### ISSUE THREAD

**Issue by AlexBryner** [salesforce/lwc#1367]
### Description

Using a Linear Gradient Tag within SVGs throws an error for missing a matching tag.  The tags can be applied to the svg with javascript, but there are errors thrown when the template is compiled with SVG Linear Gradient tags.

## Playground Link
https://developer.salesforce.com/docs/component-library/tools/playground/lq-8iCl3B/9/edit

**Comment by caridy** [comment]
Thanks for the report @AlexBryner, this seems to be a problem in the compiler. I don't think we have provision for special tagNames like `linearGradient`, which happens to be camel cased. That's not very common in HTML, I don't recall any other element with similar form.

I suspect we can add the exception in the compiler to allow such tagName. /cc @jodarove @ravijayaramappa

**Comment by quinnmcphail** [comment]
Hi there! Do you mind if I give this a shot?

**Comment by caridy** [comment]
@quinnmcphail go for it! If you need guidance, just let us know... @ravijayaramappa and @ekashida are now experts on the compiler.

**Comment by quinnmcphail** [comment]
It looks like the [parse5 package](https://github.com/inikulin/parse5) used to parse the HTML for LWC doesn't like a lot of SVG tags.

When I ran a snippet of SVG code [through the parse5 playground](https://astexplorer.net/#/gist/7a7d3160c85930137191a0cba52b9590/2e58de84391e4a3014b8babfc09ad559bb228adb), it picked up the `startTag` location for all of the tags but not the `endTag` location.

It doesn't matter if the tags are camel-cased or not, the `<stop>` and `<circle>` tags I used didn't have `endTag` locations present.

I guess this has to do with parse5 adhering to the HTML spec and not the SVG spec, so those tags might not work correctly.

I did manage to include an SVG file in an `<img>` tag and it worked, although, I had to make sure that the `xmlns` SVG attribute was set.

**Comment by diervo** [comment]
Let me talk to Ivan the owner of parse5 see if he would be ok introducing this changes.

**Comment by dahnielkim** [comment]
Are there any updates to this issue? We are running into a similar issue with other tagNames like `animateTransform` if it's embedded inside of a svg tag.

**Comment by diervo** [comment]
So we have a forked version of parse5 so we can technically add some of this there.
We are waiting for a report from the security team making sure we are whitelisting all the dangerous ones, I hope we can add those two soon.

**Comment by saoirse-zee** [comment]
Running into the same issue with svg tags like `feGaussianBlur`. Thanks for your work on this!

**Comment by narendrasinghrathore** [comment]
So is it being resolved, or need some tweaks @diervo @caridy

**Comment by diervo** [comment]
If something still missing file a new issue.

**Comment by LBSInteractive** [comment]
Hello @diervo, Is the problem resolved?

**Comment by diervo** [comment]
This is issue its been close because the fix has been implemented.

While you can't use unary tags since we have to change the html parser which is tricky and time consuming, you can use any filter tag as long as you close the tag like you would do for any non-unary element.

Here is a contrived example that compiles an works:

```html
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">

    <filter id="MyFilter" filterUnits="userSpaceOnUse" x="0" y="0" width="200" height="120">
        <desc>Produces a 3D lighting effect.</desc>
        <feGaussianBlur in="SourceAlpha" stdDeviation="4" result="blur"></feGaussianBlur>
        <feOffset in="blur" dx="4" dy="4" result="offsetBlur"></feOffset>
        <feSpecularLighting in="blur" surfaceScale="5" specularConstant=".75"
                            specularExponent="20" lighting-color="#bbbbbb"
                            result="specOut">
          <fePointLight x="-5000" y="-10000" z="20000"></fePointLight>
        </feSpecularLighting>
        <feComposite in="specOut" in2="SourceAlpha" operator="in" result="specOut"></feComposite>
        <feComposite in="SourceGraphic" in2="specOut" operator="arithmetic"
                     k1="0" k2="1" k3="1" k4="0" result="litPaint"></feComposite>
        <feMerge>
          <feMergeNode in="offsetBlur"></feMergeNode>
          <feMergeNode in="litPaint"></feMergeNode>
        </feMerge>
      </filter>
      </svg>
