### ISSUE TITLE
[compiler] compiler doesn't validate public properties with underscore names

### ISSUE THREAD

**Issue by apapko** [salesforce/lwc#1369]
### Description
The following @api properties are legal in LWC class today:
```js
import { LightningElement, api } from 'lwc';

export default class App extends LightningElement {
    @api myProp;
    @api my_public'
}
```
Per HTML standard, the attribute names must be all lower case and may only contain hyphens, which means that in order for the component author to pass _**myProp**_ via template, the property name must become hyphenated:
```html
<c-app my-prop="foo"> <c-app/>
``` 

There is inconsistency in syntax between class property _myProp_ and its equivalent html _my-prop_, but user can still pass down the value. However, there is no way to pass down a property to match class @api with underscore in its name - **my_public**, as underscore is not a legal html attribute character.

**Actual**: User has no ability to pass down a property via template to match a component api with an underscore in its name.

**Expected**: Add compile time validation to disallow public property syntax that cannot meet HTML standard for attribute naming. In other words, prevent underscores in public properties.

**Comment by caridy** [comment]
I'm not sure what the problem is. `_` is perfectly valid attribute name as far as I can tell, e.g.:

![image](https://user-images.githubusercontent.com/38969/59958283-1e79eb80-9472-11e9-8b86-8abdc1626b90.png)

**Comment by apapko** [comment]
@caridy the issue is in component update sequence, specifically in the following dev mode assertion:
```js
assert.fail(`Unknown public property "${key}" of element <${sel}>. This is likely a typo on the corresponding attribute "${getAttrNameFromPropName(key)}".`);
```
Here is the playground sample: https://playground.lwcjs.org/projects/zTgbpmHbH/20/edit

**Comment by caridy** [comment]
ok, then this is a bug in the compiler. I have looked into the compiled code, and I see this:

```js
    function tmpl$1($api, $cmp, $slotset, $ctx) {
      const {
        c: api_custom_element,
        h: api_element
      } = $api;
      return [api_element("div", {
        key: 2
      }, [api_custom_element("c-child", _cChild, {
        props: {
          "propUnderscored": "foo"
        },
        key: 3
      }, [])])];
    }
```

For some reason, the compiler is assuming that `prop_underscored` should be passed down as `propUnderscored`, which is wrong... but other than that, engine and everything else is fine.

Btw, your playground is wrong, it was passing `prop-underscored` instead of `prop_underscored` in the app template.
