### ISSUE TITLE
Format conversion between returned Data Service objects and Apex objects

### ISSUE THREAD

**Issue by shocks13** [salesforce/lwc#1380]
**Is your feature request related to a problem? Please describe.**
I've come across this issue when using both apex and lightning data service to return records. Basically the objects returned from Apex and much simpler than that of data service and so sometimes cause issues when trying to render attributes onscreen. For example onload I call an apex method to return a list of objects that displays the name field using {contact.name}

Then lets say I update that record on the screen using data service and put the updated record back into the variable contact. This is where the issues arrises as {contact.name} is no longer sufficient and its needs to change to {contact.fields.name.value}

**Describe the solution you'd like**
I'd like a conversion function which can convert either type to the other or vice versa

**Describe alternatives you've considered**
A getter on the frontend to do a check to see whats accessible is a good workaround for now but leads to lots of extra lines if multiple fields are to have getters

**Comment by kevinv11n** [comment]
I’m not following exactly what you’re looking for. Can you share some minimal code that demonstrates the issue?

**Comment by shocks13** [comment]
Sure thing, so basically I call some apex code like so:

`relatedFieldMappings({
                recordId: this.bulkUpload.id
            })
            .then(result => {
                console.log('result: ', result);
                this.fieldMappings = result;
            })
            .catch(error => {
                console.log('error: ', error);
            });`

and I render this using the following:

`<template for:each={fieldMappings} for:item="fieldMapping">
                            <c-field field-map={fieldMapping} onfieldmapped={handleFieldMapped} onfieldunmapped={handleFieldUnmapped} key={fieldMapping.Id}></c-field>
                        </template>`

the field component looks like this

`<template>
    <th data-label="Field" scope="row">
        <div class="slds-truncate" title={labelField}>
            {labelField}
        </div>
    </th>
    <td data-label="Mapping" ondrop={onDrop} ondragover={onDragOver}>
        <lightning-layout>
            <lightning-layout-item size="10">
                <div class="slds-truncate" title="Title">
                    {mappingField}
                </div>
            </lightning-layout-item>
            <template if:true={mappingField}>
                <lightning-layout-item size="2">
                    <lightning-button-icon onclick={deleteMapping} icon-name="utility:close" alternative-text="Delete"></lightning-button-icon>
                </lightning-layout-item>
            </template>
        </lightning-layout>
    </td>
</template>`

When I click on the close/delete button on that individual entry I want to update it so it doesn't contain anything in the "Mapping__c" attribute like so:

`deleteMapping = () => {
        console.log('deleteMapping');
        let fields = {};
        fields[FM_ID_FIELD.fieldApiName] = this.fieldMap.Id;
        fields[FM_MAPPING_FIELD.fieldApiName] = '';
        let record = {
            fields
        };
        updateRecord(record)
            .then((updatedRecord) => {
                console.log('updatedRecord: ', updatedRecord);
                //Field Mapping record has been updated correctly
                this.dispatchEvent(
                    new ShowToastEvent({
                        title: 'Success',
                        message: 'Mapping Is Updated',
                        variant: 'success',
                    })
                );
                //Let header list know that a field has been unmapped and therfore add it
                //
                //
                console.log('this.fieldMap: ', JSON.stringify(this.fieldMap));
                this.dispatchEvent(
                    new CustomEvent('fieldunmapped', {
                        detail: this.fieldMap.Mapping__c
                    })
                );
                this.fieldMap = updatedRecord;
            })
            .catch(error => {
                console.log('error: ', error);
            });
    }`

The problem is on this line "this.fieldMap = updatedRecord;"

It's because this.fieldMap contained an object from an apex method previously and subsequently, all my references are incorrect when I add an object from dataService object to it.

Apex Object = {this.fieldMapping.Mapping__c}
DataServiceObject = {this.fieldMapping.fields.Mapping__c.value}

Really hope that makes sense.

**Comment by kevinv11n** [comment]
Thanks for the code samples.

I don't believe it's possible to support converting to/from [Apex SObjects](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_sobject.htm) and [UIAPI Records](https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_responses_record.htm#ui_api_responses_record) in all cases. Records contains some additional data (eg [record type info](https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_responses_record_type_info.htm#ui_api_responses_record_type_info)), SObjects can be transformed (eg due to SOQL aliasing, arbitrary Apex logic).

An alternative to consider for you use case: convert both Apex SObjects and UIAPI RecordRepresentations to a common shape which your components work with.
