### ISSUE TITLE
[delegatesFocus] Handle the case where the next tab should cause the document to lose focus

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#1387]
### Description

In the current implementation, we blur the active element if there is no remaining focusable element. At this point, the active element is `document.body` and the next element to focus depends on how the browser implements sequential focus navigation.

We should allow focus to cleanly exit the current synthetic shadow so that the next tab will not cause focus to re-enter the synthetic shadow. The suggested fix is to append a focusable element to the document, focus that, and remove it. Preliminary tests saw that this worked but ended up trapping focus within the document.

#### Steps to Reproduce

https://playground.lwcjs.org/projects/_MRFFZYz8/1/edit

**Comment by ravijayaramappa** [comment]
synthetic-shadow is in maintenance mode, this won't be fixed.
