### ISSUE TITLE
[delegatesFocus] Userland focusin/focusout handlers should not execute when LWC uses those events to simulate focus delegation

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#1388]
### Description

focusin and focusout events related to our delegatesFocus implementation should be transparent to components. We currently "mute" these [here](https://github.com/salesforce/lwc/blob/5d4dc4df74283e940e282f1a6e9d7a2a25388a7c/packages/%40lwc/synthetic-shadow/src/faux-shadow/focus.ts#L193-L196) but we should be stopping immediate propagation instead.

#### Steps to Reproduce

https://playground.lwcjs.org/projects/vQLrwuAYE/6/edit
1) Click button 2
2) Shift+tab
3) Notice that the div is focused when it shouldn't be. This is because the `focusout` handler in app.js executed before our `focusin` handler for the first `lightning-button`. This causes the tabindex value of the div to change to 0 and getting picked up as a possible focus candidate. It's confusing and hard to explain.

**Comment by ravijayaramappa** [comment]
synthetic-shadow is in maintenance mode, this won't be fixed.
