### ISSUE TITLE
Support for TypeScript Using lwc-create-app

### ISSUE THREAD

**Issue by larkintuckerllc** [salesforce/lwc#1389]
It would be helpful to if the project generator, lwc-create-app, supported a TypeScript option; thus generating the project in TypeScript

**Comment by diervo** [comment]
Probably @muenzpraeger wants to move this issue to the create-app repo? and maybe @davidturissini can share with you an example for TS.

**Comment by muenzpraeger** [comment]
IF I could transfer from this repo I would... ;-)

**Comment by muenzpraeger** [comment]
@larkintuckerllc Can you open the issue here on the [lwc-create-app repo](https://github.com/muenzpraeger/lwc-create-app/issues/new/choose) - that would be great. Thanks!

**Comment by larkintuckerllc** [comment]
Assuming that since the issue is not reported in a different repository that it is fine to close here.
