### ISSUE TITLE
ability to reset an element generated from template

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#1405]
• LWC uses virtual dom mechanism to update the DOM. changing values (props and attrs) are carry on on the DOM if the structure of the DOM is preserved
• Iterations and other unpredictable structures are handled via unique keys, to try to preserve elements without introducing component state problems (that's what the infamous `key` attribute is, and why that is required inside iterations)
• DOM doesn't provide any mechanism to imperative reset the state of a built-in element to the original state, the only option is to create a new one
• LWC doesn't provide that capability either, but it doesn't provide an easy way to replace something with a new version of it without some imperative code (that's what the example attached here is doing, rendering the component twice, by removing the element from the dom and recreating a new one in the next tick)
• LWC does not reuse elements once they are removed from the DOM, a new one is always created (that's why that trick does work)

Here is an example of how that can be solved today:
https://developer.salesforce.com/docs/component-library/tools/playground/zQaqvMK5V/23/edit

I believe we can just allow `key` to dictate if a list of children is dynamic or not, and let the author to set the key to a different value to force the diffing to create a new element.

**Comment by Gr8Gatsby** [comment]
@caridy is the link showing a workaround? Or do we need to do something here?

**Comment by caridy** [comment]
yes, there is work to be done here for sure.

**Comment by gregwhitworth** [comment]
> I believe we can just allow key to dictate if a list of children is dynamic or not, and let the author to set the key to a different value to force the diffing to create a new element.

@caridy I don't know about the `key` your reference above yet but it seems this proposal would further create a dependency on the virtual DOM, correct?
