### ISSUE TITLE
IE11 performance impact documentation

### ISSUE THREAD

**Issue by davewallace** [salesforce/lwc#1420]
**Is your feature request related to a problem? Please describe.**
Feature request is related to IE11 performance, which is known to degrade with LWC.

**Describe the solution you'd like**
Doesn't have to be complicated, but details about how LWC is built or underlying technologies affecting performance negatively in IE11 would be great. This feature request isn't intended as a fix for anything, other than for people's benefit to be able to articulate what causes the performance issues. Having this information, and benchmarking tests if possible, on hand adds an additional layer of professionalism to conversations for those of us who didn't author LWC framework, but may or may not work with LWC but need to inform curious or skeptical technical teams. 

**Describe alternatives you've considered**
No alternatives per se, and we might just be missing data or documentation, we've searched quite a bit for statistical evidence and/or well articulated evidence describing the reasons for performance degradation. Some sources:
- [LWC docs](https://help.salesforce.com/articleView?id=000323354&type=1&mode=1)
- [LWC-unrelated benchmarking tests](http://incaseofstairs.com/2015/06/es6-feature-performance/)

**Additional context**
I don't actually work with LWC, my team work on a completely unrelated platform to Salesforce and we're adopting an approach considerate of Web Components and standards in general. Though our needs and stack are different, and we're not at all at the scale of Salesforce, we still need to have these informed conversations and make informed decisions. We look to the professional giants like your team for evidence and groundwork that we can utilise in those technical conversations and with those decision-making points.

Being able to back up our research with clearly articulated evidence would be super helpful. Again, maybe we just haven't come across the documentation - or perhaps the two links supplied above are all that is available - we're not sure, so we're asking :)

**Comment by caridy** [comment]
cc @pmdartus @jbleyleSF @diervo 

At the very least, we can surface the RFC for compat mode (it is somewhat distributed in different docs, we can put them together to explain how it works).

At some point we enabled the perf analysis per commit for IE11, but it was not good enough, too many variations, but maybe we can show a table with the degrading magnitud for our benchmarks, maybe running that manually from time to time.

**Comment by davewallace** [comment]
This would be fantastic, thank you for considering.

**Comment by diervo** [comment]
We have a lot of docs in the es5-proxy-compat repo, but @pmdartus and I never finish the work to open source and finish the docs :)

**Comment by nolanlawson** [comment]
IE11 is no longer supported, so closing this as not planned.
