### ISSUE TITLE
IE11: a non tabbable div tabIndex is returned as 0

### ISSUE THREAD

**Issue by sfdciuie** [salesforce/lwc#1422]
### Description

Querying a div's tabIndex in IE11 results in a value of 0 (even if it's non tabbable/focusable)

#### Steps to Reproduce

```html
<template>
  <div></div>
</template>
```
```js
console.log(this.template.querySelector('div').tabIndex);
```
#### Expected Results
`tabIndex` property should return `-1` for non tabbable elements

#### Actual Results
`tabIndex` property is `0`

### Browsers Affected
IE11 Only

### Version
- LWC: 1.0.2

**Comment by ekashida** [comment]
This is just an IE11 quirk and not an LWC bug. As a side note, we should be looking at the `tabindex` attribute instead of the `tabIndex` property in most cases since the former is not very useful.
