### ISSUE TITLE
Prevent usage of non-camelCase @api property names

### ISSUE THREAD

**Issue by StephenTangCook** [salesforce/lwc#1433]
### Description
Currently there is nothing preventing an LWC author from using a capitalized (non-camelCase) name for an `@api` property. While this works on the component itself, any parent component would not be able to set the value for this property, since we cannot disambiguate the capitalized attribute in the HTML. Thus we should not allow this in the first place.

#### Steps to Reproduce
1. Create an `@api` property in an LWC class that is capitalized (non-camelCase).
2. Create a parent component that attempts to set the value for this capitalized attribute on the child element.

https://developer.salesforce.com/docs/component-library/tools/playground/DAqeBXYIx/1/edit

```js
@api CapitalCase = "CapitalCaseValue";
```

#### Expected Results

The child should fail to compile.

#### Actual Results

Child compiles successfully.

### Browsers Affected

Any

### Version

- LWC: 1.0.3

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ekashida** [comment]
Fixed #1687. Pascal case property names are now supported to preserve backwards-compatibility.
