### ISSUE TITLE
wire-service doesn't support listener removal during invocation

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1458]
### Description

The `@lwc/wire-service` throws an unexpected error when a listener attempt to unregister itself when it is invoked.

#### Steps to Reproduce

```js
import { wireServiceRegister } from '@lwc/wire-service';

export const identifier = () => {};

wireServiceRegister(identifier, eventTarget => {
    const handler = () => {
        eventTarget.removeEventListener('connect', handler);
    };

    eventTarget.addEventListener('connect', handler);
});
```

In order to reproduce the issue, the same wire adapter should be used by 2 different components at the same time.

#### Observations

The [`invokeListener`](https://github.com/salesforce/lwc/blob/master/packages/@lwc/wire-service/src/index.ts#L42-L46) method is invoked with the array containing all the listeners, cache the length of the array and iterate over the array. The [`removeListener`](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/wire-service/src/wiring.ts#L70-L75) method also works on the same array object. If one of the listeners is removed in the middle of the iteration, the wire-service throw when invoking an array item which is out of bound (because the length of the array is cached).

#### Expected Results
The code should work as expected.

#### Actual Results
The wire-service throws an unexpected error.

### Browsers Affected
All

### Version
- LWC: 1.0.2-222.17

**Possible Solution**

The length of the listener array should not be cached.

**Comment by caridy** [comment]
I can take care of this as part of the wire reform.

**Comment by caridy** [comment]
cc @jodarove we can do this in another PR on wire-service pkg directly.

**Comment by caridy** [comment]
ping @jodarove

**Comment by jodarove** [comment]
Sure thing!

**Comment by ravijayaramappa** [comment]
@jodarove Does this issue still exist after wire reform?

**Comment by jodarove** [comment]
This is fixed with the wire protocol reform
