### ISSUE TITLE
command 'sdx.force.project.create' not found

### ISSUE THREAD

**Issue by srujan21** [salesforce/lwc#1466]
### Description
Couldn't able to create new Project via Visual Studio 
#### Steps to Reproduce
Open Visual Studio
Ctrl+Shift+P
SFDX: Create Project

Error : command 'sdx.force.project.create' not found

**Comment by Gr8Gatsby** [comment]
This issue needs to go into:
https://github.com/forcedotcom/sfdx-core/issues

@ntotten can you help get this into the correct place?
