### ISSUE TITLE
Passing attributes from Aura component to LWC

### ISSUE THREAD

**Issue by briannabrownOE** [salesforce/lwc#1469]
**Is your feature request related to a problem? Please describe.**
The auraEmbeddedLWC example from the `lwc-recipes` app provides a clear example for how to pass variables from a child LWC to a parent Aura cmp. However, I've found it difficult to find any examples of how to traverse the relationship from parent Aura cmp to child LWC. I was able to find a bit of a clue from the below note on the `auraPubsubPublisher.cmp` - but would still benefit from an example to clarify.

> Parent-to-child communication where the parent is an Aura component:
 >- If the child is an Aura component, use attribute passing or call an aura:method defined in the child component
 >- If the child is a Lightning Web component, use attribute passing or call a public @api method defined in the child component

**Describe the solution you'd like**
It would be great to include an example of how to pass an aura attribute to an embedded child lwc within the `lwc-recipes` repo. In a more immediate sense, if someone could help guide me a bit in how to do this, it would be much appreciated.

**Describe alternatives you've considered**
I've attempted to expose a variable in my lwc component with the `@api` decorator and then pass that variable value to a `@wire` call to a server side apex method:
```    @api productServiceName;
@wire(getOptionalProds, {productServiceName: '$productServiceName'}) products;
```

In my aura cmp i'm setting an attribute value from a flow and then attempting to pass that value to the lwc child cmp:

```<aura:component implements="lightning:availableForFlowScreens" access="global" controller="QuoteLineItemController">
<aura:attribute name="ProductServiceName" type="string"/>
    <c:optionalQuoteLineItemDataTable product-service-name="{!v.ProductServiceName}" onproductidlist="{!c.receiveProductIds}"/>
```

Unfortunately, this isn't working and i've run out of ways of troubleshooting what is going wrong.

**Additional context**
I really appreciate the help!

**Comment by pmdartus** [comment]
Moved the issue to https://github.com/trailheadapps/lwc-recipes/issues/125

**Comment by Sourabh42** [comment]
can u tell me how to pass the list of object from aura to lwc
