### ISSUE TITLE
drag-n-drop library is not working in lwc, but in aura.

### ISSUE THREAD

**Issue by jinlii** [salesforce/lwc#1470]
I'm using dragula library for drag-n-drop. It works in the aura component, 
```
afterDragulaLoaded: function(component, event, helper) {
 
    // Components
    var container = component.find('container');
 
    // Dragula needs the DOM elements
    var drake = dragula([container.getElement()]);
 
}
```

but not in lwc.

    example.html:
```
        <div class="dragdrop slds-m-vertical_large">
                <div class="box" id="a1">This is 1 a square div.</div>
                <div class="box" id="2">This is 2 a paragraph.</div>
                <div class="box" id="3">This is 3 another paragraph.</div>
        </div>

```
example.js
```
 let container = this.template.querySelectorAll('.dragdrop');
       console.log('container: ', container);
        let drake = window.dragula([container]);

```
containers is an empty proxy. How can I get the dom elements? Thanks in advance.

**Comment by caridy** [comment]
That is a problem with dragula library that it doesn't recognize shadow dom encapsulation. This is a library that we use internally for many things, so, this is not news for us. First the bad news, dragula hasn't been updated in more than 3 years, I don't think it is currently maintained, but the good news is that there is a PR open on the repo that works pretty well: https://github.com/bevacqua/dragula/pull/470, in fact the version that we use of dragula to test LWC and to use it internally is a distro from the branch in the PR.

I'm closing this issue as wont-fix but feel free to reopen if that doesn't work for you.
