### ISSUE TITLE
Wrapper component for Maps

### ISSUE THREAD

**Issue by miteshmsharma** [salesforce/lwc#1474]
**Is your feature request related to a problem? Please describe.**
I am frustrated when to show a map related component I have to call Google map API or use map anything as an offering from sfdc. 
**Describe the solution you'd like**
I would like to have a component which can directly use the fields to render a location on map. 
**Describe alternatives you've considered**
I have considered using Google map but it shows for development purpose only and does not do anything
**Additional context**
Very common issue so not including the screenshots

**Comment by caridy** [comment]
This is a request for lightning components team most likely. cc @garazi @gonzalocordero
