### ISSUE TITLE
lightning-combobox does not work in custom lightning-datatable

### ISSUE THREAD

**Issue by jinlii** [salesforce/lwc#1488]
custom class 
export default class TestDataTable extends LightningDatatable { }
 
custom template :
```
<template>
        <lightning-combobox
                name="progress"
                label="Status"
                value={value}
                placeholder="Select Progress"
                options={options}
                onchange={handleChange} ></lightning-combobox>
    
        <p>Selected value is: {value}</p>
    </template>
```
The template shows the dropdown correctly in a standalone component. But when included in the column template for the column in TestDataTable, it only shows the selection. When you click on the dropdown, nothing happens. The picklist values however are in the DOM when you inspect.

Is this a known bug?

Thanks!

**Comment by caridy** [comment]
This is probably on the lightning global components, not on LWC directly. cc @garazi @reiniergs

**Comment by russellsmall-litify** [comment]
I've found that the reason for this is each cell has a div with `slds-truncate` applied, which provides `Overflow: hidden`. This hides the drop down of the combobox. Removing this style allows the drop down to function properly, but I don't have a workaround yet.

**Comment by alucidwolf** [comment]
Even if you add a class to the <td> and then overwrite the .slds-truncate styles, the dropdown still does not show outside of the table
<img width="683" alt="Screen Shot 2020-09-02 at 9 27 23 AM" src="https://user-images.githubusercontent.com/563139/91989437-85de2d00-ecfe-11ea-833c-69c68b7e6095.png">

**Comment by nyaghoub** [comment]
I was able to get it to work by [following this example](https://live.playg.app/play/picklist-in-lightning-datatable). Couple of things to note to make it work. The CSS has to get added in the static resource in your org and then reference it in the js that extend the lightningTable. Also, this will not work locally, you need to make sure you deploy your code and then test it in the sandbox. I hope this will help others.

**Comment by bharvie** [comment]
After much frustration on this, discovered a simple workaround is to force wrapping on the column definition (wrapText: true - you will need to show the default header actions for it to work).

**Comment by garlac** [comment]
Hi All,

Is there any work around for this? I created a custom drop down to be used in custom lightning-datatable. However, the dropdown is not visible beyond the table container. 
![image](https://user-images.githubusercontent.com/40228026/124964557-c86b4700-e03e-11eb-8429-3e89ad629e2d.png)
Thank you.

**Comment by joelbyrd** [comment]
> Hi All,
> 
> Is there any work around for this? I created a custom drop down to be used in custom lightning-datatable. However, the dropdown is not visible beyond the table container. Tried both static resource and wrapText:true - Didnt help.
> ![image](https://user-images.githubusercontent.com/40228026/124964557-c86b4700-e03e-11eb-8429-3e89ad629e2d.png)
> Thank you.

I ran into the same thing - it's the same reason the combobox was getting cut off in the table cell - because of `overflow: hidden;`. This is being set on 2 of the table containers that get included in the datatable markup.

The fix is to create an external stylesheet and override the overflow styling for these containers and set them to "visible". I would add a CSS namespace which is the name of your custom element. Let's assume your custom datatable is <c-my-datatable> - then you would add the following to your external stylesheet that you would load in your custom datatable component:

`c-my-datatable .slds-scrollable_y,
c-my-datatable .slds-scrollable--y,
c-my-datatable .slds-scrollable_x,
c-my-datatable .slds-scrollable--x {
    overflow: visible;
}`

**Comment by manhntbkit** [comment]
> slds-truncate

awesome, it  removed "slds-truncate" or changed  overflow:auto it works!

**Comment by rovms** [comment]
Hi all,

@joelbyrd - your suggestion with the static resource css works indeed - thanks for sharing the idea.
However, this leads to another related issue for me that I am not sure how to solve. I tried to apply the visible overflow only to some of the scroll directions but that did not work. Below picture shows the issue. I have a very wide table with many columns, so the user needs to be able to scroll in horizontal direction to see the content of the last few columns. Now, (obviously) this is not possible anymore. Do you have any idea for a workaround?

![image](https://user-images.githubusercontent.com/23122786/230030292-c8d7d843-a6dd-40f5-97a8-befab4baf51d.png)

Thanks!

**Comment by jmsjtu** [comment]
Closing this out, please open a Salesforce Stack Exchange or Salesforce case if you're still experiencing this issue.

**Comment by nfqx** [comment]
I fixed it by giving my lightning-datatable a class (say, customTable) then import a CSS file as Static Resource (the LWC CSS won't pass Shadow DOM) with the following lines;

`.customTable .slds-dropdown-trigger_click.slds-is-open .slds-dropdown{
    position: fixed !important;
    z-index: 20001 !important;
    width: 140px !important; /* Set your own width in px or % of the entire screen */
}`
