### ISSUE TITLE
lightning-input percent formatter misleading

### ISSUE THREAD

**Issue by joeythomaschaske** [salesforce/lwc#1499]
### Description
When using step with a value < 1 in conjunction with a percent formatter, the displayed value shows too many 0's at the end. 

#### Steps to Reproduce
https://developer.salesforce.com/docs/component-library/tools/playground/ccS-81_hE/2/edit

#### Expected Results
onblur, the value should show 17.25% instead of 17.2500%. This is misleading and looks like the user can enter a number such as .172599, but that leads to an error of `Your entry isn't a valid increment.` 

**Additional context/Screenshots**

**Comment by sbvkrishna** [comment]
can I work on this?

**Comment by caridy** [comment]
This is the wrong repo for this issue since this is related to the implementation of `lightning-input`. cc @garazi @gonzalocordero @sfdciuie

**Comment by caridy** [comment]
asked around, this was fixed a while ago... probably pending to be released. Please, go through the support channels for a timeline.
