### ISSUE TITLE
Add `node.innerText` support for the test framework

### ISSUE THREAD

**Issue by stickel** [salesforce/lwc#1505]
**Is your feature request related to a problem? Please describe.**
LWC can utilize `node.innerText` (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) to get visible content as the visitor would see it. Currently this is unavailable when running tests and a polyfill is required.

**Describe the solution you'd like**
Adding support for `.innerText` or at least having the polyfill at a framework level so it's unnecessary to add it to each `*.test.js` file where it's needed.

**Additional context**
I'm adding this feature request after asking about it in the [Slack channel](https://sfdcessentials.slack.com/archives/C5W3E40TC/p1568233361190400)

**Comment by pmdartus** [comment]
The implementation of `HTMLElement.innerText` is not implemented in JSDOM because there is no concept of layout (https://github.com/jsdom/jsdom/issues/1245). This is, unfortunately, something that can't be polyfilled.
