### ISSUE TITLE
LWC CodeMirror integration

### ISSUE THREAD

**Issue by dmitry-rivlin-vrp** [salesforce/lwc#1520]
### Description
I have an issue with codeMirror integration to LWC.

I get an error "Failed to execute 'setEnd' on 'Range': parameter 1 is not of type 'Node'."

As i understand this issue related to LockerService.

**Comment by davidturissini** [comment]
@dmitry-rivlin-vrp could you share more info? It would be helpful if you could share your component code and template where CodeMirror is being used

**Comment by dmitry-rivlin-vrp** [comment]
**HTML**
`<template>
    <div class="wrapper">
        <div class="innerWrapper">
            <textarea id="code" name="code" class="codeMirror" lwc:dom="manual"></textarea>
        </div>
    </div>
</template>`

**Controller**
`import { LightningElement } from 'lwc';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';
import { loadScript, loadStyle } from 'lightning/platformResourceLoader';

import dConsole from '@salesforce/resourceUrl/dConsole';

export default class developerConsole extends LightningElement {

    showMessage(type, message) {
        if (type === 'EXCEPTION') console.error('DC:Exception', message);
        this.dispatchEvent(
            new ShowToastEvent({
                title: message.title, 
                message: message.message, 
                variant: type == 'EXCEPTION' ? 'error' : 'info'
            }),
        );
    }

    showEditor(scope){
        console.log('CodeMirror preparation');
        Promise.all([
            loadScript(scope, dConsole + '/codeMirror/lib/codemirror.js'),
            loadStyle(scope, dConsole + '/codeMirror/lib/codemirror.css'),
        ]).then(() => {
            CodeMirror.fromTextArea(scope.template.querySelector('.codeMirror'), {
                lineNumbers: true,
                lineWrapping: true
              });
        })
        .catch(error => {
            error.title = 'Load JS';
            scope.showMessage('EXCEPTION', error);
        });
        
    }

    renderedCallback() {
        console.log('Bingo');
        this.showEditor(this);
    }

}`

**Comment by caridy** [comment]
It is very likely that this is a locker issue since it is reporting a mismatch on the Node type, LWC has nothing to do with it most likely, but we will investigate more. Few more questions:

1. what version of codemirror are you using?
2. does this work in the LWC playground where locker is not available?

**Comment by caridy** [comment]
cc @manuel-jasso

**Comment by dmitry-rivlin-vrp** [comment]
> what version of codemirror are you using?
CodeMirror.version = "5.48.4"

**Comment by jdalton** [comment]
@dmitry-rivlin-vrp 

Depending on version Locker should be unwrapping the elements for `Range#setEnd()`. Would you try this in the [LWC playground](https://developer.salesforce.com/docs/component-library/tools/playground) and see if it works.

**Comment by jmsjtu** [comment]
If you're still experiencing this issue, please open a Salesforce Stack Exchange question or a Salesforce Case.
