### ISSUE TITLE
Documentation on Using LWC  : Need to improve the documentation

### ISSUE THREAD

**Issue by kumaresan-in** [salesforce/lwc#1521]
- Need to add architecture LWC like Angular Doc Site

- Mention all inbuild API, decorators with clear explanations

**Comment by caridy** [comment]
@kumaresan-in yes, we kinda lack of some more detailed explanations, your best bet at the moment are:

* https://github.com/salesforce/lwc/tree/master/docs/architecture
* https://github.com/salesforce/lwc-rfcs/

**Comment by caridy** [comment]
question, what do you mean by "inbuild API"?

**Comment by kumaresan-in** [comment]
Hi Caridy,

I'm telling about decorators, properties and all

**Comment by miteshmsharma** [comment]
Actually this is much needed and there is a need for a recipe cookbook
also. From Caridy's reference I can see information is scattered we need to
collate.

**Comment by Gr8Gatsby** [comment]
@miteshmsharma have you looked at the recipes repo? https://github.com/trailheadapps/lwc-recipes. Is the desire to have a Cookbook of the recipes, like a more written up guide?

**Comment by caridy** [comment]
He is asking for architecture docs @Gr8Gatsby

**Comment by nolanlawson** [comment]
Closing as we have https://lwc.dev, [Trailheads](https://trailhead.salesforce.com/content/learn/trails/build-lightning-web-components), and [Salesforce developer documentation](https://developer.salesforce.com/docs/platform/lwc/guide). Please reopen if there's something I've missed!
