### ISSUE TITLE
Testing Lightning-datatable

### ISSUE THREAD

**Issue by briannabrownOE** [salesforce/lwc#1522]
**Is your feature request related to a problem? Please describe.**

I am attempting to write a jest test for my lwc cmp that contains a `lightning-datatable`. In my test, I'd like ensure that the data passed from an imperative apex call (but mocked in my unit test) is displaying in a lwc `lighting-datatable` by counting the rows  in the datatable and comparing it to the number of records passed in the test. I haven't been able to find any code examples in the lwc repos for how to format data to be loaded into the datatable or how to use `querySelector` to get row data in the element.

**Describe the solution you'd like**

I'd like an example of how to format the data that is assigned to the datatable, as well as how use `element.shadowRoot.querySelector()` to select table rows after creating the `element` from the component. 

**Describe alternatives you've considered**

I'm a little bit stuck and i'm not sure how to get around not being able to write a unit test.

**Comment by caridy** [comment]
Not really related to this repo, but lets reroute this request to the proper folks: 

cc @gonzalocordero @reiniergs @garazi

**Comment by briannabrownOE** [comment]
Thank you for getting back to me! @caridy Where is the best place to ask these types of questions for future reference?

@gonzalocordero @reiniergs @garazi any insight would be very much appreciated.

After mocking the component/ creating the initial element, i'm attempting to assign the `lightning-datatable` to a variable with:

`const tableRows = element.shadowRoot.querySelector('lightning-datatable');`

I'm confused by the console logged output of this result:

`PatchedHTMLElement [HTMLElement] { '$$OwnerKey$$': 1, '$$OwnKey$$': 3 }` 

I'm not sure how to access features of the table to check that my mocked data is being rendered as I expect.

Thank you again for taking the time!
