### ISSUE TITLE
LWC Output Field is not showing values for some lookup fields

### ISSUE THREAD

**Issue by hugogmendes** [salesforce/lwc#1523]
**Description**
I've created a lightning-record-view-form with several fields. Some of the fields are lookups and the lookup fields are for differents objects, including custom and standard objects. The issue is that some of lookups isn't showing any value, but other do show.

**Example**
<lightning-record-view-form
    record-id="{recordId}"
	object-api-name="Suprimentos__c">
	
    <div class="slds-form" role="list">
        <div class="slds-section slds-is-open">
            <h3 class="slds-section__title slds-theme_shade">
                <span
                    class="slds-truncate slds-p-horizontal_small"
                    title="Detalhes do chamado">Detalhes do chamado</span>
            </h3>

            <div aria-hidden="false" class="slds-section__content">
                <div class="slds-form__row">
                    <template if:true="{exibirPropChamado}">
                        <div
                            class="slds-form__item slds-size_1-of-2"
                            role="listitem">
                            <lightning-output-field
                                field-name="Proprietario_do_chamado__c"
                                id="Read_Proprietario_do_chamado__c">
                            </lightning-output-field>
                        </div>
                    </template>

                </div>
                

                <div class="slds-form__row">
                    <div
                        class="slds-form__item slds-size_1-of-2"
                        role="listitem">
                        <lightning-output-field
                            field-name="Empresa__c"
                            id="Read_Empresa__c">
                        </lightning-output-field>
                    </div>
				</div>
				
				
            </div>
        </div>
    </div>
</lightning-record-view-form>

In the example above, both fields Proprietario_do_chamado__c (User) and Empresa__c (Account) are filled, but only Proprietario_do_chamado__c is showing the value.

I'm pretty sure that api field name is correct for Empresa__c.

**Comment by caridy** [comment]
@hugogmendes lets reroute this question to the proper team, the lightning namespace is not part of this repository. cc @gonzalocordero @garazi
