### ISSUE TITLE
compiler allows for private getter/setter to shadow @api property name

### ISSUE THREAD

**Issue by apapko** [salesforce/lwc#1525]
### Description
Compiler allow private getter and setter functions to shadow public property names

```js
import { LightningElement, api } from 'lwc';

export default class App extends LightningElement {
    @api foo = 1;

    set foo(value) {}
    get foo() {}
}
```
Playground [link](https://developer.salesforce.com/docs/component-library/tools/playground/KQLparp83/9/edit)

**Expected**:
Compiler must throw a `Duplicate @api property "foo".` error

**Comment by caridy** [comment]
@jodarove this is also related to the other issue with fields vs accessors, the runtime error that we discussed yesterday.

**Comment by pmdartus** [comment]
The code snippet here is valid javascript, and if we were to roll out such compiler change on the platform it would be breaking change. Instead of surfacing such issue as a compilation error, I would advocate for creating a new best practices linting rule to the eslint-lwc-plugin package.

**Comment by caridy** [comment]
@pmdartus is right... too late to enforce this, but at least we should be able to lint it.this seems very similar to the upper case field name issue @apapko

**Comment by apapko** [comment]
Agreed, this should this be an eslint rule in eslint-lwc-plugin. As for core developers, this rule can be configured as a warning. cc @pmdartus

**Comment by pmdartus** [comment]
I created a specific issue for this: https://github.com/salesforce/eslint-plugin-lwc/issues/25
