### ISSUE TITLE
Review and help webcomponents.dev

### ISSUE THREAD

**Issue by kevinv11n** [salesforce/lwc#1529]
From @georges-gomes

> Just a quick note to let you know that we released an experimental support for LWC on https://webcomponents.dev
We would love to hear your feedback and get recommendations going forward with it.
Discussing it on our Slack is probably a better option.

@diervo @Gr8Gatsby @muenzpraeger @caridy

**Comment by Gr8Gatsby** [comment]
The single file format is quite nice. I know we'd discussed in the past. What does the team think of the `<template>` `<script>` `<style>` Approach. This does match Vue's approach: https://vuejs.org/v2/guide/single-file-components.html. I noticed that this makes LWC a bit easier to teach, like as in recipes etc...

**Comment by diervo** [comment]
Technically `<style>` works, however @caridy had some concerns with WYSIWYG, since we will be removing that style tag at runtime from the DOM.

**Comment by caridy** [comment]
I will like to work toward that goal but unfortunately HTML modules are not ready yet... once they are... it is going to be easier...  basically, writing a single file might require some explicit connection between the different pieces from the same file... vs regular bundle which we do the implict linking.

**Comment by georges-gomes** [comment]
As a quick update. we now support LWC through multiple files as it was intended 👍
