### ISSUE TITLE
[Engine] expose a way for 3rd party libraries to produce read only proxy objects

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#153]
### Description

LDS, and other libraries that produce objects might want to produce values that can be used as properties. Additionally, they want to tap into the internal mechanism of the reactive engine to produce reactive objects that can trigger rehydration.

Initially, we want to try this model with LDS, and for what, we we exposing a high-privilege (not-documented) api to LDS can import it.

**Comment by jmsjtu** [comment]
We reviewed this as a team and the `readonly` decorator as described in this issue can be achieved with a combination of signals + `Object.freeze`.

Closing this issue out.
