### ISSUE TITLE
Implement lwc:dom="synthetic-portal"

### ISSUE THREAD

**Issue by ravijayaramappa** [salesforce/lwc#1530]
**Is your feature request related to a problem? Please describe.**
Allow legacy features that were built before shadow dom semantics existed and hence do not respect those semantics, to be manually injected to a portal of an lwc component.

**Describe the solution you'd like**
Similar to lw:dom="manual", we can have a lwc:dom="synthetic-portal" feature.

**Describe alternatives you've considered**

**Additional context**
This is in context of lwc usage on the salesforce platform. The previous generation of lightning components may have to embedded inside an lwc component. In additional, such components can be using third party libraries that were designed without shadow semantics in mind.

**Comment by ekashida** [comment]
Could we be explicit about what this directive would do?

**Comment by caridy** [comment]
RFC is needed for this... so I suspect we will have a lot more info there. Who is doing the RFC?

**Comment by jbleyleSF** [comment]
@ravijayaramappa what is a "a portal of an lwc component"? 
Regarding this statement, I thought Aura components weren't allowed to be nested in an LWC:
>The previous generation of lightning components may have to embedded inside an lwc component.

**Comment by nolanlawson** [comment]
Closing for now, please reopen if this is still planned.
