### ISSUE TITLE
Line break after(.) when we use prettier VS Code extension 

### ISSUE THREAD

**Issue by SumitSFDC1506** [salesforce/lwc#1535]
Hi All,

I am using Prettier in my JS code.
The original Code is as below:
var num = Math.floor (Math.random() * 1E+7).toString().replace(/.\d+/ig, "")

and after passing it through prettier
var num = Math.floor(Math.random() * 1e7)
.toString()
.replace(/.\d+/gi, "");

i don't want this to happen. Please suggest which configuration of prettier in VS Code would help me here

**Comment by pmdartus** [comment]
Prettier is an opinionated formatting tool with a limited set of [options](https://prettier.io/docs/en/options.html). However, there is no option to configure how chain calls should be formatted. You can always disable prettier if you are not happy with the way your code is formatted.
