### ISSUE TITLE
Inline Editing for Multiple Rows Lightning Datatable

### ISSUE THREAD

**Issue by briannabrownOE** [salesforce/lwc#1537]
### Description
Following the instructions described [here](https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.data_table_inline_edit), i'm attempting to build a lightning datatable with inline editing available. I'm having a couple of issues. One is that my existing field values are not visible in my data table for number columns. The second issue is i'm not able to successfully use `updateRecord()` to update my records with `draft-values` when the `onsave` event is handled.

#### Steps to Reproduce

Attempt to create a lightning datatable with inline editing enabled for some columns with multiple records.

https://developer.salesforce.com/docs/component-library/tools/playground/hj4Df12_1/8/

Note: this doesn't compile at all because of the wired apex controller. 

Here is what my columns look like:
```
const COLS = [
    { label: 'Subscription Name', fieldName: 'Custom_Text_Field__c', editable: false },
    { label: 'Months Paid Upfront', fieldName: 'Custom_Number_Field__c', type: 'Number', typeAttributes: {minimumIntegerDigits: 2, minimumSignificantDigits: 3}, editable: true },
    { label: 'Commit Term Months', fieldName: 'AnotherCustom_Number_Field__c', type: 'Number', typeAttributes: {minimumIntegerDigits: 2, minimumSignificantDigits: 3}, editable: true },
]

```

I closely followed the instruction in <Strong>[Create a Data Table with Inline Editing](https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.data_table_inline_edit)</Strong>
 for my `onsave` event handler.

```
handleSave(event) {

    const recordInputs =  event.detail.draftValues.slice().map(draft => {
        const fields = Object.assign({}, draft);
        return { fields };
    });
    
    const promises = recordInputs.map(recordInput => {
        console.log('record input', recordInput)
        updateRecord(recordInput)
    });


    Promise.all(promises).then(() => {
        this.dispatchEvent(
            new ShowToastEvent({
                title: 'Success',
                message: 'Line Items Updated',
                variant: 'success'
            })
        );

        // Clear all draft values
        this.draftValues = [];

        // Display fresh data in datatable
        return refreshApex(this.<var returned from wired Apex>);
    }).catch(error => {
        this.dispatchEvent(
            new ShowToastEvent({
                title: 'Error editing record',
                message: error.body.message,
                variant: 'error'
            })
        );
    });

}
``` 

#### Expected Results
Expect existing data to display and for edited values in the datatable to be saved to record by event handler.

#### Actual Results
Existing values don't display until pencil is clicked on editable fields in the table. Edited values are not saved to record. 

### Version

- LWC: x.x.x

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by caridy** [comment]
This is related to base components, not to this repo, but let me try to bring the attention for other folks: cc @gonzalocordero @garazi
