### ISSUE TITLE
Winter 20 - change in behaviour when updating api property

### ISSUE THREAD

**Issue by gbreavin** [salesforce/lwc#1547]
### Description

Firstly - I know we shouldn't update api properties! However, we think we've found an edge case which changes between Summer 19 and Winter 20, without an error or warning to the developer indicating what's going on.

The issue seems to be when a property in a child component is updated in a forEach loop - this seems to bypass some of the read-only variable checks. In Summer 19, the desired side-effects (e.g. re-render) happen, but in Winter 20 they do not, so it appears like a breaking change (it's not, it's actually enforcing the way it's supposed to work, but without a warning or error, devs might not realise this)

#### Steps to Reproduce
Spin up two scratch orgs, one Summer 19 and on Winter 20. Enable Lightning Debug mode for your user. Push the components from the Playground link below to each org.

https://developer.salesforce.com/docs/component-library/tools/playground/0PlAQj5OZ/

Add the following meta xml file in the Parent Component folder as myParent.js-meta.xml.

```
<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata" fqn="myParent">
    <apiVersion>46.0</apiVersion>
    <isExposed>true</isExposed>
    <targets>
        <target>lightning__RecordPage</target>
    </targets>
</LightningComponentBundle>
```

Navigate to a record page, edit the page and add the component somewhere. Click the button - in the Summer 19 org, the component updates, and in Winter 20 it does not, but in both cases, there's no warning or error in the Javascript console as to why.

#### Expected Results

In Winter 20, the update to the items in the forEach loop should cause nasty red errors to appear in the Javascript debug console.

#### Actual Results

The logic that tries to modify the object fails but without any indication as to what happened or why.

### Browsers Affected

Chrome, presumably others

Appreciate this might be majorly esoteric and not worthy of the time to implement a fix, but there may potentially be other devs relying on the previous behaviour (particularly with datatables?)

**Comment by caridy** [comment]
I looked into the details. I don't recall any particular change here, other than enforcing a little bit more the semantics of the read only values. In this case, they mutation is a no-op and does not really change the values inside that array, which means it doesn't really affects the UI. Unfortunately, the playground link that you provided does not work.

**Comment by gbreavin** [comment]
Hi @caridy 

Apologies, I was using the playground as a way of sharing the sample code (I wrote the code on my machine to be able to push to Summer 19 and Winter 20 scratch orgs, and didn't have time to refactor to work in the playground).

Here's a playground with the example - but **please note**, the playground's behaviour is in line with what I expect - click the button and you get console errors. 

* In Summer 19, the button click updates the properties and the components re-render.
* In Winter 20, the button click does not update the properties, but no error is thrown.

Playground link: https://developer.salesforce.com/docs/component-library/tools/playground/eiRQNX2R_/1/edit

Just to reiterate - I agree that the update shouldn't be allowed, but given the change in behaviour in this use case (and I admit - this is an edge case and therefore is probably not that heavily used), devs might appreciate more direction as to why something "broke" in Winter 20.

**Comment by caridy** [comment]
cc @Gr8Gatsby

**Comment by apapko** [comment]
The error is generated by the [observable-membrane](https://github.com/salesforce/observable-membrane/blame/4aa7e417755796a99df6d0180d61cba10f7cb991/src/read-only-handler.ts#L39) and has been in place for the last 2 years. The only time the error won't be produced is when the code is ran in [production](https://github.com/salesforce/observable-membrane/blame/4aa7e417755796a99df6d0180d61cba10f7cb991/src/read-only-handler.ts#L37). @gbreavin i believe there is no difference in the behavior between Summer 19 and Winter 20 and suspect that the change you are observing is due to the environment differences - dev vs prod? 

cc @caridy

**Comment by gbreavin** [comment]
@apapko Yes, that's certainly possible!

**Comment by apapko** [comment]
Feel free to re-open this issue if you find that the investigation results contradict your finding.
