### ISSUE TITLE
line let enc = new TextDecoder("utf-8") throw exception

### ISSUE THREAD

**Issue by dmitry-rivlin-vrp** [salesforce/lwc#1554]
Line let enc = new TextDecoder("utf-8") throw exception in LWC JS controller

**Comment by pmdartus** [comment]
I will close this issue for now, since the bug report doesn't match the issue template.

I am suspecting you are facing this issue only when running unit tests and is due to the fact that JSDOM doesn't implement `TextEncoder` and `TextDecoder` (https://github.com/jsdom/jsdom/issues/2524).
