### ISSUE TITLE
Normalize the build script across all sub packages of lwc

### ISSUE THREAD

**Issue by ravijayaramappa** [salesforce/lwc#1558]
**Is your feature request related to a problem? Please describe.**
Currently each sub package under the @lwc have separate build scripts. Often, each build script is identical and results in a lot of duplication. This feature request is to create a common build script at the root level and reuse it across the sub packages.

**Additional context**
https://github.com/salesforce/lwc/pull/1504#discussion_r331846869

**Comment by nolanlawson** [comment]
This is fixed by #3456
