### ISSUE TITLE
PDF/Excel report generation for LWC

### ISSUE THREAD

**Issue by yasarshaikh** [salesforce/lwc#1559]
**Is your feature request related to a problem? Please describe.**
Currently there is no option available to generate the Aura/LWC component to PDF/Excel for reporting purpose. 

**Describe the solution you'd like**
As Visualforce has an option like renderAs (which works with pdf/excel etc). I am expecting to have the same in LWC. Since we use different charts and data for reporting purpose, there is an issue with current pdf generation options. 

**Describe alternatives you've considered**
1. pdfjs as suggested by git user pmdartus : However it is not working because of Lightning locker service. If possible could you please suggest the alternatives for the same. 
2. VF with renderas pdf : However it is not possible, since LWC invoked by means of JS. 

**Additional context**
If possible, please give an option like getting entire LWC body as blob(the same is working with PageReference and VF)

**Comment by Gr8Gatsby** [comment]
@yasarshaikh, thank you for taking the time to submit a request to LWCs Open Source Project. Currently, this is no work in our plans to support an output format for components.

PDF is a common scenario, but likely will be solved outside of an individual component capability.
The Core LWC project is focused on rendering in the DOM. I have passed along this request to other teams thinking about how to support PDF/Excel scenarios at the page level.
