### ISSUE TITLE
TreeGrid. Column with icon position left

### ISSUE THREAD

**Issue by dmitry-rivlin-vrp** [salesforce/lwc#1570]
#### Steps to Reproduce
as you can see we don't have icon from left side
https://developer.salesforce.com/docs/component-library/tools/playground/t-IUPdQAG/3/edit

as you can see we have icon from right side
https://developer.salesforce.com/docs/component-library/tools/playground/t-IUPdQAG/2/edit

**Comment by diervo** [comment]
Same as https://github.com/salesforce/lwc/issues/1571

This is not an issue on the LWC framework, this is on Salesforce Lightning components. Moreover you are not following the the guidance we have provided for filing issues, please do fill correctly the issue next time.

@gonzalocordero @reiniergs can you please check if this a bug indeed, file a ticket in after close this issue?

**Comment by Gr8Gatsby** [comment]
Opened an internal bug to make progress, will update status once progress is made.
