### ISSUE TITLE
TreeGrid. First column with type "button-icon"

### ISSUE THREAD

**Issue by dmitry-rivlin-vrp** [salesforce/lwc#1571]
https://developer.salesforce.com/docs/component-library/tools/playground/t-IUPdQAG/4/edit

as you can see we can't see icon in first column

**Comment by diervo** [comment]
This is not an issue on the LWC framework, this is on Salesforce Lightning components.

@gonzalocordero @reiniergs can you please check if this a bug indeed, file a ticket in after close this issue?

**Comment by Gr8Gatsby** [comment]
Opened internal bug, will update status once updates are available.

**Comment by pmdartus** [comment]
From Lightning Base Component team:
> This issue will never be fixed.
