### ISSUE TITLE
Condition based child rendering

### ISSUE THREAD

**Issue by kamalkantappirio** [salesforce/lwc#1573]
I have two components 1.AccountList  2. AccountRow.
In the account list component, we have @trackaccounts array and us iterator this data and showing multiple  AccountRow.

Let's think when we update the single account(in @track accounts) but all the child(AccountRow) is rendering.

So we need a feature we can only render that update child not all the child.

The same life cycle method is available in react is called **static getDerivedStateFromProps()**

**Comment by diervo** [comment]
Sorry I don't fully understand your question, you can do all the computations on a getter, there is no need to some side-effect derivation...

Moreover this does not follow the template we provide with repro steps, or specific details. It will be helpful is you can give us an example of code or a repro case. 

Closing this for the reasons mentioned above, feel free to open a new issue following the steps we requested.

**Comment by caridy** [comment]
As @diervo mentioned, we need more information, repro case, etc. Most likely, the problem that you have is the `key` in the iteration, if the key is not preserved for some elements in the tracked accounts, those elements will not be preserved as well, it is all about the keys.
