### ISSUE TITLE
Private field declarations in classes (# support) error

### ISSUE THREAD

**Issue by yaminm** [salesforce/lwc#1579]
### Description
I want to leverage the private field declarations in lwc classes
#### Steps to Reproduce

create a service class and use #

```
class  SapCarConfiguratorUtil {

    #MULTIPICKLIST = 'multipicklist';
    constructor(jsonResponse) {
        console.log(this.#MULTIPICKLIST);
   }

}

export {SapCarConfiguratorUtil}

```

https://developer.salesforce.com/docs/component-library/tools/playground

```js
const your => (code) => here;
```

#### Expected Results
Deploy to org
#### Actual Results
ERROR deploying LightningComponentBundle lwc/sapCarConfiguratorUtil/sapCarConfiguratorUtil.js: LWC1509: Unexpected character '#' (7:4)

### Version
API:46.0

**Comment by caridy** [comment]
@yaminm private fields are stage 3, once they reach stage 4, and are implemented in modern browsers, we will enable it with the corresponding transpilation down to IE11, for now... we keep waiting.

Btw, keep in mind that we provides protected fields at the moment, only those with `@api` are truly public, while regular fields are basically protected.
