### ISSUE TITLE
Getting error on using @wire(CurrentPageReference) pageRef;

### ISSUE THREAD

**Issue by MuzaffarMahmood** [salesforce/lwc#1591]
Getting following error on using @wire(CurrentPageReference) pageRef;

Error: [LWC error]: Invalid event type "WireContextEvent" dispatched in element <c-lineitemdetail-header-component>. Event name must 1) Start with a lowercase letter 2) Contain only lowercase letters, numbers, and underscores

<c-lineitemdetail-header-component>

    at Object.logError (aura_proddebug.js:4268)

    at ConstructionEstimation.dispatchEvent (aura_proddebug.js:7622)

    at ConstructionEstimation.wrappedMethod [as dispatchEvent] (aura_proddebug.js:12985)

    at WireEventTarget.dispatchEvent (aura_proddebug.js:9501)

    at d.get (contextService.js:2)

    at eval (contextService.js:2)

    at E (contextService.js:2)

    at Object.t.getContextValue (contextService.js:2)

    at c.getCurrentPageReference (pageService.js:2)

    at eval (navigation.js:2)

**Comment by surendra-dev** [comment]
Hi @MuzaffarMahmood ,

It seems you are trying to emit event name like this : WireContextEvent

According to LWC rules you can event name should be following :
- wirecontextevent
- wire_context_event

You can't write in upper case.
Thanks

**Comment by MuzaffarMahmood** [comment]
Hi @surendra-dev,
First of all thank you for replying. I am not emitting any event. I am just adding this line in my LWC js file. @wire(CurrentPageReference) pageRef;

May be this wire is emitting some event and there is bug in LWC framwork. But this error is not an issue. It is working fine in desktop salesforce web app on chrome browser but it is not working on Salesforce1 mobile app and i could not get recordId passed from previous page via this pageRef.state or attribute. Again only in mobile app this is the problem. You can see detail  of the bug here: https://developer.salesforce.com/forums?inputboxform=lwc#!/feedtype=SINGLE_QUESTION_DETAIL&dc=Mobile&criteria=ALLQUESTIONS&id=9062I000000Xlm6QAC

**Comment by caridy** [comment]
Related to the upcoming wire reform: https://github.com/salesforce/lwc/pull/1459

cc @jodarove @jbenallen can you help here?

@MuzaffarMahmood we will probably need more information about where are you seeing that error.

**Comment by MuzaffarMahmood** [comment]
@caridy Thank you for reply. 
Error shows on browser console when we enable LWC bugging from Salesforce admin. But the problem is we can not get parameters from state or attributes of pageRef only in Salesforce mobile app. 
For details: https://salesforce.stackexchange.com/questions/282419/in-salesforce1-app-unable-to-get-recordid-from-currentpagereference-wire-adapter

**Comment by jbenallen** [comment]
The underlying implementation behind that wire is resulting in that event's emission. Upcoming work will refactor this and remove this. The console error is not causing any functional issues since it's not actually being thrown in the stack and is merely being logged. It is safe to ignore and will be removed in the future.

**Comment by caridy** [comment]
Closing this in favor of the proper stackexchange question, no changes needed in this repo.

**Comment by ckarimanoor** [comment]
> The underlying implementation behind that wire is resulting in that event's emission. Upcoming work will refactor this and remove this. The console error is not causing any functional issues since it's not actually being thrown in the stack and is merely being logged. It is safe to ignore and will be removed in the future.

Hi jbenallen, 
Do you know when the upcoming work will release this? Are you referring to the Salesforce Release or some thing else? Please confirm. I am trying many samples but @wire is not working in any of them. I am using await expression in renderedCallback() async function.

**Comment by ypeskov** [comment]
Is there any update about the fix? I am getting the same error for the next code:

`this[NavigationMixin.GenerateUrl]({
                type: 'standard__recordPage',
                attributes: {
                    recordId: result.Id,
                    actionName: 'view',
                },
            })`

yes it doesn't break anything on a page,  but it is indeed not nice in console.

**Comment by jbenallen** [comment]
@ckarimanoor the error logged in the console has no impact on functionality. If you are having problems using `@wire` in your code, it would not be related to this logged error.

@ypeskov the work to refactor the underlying implementation, avoiding this logged error, isn't complete yet.

**Comment by SalesforceBobLightning** [comment]
Hey @jbenallen - Hope you're well

Just looking for an update on this error message, whenever we build anything we end up using `@wire(CurrentPageReference) pageRef;` which means the console full of these non-error message, would be better developer experience if they went away :-)
