### ISSUE TITLE
"spellcheck" attribute changed from "false" to "true"

### ISSUE THREAD

**Issue by sfdciuie** [salesforce/lwc#1595]
### Description
Spellcheck is a global enumerated attribute (possible attribute values are "true" and "false") 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck , yet when the value of "false" is passed, when rendering in the DOM the value is changed to "true" (implying that it thinks it's a boolean and not enumerated).

#### Steps to Reproduce
https://developer.salesforce.com/docs/component-library/tools/playground/9QyIG6iLa/1/edit
Inspect  `<c-child>` to see how the `spellcheck` attribute was set in the DOM.

`<c-child spellcheck="false"></c-child>`

#### Expected Results
`<c-child spellcheck="false"></c-child>` in the DOM

#### Actual Results
`<c-child spellcheck="true"></c-child>` in the DOM

**Comment by jodarove** [comment]
`translate` is another attribute in the same situation: https://developer.salesforce.com/docs/component-library/tools/playground/9QyIG6iLa/2/edit

**Comment by ekashida** [comment]
Fixed #1610
