### ISSUE TITLE
lightning-slider triggers noblur event when you slide

### ISSUE THREAD

**Issue by jinlii** [salesforce/lwc#1603]
### Description
This is not an issue in Chrome. I wanted to slide without triggering onblur. Onblur I will be closing the slider.

#### Steps to Reproduce

```  
<lightning-slider value={slideVal} label='' min=0 max=10 onchange={handleOnChange} onblur={closeSlider}>
</lightning-slider>
```

#### Expected Results
when sliding, onblur is not triggered.

#### Actual Results
when sliding, onblur is triggered. As a result, the onblur handler is being invoked which is supposed to close the slider and return to a read only view of just the value.

### Browsers Affected
Safari

**Comment by jinlii** [comment]
Is this a known issue? Is there a workaround? Thanks for your help in advance!

**Comment by caridy** [comment]
@jinlii this is the wrong repo for this issue, but we can reroute it from there via @Gr8Gatsby and @garazi

**Comment by pmdartus** [comment]
From the Lightning Base Component team:
> This issue won't be fixed because it is working as designed.
