### ISSUE TITLE
Module resolver doesn't process lwc.config.json in npm modules

### ISSUE THREAD

**Issue by tedconn** [salesforce/lwc#1607]
### Description

The module resolver does not properly process the lwc.config.json found in npm modules.

#### Steps to Reproduce

add an lwc.config.json to your package which looks like this:

```json
{
  "lwc": {
    "modules": ["@my/module"]
}
```

in `@my/module` add an `lwc.config.json` like this:

```json
{
  "lwc": {
    "modules": ["src/modules"]
}
```

#### Expected Results

The modules from @my/module/src/modules will be added to the module path.

#### Actual Results

They won't be because when the module resolver sees that an npm module is being referenced, it correctly tries to resolve the modules but instead of passing in the rootDir of the npm module (so that the lwc.config.json can be subsequently found from there), it passes in the path of the actual `lwc.config.json`.

https://github.com/salesforce/lwc/blob/e972ea774056579480fb3e040ce584019b367fe7/packages/%40lwc/module-resolver/src/index.ts#L72

**Possible Solution**

Pass in the `dirname` instead of the file itself.

**Comment by pmdartus** [comment]
Fixed with #1602
