### ISSUE TITLE
Assert Violation: [object:vm undefined] must be inserted.

### ISSUE THREAD

**Issue by lozforce** [salesforce/lwc#1612]
### Description
In a stand-alone LWC app, clicking around the website we sometimes get an error caught by the global error handler. The error doesn't appear to have any detrimental effects to the UI or to the functionality.

#### Steps to Reproduce
There is no consistent repro. 

Please contact me on Slack to get a link to the SPA and to the source.

#### Expected Results
No error is thrown

#### Actual Results
![AssertViolationCropped](https://user-images.githubusercontent.com/47344313/68623261-eeff6600-0488-11ea-8d42-e77f18d67242.png)

### Browsers Affected
Seen on chrome Version 78.0.3904.87

### Version
    "dependencies": {
        "@salesforce-ux/design-system": "^2.9.4",
        "lwc-components-lightning": "1.4.4-alpha",
        "lwc-services": "1.2.2",
        "rxjs": "^6.5.3"
    },
    "devDependencies": {
        "husky": "^2.3",
        "lint-staged": "^8.1.5"
    },
    "engines": {
        "node": ">=8.9.4"
    },

**Comment by pmdartus** [comment]
@lozforce I will share this issue for now since there isn't much we can debug. Feel free to reopen the issue when you can share a small reproduction case for this assertion error.
