### ISSUE TITLE
Freeze column in datatable 

### ISSUE THREAD

**Issue by wiktoriasobczyk** [salesforce/lwc#1628]
I created lightning-datatable and I want to freeze 1'st column .
How to freeze first column only while scrolling horizontal  in lightning datatable or css?
I tried add additional css:
.THIS table tr td:first-child {
    position:sticky; 
    top:0; 
}
but it doesn't work. 
Thank you for helping!

**Comment by caridy** [comment]
@wiktoriasobczyk this is the wrong repo for support or features on global components, this is about the LWC library itself, not the component. You should try: https://powerofus.force.com/s/article/How-to-Create-a-Technical-Support-Case-with-Salesforce-Support
