### ISSUE TITLE
Consider using read-only membrane to invoke wire-service listeners

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1634]
TODO details: [property-trap.ts](https://github.com/salesforce/lwc/blob/71cabd5b83a0cd84c6eff11be4d574923f7db646/packages/%40lwc/wire-service/src/property-trap.ts#L39)

**Comment by ravijayaramappa** [comment]
@jodarove Is this issue still valid anymore? 
The file referenced in the issue comment is no more in the repo.

**Comment by nolanlawson** [comment]
@pmdartus Closing based on above comment, please reopen as necessary.
