### ISSUE TITLE
Optimize createKeyToOldIdx

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1637]
TODO details: [snabbdom.ts](https://github.com/salesforce/lwc/blob/71cabd5b83a0cd84c6eff11be4d574923f7db646/packages/%40lwc/engine/src/3rdparty/snabbdom/snabbdom.ts#L37)

**Comment by nolanlawson** [comment]
@pmdartus Is this issue still valid? Or can it be closed?

**Comment by pmdartus** [comment]
I don't recall. I will close this item.
