### ISSUE TITLE
Add type definition for buildCustomElementConstructor (and other publicly available methods)

### ISSUE THREAD

**Issue by lozforce** [salesforce/lwc#1642]
### Description
buildCustomElementConstructor is used in LWC apps scaffolded by the create-lwc-app. In other words, it's publicly exposed and used. There's no type definition for this method in types.d.ts.

#### Steps to Reproduce
```
npx create-lwc-app my-app
cd my-app
```
Open up index.ts in VS Code
Notice the squiggly line under "buildCustomElementConstructor" on the import line.

#### Expected Results
No squiggly

#### Actual Results
Squiggly line. Tooltip says: "Module '"lwc"' has no exported member 'buildCustomElementConstructor'.ts(2305)"

### Browsers Affected
VS Code 1.40.2

### Version
"lwc-services": "^1.3.12"

Transitive dependency: 
@lwc/engine@1.1.1

**Possible Solution**
Add the necessary type info into 
node_modules/lwc/types.d.ts

For example:
```
export function buildCustomElementConstructor(value: any): any;
```
Please replace "any" with proper types

**Comment by lozforce** [comment]
Another instance:
```import { createElement } from 'lwc';```

**Comment by caridy** [comment]
experimental `buildCustomElementConstructor` method will be removed by https://github.com/salesforce/lwc/pull/1395

other experimental APIs like `createElement` will eventually be removed as well, that's why we don't promote them much.

**Comment by ekashida** [comment]
The experimental `buildCustomElementConstructor` has been deprecated as of v1.3.11 and is superseded by the `LightningElement.CustomElementConstructor` getter for which we expose types as of #2010.
