### ISSUE TITLE
Enable tsc for @lwc/synthetic-shadow package

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1649]
### Description

Currently the `@lwc/synthetic-shadow` doesn't run `tsc` as part of the [`build`](https://github.com/salesforce/lwc/blob/331cf3508ee5a2dd6b2e97eb464617f858f5527b/packages/@lwc/synthetic-shadow/package.json#L10) script. It only runs `rollup`. Like the all the other packages, `tsc` should run before `rollup` to catch Typescript related errors.

**Comment by caridy** [comment]
Ah, good catch! we remove it because we don't produce the ES version of this polyfill nor the types, but we can definitely run it without output for validation.
