### ISSUE TITLE
Empty object being returned on `querySelector`

### ISSUE THREAD

**Issue by thiagorp** [salesforce/lwc#1663]
### Description

When I call `this.template.querySelector('.popover')` an empty object is being returned. I understood that the method would return `null` when the element doesn't exist or the first element when it does, but this contract is not being respected.

If I do `console.log(this.template.querySelectorAll('.popover'))` I see that the `target` property of `[[Handler]]` has the element I want to be returned, but if I try `console.log(this.template.querySelectorAll('.popover').length)` it returns `0`.

This is only happening on the Salesforce platform, it works fine on the playground, so I imagine it's something to do with locker?

#### Steps to Reproduce

Here is my HTML markup:

```html
<template>
  <slot class="popover" data-visible={visible} style={style}></slot>
</template>
```

**Comment by pmdartus** [comment]
Yes if it works on the playground then, this should be related to Locker. 
Let's keep this issue open for tracking purposes until the locker team acknowledges or not the bug.

**Comment by manuel-jasso** [comment]
Hi @thiagorp, I am with Locker team, I tested your code but in my environment I didn't see the error, i.e. `console.log(this.template.querySelectorAll('.popover').length)` returns `1` with Locker enabled.

What version of LWC are you testing with? Are you using SFDX to deploy your code to an Org? Can you share all of your code, not just the template?

Thanks!

**Comment by jmsjtu** [comment]
Closing as this is unrelated to LWC, please open a Salesforce Stack Exchange question or a Salesforce Case if you're still experiencing this issue.
