### ISSUE TITLE
lightning-layout does not work in Microsoft Edge

### ISSUE THREAD

**Issue by alafemina** [salesforce/lwc#1673]
### Description
LWC layout does not flow properly on Edge/IE11 when using lightning-layout-item with Size Attribute

#### Steps to Reproduce
1. Create a component with the following template:
```
<template>
    <lightning-layout>
        <lightning-layout-item size="8">
            <lightning-card title="Test Left Column (2/3 width)"></lightning-card>
        </lightning-layout-item>
        <lightning-layout-item size="4">
            <lightning-card title="Test Right Column (1/3 width)"></lightning-card>
        </lightning-layout-item>
    </lightning-layout>
</template>
```
2. Deploy and open in Microsoft Edge
3. Layout is not correct, items aren't in two columns with appropriate widths

https://developer.salesforce.com/docs/component-library/tools/playground/xmMHZzf7/1/edit

#### Expected Results

![image](https://user-images.githubusercontent.com/53837133/72288799-d3931180-3617-11ea-834a-da585935a481.png)

#### Actual Results

![image](https://user-images.githubusercontent.com/53837133/72291721-edcfee00-361d-11ea-96db-b5578203f7c1.png)

### Browsers Affected
Microsoft Edge

### Version

- LWC: latest

**Additional context/Screenshots**
My Salesforce Team is developing a new application built entirely with LWC. The application does not render according to SLDS standards in Microsoft Edge and we must support this browser in accordance with https://help.salesforce.com/articleView?id=getstart_browsers_sfx.htm&type=5

**Comment by caridy** [comment]
This is the wrong repo for lightning-* components, let me loop the right folks so they can guide you. cc @Gr8Gatsby @garazi

**Comment by garazi** [comment]
This is due to the fact that Legacy Edge did not support custom elements in a flexbox context. Instead of using lightning-layout, you should use a <div class="slds-grid"> and grid items (with sizes), per the SLDS grid documentation.
