### ISSUE TITLE
[Perf Optimization] separate the reactive phase for render method from the template function

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#1678]
Now that we have a reactive model that supports multiple phases/procedures, we can discuss whether or not we will like to separate the template function invocation from the render method invocation to use two separate phases (currently denoted by `vm.tro`). The gain here is that most components do not have logic in their render() method, in fact, most of them don't even have a render method.

If we have a separate phase, we could only recall the `render()` method if we are sure that something used by the logic during the last call to `render()` has change, otherwise, don't even bother to call it, and just re-evaluate the already selected template function (from the previous call to render method), and use a separate phase to tell you when the template function needs to be invoked.

The only drawback that I can think of here is that sometimes the `render()` method is just not even call, while the UI is updated, and the `renderedCallback` is also invoked since that one is not really about the `render()` method, but about updating the UI.

**Comment by pmdartus** [comment]
> The gain here is that most components do not have logic in their render() method, in fact, most of them don't even have a render method

As mentioned, the `render()` method invocation is really lightweight because in 99% of the cases it just returns the template associated with the component. I am uncertain the expected performance gain this change brings outweighs the memory overhead (extra properties to track) and the maintenance complexity it would introduce.

**Comment by caridy** [comment]
You are probably right @pmdartus, we can close this one.
