### ISSUE TITLE
onrowaction in datatable

### ISSUE THREAD

**Issue by holapancho** [salesforce/lwc#1685]
**Is your feature request related to a problem? Please describe.**
I need to know when the user select press a checkbox in the datatable and return the selected row.

**Describe the solution you'd like**
This is solved in datatable aura component, it's called **onrowselection** action.

**Describe alternatives you've considered**
If exist a workaround please let me know, thanks :)

**Comment by pmdartus** [comment]
Thanks for reporting this issue @holapancho. This is the wrong repo for lightning-* components, let me loop the right folks so they can guide you. cc @Gr8Gatsby @garazi

**Comment by garazi** [comment]
@holapancho are you talking about a checkbox as a column or THE checkbox column that is the first column in the datatable?

**Comment by jmsjtu** [comment]
Closing this as it is unrelated to LWC, please open a Salesforce Stack Exchange question or Salesforce Case if you're still experiencing this issue.
