### ISSUE TITLE
TR treats as inline element other child components.

### ISSUE THREAD

**Issue by gonardfreeman** [salesforce/lwc#1691]
#### Steps to Reproduce
1. Created datatable
2. Create `<c-child>` el to put row in it
3. Create loop over data list
4. wrap child el in `<tr>` tag and add keys

**Playground link**
https://developer.salesforce.com/docs/component-library/tools/playground/NzIP6A6k/7/edit

#### Expected Results
`<tr>` treats `<c-child>` as normal shadow el and compile code inside it

#### Actual Results
`<tr>` treats `<c-child>` as inline el and do not compile it

### Browsers Affected
Chrome, Brave confirmed. Other I think the same

### Version
- LWC: 1.1.13-224.4
- sfdx-cli/7.42.1-e41dbeb8d9 darwin-x64 
- node-v10.15.3
- NPM 6.10.2

**Additional context/Screenshots**
![Screenshot 2020-01-22 at 10 37 13](https://user-images.githubusercontent.com/16113714/72878220-3b75e600-3d03-11ea-9b63-4da481d80ced.png)

**Additional notes**
Put `<tr>` inside element does not solve it due to problem that table styles would be broken. I can rewrite them in `.css` file from scratch but as for me it is bad idea.

**Comment by pmdartus** [comment]
As defined by the [HTML specification](https://html.spec.whatwg.org/#the-tr-element), `<tr>` elements can only have `<td>` and `<th>`, `<script>` and `<template>` children. Due to this reason, you can't have LWC as children of the `<td>` element and it's something that will not be fixed. In the following example, you can see that the HTML parser move the invalid elements out of the `<table>` : https://jsfiddle.net/pmdartus/w7td8xvc/5/

That being said your example is interesting because the parser doesn't recover well from `<td>`. The template compiler produces an unexpected string.

**Comment by gonardfreeman** [comment]
> As defined by the [HTML specification](https://html.spec.whatwg.org/#the-tr-element), `<tr>` elements can only have `<td>` and `<th>`, `<script>` and `<template>` children. Due to this reason, you can't have LWC as children of the `<td>` element and it's something that will not be fixed. In the following example, you can see that the HTML parser move the invalid elements out of the `<table>` : https://jsfiddle.net/pmdartus/w7td8xvc/5/
> 
> That being said your example is interesting because the parser doesn't recover well from `<td>`. The template compiler produces an unexpected string.

Thanks for clarification!

**Comment by gonardfreeman** [comment]
@pmdartus one little update. if you use `<tr>` inside loop it requires 2 keys on each el
```
<tbody>
   <template for:each={items} for:item="item">
        <tr key={item.Id}>
              <c-child key={item.Id} item={item}></c-child>
        </tr>
  </template>
</tbody>
```
but in other cases it is enough to put them only on wrap el:
```
<template for:each={days} for:item="day">
        <div key={day}>
            <c-child day={day}></c-child>
        </div>
    </template>
```
or at component itself
```
<template for:each={days} for:item="day">
        <c-child key={day} day={day}></c-child>
</template>
```

**Comment by pmdartus** [comment]
I am not certain to understand your question. The `key` directive should only be needed on the direct children of the elements with `for:each` directive.

```html
<template>
  <tbody>
    <template for:each={items} for:item="item">
      <tr key={item.id}>
      </tr>
    </template> 
  </tbody>
</template>
```

**Comment by gonardfreeman** [comment]
@pmdartus here few screens, so you can see it:
![Screenshot 2020-01-22 at 18 03 47](https://user-images.githubusercontent.com/16113714/72910713-9a5a5000-3d41-11ea-9cc5-6f0dbd1a1aa6.png)
![Screenshot 2020-01-22 at 18 03 28](https://user-images.githubusercontent.com/16113714/72910714-9a5a5000-3d41-11ea-9a32-a13ad5ebb0da.png)

Basically it requires to put key on each child. And here what I've got from console while deploying it to org:
`[Line: 35, Col: 25] LWC1071: Missing key for element <c-single-milestone> inside of iterator. Elements within iterators must have a unique, computed key value.`

**Comment by suresh83kumar** [comment]
Is there a workaround for this?

**Comment by caridy** [comment]
@suresh83kumar that seems more like an issue with the linting rule, which we should update to fix this message, but functionally wise, it should be fine.

**Comment by suresh83kumar** [comment]
I get key error when I deploy the code to org. Can you guide me how to
deploy bypassing that error?

**Comment by caridy** [comment]
@Gr8Gatsby this seems to be a platform issue, can you follow up asap?

**Comment by caridy** [comment]
@suresh83kumar the workaround here is to add the same key that you add to the parent `<tr>`. Adding an extra key will do nothing but will bypass the linter.

**Comment by pmdartus** [comment]
@caridy I don't think there is any workaround. `<tr>` elements can only have `<td>` and `<th>`, `<script>` and `<template>` children (see https://github.com/salesforce/lwc/issues/1691#issuecomment-577117572).

The parse5 automatically fixes this to match with the actual browser behavior. Let's take the following example:

```html
<table>
  <tbody>
    <template>
      <tr>
        <x-foo></x-foo>
      </tr>
    </template>
  </tbody>
</table>
```

The actual generated DOM will be:

```html
<table>
  <tbody>
    <template>
      <tr></tr>
      <x-foo></x-foo>
    </template>
  </tbody>
</table>
```

See the live example: https://jsfiddle.net/pmdartus/0ybpLtan/1/. So regardless if you add `key` directive on the custom element, the generated DOM will not be what you expect. The LWC compiler might be able to give you a better error message. But the workaround is not to add custom elements in `<tr>` elements.

**Comment by suresh83kumar** [comment]
I agree with you. Implementing key workaround doesn’t work for me. I am
kind of stuck in release now. Any recommendations or alternatives to move
forward would be appreciated.

Regards,
Suresh

**Comment by caridy** [comment]
Ah, apologies, I didn't look at the details in deep before replying. @pmdartus is absolutely right, this is not a problem with the linter, but with the invalid markup, and how it is parsed. I suspect your problem is even bigger, probably using a `td` inside `x-foo`'s template, which is only invalid (@pmdartus do we have linter errors for that? IIRC we had a issue open for that from a very long time).

@suresh83kumar two possible solutions:

1. you add the `td` or the `td`s in the parent component (similar to what we do in datatable).
2. you move away from tables all together and use layout/grid with a bunch of custom elements to align them accordingly.

**Comment by apapko** [comment]
@pmdartus given there is no workaround, can this be closed?

**Comment by pmdartus** [comment]
Yes, the remaining work overlaps with #248. Let's close this issue.
