### ISSUE TITLE
[synthetic-shadow] non-composed events are observable outside of shadow tree

### ISSUE THREAD

**Issue by ravijayaramappa** [salesforce/lwc#1700]
### Description
A non-composed event dispatched on an element in a shadow tree can be listened to at the document.body element. 

#### Steps to Reproduce
https://playground.lwcjs.org/projects/AXvaFl_o/2/edit

```js
export default class App extends LightningElement {
    renderedCallback() {
        document.body.addEventListener('test', (evt) => {
            console.log('Event received at body');
            console.log(evt.target);
            console.log(evt.composed);
        })
        const div = this.template.querySelector('div');
        const event = new CustomEvent('test', { bubbles: true });
        div.dispatchEvent(event);
    }
}
```

Alternative reproduction steps with LWC components only: [playground](https://developer.salesforce.com/docs/component-library/tools/playground/S1wRP35ub/7/edit)

#### Expected Results
Expected that event listener is not invoked. There should be no console logs.

#### Actual Results
Listener is invoked and you will see console logs.

### Browsers Affected
All

### Version
- LWC: 1.2.1

**Comment by caridy** [comment]
this is supposed to be addressed by https://github.com/salesforce/lwc/pull/1569

**Comment by ekashida** [comment]
https://github.com/salesforce/lwc/issues/2121
