### ISSUE TITLE
Instalation ERROR

### ISSUE THREAD

**Issue by Marcelovv2** [salesforce/lwc#1718]
Windows 10 64 bit, node 12.15.0, npm 6.13.7
I'm following https://lwc.dev/guide/install#tools and encounter errors at the beginning,

`salesforce> npx create-lwc-app mvv-app
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @typescript-eslint/typescript-estree@2.19.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@typescript-eslint/parser'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\marce\AppData\Roaming\npm-cache\_logs\2020-02-10T20_26_01_533Z-debug.log
Install for [ 'create-lwc-app@latest' ] failed with code 1`

**Comment by jbleyleSF** [comment]
@muenzpraeger

**Comment by jbleyleSF** [comment]
@Marcelovv2 I'm seeing the same issue on Mac/Chrome. 
Would you mind creating an issue at 
https://github.com/muenzpraeger/create-lwc-app/issues

I'll close this issue. Thank you.
