### ISSUE TITLE
[engine] verify and gate the usage of globals

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#173]
### Description

We have identified issues related to usage of globals like `removeEventListener`, which was supposed to be imported from the module that caches all those from `Element.prototype`, but the import statement was never defined, and since `removeEventListener` is in fact a global, the IDE doesn't complain, and everything works fine in most browsers except IE11. We better figure a way to prevent this from happening again.

**Comment by jmsjtu** [comment]
We reviewed this as a team and since we're no longer supporting IE11 this issue can be closed.
