### ISSUE TITLE
LWC container created on init call overriding all other LWCs already rendered with their own unique state

### ISSUE THREAD

**Issue by albarivas** [salesforce/lwc#1731]
Original issue from @gigiskarlett https://github.com/dreamhouseapp/dreamhouse-lwc/issues/104

----

Situation: Up until Salesforce API got upgraded to 48.0 every time an agent would open a salesforce tab when opening a support case I was able to create a new aura:component that would trigger an init call to the controller creating a div with a unique id and then create a LWC component that contains our bundle.js react code that would look for this unique id and would get inserted in it without affecting any other LWC components that were already rendered (since they have unique ids and the LWC would only get inserted in the div we had just created) and then we would set the LWC component into a div on the cmp on the same init call. Here is the code:

CMP Component: //Here we create the .cmp that will be executed every time a user opens a new tab and where we define where our lwc and div that contains our app will be set to.

```
 <aura:component implements="flexipage:availableForAllPageTypes
      access="global" controller="auraController">
      <aura:handler name="init" value="{!this}" action="{!c.init}" />
      <aura:attribute name="reactApp" type="Aura.Component[]" access="global"/>
      <aura:attribute name="reactAppBundle" type="Aura.Component[]" access="global" />
      <lightning:card aura:id="reactApp" class="customCardClass">{!v.reactApp}</lightning:card>
      <div aura:id="reactBundle">{!v.reactAppBundle}</div>
    </aura:component>
```

JS Component: //Here we execute the init call every time a user opens a new tab we assign this div an unique id and then we create the LWC component that will get inserted into this div

```
init: function(cmp) {
    let id = Math.random()
      .toString()
      .substr(2);


    $A.createComponents(
      [
        ["div", { id: id }],
        [
          “c:lwc",
          {
            Id: id
          }
        ]
      ],
      function(results) {
        cmp.set("v.reactApp", [results[0]]);
        cmp.set("v.reactAppBundle", [results[1]]);
      }
    );
  }
```

LWC: //Here we get that id that was created in the controller and through the LWC client, we pass it to the React frontend code so it knows what DOM element it needs to get attached to.

```
export default class lwc extends LightningElement {
  @api id;
  renderedCallback() {
  getSessionId().then(result => {
      this.sessionId = result;
      Promise.all([loadScript(this, app + "/bundle.js")])
        .then(() => {
          window.render(this.id); (this will be used in the frontend code
        })
        .catch(error => {
          console.log(error);
        });
    });
 }
}
```

React Code: //this is the entry point where we define to what DOM element it should append itself to when the id is received from the LWC client

```
let renderApp = function (id: any) {
  store.dispatch(setAppClientId(id));
  ReactDOM.render(
    <Provider store={store}>
      <Router>
        <App />
      </Router>
    </Provider>,
    document.getElementById(id ||'root')
  );
};

(window as any).render = renderApp;
```

The problem: The issue we’re facing is ever since the API got upgraded to 48.0 the same code that was working before it’s no longer working and the problem we’re experiencing is that now when we set the LWC component we just created into the body of the div we also just created it’s setting/overriding the state of all the other LWCs that were already rendered (which is the problem since the state is unique per LWC). We know this from seeing the behavior in the DOM. Sorry if this may be unrelated but thought I'd give it a shot

**Comment by diervo** [comment]
Alba this is a very contrived and unrelated LWC problem, and I don't think is the right forum for it, so I'm going to close this issue. However in an attempt to help, here are some suggestions:

1) Don't use `let` in aura, is not supported in ES5.
2) It is likely to be an issue on the way you instantiate your aura => LWC. Try to call you you attribute other name than `Id`, see if that helps.
3) If the id is being "reused" there is a serious memory leak somewhere and some lifecycle is not being cleaned up correctly.

You can ask in the internal slack channel if someone has time to debug this with you from the team.

P.S: Aura + React + LWC? You are asking for a lot of trouble, thats for sure! :)
