### ISSUE TITLE
Discrepancy between native and synthetic shadow when slotting content

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#1734]
### Description

Given multiple slots with the same name, slotted content for that name should only be rendered under the first slot. LWC renders slotted content under each slot.

#### Expected Results

https://jsbin.com/hiruxewuvu/edit?html,output

#### Actual Results

https://developer.salesforce.com/docs/component-library/tools/playground/0xHlB1Cd/1/edit

### Browsers Affected

All browsers

### Version

- LWC: 1.3.1

**Comment by caridy** [comment]
uff, that should have been a compiler error to avoid people producing wrong template. @reiniergs is it possible to answer this question with static analysis to see if someone is doing that?

**Comment by diervo** [comment]
That is far from ready
