### ISSUE TITLE
Hidden attribute not working properly for empty string

### ISSUE THREAD

**Issue by jodarove** [salesforce/lwc#1741]
### Description
In a component template when setting the `hidden` attribute of a regular or custom element to empty string, the rendered element is not hidden.

#### Steps to Reproduce

LWC playground: https://developer.salesforce.com/docs/component-library/tools/playground/wVIn9_yb/2/edit
```html
<template>
    <div hidden="">
        This text should be hidden
    </div>
</template>
```

#### Expected Results
The div should be hidden ( https://codepen.io/jodarove/pen/mdJWaOR )

#### Actual Results
The div is not hidden

### Browsers Affected
All

**Additional context**
The hidden attribute is a boolean attribute, and is treated as such by the framework, but if you set it to a string other than `"true"` or `"false"` the compilation will succeed without any error.

In the template compiler and because of https://github.com/salesforce/lwc/blob/master/packages/@lwc/template-compiler/src/parser/attribute.ts#L243 `isAttribute` will return false for all booleanAttributes, and will set the value on the property instead of setting the attribute. 

Note: Setting the `hidden` property of an element to `''` sets it to `false`.

**Comment by caridy** [comment]
Compiler should consider this boolean.
