### ISSUE TITLE
lightning-formatted-date-time & lightning-input type="date" wrongly rendering Portuguese dates

### ISSUE THREAD

**Issue by jastend** [salesforce/lwc#1780]
### Description
When using Brazilian Portuguese locale and language, I have noticed that there's a display issue when using both `lightning-formatted-date-time` and `lightning-input type="date"`.

The output will look like this:

> 28 '28e' jan. '28e' 2020

#### Steps to Reproduce
Make sure to set the locale to Brasilian Portuguese. This won't work on local dev environments.

Example: https://developer.salesforce.com/docs/component-library/tools/playground/NwceWGUS7/1/edit

#### Expected Results

> 28 jan. 2020

#### Actual Results

> 28 '28e' jan. '28e' 2020

### Browsers Affected

Verified in:

- Google Chrome (latest stable)
- Firefox (74) 

### Version
Current live version

**Possible Solution**
My current workaround is to use a shortened format as shown in my example.

**Comment by diervo** [comment]
Sorry but unfortunately this is not the right forum/repository to solve salesforce component specific issues. Please raise an issue in stackoverflow. Maybe @gonzalocordero will be able to forward this bug to the Component's team.
