### ISSUE TITLE
Self closing <animateTransform> and <path> fails at compilation

### ISSUE THREAD

**Issue by narendrasinghrathore** [salesforce/lwc#1781]
### Description
Using svg in template or component. Getting error at compiler and linter.
#### Steps to Reproduce
Add svg in component html file and complier generate error 
![image](https://user-images.githubusercontent.com/4208015/77553405-c7aab200-6eda-11ea-8b2a-c4ec5e26a825.png)

https://developer.salesforce.com/docs/component-library/tools/playground/lq-8iCl3B/27/

**Comment by narendrasinghrathore** [comment]
It generated error first for <path> i.e. has no matching closing tag, i manually added closing tag for that ( problem solved or you can say no lint or compiler error ).
Second error for <animateTransform> i.e. has no matching closing tag, i manually added closing tag for same, but getting same error.

**Comment by dahnielkim** [comment]
I am getting this error only when running jest-tests.

**Comment by caridy** [comment]
cc @apapko @ravijayaramappa

**Comment by pmdartus** [comment]
The template compiler has an incomplete least of self-closing elements ([code](https://github.com/salesforce/lwc/blob/master/packages/@lwc/template-compiler/src/parser/html.ts#L48-L72)).

**Comment by dahnielkim** [comment]
Are there any updates regarding fixing this issue?

**Comment by diervo** [comment]
Right now the team doesn't have bandwidth for this issue, and we will get to it whenever we have some spare time. That being said you have two options:

1) You can issue a PR and fix it!, we can guide you on where the code it)

2) A trival alternative is, you can just make those tags non self closing:

```
<svg xmlns="http://www.w3.org/2000/svg">
  <path d="M19.4"></path>
  <animateTransform attributeName="transform"
                          attributeType="XML"
                          type="rotate"
                          from="0 60 70"
                          to="360 60 70"
                          dur="10s"
                          repeatCount="indefinite"></animateTransform>  
                        </svg>
```

I know that works because I took this code (and simplified it) from a production app. You should be unblocked, but you should consider option 1 :)

**Comment by nolanlawson** [comment]
For whatever reason, `<animateTransform />` works out-of-the-box today with LWC, but `<path />` doesn't (38a2dd8a0). So I'm going to close this in favor of #2533.
