### ISSUE TITLE
[Feature Request] Side Effects

### ISSUE THREAD

**Issue by aputinski** [salesforce/lwc#1790]
**Is your feature request related to a problem? Please describe.**

Currently, running side effects (network requests, manual dom updates, etc) after prop changes is very cumbersome.

The recommended approach is to use getters/setters. As far as I understand, the following code is what would be required to run `sideEffect` whenever
`a` `b` or `c` changes.

```javascript
class Component extends LightningElement {
  _a;
  @api
  get a() {
    return this._a;
  }
  set a(value) {
    this._a = value;
    this.sideEffect();
  }

  _b;
  @api
  get b() {
    return this._b;
  }
  set b(value) {
    this._b = value;
    this.sideEffect();
  }

  _c;
  @api
  get c() {
    return this._c;
  }
  set c(value) {
    this._c = value;
    this.sideEffect();
  }

  sideEffect() {
    let { a, b, c } = this;
    console.log(a, b, c);
  }
}
```

The first issue with this code is the amount of boiler plate needed.
Secondly, because setters are called synchronously, `sideEffect` will be called immediatley after each prop change. This has the potential to cause performance problems and potentually unintended side effects (making too many network requests). These problems could be mitigated by debouncing the side effect and diffing the prev/next values.

**Describe the solution you'd like**

Some mechanism for easily reacting to prop changes.

## Callback

One option is for a new callback method. Something like `updatedCallback()`

```javascript
class Component extends LightningElement {
  @api a;
  @api b;
  @api c;
  @api d;

  updatedCallback() {
    // a, b, c, or d was updated
    // Check if a, b, or c was updated and run the side effect
  }
}
```

This could use similar huristics to template updates which I beleive get triggered
one microtask after the first prop update.

With this approach, new boilerplate will be introduced to track previous prop values
and run side effects only when the values have changed.

For this callback to be useful, it would be great to know what props changed (similar to `attributeChangedCallback`).

```javascript
updatedCallback(changes) {
  for (let { name, oldValue, newValue } of changes) {
    // Check what properties were updated and only run
    // side effects for relavant updates
  }
}
```

Even with the change object, you will still be required to check which properties have changed and only run the side effect on relevant changes.

I'd also like to propose this function gets invoked after `connectedCallback` which maybe means using a different name? I'd like to avoid having to run the same code in
`connectedCallback` and `updatedCallback`.

```javascript
connectedCallback() {
  // Run side effect
}
updatedCallback(changes) {
  // Run side effect
}
```

## Decorator

`updatedCallback` seems like the most pragmatic approach, but ideally I'd like to have
something similar to `useEffect` in React.

```javascript
useEffect(() => {
  // a, b, or c was updated
  return () => {
    // Will get called the next time this effect is run or
    // if the component is unmounted.
    // Can be used to clean up listeners/subscriptions
  };
}, [this.a, this.b, this.c]);
```

The benefit of this approach is that the callack is only invoked when the dependencies have changed. Since LWC already tracks prop usage, LWC could track what properties
are used in the callback and avoid having to specify a dependencies array.

```javascript
class Component extends LightningElement {
  @api a;
  @api b;
  @api c;

  @effect
  sideEffect() {
    // a, b, or c was updated
    let { a, b, c } = this;
    console.log(a, b, c);
    return () => {
      // Cleanup
    };
  }
}
```

**Comment by caridy** [comment]
I'm definitely not ok with either of those solutions, nor with the possibility to observe that point in time during the life-cycle of the component in a synchronous manner, but we can discuss it for sure. We have debated this in the past multiple times, this is a gigantic foot-gun because it will be part of the critical path that might attempt to block the rendering mechanism. 

Additionally, as we continue moving forward with the wire reform, eventually, you will be able to define your own wire adapter that can do some of this work in ways that will not block the main critical path by definition.

Now, I will like to see not only the theoretical part of why do you need this feature, but the practical part of it, what exactly are you trying to do, maybe we can help to provide a better choice.

**Comment by aputinski** [comment]
The most obvious use of this feature is making network requests when the component connects and when properties change. We're working on several components that need to do this. I also have other components that need to run manual dom side effects when properties change.

**Comment by caridy** [comment]
Note: on an offline conversation with @aputinski we agreed that a wire adapter is good enough for this use-case, it gives you reactivity for configuration passed to the wire adapter (which can include a, b, c from the example above), and will allow you to detect connect and disconnect of the element itself, which is all you need to go and fetch data. That's the main use-case for the wire protocol anyway.
