### ISSUE TITLE
Node.contains API is broken, returns false for node itself

### ISSUE THREAD

**Issue by bmblb** [salesforce/lwc#1791]
### Description
Node.contains API doesn't work like it is described in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains). Latter states that

> The Node.contains() method returns a Boolean value indicating whether a node is a descendant of a given node, i.e. the node itself,

#### Steps to Reproduce
See this playground app:
https://developer.salesforce.com/docs/component-library/tools/playground/OhXG7B2Gh/3/edit

#### Expected Results

`true` is shown on the page
#### Actual Results

`false` is shown
### Browsers Affected

Fails in chrome and firefox. Issue promises to be cross-browser

**Comment by bmblb** [comment]
Workaround:
```
const contains = Node.prototype.contains;
Node.prototype.contains = function (value) {
    if (value === this) {
        return true;
    }
    else {
        return contains.apply(this, arguments);
    }
}
```

I was afraid it won't help given the amount of encapsulation and protection, but it did.

**Comment by bmblb** [comment]
I see a PR with a fix already. Very impressive!

**Comment by ravijayaramappa** [comment]
@bmblb thanks for reporting the issue.
