### ISSUE TITLE
Cannot set currentNode on tree walker

### ISSUE THREAD

**Issue by bmblb** [salesforce/lwc#1795]
### Description
`Failed to set the 'currentNode' property on 'TreeWalker': The provided value is not of type 'Node'`

#### Steps to Reproduce
1. Create LWC app like in this playground: https://developer.salesforce.com/docs/component-library/tools/playground/WybjPasaI/1/edit
Issue is not reproducible there, but I can see it

#### Expected Results
*Current node* element should cycle item 1 -> item 2 -> item 3 -> item 1 -> ...

#### Actual Results
stops on item 3

### Browsers Affected
Doesn't look browser-specific

### Version
- "lwc-engine": "1.1.13-224.4"

**Possible Solution**

**Additional context/Screenshots**
raw is original TreeWalker class, but value is an element wrapper. Smth like this is probably missing somewhere: 
![image](https://user-images.githubusercontent.com/45400762/78157548-c2a0b200-7448-11ea-9354-38dd8c2ccbef.png)

**Comment by caridy** [comment]
This is another one that is on locker service rather than this library. As you can see, that's a SecureElement target in the screenshot above, that indicates that this is coming from Locker, which is not doing the proper unwrapping of those proxies before calling the underlaying DOM api. Feel free to open a bug for that team.

**Comment by bmblb** [comment]
Could you please tell me where to report that problem?

**Comment by caridy** [comment]
cc @seksenov

**Comment by jmsjtu** [comment]
Closing this as it is unrelated to LWC, please open a Salesforce Stack Exchange question or Salesforce Case if you're still experiencing this issue.
