### ISSUE TITLE
Provide tools/hooks for debugging in all browsers + standalone apps

### ISSUE THREAD

**Issue by diervo** [salesforce/lwc#18]
While developing a standalone app or in a browser other than Chrome, we don't pull the devTools module for Proxys, which makes debugging very hard.

Moreover we should provide some scape hatch or tool for non-chrome browsers so we can also unwrap a proxy.

Some ideas: 
- expose a global `unwrap` in DEV mode.
- monkey patch console.log (probably this will have a lot of side-effects)
- add a special global `console.logProxys` that will do the banch-check for Proxys

**Comment by jmsjtu** [comment]
We're not planning on working on this now.

**Comment by nolanlawson** [comment]
To clarify: we support the Chrome-specific devtools formatters format – if another standard emerges that has cross-browser support, then we will use that. But in the meantime I can't see a cross-browser solution other than writing a full DevTools extension for all browsers.
