### ISSUE TITLE
Cannot set drag image on DataTransfer

### ISSUE THREAD

**Issue by bmblb** [salesforce/lwc#1809]
### Description
Exception is thrown when trying to set dragImage:
```
Uncaught TypeError: Failed to execute 'setDragImage' on 'DataTransfer': parameter 1 is not of type 'Element'.
    at HTMLDivElement.<anonymous> (VM57 compiledPreview.js:710)
    at HTMLDivElement.fnOrObj.$$lwcEventWrapper$$ (VM54 synthetic-shadow.js:2471)
```

#### Steps to Reproduce
As usual, not reproducible on a playground, locker service is required:
https://developer.salesforce.com/docs/component-library/tools/playground/EUbKngS5n/2/edit

#### Expected Results
Blank image to be set

#### Actual Results
Exception is thrown

### Version
- "lwc-engine": "1.1.13-224.4"

**Possible Solution**

**Additional context/Screenshots**
Probably same problem as in here: https://github.com/salesforce/lwc/issues/1795

If so, please tell me how to report that to salesforce? It appears special support subscription is required for that, which I don't have.

**Comment by ahmet-eren** [comment]
It is needed to be fixed. Thanks!

**Comment by SalesforceBobLightning** [comment]
Is there a timeline for a fix to this?

**Comment by pmdartus** [comment]
This is a question for @manuel-jasso.

**Comment by manuel-jasso** [comment]
Thanks for the heads up, @pmdartus, indeed this seems to be a Locker issue.

@SalesforceBobLightning @ahmet-eren @bmblb I have created internal ticket W-7947643 to track this, what is your priority so that we can prioritize internally?

FYI @animmakayala @seksenov @salesforce/ui-security

**Comment by LukeKoz** [comment]
@manuel-jasso 

Our main use case for this is drag-and-drop functionality using HTML5 where would like to replace or eliminate the default drag image entirely.
Our current use case is where we are resizing columns in a custom table component, we are using the HTML5 drag functionality to achieve this efficiently and would like to eliminate the ghost image. 

I am getting the issue even if I create the element dynamically:

```javascript
const img = new Image();
img.url = '/path/to/resource.gif';
event.dataTransfer.setDragImage(img, -99999, -99999);
```

**Comment by bmblb** [comment]
We implement a floating window drag drop and it looks bad with default drag image

**Comment by manuel-jasso** [comment]
Thanks @LukeKoz and @bmblb, the importance of this is clear, but we'd like to know the priority. There are basically two options: [1] we can work on this during our regular release cycle (next one is Feb/2021), or [2] if this is a high priority we can do a patch release sooner, but the date would still be TBD and the process is more involved.

**Comment by bmblb** [comment]
The sooner the better, of course. But I have to admit this problem doesn't really break anything, so far from high priority :) We found a way around. It just looks terrible.

**Comment by manuel-jasso** [comment]
Thanks @bmblb, we'll keep this in our regular release queue then.

**Comment by scottbcovert** [comment]
I have a similar use case as @LukeKoz & @bmblb where I'd like to replace the default drag image with custom styling. Just wondering if/when a patch is expected for release - thanks!

**Comment by ahmeterenslalom** [comment]
@manuel-jasso Any update on this issue? - thanks!

**Comment by manuel-jasso** [comment]
Hi @ahmeterenslalom, sorry for the delayed response.

This issue happens only in what we're starting to call "Legacy Locker", which is the version of Locker that has been running in production for the last few years. The security model of Legacy Locker is not as rock solid as we wanted it to be, and it was impossible to refactor the code, we had to rearchitect it and reimplement it, and we are calling this "Locker vNext".

Locker vNext is where our focus is, this means that Legacy Locker is in maintenance mode, and we will only fix critical security bugs.

From the description, this is not a critical security bug, so we will not be fixing it in Legacy Locker, and we know this is not a problem in Locker vNext, so we are asking customers to wait until Locker vNext is GA. For dates, I would defer to @seksenov, our Product Manager.

**Comment by jmsjtu** [comment]
Closing this as it is unrelated to LWC, please open a Salesforce Stack Exchange question or Salesforce Case if you're still experiencing this issue.
