### ISSUE TITLE
Cannot construct URLSearchParams

### ISSUE THREAD

**Issue by fenixjke** [salesforce/lwc#1812]
### Description
An exception is thrown in a component when trying to create an instance of URLSearchParams.

### Steps to Reproduce
1. create a component
2. add URLSearchParams instance creation to the constructor
3. add the component to a lightning app
4. open the app.

### Playground
The exception is not reproducible in the playground.

### Code Snippet
```js
export default class App extends LightningElement {
    constructor() {
        super();
        new URLSearchParams();
    }
}
```

### Expected Results
URLSearchParams is constructed

### Actual Results
[Failed to construct 'URLSearchParams': Please use the 'new' operator, this DOM object constructor cannot be called as a function.]

**Comment by caridy** [comment]
LWC doesn't really care much about what DOM APIs do you use from globals. This is locker restricting access to certain capabilities in platform. cc @manuel-jasso to re-route this issue to the proper queue.

**Comment by manuel-jasso** [comment]
@seksenov @caridy Tracking on W-7429733

**Comment by VijayaSankarN** [comment]
This issue affects me as well. Can't find an easy workaround. Any updates?

**Comment by VijayaSankarN** [comment]
But Locker API Viewer says it is supported:
![image](https://user-images.githubusercontent.com/12524485/84040064-c65c3200-a9bf-11ea-949d-4777c4f995ce.png)

Still reducing the API version to 46 doesn't help :(

**Comment by pedrumgolriz** [comment]
Using this successfully: 
```
 var url = new URL(document.URL);
 const params = url.searchParams;
```

You can still use get and has methods, so same effect for my use

**Comment by jmsjtu** [comment]
Fixed in Locker
