### ISSUE TITLE
[testing] Allow declarative testing of native components

### ISSUE THREAD

**Issue by jarrodek** [salesforce/lwc#1813]
**Is your feature request related to a problem? Please describe.**
If I understand correctly, LWC also targets off-core environments which leads to various use scenarios of a component. Currently, at least as much as I can see in the documentation, the tests are based on imperative use. 

To visualize:

```javascript
const element = createElement('my-greeting', {
  is: MyGreeting
});
document.body.appendChild(element);
```

This is not how you normally construct an instance of an element. You either create an instance  declaratively or you would use `document.createElement()`. You can technically register an element in your tests and then create some helper function that construct the template and insets it into the DOM but that would be a repetitive task to do.

**Describe the solution you'd like**
I would like to see a helper method in tests that will allow me to use a component in a declarative fashion. This function would create a fragment of the DOM, would inset it to the body, and returns a reference to the first, top most element in the template.

```javascript
import { fixture } from '@lwc/testing'; // <- this is just an example. It can be whatever. Just not sure why testing framework is included into the same package as lwc. **Don't** reference it in comments.

describe('my-element', () => {
  async function basic() {
    return await fixture(`
    <template>
      <my-element attr="value"></my-element>
    </template>
    `);
  }

  it('has a property set from an attribute', async () => {
    const element = await basic();
    assert.ok(element.attr);
  });
});
```

The fixture function inserts the element to the body. The method is asynchronous so the returned element is already upgraded when returned by the function. This allows to start testing without constantly using timeouts to test the behavior of the component.
It also manages the lifecycle of the test so when the test finish it automatically removes inserted element from the body so manual clean up is not necessary. Alternatively you can expose another helper method like `testCleanup()` that would clean up the body. 

**Describe alternatives you've considered**
Generally doing it manually but it doesn't scale. Each developer would have to find a way of doing this. Most won't even bother.

**Comment by caridy** [comment]
There are two things here:

1. `createElement` API
2. provide an abstraction to facilitate testing

For 1), that's marked as experimental API, and it is just there because of IE11 and platform. In user-land code, that should never be used, same in tests, instead you should use the WC mechanism:

```
customElements.define('my-greeting', MyGreeting.CustomElementConstructor);
const element = document.createElement('my-greeting');
document.body.appendChild(element);
```

There is nothing special about that code, and existing abstractions for WC should work here the same way.

For 2), we did create a runtime compiler, similar to that, we ended up removing it (probably still around), but only accessible in our own tests for framework, but we walked away from it due to other hazard, in favor of karma, with the proper compilation step.

**Comment by pmdartus** [comment]
On the custom element usage, if you are using jest to run the tests, it would require to change the environment to consume jsdom version 16.2 and above (jest packages jsdom version 15). This is the version where we landed custom element support in JSDOM.

Thanks for voicing your concerns concerning the testing ergonomics. I would be happy to collaborate with you to see how we can make testing more elegant and maintainable.

**Comment by nolanlawson** [comment]
Following up on Caridy's comment, I think the `CustomElementConstructor` API does solve much of this use case. As for the use case of "I want to create components at runtime in the browser," this is not planned and likely will never happen. (Although as https://lwc.dev shows, you can run the LWC compiler in a web worker! 🤓 )

Closing for now, please reopen if we've misunderstood the request.
