### ISSUE TITLE
Use "module" entry to recognize ESM version of a package

### ISSUE THREAD

**Issue by jarrodek** [salesforce/lwc#1817]
**Is your feature request related to a problem? Please describe.**

The problem surface when trying to use `sinon` package in tests but imports in the component file would also benefit from correct module resolution. A package.json may contain the `module` property that points pout to the generated ESM file that should be resolved when requiring the module from ESM code.

So instead of importing a module like this:

```javascript
import sinon from 'sinon/pkg/sinon-esm.js';
```

I would like to import it like this:

```javascript
import sinon from 'sinon';
```

Sinon's "module" entry says where the ESM is:

```json
"module": "./pkg/sinon-esm.js",
```

With current module resolution the author of a component needs to know internal structure of the package to learn what file to import. This should not work this way.

**Comment by caridy** [comment]
I'm not sure what is the ask, can you elaborate more? all our pkgs are defining the non-standard entry in the package.json: https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine/package.json#L5-L6

So, if you import them from a file that can resolve using those non-standard mechanism, it should work.

I don't understand what is what you're importing from a component. For that component to work in platform, were no npm is available, they component can't resolve that as part of the bundling process. Is that what you're looking for? Why a component attempt to import sinon?

**Comment by jarrodek** [comment]
I am not importing anything from any component. I am importing something from an npm package to tests. When importing sinon it is trying to compile the source of sinon which is unnecessary because sinon has already ESM ready version.

**Comment by diervo** [comment]
It's your code the one that is deciding how to resolve the imports... Depending on the tool (rollup, webpack) and the environment (node, browser) and the configuration and plugins you use, you can achieve and resolve however you like it...

**Comment by pmdartus** [comment]
The LWC module resolver will not attempt to resolve non-LWC modules. If you are using rollup for application bundling, you can rely on the `@rollup/plugin-node-resolve` to do this. Here is an example of a rollup config mixing both LWC modules and NPM packages: https://github.com/pmdartus/rcast/blob/master/scripts/rollup.config.js#L50-L54. For Webpack-based applications, it should work out of the box.

Since NPM packages resolution is out of the scope of the LWC modules resolver, I will close this issue for now.
