### ISSUE TITLE
MutationObserver not working in Portal context

### ISSUE THREAD

**Issue by pibenett** [salesforce/lwc#1821]
### Description
MutationObserver seems to be working in local dev server, playgrounds, etc. but not in a portal context where we never reach the callback fn.

#### Steps to Reproduce

- Try to observe a div attribute's mutation for example

```js

renderedCallback() {
this.setObserver();
}
setObserver() {
  let mo = new MutationObserver(  (mutationsList) => {
    for (let mutation of mutationsList) {
        // do some stuff
    }
  });
  let config = {
      childList: true ,
      attributes: true
  }
  let div = this.template.querySelector('div');
  mo.observe(div, config);
}

// random click event with style modification
handleClickDiv(event) {
  let div= event.target;
  div.style.width = '10px';
}
```

#### Expected Results
We reach the MutationObserver callback fn

#### Actual Results
We never reach the MutationObserver callback fn

### Browsers Affected
At least the last version of Chrome

### Version

- LWC: x.x.x

**Comment by pmdartus** [comment]
Thanks for reporting this issue @pibenett. Just to clarify, what you mean by "in a portal context" is in the context of a Salesforce application?

**Comment by pibenett** [comment]
In a community context sorry we're used to call it "portal" :).

**Comment by pmdartus** [comment]
@seksenov @manuel-jasso I debug through the code on a scratch org and it appears that the issue originates from Locker. In the example above Locker is filtering out the `MutationRecord` because it considers the target not to be accessible from the component.

**Comment by manuel-jasso** [comment]
Thanks @pmdartus, I created W-7434565 to track this, FYI @seksenov

**Comment by pibenett** [comment]
Hello,
Do you have by chance any news about this about this topic? 
Thanks

**Comment by manuel-jasso** [comment]
Hello @pibenett, we are working on a solution but we have pros/cons to ponder before deciding on implementation, we should be able to make a decision this week and after that we can communicate a timeframe.  

Cc @seksenov @jdalton

**Comment by manuel-jasso** [comment]
Hi @pibenett, we identified the root cause and are working on a fix, our normal workflow is to fix things for our next major release, but please let us know your priority.

Cc @seksenov @animmakayala @salesforce/ui-security

**Comment by pibenett** [comment]
Hi @manuel-jasso! 
Thanks for your answer.
The community i'm working on will go live in production at the beginning of september so if by chance it could be fixed before it would be very great :).

**Comment by pibenett** [comment]
Hello!
Any news please? Seems that the problem is still here on my side :s

**Comment by manere** [comment]
@pibenett What ever happend to this? Any updates on this?
