### ISSUE TITLE
Performance issue when passing array down in grand-level children components.

### ISSUE THREAD

**Issue by wojciechSlodziak** [salesforce/lwc#1833]
### Description
There seems to be a big negative performance impact when passing array down into grand-level children components and accessing it there.

#### Steps to Reproduce
Someone already described it thoroughly on stackexchange.
https://salesforce.stackexchange.com/questions/295924/array-find-and-array-findindex-has-worst-performance-in-lwc-lightning-locker

Performance screenshot from Chrome Dev Console:
![image](https://user-images.githubusercontent.com/3159153/79550312-75ebe680-8098-11ea-8dd0-a25fb1cdbcd0.png)
This piece of code is just accessing the array to check for it's **length**.

#### Workaround
I am currently using JSON.stringify + JSON.parse combination, to workaround the issue.
In Parent component, instead of passing Array object (Proxy) into children I am passing JSON instead.

In grand-grand-Children I am parsing the JSON, and the performance is fine.

**Comment by amorek** [comment]
I was affected by this issue in old Aura in the past and had to do shallow copy for performance boost.

**Comment by caridy** [comment]
yeah! no much we can do in LWC since Locker is a layer on top of it, but the good news is that I have been working with the locker team to solve this problem in locker by changing the way locker sandboxes LWC components, stay tune. I can keep this open until that is out in production.

**Comment by caridy** [comment]
cc @seksenov @manuel-jasso

**Comment by manuel-jasso** [comment]
As per @seksenov we're tracking this internally via W-7045423

**Comment by abdulsattar** [comment]
This is fixed in [Lightning Web Security](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.security_lwsec_intro).
