### ISSUE TITLE
[synthetic-shadow] always appends elements to the shadow by default

### ISSUE THREAD

**Issue by gonzalocordero** [salesforce/lwc#1840]
### Description
With synthetic shadow on, appending any element to a custom element assumes appending it to the shadow by default, however, the semantic is "incorrect" since in theory you could append an element to a custom element's light DOM. 

#### Steps to Reproduce

```
    customElements.define('my-test', buildCustomElementConstructor(Test));
    const element = document.createElement("my-test");
    const input = document.createElement('input');
    element.appendChild(input);
```

With synthetic on: `document.querySelector('my-test').shadowRoot.querySelector('input')` returns true
With synthetic off: `document.querySelector('my-test').shadowRoot.querySelector('input')` returns null

#### Expected Results
Mimic the real shadow behavior, only attach to the element when is explicitly specified. 

#### Actual Results
Any appendChild operation will result in appending to the "shadow". 

### Browsers Affected
All

### Version
LWC 1.1.5

**Comment by diervo** [comment]
@gonzalocordero you should be using the new API not the deprecated one :)

**Comment by caridy** [comment]
This will be solved by https://github.com/salesforce/lwc/pull/1594, it will take a while, up until now we have been saying that root elements do not support slotting.

**Comment by gonzalocordero** [comment]
Thanks @caridy. 

FYI @jarrodek

**Comment by jarrodek** [comment]
I believe the title is a little bit misleading. It should be "Don't append elements to the shadow" as in this case I was able to append an element to as shadow DOM from the outside the shadow boundary and by calling non-shadow DOM related APIs.

**Comment by nolanlawson** [comment]
This issue should be fixed by now. Please reopen if I'm mistaken.
