### ISSUE TITLE
Inherit css from page

### ISSUE THREAD

**Issue by a-v-w** [salesforce/lwc#1841]
Most apps have reusable styling & reset styles like "normalize.css". Based on my research the only way to utilize reusable styling is to use the "@import" approach which is a rather bulky approach in my opinion and also doesn't make using libraries like SLDS practical as you would be importing a massive css library for every component that needs to utilize the styling.

If would be nice if there was a way that your components can utilize css rules loaded on the page.

I have tried writing only the necessary styling needed per component but it's rather frustrating to have to specify a variant of a spacing rule in 20 different components.

I hope I am just being absent minded and the solution to my problem already exists I just haven't found it online.

**Comment by pmdartus** [comment]
Letting the style from the page leak into components break the encapsulation and couple your components with a specific page. This goes against how Shadow DOM works and the overall philosophy this project is pursuing.

> I have tried writing only the necessary styling needed per component but it's rather frustrating to have to specify a variant of a spacing rule in 20 different components.

Did you try to create a shared module with your utility CSS rules? You can find more details in the [documentation](https://lwc.dev/guide/css#share-css-style-rules).

**Comment by thiakil** [comment]
How does one make that work with something like SLDS?

It works if you keep it in one component, but starts to break down when you use sub-components - https://github.com/thiakil/lwc-os-slds
This example uses `salesforce-lightning-design-system.sanitized.css` from the slds zip download as it's not possible to use the main one due to "unsupported selectors" like `:root`

The "split" combo box's list items don't get their padding, so unless I'm missing something it's not as simple as 'just add it as a module'.
The css is also repeated in each component's shadow root, which means we'd need to split out only the relevant css to avoid too much memory bloat?

**Comment by thiakil** [comment]
Seems this is a larger issue of the Shadow Root in general, and perhaps a major difference between LWC on SF and LWC Open Source - it seems SF doesn't use the native Shadow Root?

Some reading:
- https://www.smashingmagazine.com/2016/12/styling-web-components-using-a-shared-style-sheet/ (2016)
- https://css-tricks.com/styling-a-web-component/ 2019 (updated 2020)

So at the moment, it seems like there is no good solution for reusing existing CSS libraries with LWC in Shadow Root mode.
Would it be possible to run LWC OS without Shadow Root? (i.e. as more Custom Elements than Web Components)

**Comment by thiakil** [comment]
And now I found the synthetic-shadow package - https://salesforce.stackexchange.com/a/271910

Hopefully this helps those like me who came across this issue without knowing about that - it's not mentioned on the CSS pages on lwc.dev, only the Composition->Shadow DOM section (nor does the boilerplate seem to show its usage)

**Comment by nolanlawson** [comment]
We now support light DOM mode. Since this is an issue with shadow DOM in general, I'll close this issue for now.

Related discussion on general styling of shadow roots: https://github.com/WICG/webcomponents/issues/909

Please reopen if I made a mistake in closing this.
