### ISSUE TITLE
field duplication doesn't cause a compilation error

### ISSUE THREAD

**Issue by diervo** [salesforce/lwc#1844]
### Description

As per https://github.com/salesforce/lwc/issues/1843 if a user defines a decorated field and a getter/setter with the same name, due to our decorators transformation and the order which is execute with respect the class field babel plugin, the code will not fail, causing runtime ambiguous behaviour.

The compiler should throw.

**Comment by pmdartus** [comment]
I don't think this belongs to the compiler, the example you are referencing is valid javascript. It rather belongs to linting. We already have https://github.com/salesforce/eslint-plugin-lwc/issues/25 tracking this specific issue.

If you are fine with this approach, let's close this issue.
