### ISSUE TITLE
Add npm module resolution test to @lwc/rollup-plugin

### ISSUE THREAD

**Issue by gonzalocordero** [salesforce/lwc#1845]
We should consider enhancing our tests for `@lwc/rollup-plugin` to include tests to cover resolution for an NPM package as outlined here: https://rfcs.lwc.dev/rfcs/lwc/0020-module-resolution#npmmodulerecord

As we get into exposing more NPM modules, we should make sure that there is a test that people can use a reference.

Thanks!

**Comment by diervo** [comment]
@gonzalocordero is there an issue? we do have test and an 90% coverage:

https://github.com/salesforce/lwc/tree/master/packages/%40lwc/module-resolver/src/__tests__/fixtures

https://github.com/salesforce/lwc/tree/master/packages/%40lwc/rollup-plugin/src/__tests__/fixtures/multi_version

**Comment by gonzalocordero** [comment]
@diervo All good, by reading the test descriptions I couldn't find one that was mapping to the NPM use case, but  the one with `"multi-package-version"` does.
