### ISSUE TITLE
[IE11] EventTarget.dispatchEvent() returns true even when a handler calls preventDefault()

### ISSUE THREAD

**Issue by bakhtiari** [salesforce/lwc#1848]
### Description
`EventTarget.dispatchEvent()` returns `true` even when one of the event handlers calls `Event.preventDefault()`. This only happens on IE.
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent

However, the `defaultPrevented` property of the event (https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented) has the correct value which is currently being used as a workaround

#### Steps to Reproduce
Try the following on IE:

```
// child component
const autofocus = this.dispatchEvent(
  new CustomEvent('autofocus', { cancelable: true })
);
if (autofocus) {
  console.log('focus()');
}

// parent component:
handleaAutoFocus(event) {
  event.preventDefault();
}
```

The following code works:

```
const autoFocusEvent = new CustomEvent('autofocus', {
  cancelable: true,
});
this.dispatchEvent(autoFocusEvent);

if (!autoFocusEvent.defaultPrevented) {
  console.log('focus()');
}
```

**Comment by nolanlawson** [comment]
IE is no longer a supported browser, so it's unlikely we'll fix this. Closing for now, please reopen as necessary.
