### ISSUE TITLE
querySelector result is always empty if file makes a non-default export

### ISSUE THREAD

**Issue by rgalanakis** [salesforce/lwc#1891]
### Description

If an LWC makes a default export for its component, plus an additional export, then `template.querySelectorAll('div')` (or any selection) is empty. Removing the additional export removes this bug.

#### Steps to Reproduce

Using this template:

```html
<template>
    <div>what in the world</div>
</template>
```

And this JavaScript:

```js
import { LightningElement, api } from "lwc";

// THIS IS THE MONEY LINE
export const t1 = 123;

export default class MyComponent extends LightningElement {
	@api reportValidity() {
		console.log('div count', this.template.querySelectorAll('div').length);
	}
	renderedCallback() {
		console.log('div count', this.template.querySelectorAll('div').length);
	}
}
```

The query selector will always return 0 results, no matter what.

If you remove the `export const t1` line (so there is only the default export) this problem disappears.

You can see the diff between the compiled versions here: https://www.diffchecker.com/iFhvJQBF

I tried to repro this in the playground but couldn't: https://developer.salesforce.com/docs/component-library/tools/playground/ol0g50Fk0/1/edit

However I don't think it's any issue in our org, as it's a pretty simple dev org.

#### Expected Results

The query selector is not empty.

#### Actual Results

The query selector is empty.

### Browsers Affected

Chrome 81 and probably more.

### Version

Not sure, this is in Salesforce, API version 48.

**Comment by pmdartus** [comment]
After debugging this looks like a locker issue.
/cc @caridy

**Comment by the-last-byte** [comment]
Afternoon!  Just writing to say that this is still an issue in API version 50.

**Comment by rgalanakis** [comment]
Note that this is causing an additional problem we just discovered. We have an element in our template like:

```html
<input onclick={handleClick} />`
```

Given a controller file like:
```js
export const WHAT_A_WORLD = 1;

export default class MyComponents extends LightningElement {
  handleClick(e) {
    console.log(e.target.classList)
  }
}
```

The target in handleClick is the `MyComponent` element, NOT the actual element that receives the event (it looks like something in `SecureDOMEvent()` `createFilteredProperty` traversal eats things up).

Any update on resolving this?

**Comment by caridy** [comment]
hmm, this sounds like a bug in locker. in theory, it should not touch that event because it hasn't propagated outside of the shadow boundary yet, remember that locker doesn't have jurisdiction inside shadows. cc @manuel-jasso to follow up on that front.

**Comment by manuel-jasso** [comment]
I updated [W-8386672](https://gus.lightning.force.com/lightning/r/0D5B000001J5QVyKAN/view) to follow-up internally.

**Comment by vincentducorps** [comment]
Any update?

**Comment by manuel-jasso** [comment]
Hi @vincentducorps, sorry for the delay, the result of our investigation is that our current version of Locker doesn't support multiple exports from a module that renders a component, this is why removing the `export const t1 = 123;` makes it work. Current Locker is in maintenance mode and we won't be adding this capability to it, but we are currently working on "Locker vNext", our next-generation Locker, and Locker vNext will support this use case. We plan to have Locker vNext available for our "Summer '22" release.

Cc @caridy @animmakayala @seksenov @salesforce/ui-security

**Comment by rgalanakis** [comment]
Could you add a console error or some other type of way to avoid people having to discover this limitation themselves purely from trial-and-error?

**Comment by manuel-jasso** [comment]
> Could you add a console error or some other type of way to avoid people having to discover this limitation themselves purely from trial-and-error?

@rgalanakis, this is a fair question but it is for @seksenov (Locker Product Manager) and @animmakayala (Locker Engineering Manager)

**Comment by seksenov** [comment]
Hello @rgalanakis we will be adding this issue to our external developer documentation so that it is known and documented. Long term we are woking on fixing the issue and releasing it in a future release.
