### ISSUE TITLE
Re-render error with custom lightning datatables

### ISSUE THREAD

**Issue by hxk1633** [salesforce/lwc#1895]
### Description
This is the re-render error via JS/Lightning App Builder :
**TypeError: Cannot read property 'detach' of undefined < c-custom-data-table >**
The data table is taking advantage of custom types which extends the lightning data table class.
#### Steps to Reproduce
Go to Lightning App Builder and delete the custom data table. A re-render error appears. You will also get this error when you try to re-render the custom data table or remove it in the LWC Javascript code. Note that this error can not be reproduced with a normal lightning data table (< lightning-datatable >).

### Source of error:
File name: https://windstream--devkaiser.lightning.force.com/components/lightning/datatable.js
Function: i.disconnectedCallback

**Comment by pmdartus** [comment]
Thanks for reporting this issue @hxk1633. I will have close it since it doesn't follow the issue template. Please share the actual component code in the issue template and join it if possible with playground link.
