### ISSUE TITLE
Is there a way to globally handle apex errors (like HTTP 500) in LWC?

### ISSUE THREAD

**Issue by leonicolas** [salesforce/lwc#1900]
Is there a way to globally handle apex errors (like HTTP 500) in LWC, something similar to Aura doneWaiting even or XMLHttpRequest load event? 
Currently, to do it, It's necessary to add a catch on every wired call promise.

**Comment by kevinv11n** [comment]
This question is specific to LWC on Lightning Platform so I'll close this issue shortly.

But to answer your question - no, there is no mechanism to do this. If you use a data manager - presentation component structure, you could centralize the data loading and thus error handling in the data manager component.

**Comment by leonicolas** [comment]
Thank you @kevinv11n
