### ISSUE TITLE
export WireAdapter and WireAdapterConstructor

### ISSUE THREAD

**Issue by mburr-salesforce** [salesforce/lwc#1909]
The wire reform changes introduced a contract between wire adapter authors and LWC that is described by the [WireAdapter](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine/src/framework/wiring.ts#L192) and [WireAdapterConstructor](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine/src/framework/wiring.ts#L227) interfaces. The Typescript definitions of these interfaces should be exported from LWC so that wire adapter authors are not forced to duplicate them in their own code.

**Comment by priandsf** [comment]
The dataCallback interface also needs to be exported (and probably renamed DataCallback)

**Comment by caridy** [comment]
Hmm, I might be missing something here. If the `wire` decorator is exposed (and it is), then its declaration, and dependencies are going to be automatically exported. So, on that sense, component's authors need nothing else.

Oh, I see... adapters authors don't use `wire` decorator at all. This makes total sense... @jodarove can you take care of this?

**Comment by mburr-salesforce** [comment]
The exported types are working fine, but need to add `ConfigValue`, `ContextValue`, and `WireAdapterSchemaValue` to the list.

**Comment by caridy** [comment]
@jodarove can you look into that?

**Comment by jodarove** [comment]
Fixed with #1951
