### ISSUE TITLE
Allow multi page application

### ISSUE THREAD

**Issue by aslambari** [salesforce/lwc#1915]
We are easily able to setup LWC application using https://lwc.dev/. But as per given example, we are only able to setup Single Page Application. Our client needs a Multiple Page Website using this framework. How to do that?

We have lwc-services.config.js file. In that file also we are allowed to give only 1 sourceDir. This way, LWC OSS only supporting Single Page Application. I can see we have a default Client folder in application. In that we have index.html / index.js files. If i want different files for other pages like "login.html", "about.html", "myaccount.html", then it does not work. I tried different ways, but what i see is that only index.html/index.js works. Any other files failed to load or work.

Any idea, how to achieve multi page website using this framework?

**Comment by pmdartus** [comment]
Thanks for reporting this use case @aslambari. This is a new feature request for [create-lwc-app](https://github.com/muenzpraeger/create-lwc-app/). As far I as understand, there is no way today with the create-lwc-app to have multiple entry points in the application.

I will close this issue on the LWC repository. We can continue the discussion on https://github.com/muenzpraeger/create-lwc-app/issues/611

**Comment by muenzpraeger** [comment]
@aslambari Not sure I understand the issue. `lwc-services` supports multiple entry points that you can define via a [custom webpack config](https://webpack.js.org/concepts/entry-points/#multi-page-application).

**Comment by aslambari** [comment]
@muenzpraeger The lwc application using "lwc-services.config.js" file. I am not sure how to configure it for multiple pages. As per @pmdartus this is not possible right now in current implementation.

If you can explain little bit, it would be great.

**Comment by muenzpraeger** [comment]
@aslambari The bundling happens in the default configuration using `webpack`. If you want to have multiple entry points for the dependency graph you'd have to build a custom `webpack.config.js`, based on the above linked configuration, and pass it via the `-w` parameter to your buildscripts.

**Comment by muenzpraeger** [comment]
Also let's take the discussion to [here](https://github.com/muenzpraeger/create-lwc-app/issues/611), if there is any further discussion needed.
