### ISSUE TITLE
Cannot construct TextDecoder

### ISSUE THREAD

**Issue by chrinder** [salesforce/lwc#1931]
### Description
An exception is thrown in a component when trying to create an instance of TextDecoder("utf8").
#### Steps to Reproduce

1. create a component
2. add TextDecoder("utf8") instance creation to the constructor
3. add the component to a lightning app
4. open the app.
```js
export default class App extends LightningElement {
    constructor() {
        super();
        new TextDecoder('utf8');
    }
}
```

#### Expected Results
TextDecoder is constructed

#### Actual Results
Failed to construct 'TextDecoder': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

**Comment by chrinder** [comment]
@manuel-jasso Is this a LWC issue or Locker Issue.  In the [Locker API Viewer](https://developer.salesforce.com/docs/component-library/tools/locker-service-viewer) it shows that TextDecoder is supported.

**Comment by manuel-jasso** [comment]
Hi @chrinder this looks like a Locker issue. We're tracking internally with **W-7715657**

FYI @seksenov @caridy @pmdartus

**Comment by chrinder** [comment]
@manuel-jasso. Thank you. Any idea on where it falls in the dev queue to be looked into as to when it might be fixed? Thanks again.

**Comment by manuel-jasso** [comment]
@chrinder We will prioritize this week and will let you know a timeline after that. Thanks for the follow-up.

Cc @seksenov @animmakayala

**Comment by manuel-jasso** [comment]
Hi @chrinder, @p-wu-214 had a fix for this and will be available for our next major release.

FYI @seksenov @animmakayala @salesforce/ui-security

**Comment by chrinder** [comment]
Thank you!  Really appreciate it.
