### ISSUE TITLE
Can not set api attribute capture from a component

### ISSUE THREAD

**Issue by jodarove** [salesforce/lwc#1957]
### Description
A component with an `@api` attribute named `capture` (also others from [this list](https://github.com/salesforce/lwc/blob/master/packages/@lwc/shared/src/html-attributes.ts#L10)) can't be set to `true` (or `false`) on the template; it throws a compile error:

```
LWC1037: To set a boolean attributes, try <c-child capture> instead of <c-child capture="true">. If the attribute is present, its value must either be the empty string or a value that is an ASCII case -insensitive match for the attribute's canonical name with no leading or trailing whitespace.
```

#### Steps to Reproduce

https://developer.salesforce.com/docs/component-library/tools/playground/3nIYhsgem/1/edit

#### Expected Results
No error, `capture` is a boolean attribute of `input type=file` only.

#### Actual Results
Compile Error: `LWC1037: To set a boolean attributes, try <c-child capture> instead of <c-child capture="true">. If the attribute is present, its value must either be the empty string or a value that is an ASCII case -insensitive match for the attribute's canonical name with no leading or trailing whitespace.`

### Browsers Affected
All

**Comment by ekashida** [comment]
Just to add a little more context: We currently only consider the attribute name when determining whether it is boolean or not. Since all boolean attributes are not global attributes, we should also be considering the element.
