### ISSUE TITLE
Maintain Id attribute on templates after rendered

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#1969]
**Is your feature request related to a problem? Please describe.**
If I declare an attribute Id in my template it gets overwritten after rendered. This will simplify the way we create e2e tests and we can stop using the community suggestion of adding a data-id to the component.

**Describe the solution you'd like**
I would like to declare an Id in my template and see it as I declared when the component is rendered.

**Describe alternatives you've considered**
I'm using data-id as my Id when I need it.

**Comment by pmdartus** [comment]
@AllanOricil Thanks for raising this issue. For accessibility reasons and because of shadow DOM, the `id` attribute has to be transformed at runtime. By transforming the id attribute value it is possible to guarantee its uniqueness across the page.

I agree with you, using classes or `data-*` attributes to query the DOM is not as straight forward as global ids. That being said, we are not ready to make this tradeoff.

**Comment by AllanOricil** [comment]
@pmdartus no problem. 
I recommended it because I saw React and Vue maintain their IDs.

**Comment by pmdartus** [comment]
Yes, this is because React and Vue don't operate in the Shadow DOM and don't attempt to polyfill it.

**Comment by AllanOricil** [comment]
@pmdartus what if we give the Id and then an immutable attribute is created automatically after the component is rendered? Like, if I pass the Id="myPreciousButton" then the rendered component could have data-id="myPreciousButton", it could be name too. I don't know if it is over engineering but I really hate to add a fake Id just for testing all the time.

**Comment by pmdartus** [comment]
I am personally not a fan of adding such implicit behavior. @caridy @diervo Any thought about this proposal?

There is plenty of alternatives outside id refs. Nothing prevents you from using the tag name, the class name, or other more complex CSS selectors to target DOM nodes for E2E testing.

**Comment by caridy** [comment]
yeah, the theory is what eventually, once we start moving into native shadow, the mangling is not needed, and the code will work the same way... adding an extra magical argument means that in native shadow, we will have to also do that even when the value is the exact same as the id, which is not ideal. As @pmdartus said, adding a little bit more code on your side to find the elements is just a far better solution that will last without any extra magic or consequences.
