### ISSUE TITLE
LWC Engine No Longer Has VM Accessible (in Tests)

### ISSUE THREAD

**Issue by KevSlashNull** [salesforce/lwc#1981]
### Description

Hey! This is not a documented feature and I’m not sure if it’s a bug. This is related to the [sfdx-lwc-jest](https://github.com/salesforce/sfdx-lwc-jest) project but the “feature” came from the lwc engine.

I was using the LWC VM (`Symbol(ViewModel)`) in `v0.5.5` to obtain access to the `cmpTrack` variables and `component` methods of an element as they are not accessible through `createElement`. Sometimes I want to directly check the value of a tracked variable or (which is more important to me) execute methods that I don’t want to annotate with `@api`.

Do you plan on implementing it again or is there another way to accomplish this? In Apex there is the `@TestVisible` annotation which is really helpful for making small units but something similar doesn't exist in LWC to my knowledge.

#### Steps to Reproduce

1. Install `@salesforce/sfdx-lwc-jest` in version 0.5.5
2. Create an empty LWC with one track variable or a method.
```js
import { LightningElement, track } from "lwc";

export default class TestComponent extends LightningElement {
    @track hello = "world";
    
    testMethod() {
        this.hello = "people";
    }
}
```
3. Write a test that will print the symbols of the element
```js
import { createElement } from "lwc";
import testElement from "c/testElement";

describe("c-test-element", () => {
    it("has view model", () => {
        let element = createElement("c-test-element", { is: testElement });
        document.body.appendChild(element);
        
        expect(Object.getOwnPropertySymbols(element).find(item => item.toString() === "Symbol(ViewModel)")).toBeTruthy();
        // Here we could access the VM and execute the `testMethod` -> element[viewModelSymbol].component.testMethod();
    });
});
```

#### Expected Results
In <= `v0.5.5` of sfdx-lwc-jest this works.

#### Actual Results
In >= `v0.8.0` of sfdx-lwc-jest this does not work.

### Browsers Affected
none

### Version

- Works in `@lwc/engine`: "0.37.4-220.2"
- Doesn’t work in `@lwc/engine`: "1.3.7-226.4"

**Possible Solution**
A possible solution would be to add the following line to the `node_modules/@lwc/engine/dist/engine.cjs.js` but it’s a very hacky way that I’m reluctant to use in a business environment.

```js
exports.createElement.getAssociatedVM = getAssociatedVMIfPresent;
```

**Additional context**
I know that accessing tracked variables which are also present in the UI is not good practice. The use case for it would be to check them if they are not shown in the UI.

**Comment by pmdartus** [comment]
Thank you for reporting this detailed issue @KevSlashNull.

We are not planning to expose the component internal component state outside the component (regardless of the environment the component is running in). We made the decision early in LWC development that the internal component state should not be accessed by the testing code to ensure to enforce true component unit testing.

I will this issue for now since we are not planning to fix it.
