### ISSUE TITLE
Chrome can't find a button in the DOM using CSS Selector

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#1989]
### Description
I used Chrome built in functionality to get the CSS selector of the Filter button in the data table, but it seems Chrome can't find it. I have also tested with other types of selectors chrome has, and only the `Xpath' worked. 

This image shows the DOM structure and the button element I tried to select.
![image](https://user-images.githubusercontent.com/55927613/88205817-36a7d580-cc45-11ea-90e0-b4a0af28d2e9.png)

When using the generated CSS selector to select the Button the result is `null`
![image](https://user-images.githubusercontent.com/55927613/88207472-c0f13900-cc47-11ea-9ea3-c0fd884bbaf2.png)

Then I started to delete the css selector until I could see an element on the console. It worked, I was able to see a component element.
![image](https://user-images.githubusercontent.com/55927613/88207733-20e7df80-cc48-11ea-9f04-982e8c30c2c1.png)

But I needed to get a button that was inside of this component. Then I applied `> *` to get all the Children of this element and the result was `null`. So It showed to me that I can't go further in the DOM to select elements using CSS.
![image](https://user-images.githubusercontent.com/55927613/88207840-4379f880-cc48-11ea-81c8-ad58d7d657aa.png)

But what caught my attention is that using the full xpath Im able to do it without any problem
Chrome Xpath
![image](https://user-images.githubusercontent.com/55927613/88207398-a4ed9780-cc47-11ea-8909-69927a34b2e8.png)

Firefox Xpath
![image](https://user-images.githubusercontent.com/55927613/88206927-f6495700-cc46-11ea-8de4-40b160c3f7e5.png)

I don't know if this a framework issue or a browser issue. I just know that css selectors don't work in both Firefox and Chrome.

#### Expected Results
Chrome should be able to see the element using CSS

#### Actual Results
Chrome can't query the element using CSS

### Browsers Affected
Just noticed it with chrome.

**Comment by ekashida** [comment]
@AllanOricil What you're observing is the restriction put in place by LWC's shadow dom polyfill. You can learn more about shadow dom here: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

Could you describe a little more about what you're trying to accomplish?

**Comment by AllanOricil** [comment]
> @AllanOricil What you're observing is the restriction put in place by LWC's shadow dom polyfill. You can learn more about shadow dom here: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM
> 
> Could you describe a little more about what you're trying to accomplish?

@ekashida I'm trying to create automated E2E tests using Nightwatch/Cypress. What do you recommend me to do?

**Comment by AllanOricil** [comment]
@ekashida the link above did not work. I was not able to bring the shadow element to the dom. After running the code below it removed all the elements of the screen. So how am I suppose to create e2e tests using css selectors ? I could not find Salesforce documentation about it.

````javascript
// Iterate over all elements in the main DOM.
for (let el of document.getElementsByTagName('*')) {
   // If element contains shadow root then replace its 
   // content with the HTML of shadow DOM.
   if (el.shadowRoot) el.innerHTML = el.shadowRoot.innerHTML;
}
````

![image](https://user-images.githubusercontent.com/55927613/89293174-60092e00-d655-11ea-96f2-bcdbaa21a4c3.png)

**Comment by AllanOricil** [comment]
Could somebody explain to me why I can't select the child element using css? I really dont understand

![image](https://user-images.githubusercontent.com/55927613/89293825-7663b980-d656-11ea-9f5f-499175645861.png)

**Comment by AllanOricil** [comment]
Found another good [article](http://morlack-presentations.s3-website-eu-west-1.amazonaws.com/presentations/2017-webcomponents) of a possible solution. I will try it too.
