### ISSUE TITLE
Request: A state container mechanism for LWC

### ISSUE THREAD

**Issue by prashantk0001** [salesforce/lwc#1994]
**Is your feature request related to a problem? Please describe.**
As the requirements for LWC single-page applications have become increasingly complicated, our code must manage more events than ever before. UI events are also increasing in complexity, as we need to manage active routes, selected tabs, spinners, pagination controls, and so on.

Managing this ever-changing situation is hard. If a component can update another component, which updates another component, and this, in turn, might cause another component to update. At some point, you no longer understand what happens in your app as you have lost control over the when, why, and how of its events. When a system is opaque and non-deterministic, it's hard to reproduce bugs or add new features.

There's only a percentage of reusability which can be achieved when going with lwc, which requires the components to be loosely coupled through events. Real-world Client Requirements are mostly unique and it is hard to achieve reusability after some percentage of it is achieved. But what if we could create loosely coupled & abstract application modules that don't use event and yet can be re-used, this opens a path for us to create a manageable and reusable bundle of Lightning Web Components.

**Describe the solution you'd like**
A state container mechanism, so the above-listed problems could be resolved using this mechanism, I tried to build my own workaround using Redux, which is typically used with React and It seems to resolve the issues. It can be reviewed here, but the solution I am requesting could be more native to LWC and probably can re-use the already built mechanisms.

Here's where you can find my implementation: [lwc-redux](https://github.com/prashantk0001/lwc-redux)

**Describe alternatives you've considered**
Alternatively, I checked other state container mechanisms, Flux, MobX, but found Redux which has a large community and plugins available already.

**Additional context**
![Example](https://raw.githubusercontent.com/prashantk0001/lwc-redux/master/docs/lwc-event-vs-redux.jpg)

This will help us bind the components inside a module tightly but make the module completely reusable and decoupled.
The proposed solution should be made to work with existing event-based architecture.

**Comment by caridy** [comment]
@prashantk0001 thanks for articulating the issue, sounds good.

It has been our position that you should be able to implement redux, or any of the other shared state mechanism with LWC today without requiring any changes to its engine. I will be curious what do you think can be improved in LWC to better support that. Do you have a concrete example of what is missing that will make your life easier as a library developer authoring lwc-redux? As far as I can tell, there is nothing missing. When you say native support in LWC, I suspect that you're either argueing that we should provide an out of the box library for that, which I don't think we will, or you're referencing to special funcionality that you will like to see available for you and others to create those libraries in user-land?

**Comment by diervo** [comment]
Here is an example repo (probably outdated how to use Redux with LWC: https://github.com/pmdartus/rcast

**Comment by prashantk0001** [comment]
@caridy  Thanks for taking a look, Redux part was just for example, I actually meant that similar feature could be provided natively, but the counter is equally good that we should be able to implement these of libraries. I have no further questions

**Comment by prashantk0001** [comment]
Closing since no further actions required.
