### ISSUE TITLE
Missing declaration for `querySelector` / `querySelectorAll` on ShadowRootTheGoodPart

### ISSUE THREAD

**Issue by muenzpraeger** [salesforce/lwc#2017]
### Description
The types that are provided with the `lwc` package are incomplete, and [miss for example](https://github.com/salesforce/lwc/blob/master/packages/lwc/types.d.ts#L105-L128) `querySelector` / `querySelectorAll`. This breaks the compilation of TypeScript based projects.
 
#### Steps to Reproduce
1. Create a new LWC project with TypeScript.
2. Use in the project `this.template.querySelector('somediv');`

![image](https://user-images.githubusercontent.com/2205451/91849103-cfc20700-ec5b-11ea-8e57-975635c0b79c.png)

#### Expected Results
Proper typing support.

#### Actual Results
Running `tsc` throws error because of this.

### Browsers Affected
n/a

### Version
- LWC: 1.7.3

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by pmdartus** [comment]
Fixed with https://github.com/salesforce/lwc/pull/2067
