### ISSUE TITLE
@lwc/shared code is duplicated in published scripts in consuming packages

### ISSUE THREAD

**Issue by nrobertdehault** [salesforce/lwc#2024]
### Description

ESM and CJS scripts published for the packages consuming `@lwc/shared` contain duplicated code from `@lwc/shared` like `HTML_ATTRIBUTES_TO_PROPERTY`, `AriaPropertyNames` or `_globalThis` which are defined 3 times under different names. 

#### Steps to Reproduce

Build locally and search `packages/@lwc` for the `const HTML_ATTRIBUTES_TO_PROPERTY$` string. 

#### Expected Results
No match, published ESM/CJS scripts do not contain duplicated code

#### Actual Results
Search above returns the following matches, meaning that `HTML_ATTRIBUTES_TO_PROPERTY` in this example is defined at least twice under different names: 

```
packages/@lwc/engine-core/dist/engine-core.js
packages/@lwc/engine-core/dist/engine-core.cjs.js
packages/@lwc/engine-dom/dist/engine-dom.js
packages/@lwc/engine-dom/dist/engine-dom.cjs.js
packages/@lwc/engine-server/dist/engine-server.cjs.js
packages/@lwc/engine-server/dist/engine-server.js
packages/@lwc/engine/dist/engine.js
packages/@lwc/engine/dist/engine.cjs.js
packages/@lwc/synthetic-shadow/dist/synthetic-shadow.js
```

### Browsers Affected
n/a

### Version
- LWC: 1.7.14

**Comment by nolanlawson** [comment]
Fixed by https://github.com/salesforce/lwc/pull/2416
