### ISSUE TITLE
dropdown-alignment parameter does not respect option of auto on lightning-combobox in LWC

### ISSUE THREAD

**Issue by yk92** [salesforce/lwc#2044]
**Description**
When using the lightning-combobox component and setting the dropdown-alignment parameter to a value of auto, the dropdown window is not working properly and opening upwards when space demands it.

**Expected Results**
Dropdown's alignment is dynamically determined and opens up when space below component is limited

**Actual Results**
Dropdown always defaults to opening downwards no matter the amount of space

**Browsers Affected**
only tested on Chrome

**Version**
LWC: 1.8.2 / Latest

**Possible Solution**

None that I know of, I tried everything I could think of but nothing works right

**Comment by EmilSabri** [comment]
Same issue here. Sad it hasn't been fixed in 3 years

**Comment by nolanlawson** [comment]
I'm sorry to hear that this is still affecting you @EmilSabri. FWIW, this is an issue in Lightning Base Components and not in the open-source LWC framework (this repo). The best way to get traction on this would be to post on [Salesforce Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) or open a [Salesforce case](https://help.salesforce.com/s/).

**Comment by EmilSabri** [comment]
@nolanlawson Just fixed it. As usual the culprit was myself 😔 Sorry!
