### ISSUE TITLE
Module not found: Error: Can't resolve 'lightning/platformResourceLoader'

### ISSUE THREAD

**Issue by jesusarockias** [salesforce/lwc#2048]
I have created a LWC (Lightening Web Component)by referring below documentation.

https://trailhead.salesforce.com/en/content/learn/projects/build-your-first-app-with-lightning-web-components-open-source/create-the-application

And, I expect to use jQuery by referring the below link

https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.js_third_party_library

But, getting module not found issue as follows,

`Module not found: Error: Can't resolve 'lightning/platformResourceLoader'`

Please can any one help me on this.

**Comment by jesusarockias** [comment]
Hello team!!!

Any update on this?

**Comment by ravijayaramappa** [comment]
The 'lightning/platformResourceLoader' component is part of lightning base components. They are available on the Salesforce platform and can be referenced as 'lightning/xxx' in your LWC components. 
However, for usage outside of Salesforce platform, they cannot be referenced as 'lightning/xxx'. [Here is more documentation](https://github.com/salesforce/base-components-recipes#experimental-use-base-components-outside-of-salesforce-platform) about how to use it outside of Salesforce platform.

**Comment by jesusarockias** [comment]
Thanks @ravijayaramappa 

So, if we use the method in below link, can we avoid this error.

https://sfdcmonkey.com/2019/02/15/lightning-web-component-deploy-org/

**Comment by ravijayaramappa** [comment]
In general, yes. If you author LWC components and push it to the salesforce org, your components should be able to reference lightning base components.
(Disclaimer: The link provided is not official Salesforce content. We are not responsible for the content or its accuracy)

**Comment by jesusarockias** [comment]
@ravijayaramappa I am using trail version and checking the compatibility of using a 3rd party UI component with Salesforce such as Syncfusion with it before deciding on this.

Yes, I am aware that we can use 3rd party libraries but we want to check it directly since these 3rd party component mostly create elements at runtime using "document.createElement". But, as per the standard of Salesforce LWC, we could not use these while create LWC.

https://developer.salesforce.com/docs/component-library/documentation/en/lwc/security_locker_dom

But, while checking by creating LWC as per the below link,
https://sfdcmonkey.com/2019/02/15/lightning-web-component-deploy-org/

I am getting the following error while connecting to Salesforce account
![image](https://user-images.githubusercontent.com/41784897/94424992-c3709180-01a8-11eb-845b-045c075770fc.png)

While searching in the internet, I found that trail version did not have the API support.

Please suggest me to connect my local salesforce project with high priority since my trail ends in 8 days,

Else, please let us know whether we can use the Syncfusion in LWC components that you can refer from the below links.

https://ej2.syncfusion.com/documentation/introduction/
https://ej2.syncfusion.com/demos/

**Comment by jesusarockias** [comment]
Hello team & @ravijayaramappa ,

Any help on the above query? 

Else, point me to the correct portal to ask this query to SalesForce team

**Comment by diervo** [comment]
Your best bet (since this has nothing to do with LWC or this repository) is to ask a question in our salesforce official forums such as [StackExchange](https://salesforce.stackexchange.com/questions/ask)

**Comment by jesusarockias** [comment]
Thanks @diervo I have created the below forum discussion

https://salesforce.stackexchange.com/questions/321137/compatibility-of-using-syncfusion-js-component-in-lwc

Whether the posted in that forum will be addressed by SalesForce team or community users?
