### ISSUE TITLE
No instructions on how to add to existing project

### ISSUE THREAD

**Issue by BrettMN** [salesforce/lwc#2056]
### Description

Some projects already exist and might want to use LWC but the "Installation" instructions in the documentation only show how to create a new project through `create-lwc-app` 

#### Steps to Reproduce

Try to add LWCs to an existing project following the "Installation" steps in guide.

#### Expected Results
Directions or documentation that show how to add LWC to a project

#### Actual Results
only directions for how to create new projects with create-lwc-app

### Browsers Affected
All

### Version

- LWC: Current

**Possible Solution**
Add Installation instructions

**Additional context/Screenshots**

**Comment by pmdartus** [comment]
FYI @gregwhitworth.

**Comment by AvanParvadiya** [comment]
I am new to SalesForce. I am working with nodejs. Now i want to add lwc in my existing project but i don't know how....
Can anyone can help me??

**Comment by pmdartus** [comment]
Added a new section to the installation page covering how to build LWC components using rollup: https://lwc.dev/guide/install#via-rollup. It is the recommended approach for integration LWC components with an existing project.

Closing this issue for now but feel free to comment if more information is required.
