### ISSUE TITLE
XSLTProcessor fails in lightening web component when added to page layout

### ISSUE THREAD

**Issue by sagar2dumbre** [salesforce/lwc#2069]
Hi,
I am trying to apply `XSLT` transformation to an `xml` file and display the output in `div` element. Below code works in the local development server. However, if I add this component in any page layout in salesforce, it failed with below error.

> TypeError: XSLTProcessor constructor: 'new' is required

Code:

```
import { LightningElement } from 'lwc';
import testXml from '@salesforce/resourceUrl/testXml';
import testXslt from '@salesforce/resourceUrl/testXslt';

export default class MyComponent extends LightningElement {

    renderedCallback() {
        const xsltProcessor = new XSLTProcessor();
        xsltProcessor.importStylesheet(testXslt);
        const result = xsltProcessor.transformToFragment(testXml, document);

        this.template.querySelector('.container').appendChild(result);
    }
}
```

Any suggestion to make it work within salesforce?

**Comment by pmdartus** [comment]
This looks like a locker related issue. From the [Locker  API viewer](https://developer.salesforce.com/docs/component-library/tools/locker-service-viewer) `XSLTProcessor` is supported, but the same error is reported when trying to running the code in [Locker Sandbox](https://developer.salesforce.com/docs/component-library/tools/locker-service-console).

@manuel-jasso

**Comment by animmakayala** [comment]
This is addressed in our current main (Spring '21 release).
