### ISSUE TITLE
Enabling Dev Tools Custom Formatters Causes Dev Tools to Miss Breakpoints

### ISSUE THREAD

**Issue by AlexBryner** [salesforce/lwc#2070]
### Description

Turning on the lwc custom formatter for console logs that unwraps proxies seems to keep dev tool breakpoints from being hit with minified code.  Able to produce in Salesforce Experience Cloud (communities), have not been able to reproduce within Core Salesforce.

> Custom formatters aren’t enabled by default in Chrome, so you’ll need to set Chrome DevTools => Settings => Enable custom formatters.

Turn off the custom formatter and everything works as expected.

#### Steps to Reproduce

Open a Salesforce Experience Cloud Page that has an LWC, Enable Custom Formatter and then refresh the page. After, open the sources tab in dev tools and set a breakpoint within an lwc do something that should trigger the break point but it won't.

Disable Custom Formatter, clear all breakpoints, and then refresh the page. After, open the sources tab in dev tools and set a breakpoint within an lwc and do something that should trigger the break point, now this works as expected.

I have been able to successfully produce this on 

https://developer.salesforce.com/docs/component-library/bundle/lightning-accordion/example
- Sources - components/componentreference/playground.js
- Setting a breakpoint on the playground component within the run preview method (formatted line 75)
- Then clicking the Run Button to refresh the preview

#### Expected Results

Breakpoints set within the Dev Tools Sources Tab should be hit when that code is reached.

#### Actual Results

While Custom Formatters are enabled break points are not hit.

### Browsers Affected

Chrome Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by pmdartus** [comment]
I wasn't able to reproduce this issue with the steps on the same Chrome version.
I am suspecting that a chrome extension might be interfering here. @AlexBryner Are you able to reproduce the same issue with the guest user profile without any chrome extension?

**Comment by AlexBryner** [comment]
I tried it on a clean install of chrome and was not able to reproduce this.  Thank you for looking into this @pmdartus I'll determine what is happening on my end
