### ISSUE TITLE
Navigation Mixin does not work

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2073]
### Description
I tried to use the navigaton example from the official docs, as it is, and it didn't work. On the local development server this example throws an error, while inside salesforce it does not throw anything.

https://developer.salesforce.com/docs/component-library/bundle/lightning-navigation/documentation

#### Steps to Reproduce

Create a LWC component with a button.

````html
<template>
<button onclick={onClickNavigationButton}>Go to Account Home</button>
</template>
````

````javascript
import { LightningElement } from "lwc";
import { NavigationMixin } from 'lightning/navigation';

export default class TestComponent extends LightningElement {

  onClickNavigationButton(){
    this[NavigationMixin.Navigate]({
      type: 'standard__objectPage',
      attributes: {
          objectApiName: 'Account',
          actionName: 'home',
      },
    });
  }
}
`````

or

````javascript
import { LightningElement } from "lwc";
import { NavigationMixin } from 'lightning/navigation';

export default class TestComponent extends LightningElement {

  onClickNavigationButton(){
    this[NavigationMixin.Navigate]({
      type: 'standard__objectPage',
      attributes: {
          objectApiName: 'Account',
          actionName: 'new',
      },
    });
  }
}
`````

#### Expected Results
It should send the user to the account home page or new page

#### Actual Results
on Local development server it throws this exception

![image](https://user-images.githubusercontent.com/55927613/97784852-5b431000-1b99-11eb-902f-bb10095189fd.png)

on Salesforce org it does not throw any error and it does not navigate the user to anywhere.

### Browsers Affected
Tested only on Chrome Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by pmdartus** [comment]
Hi @AllanOricil 

Thanks for taking the time to provide a detailed reproduction case. Any bug/question unrelated to the core LWC framework will not be responded to on this issue tracker. So I will close this issue.

For any question related to LWC dev server please refer to [lwc-dev-server-feedback](https://github.com/forcedotcom/lwc-dev-server-feedback). For any other questions, I would recommend posting it to [Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components).
