### ISSUE TITLE
maximumFractionDigits in datatable not working on currency field

### ISSUE THREAD

**Issue by w1h** [salesforce/lwc#2080]
### Description
maximumFractionDigits attribute should limit number of decimal place but it has no effect in datatable when field type is set to currency

#### Steps to Reproduce
Go to https://developer.salesforce.com/docs/component-library/bundle/lightning-datatable/example
Add `typeAttributes: { maximumFractionDigits: 0 }` on Balance column

```js
const columns = [{ label: 'Balance', fieldName: 'amount', type: 'number', typeAttributes: { maximumFractionDigits: 0 }},];
```

#### Expected Results
Balance
$685

#### Actual Results
Balance
$685.33

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/25964765/98557812-f4161180-22a4-11eb-8b16-e8abf1a63135.png)

**Comment by jye-sf** [comment]
Thanks for surfacing this.

The root issue here is that `lightning-formatted-number` gives priority to `minimumFractionDigits` over `maximumFractionDigits`, and our locale formats set the default for both to `2`. 

@w1h on your end, you can resolve this issue by adding an explicit `minimumFractionDigits`.
```
const columns = [{ label: 'Balance', fieldName: 'amount', type: 'number', typeAttributes: { minimumFractionDigits: 0, maximumFractionDigits: 0 }},];
```

On our end, we can look into either improving the documentation around this or enhancing the component to give priority to the value explicitly set by the user.

**Comment by jmsjtu** [comment]
Closing this as it is unrelated to LWC, please open a Salesforce Stack Exchange question or Salesforce Case if you're still experiencing this issue.
