### ISSUE TITLE
Template compiler doesn't properly recover from invalid HTML

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#2084]
### Description

The template compiler uses to a spec-compliant HTML parser ([parse5](https://github.com/inikulin/parse5)). Because of the permissive nature of HTML, the parser will attempt to fix invalid HTML structures. It appears that in some cases, the parser is not able to fix the HTML and keep the old HTML content arround.

#### Steps to Reproduce

Create a component will the following template and render it:

```html
<template>
    <tr>
        <unkonwn></unkonwn>
    </tr>
</template>
```

Example: https://webcomponents.dev/edit/WtUcBz1wPqeyJDzLw0Xc

#### Expected Results DOM structure
```html
<tr c-app_app=""></tr>
<unkonwn c-app_app=""></unkonwn>
```

#### Actual Results DOM structure

The `<tr>` element should be empty, but it contains the escaped version of the original HTML content.

```html
<tr c-app_app="">
  &lt;unkonwn&gt;&lt;/unkonwn&gt;
</tr>
<unkonwn c-app_app=""></unkonwn>
```

### Version
- LWC: 1.9.1

**Comment by nolanlawson** [comment]
I [tried to repro](https://stackblitz.com/edit/salesforce-lwc-rhmset?file=src/modules/x/app/app.html) but was unable:

![Screen Shot 2022-08-08 at 4 27 27 PM](https://user-images.githubusercontent.com/283842/183531462-b0baa48b-f678-4ac6-9b8a-356a38a2e67b.png)

This seems solved by #2429.
