### ISSUE TITLE
Lightning tree grid show some weird icons

### ISSUE THREAD

**Issue by Yasir-Sheriff** [salesforce/lwc#2101]
### Description
When I've chosen the lightning tree grid row-level record shows some weird icon 

![image](https://user-images.githubusercontent.com/52495811/99524289-3d114880-29be-11eb-9a9a-b6f31bce55ac.png)

![image](https://user-images.githubusercontent.com/52495811/99524347-51eddc00-29be-11eb-94fa-15571128537a.png)

#### Steps to Reproduce
Open link -> https://developer.salesforce.com/docs/component-library/bundle/lightning-tree-grid/example -> select any record chevron icon visible some black box icons

https://developer.salesforce.com/docs/component-library/tools/playground/4nOWks80l/1/edit

![image](https://user-images.githubusercontent.com/52495811/99525823-5e733400-29c0-11eb-9ff2-7bba073b3087.png)

### Version

- LWC: x.x.x

**Comment by AllanOricil** [comment]
I opened in my browser the playground link and it is working as expected. There is no weird icon appearing on my side.

**Comment by Yasir-Sheriff** [comment]
> I opened the playground link and the lightning tree component is working as expected. There is no weird icon appearing on my side.

Hello @AllanOricil  can you open the playground link and click on the chevron arrow in someplace you seeing some weird icons
![image](https://user-images.githubusercontent.com/52495811/99953717-b090cc80-2da7-11eb-8bb1-537a88880091.png)

I have tested Chrome, Microsoft Edge and Safari browser have the same issues 
but firefox in Windows 10 is working as expected but the same browser in MAC OS got the issues

**Comment by AllanOricil** [comment]
@Yasir-Sheriff below you can see what was rendered on my side.

![image](https://user-images.githubusercontent.com/55927613/99957256-4cf2a900-2d7f-11eb-9b29-0752ba6e7866.png)

My Chrome version
![image](https://user-images.githubusercontent.com/55927613/99957307-685db400-2d7f-11eb-9c07-98a16d92a091.png)

**Comment by AllanOricil** [comment]
@Yasir-Sheriff good news. I was able to reproduce the issue. It is a bad css class that is causing it. But to see it the user has to click between the Chevron and the Label. It is very hard to achieve it. But good you found.

![image](https://user-images.githubusercontent.com/55927613/99957961-69dbac00-2d80-11eb-9d73-b3f7112622b3.png)

**Comment by AllanOricil** [comment]
@Yasir-Sheriff I opened an issue on the design system repo too. Maybe it is on their side or the tree component is not using the right css classes.

**Comment by AllanOricil** [comment]
![image](https://user-images.githubusercontent.com/55927613/99958878-05b9e780-2d82-11eb-9b1a-2ffad72e17df.png)

**Comment by kflournoy-sf** [comment]
Hi @Yasir-Sheriff and @AllanOricil - FYI we actually have this bug already identified, and it's on the appropriate team's roadmap to address. Thanks for the report!

**Comment by jmsjtu** [comment]
Closing this as it is unrelated to LWC, please open a Salesforce Stack Exchange question or Salesforce Case if you're still experiencing this issue.
