### ISSUE TITLE
Getter does not Rerender Child component

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2105]
### Description
When an array  that a getter depends on changes, a child component that uses this getter does not rerender. Even if I call the getter once inside the method that changed `this._entries`, as shown in the code below, the child is not rerendering. Is it the expected behavior? Why?

````html
//PARENT
<template>
     //this child component is just printing the values in the array
    <c-child entries={_myEntriesGetter}></c-child>

     //this removes the entry from the array but the child does not rerender
    <lightning-button label="Remove Entry - Does no Work" onclick={removeEntry}></lightning-button>

     //this button removes the entry from the array and the child rerender
    <lightning-button label="Remove Entry - It Works" onclick={removeEntry_v2}></lightning-button>
</template>
````

````js
export default class Parent extends LightningElement {

get _myEntriesGetter() {
    return this._entries.map((view) => {
      return {
        label: view.label
      };
    });
  }

_entries = [
{
label: 'pera',
isSelected: false,
otherProp: false,
otherProp2: false,
otherProp3: false
},
{
label: 'abacaxi',
isSelected: false,
otherProp: false,
otherProp2: false,
otherProp3: false
}
];

//If I remove an element from the array, the child does not rerender.
removeEntry(){
this._entries.splice(0, 1);
//I can see it changed
console.log(this._myEntriesGetter);
}

//If I reconstruct the entire array after removing an element, the child is rerendered
removeEntry_v2(){
this._entries.splice(0, 1);
this._entries = [...this._entries];
}

}

````

#### Expected Results
The child component should rerender.

#### Actual Results
The child component is not rerendering.

**Comment by pmdartus** [comment]
This is the expected behavior, all the fields on an LWC component are tracked in a shallow fashion. You can use the `@track` to make the framework observe mutation on an object. More details about this can be found here:  https://lwc.dev/guide/javascript_reactive#field-reactivity

**Comment by AllanOricil** [comment]
> This is the expected behavior, all the fields on an LWC component are tracked in a shallow fashion. You can use the `@track` to make the framework observe mutation on an object. More details about this can be found here: https://lwc.dev/guide/javascript_reactive#field-reactivity

@pmdartus thank you for your response 👍
