### ISSUE TITLE
Modules folder hierarchy greater than 2 levels?

### ISSUE THREAD

**Issue by FlyGuy352** [salesforce/lwc#2125]
Hi, 

This is an example reflecting the current structure of my project modules folder.

modules
├───codemod
│   ├───coreModController
│   ├───coreModHelper
│   ├───coreModMarkup
│   ├───utilModComponentCallExpressions
│   ├───utilModControllerMethodDefinition
│   ├───utilModHelperCallExpressions
│   └───utilModProgram
└───ui
    ├───app
    │   └───__tests__
    └───greeting
        └───__tests__

When I tried to create another folder under the utilModProgram directory for example, I can't seem to be able to access the JavaScript file within from my import statements. Is there a limit to the depth of the directory structure being enforced?

**Comment by pmdartus** [comment]
LWC doesn't enforce any limit on the folder structure depth.

Please share a minimal repro (as a standalone LWC project or an SFDX project) so we can qualify properly the problem you are facing. Until then, I will close this issue.

**Comment by FlyGuy352** [comment]
I've set up a sample repro here: https://github.com/FlyGuy352/LWCFolderDepthLimit. In particular, I've commented the issue in https://github.com/FlyGuy352/LWCFolderDepthLimit/blob/main/src/client/modules/namespace1/app/app.js.

May I also refer you to https://rfcs.lwc.dev/rfcs/lwc/0020-module-resolution#detailed-design.

Thanks.
