### ISSUE TITLE
Lightning Input : type="search" shows "clear" icon even after setting the disabled property to true when it has a value

### ISSUE THREAD

**Issue by prashantk0001** [salesforce/lwc#2128]
#### Steps to Reproduce

Lightning Input : type="search" shows "clear" icon even after setting the disabled property to true when it has a value, it clears the value when clicked on.

https://webcomponents.dev/edit/QMxvLx4jYY3dP1ARL2r0

```
<lightning-input
            name="enter-search"
            label="Search when user hits the 'enter' key"
            type="search"
            value="some value" 
            disabled>
</lightning-input>
```

#### Expected Results
Should not show the clear icon when input is disabled and has a value. When clicked, it should not clear the value of disabled input.

#### Actual Results
currently shows the clear icon when input is disabled and has a value.When clicked, it clears the value of disabled input.

### Browsers Affected
All
### Version

**Possible Solution**

Below CSS could fix issue within component's CSS file:
```
input[disabled] + lightning-primitive-icon + div {
	display: none;
}
```
OR
Render the icon conditionally using disabled property

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

![image](https://user-images.githubusercontent.com/37791818/101721131-44170c80-3acd-11eb-90b2-9daffdd6ddca.png)

**Comment by pmdartus** [comment]
From the Lightning Component team: 

> Due to the low priority nature of these bugs, we do not have the bandwidth to address them. Please reopen this bug only if it is a business blocker.

**Comment by wasimsk9579** [comment]
i want search icon at right corner side
