### ISSUE TITLE
`lightning-input[type="checkbox"]` required do not allow save unchecked value

### ISSUE THREAD

**Issue by gonardfreeman** [salesforce/lwc#2144]
#### Steps to Reproduce

- Create input
- report inputs validity

```js
this.inputEl.reportValidity();
```

#### Expected Results
Input is valid if unchecked

#### Actual Results
Error: complete this field

### Browsers Affected

not browser specific

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![Screenshot 2020-12-24 at 13 41 14](https://user-images.githubusercontent.com/16113714/103086608-b4558000-45ed-11eb-9bc1-0cc283940430.png)

**Comment by jmsjtu** [comment]
Closing this as it is unrelated to LWC, please open a Salesforce Stack Exchange question or Salesforce Case if you're still experiencing this issue.
