### ISSUE TITLE
Action slot in lightning-card not appearing in proper place.

### ISSUE THREAD

**Issue by rrcook** [salesforce/lwc#2146]
### Description
I'm working on a small app in Salesforce and porting it to lwc-oss, using the lightning base components. I have a lighning-button in an actions slot in a lightning-card. In Salesforce the button appears in the proper place, but in lwc oss the button appears above the lightning-card.

#### Steps to Reproduce

https://developer.salesforce.com/docs/component-library/tools/playground

``` 
       <lightning-card title={cardTitle}>
          <!-- Weather button goes here -->
          <div slot="actions">
            <lightning-button label="Get Weather" class="slds-m-around_medium" onclick={openWeatherTab}></lightning-button>
          </div>
        </lightning-card>
```

### Browsers Affected

Chrome and Firefox on macOS Catalina

### Version

- LWC: x.x.x

**Possible Solution**

**Additional context/Screenshots**
First screenshot is from Salesforce, second is from lwc-oss
<img width="741" alt="Screen Shot 2020-12-31 at 9 18 02 PM" src="https://user-images.githubusercontent.com/787296/103432596-910f6f80-4baf-11eb-8c87-145f77e53d1e.png">
<img width="937" alt="Screen Shot 2020-12-31 at 9 18 21 PM" src="https://user-images.githubusercontent.com/787296/103432597-97055080-4baf-11eb-8cfe-f84f6a8de270.png">

**Comment by rrcook** [comment]
I have a simpler example of the problem. Following these directions to make a lwc.dev style app with lightning base components and styling,
[https://developer.salesforce.com/blogs/2020/12/build-connected-apps-anywhere-using-lightning-base-components.html](url)
Then in between the container div and the link div, add a div with the lightning-card example,
```
        <div>
            <lightning-card  title="Hello">
                <lightning-button label="New" slot="actions"></lightning-button>
                <p class="slds-p-horizontal_small">Card Body (custom component)</p>
                <p slot="footer">Card Footer</p>
            </lightning-card>
        </div>
```
it renders as this:
<img width="1036" alt="Screen Shot 2021-01-03 at 4 34 16 PM" src="https://user-images.githubusercontent.com/787296/103489386-2abe6300-4de2-11eb-8130-ec548c88c8c4.png">

**Comment by FabienTaillon** [comment]
@pmdartus actually I don't think it's an external issue, but instead this seems to be linked to issue #2029.
If I look at the rendered DOM, we can see that the lightning buttons are not rendered in the correct slot location.
Manually moving the DOM elements where they should be rendered fix the issue:

![image](https://user-images.githubusercontent.com/2465122/116858887-6e45a400-abff-11eb-88fb-44d4e2735c18.png)

**Comment by jmsjtu** [comment]
See #2029
