### ISSUE TITLE
Remove manual resolution of systeminformation dependency

### ISSUE THREAD

**Issue by ravijayaramappa** [salesforce/lwc#2149]
### Description
PR https://github.com/salesforce/lwc/pull/2145 introduces a manual resolution of `systeminformation` package version. This is to address a [security vulnerability](https://github.com/sebhildebrandt/systeminformation/security/advisories/GHSA-m57p-p67h-mq74). 

The usage of "systeminformation" package is as follows
perf-benchmarks > @best/cli > @best/utils > systeminformation
Issue filed for best repo salesforce/best#263

When can the manual resolution be reverted?
Once @best/utils updates its version of systeminformation, the manual resolution in lwc can be reverted.

**Comment by diervo** [comment]
@ravijayaramappa I will update all the best dependencies this week.

**Comment by nolanlawson** [comment]
All manual `"resolution"`s have been removed.
