### ISSUE TITLE
LWC embed in angular application

### ISSUE THREAD

**Issue by ajay312** [salesforce/lwc#2159]
I have LWC component and it must render in angular component .Steps to follow embed Lwc in angular

**Comment by pmdartus** [comment]
I would recommend looking at https://developer.salesforce.com/blogs/2020/11/how-to-use-apex-natively-with-svelte-vue-and-preact-within-lwc.html explaining how to integrate other popular frameworks with LWC on Salesforce. This might work depending on how your Angular app is setup.

An alternative approach would be to use the [lightning:container](https://developer.salesforce.com/docs/component-library/bundle/lightning:container) component (only available in Aura). This is the most straightforward approach to integrate third-party applications on Salesforce.

For further guidance, I would recommend posting your question [StackExchange](https://salesforce.stackexchange.com/).

**Comment by ajay312** [comment]
@pmdartus  We have Angular application which is build on  latest version .Could we use angular components in LWC application with out using Lightning container?

**Comment by nolanlawson** [comment]
@ajay312 You can use any third-party framework without lightning:container by using `lwc:dom="manual"`. It looks like you can use a technique [like this](https://angular.io/guide/dynamic-component-loader) to render Angular components into arbitrary DOM elements.

Note though that if you are trying to embed an entire application that does its own routing, etc., then you will need lightning:container.

**Comment by pmdartus** [comment]
@ajay312 I would also recommend looking at this issue https://github.com/salesforce/observable-membrane/issues/59 if you are planning to load Angular in the same document as LWC. Zone.js aggressively patches some JavaScript APIs that might result in breaking LWC reactivity system in certain cases.
