### ISSUE TITLE
resize event handler doesn't work for lightning-tree-grid component

### ISSUE THREAD

**Issue by vkamenskyi** [salesforce/lwc#2162]
### Description

lightning-tree-grid resize event cannot be handled in the host component

#### Steps to Reproduce

1. create a new custom component;
2. put `lightning-tree-grid` component inside the template;
3. set columns and data with valid values;
4. set `onresize` handler for the `lightning-tree-grid`;
5. debug the resize event on changing tree grid column width in the browser;

```html
<template>
    <lightning-tree-grid 
        key-field="id" 
        columns={columns} 
        data={data} 
        onresize={handleResize}>
    </lightning-tree-grid>
</template>
```

```js
import { LightningElement, track, api } from 'lwc';

export default class App extends LightningElement {
    columns = [{label:'Value', fieldName:'value'}, {label:'Label', fieldName:'label'}];
    data = [
        {id:'1', label: 'first', value: 'first'},
        {id:'2', label: 'second', value: 'second'}
    ];

    handleResize(event) {
        console.log('... resize ...', event.detail);
        alert('Resize!');
    }
}
```

#### Expected Results
Resize handler should invoke on column width change

#### Actual Results
Resize handler doesn't invoke on column width change

### Browsers Affected
Chrome, Version 87.0.4280.88 (Official Build) (x86_64)

### Version
Salesforce Winter '21

**Comment by jmsjtu** [comment]
Closing this as it is unrelated to LWC, please open a Salesforce Stack Exchange question or Salesforce Case if you're still experiencing this issue.
