### ISSUE TITLE
Error: `Assert Violation: Failed to construct...`

### ISSUE THREAD

**Issue by aputinski** [salesforce/lwc#2208]
### Description

When run in Jest, I'm getting an error `Assert Violation: Failed to construct '<tds-avatar>': The result must not have attributes` when calling `document.createElement` on an element registered using `CustomElementConstructor`. This seems to be related to decorating properties that already exist on `LightningElement` such as `title`. Runs in the browser with no problem.

#### Steps to Reproduce

https://github.com/aputinski/lwc-test-case-failed-attributes

### Version
- LWC: 1.17.0

**Comment by aputinski** [comment]
This is related to https://github.com/salesforce/lwc/issues/2209. No error is thrown when using a named class.

**Comment by nolanlawson** [comment]
Closing old issues, please reopen if you have a reproducible test case. Thanks!
