### ISSUE TITLE
@lwc/babel-plugin-component doesn't inject registorDecorators for unnamed classes

### ISSUE THREAD

**Issue by aputinski** [salesforce/lwc#2209]
### Description

For some reason, `@lwc/babel-plugin-component` doesn't call `registorDecorators` when exporting a default unnamed class.

#### Steps to Reproduce

https://runkit.com/600f007886d884001ad1a0c5/600f0078b5a1e60019ee02cd

### Version
- LWC: 1.17.0

**Comment by pmdartus** [comment]
FYI @ekashida it would be great to add a test for this specific case as you are reworking the transformer.
