### ISSUE TITLE
Hot reload without refreshing the entire page

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2210]
**Is your feature request related to a problem? Please describe.**
The lightning dev server is cool. It helps me a lot to locally visualize the changes I do to my components. It really speeds up the development. But it also introduces a small waste of time, which is irritating. It refreshes the entire page every time I save any change. Even when it is just a simple CSS class addition.

**Describe the solution you'd like**
Stop reloading the entire page and just update the component that has been changed. You can use the Vue DX to improve the LWC local dev server and improve its DX.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
N/A

**Comment by diervo** [comment]
HMR was implemented a month or so ago https://github.com/salesforce/lwc/pull/2071
Is not "publicly available" via types but you can use it (we tried webpack integration and it works like a charm). We are using it internally for a project we will unveil soon. @Gr8Gatsby could add you to the pilot if you are interested.

**Comment by AllanOricil** [comment]
@diervo I would like to try. @Gr8Gatsby could you add me to this pilot?

**Comment by gonardfreeman** [comment]
@diervo is that will be available for localdev on salesforce?

**Comment by diervo** [comment]
Yes it all will be using the same architecture and stack underneath!

**Comment by pmdartus** [comment]
Closing this issue since there is no action item for the LWC team.

**Comment by AllanOricil** [comment]
@diervo is this solution publicly available???

**Comment by diervo** [comment]
We will be presenting it at dreamforce, stay tuned :)
