### ISSUE TITLE
LocalDevServer rebuilds whole project after saving one file.

### ISSUE THREAD

**Issue by gonardfreeman** [salesforce/lwc#2214]
I'm not sure is this would be a feature or it is a bug or something wrong with my setup.
As I can see it creates hashes to every file and changes hash only to saved file, so I assume it have been almost done or done already.

**Is your feature request related to a problem? Please describe.**
It would be great that local dev server do not rewrite every single file after save of one file.

**Describe the solution you'd like**
After I save file localdevserver rewrites(rebuilds) only saved file.

**Environment** 
MacOs BigSur 11.1
SFDX version `sfdx-cli/7.82.1-0 darwin-x64 node-v11.15.0`
LocalDev `@salesforce/lwc-dev-server:2.9.0`
NPM 6.14.10
Node 11.15.0

**Comment by pmdartus** [comment]
I moved this issue to the appropriate repo https://github.com/forcedotcom/lwc-dev-server-feedback/issues/99.
