### ISSUE TITLE
A way to find LWC utilization on the web

### ISSUE THREAD

**Issue by gregwhitworth** [salesforce/lwc#2237]
**Is your feature request related to a problem? Please describe.**
Currently, when trying to derive LWC utilization on the web we look at NPM downloads and other similiar utilization boards. In order to further understand its utilization in the longer tail of the web I'd like to see a fingerprint that we can key on when doing an httparchive big query to identify scenarios that may not be running the LWC engine. Currently one can do this for sites that include a reference of LightningElement but this doesn't capture sites such as lwc.dev that are built with LWC but don't need the client side engine to function.

**Describe the solution you'd like**
As noted above, some solution like:
`<meta name="lwc" content="1.8">`

**Describe alternatives you've considered**
Tracking down a generic fingerprint in the dist bundles. Unfortunately I haven't been able to find especially given that some of the usecases denoted above do not have JS.

**Comment by pmdartus** [comment]
It's interesting to put a meta tag. I am not aware of any other framework inserting a meta tag on evaluation for tracking purposes.

The HTTP Archive big query does contain a table for response body `httparchive:response_bodies`. We can potentially look for `LightningElement`. I am wondering if it's a better alternative. I don't have enough credits on my personal GCP account to run this query :/

```sql
SELECT url  
FROM `httparchive.response_bodies.2020_10_01_desktop` 
WHERE REGEXP_CONTAINS(url, r"\.js") AND REGEXP_CONTAINS(body, r"LigthningElement") 
LIMIT 1000
```

**Comment by gregwhitworth** [comment]
@pmdartus already ran that query on BigQuery (I can send you the results) - and got a lot of results but the majority of them lightning out scenarios. The issue here is that if you go to lwc.dev for example there is no JS and thus no way of knowing utilization on static sites.

> It's interesting to put a meta tag. I am not aware of any other framework inserting a meta tag on evaluation for tracking purposes.

You're correct, ironically this is quite annoying at times for browser vendors. I even tried once to find actual web utilization of lodash, sure we all know it's out there but what specifically and what specifically is called? It helps in prioritizing performance optimizations or future standards. I had discussed a package.json type approach in the response body to JDD (back in our MS days) which would require some standard involvement but would help solve this.

**Comment by pmdartus** [comment]
> The issue here is that if you go to lwc.dev for example there is no JS and thus no way of knowing utilization on static sites.

The lwc.dev main page doesn't use LWC at all, it's a pure static page. Some of the documentation pages use LWC for the playground (for example: [HTML Template](https://lwc.dev/guide/html_templates)). Do you know if HTTP archive only indexes the main page or if it indexes all the pages?

**Comment by nolanlawson** [comment]
Currently one way you can do this is by checking `'lwcRuntimeFlags' in globalThis`. However, this may not always be true in the future.

I would be curious to know how popular "built with" tools actually figure this out for React, Vue, et al. Some of these don't even attach globals to the `window`, so I'm not sure how you could identify them.

**Comment by nolanlawson** [comment]
Closing as it's not clear to me that there's an action item on the LWC OSS repo for this. There are dashboards showing library/framework usage across the web with analyze the HTTP responses to sniff for certain patterns ([e.g.](https://w3techs.com/faq)). If such a site wanted to track LWC usage, they could use the above patterns to figure it out (e.g. `lwcRuntimeFlags`, `LightningElement`).
