### ISSUE TITLE
Could not resolve "FlowComponent.propertyName". You can say myField, myField.myChoice.selected, or myField.myChoice.input

### ISSUE THREAD

**Issue by gmpmovies** [salesforce/lwc#2258]
### Description
I am getting the following error message every time I run a flow, that does not actually appear to experience the error described. The exact error message is `Could not resolve 'JobRunStatus.statusJson.' You can say myField, myField.myChoice.selected, or myField.myChoice.input`. And here is what I have setup:

The very last step in a flow I have setup displays a custom LWC which accepts one parameter: `statusJson`.

<img width="311" alt="Screen Shot 2021-03-01 at 2 46 07 PM" src="https://user-images.githubusercontent.com/43527569/109563339-dd3a3b80-7a9c-11eb-9749-1efad0f5ff4b.png">

Here you can see the component setup, and it is receiving a JSON string that will be parsed and organized by the component and displayed to the user.

<img width="1218" alt="Screen Shot 2021-03-01 at 2 47 35 PM" src="https://user-images.githubusercontent.com/43527569/109563483-12468e00-7a9d-11eb-80f6-f91b5143ddc9.png">

The target config of the .js-meta.xml file for the component looks like this:
```
<targetConfigs>
        <targetConfig targets="lightning__FlowScreen">
            <property name="statusJson" type="String" label="Status JSON Response" description="Enter the JSON response from the Job Run Status Endpoint here." required="true"/> 
        </targetConfig>
    </targetConfigs>
```

and the actual .js file contains the code to capture the config variable and use it in the component:
```
    _statusJSON = '{}';
    isLoaded = false;

    @api
    get statusJson() {
        return this._statusJSON;
    }

    set statusJson(val) {
        this._statusJSON = this.formatJobRunInfo(val);
        this.isLoaded = true;
    }
```

When I run the flow, everything appears to work perfectly, and the custom LWC displays as expected with the correct data sent through the JSON string.

<img width="856" alt="Screen Shot 2021-03-01 at 2 50 53 PM" src="https://user-images.githubusercontent.com/43527569/109563849-897c2200-7a9d-11eb-8df4-0a3d687ea6ac.png">

However, when I hit finish, I am suddenly seeing an error saying that the statusJson variable could not be resolved, when in fact it appears that it did resolve and everything functioned properly. I could in fact be doing something wrong, however this does appear to be a bug since the config property is resolving just fine and the component is displaying as expected. There haven't been any issues with this component until today.

<img width="851" alt="Screen Shot 2021-03-01 at 2 51 49 PM" src="https://user-images.githubusercontent.com/43527569/109563948-a87ab400-7a9d-11eb-9de5-291ac2877b14.png">

**Comment by pmdartus** [comment]
Thanks for reporting this details bug @gmpmovies. However, I will have to close it.

This repository is not the appropriate channel to report bugs related to Salesforce Flows. We only accept issues and feature requests related to the LWC core framework on Github. Bugs related to the Salesforce platform should be reported by logging a support case.
