### ISSUE TITLE
Getting/setting properties in connectedCallback()

### ISSUE THREAD

**Issue by mihmunta** [salesforce/lwc#2262]
I would like to know why Salesforce LWC documentation recommends not to get/set fields in the connectedCallback(). Instead of which they recommend using getters and setters(isn't that essentially the same to just setting fields directly?). The link to the documentation is [here](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/reference_lifecycle_hooks). What is the reasoning behind this and also does this concern LWC only or HTML web components in general? Link to  [stackexchange](https://salesforce.stackexchange.com/questions/334634/lwc-setting-properties-in-connectedcallback)

**Comment by pmdartus** [comment]
Ahah, good timing @mihmunta! I just finished responding to that post on StackExchange: https://salesforce.stackexchange.com/a/335846/12482.
