### ISSUE TITLE
lightning-formatted-number: Currency symbol is not displayed in specific conditions

### ISSUE THREAD

**Issue by pkozuchowski** [salesforce/lwc#2272]
We have strange case where in browser's incognito mode for specific users, currency symbol is not displayed on some of the components. 
For example, in incognito mode on my QA's user, the datatable will display first row without currency symbol, while other rows have currency symbol and it works on my salesforce user.

I don't think I can get reproduction steps that would work on any environment...

First row does not have symbol, but entire column has the same setup:
![image](https://user-images.githubusercontent.com/4470967/111783226-494cda00-88ba-11eb-9712-dcc94fcce68a.png)

All rows use the same currency configuration:
![image](https://user-images.githubusercontent.com/4470967/111783296-5b2e7d00-88ba-11eb-80d8-5bfe31059ecb.png)

Screenshots from debug session for the component without symbol:
![Screenshot_1](https://user-images.githubusercontent.com/4470967/111783437-84e7a400-88ba-11eb-8736-e1ec410cb81c.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/4470967/111783441-85803a80-88ba-11eb-87f4-63e71d7234b6.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/4470967/111783442-8618d100-88ba-11eb-875a-7b0c284649b6.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/4470967/111783443-8618d100-88ba-11eb-84b6-ca97a4ceee84.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/4470967/111783446-86b16780-88ba-11eb-8999-91bd07f81253.jpg)

**Comment by jmsjtu** [comment]
Closing this as this is an issue with Lightning Base Components, please open a Salesforce Stack Exchange question or Salesforce Case if you're still experiencing this issue.
