### ISSUE TITLE
Wire Adapter fails to preserve `this` context when passed a class member

### ISSUE THREAD

**Issue by gelliott181** [salesforce/lwc#2274]
### Description
When using a method as part of a wire configuration the framework drops the `this` context of the function.

#### Steps to Reproduce
Step 1: Create a class with a function to call that returns the `this` of the class.
Step 2: Create a wire adapter for that class.
Step 3: Wire a component using the previous objects.
Step 4: Access the `this` value in the service class method. If the method called is `async` the value will be undefined. If the method called is not `async` the value will be the wire adapter object. Neither is the class object intended or expected to be accessed.

Reproduction
https://webcomponents.dev/edit/mi3E7orbvoWyvkcHc4ov

#### Expected Results
The `this` context used in the class methods is the class instance itself

#### Actual Results
When no `async` methods have been wired, `this` is assigned to the Wire Adapter object.
When a wire adapter has been used to wire an `async` method, `this` is undefined for `sync` and `async` methods using the same adapter class.

### Browsers Affected
Chrome V89

### Version
- LWC: Whatever you have running on the platform.

**Additional context/Screenshots**
It's possible to work around this by using `bind()` to directly bind the class object to a method instance and pass that in. This isn't ideal as my original intent was to use wires to handle function composition (in this case creating new Observable streams) and move non-UI logic up out of display components (hampered by the additional getters required to bind methods).

Currently I am working around this by not using `this` to access class members where I want to wire something. That's also not great, it breaks well known and widely used JS syntax.

**Comment by pmdartus** [comment]
Thanks for opening this issue @gelliott181. The fact that the `this` value is the method is not bound to the original object is to be expected.

Each time one of the properties of the wire config changes, the LWC engine creates a new object config collects all the values and invokes the wire adapter with the new config. You can think of the adapter config the same way as an object you pass to a function. When the dynamic expressions are resolved, the method is dereferenced from its original object explaining why the `this` value changes.

Let me take an example to illustrate this:

```js
import { LightningElement, wire } from 'lwc';
import Adapter from './adapter';

export default class extends LightningElement {
  @wire(Adpater, { prop: '$foo.bar' })
  wiredProp;
}
```

The LWC compiler transforms this into:

```js
import { LightningElement, wire } from 'lwc';
import Adapter from './adapter';

export default class extends LightningElement {
  wiredProp;
}

registerDecorators(App, {
  wire: {
    wiredProp: {
      adapter: Adapter,
      dynamic: ["prop"],
      config: function ($cmp) {
        return {
          prop: $cmp.foo?.bar
        };
      }
    }
  }
});
```

As you dereference the `bar` method from the `foo` object, the `this` value will is not preserved when invoking `foo`. You have multiple options to keep the `this` intact:
- bind the `bar` method to the `foo` object as you mentioned previously.
- turn the `bar` method into an arrow function expression and trapping the `this` value inside it.
- pass `foo` in the config and let the adapter invoke `foo.bar`.

**Comment by gelliott181** [comment]
@pmdartus thanks for the explanation! The missing registerDecorators transform helped me see where `this` wasn't. Will this be noted in platform documentation in the future?

Specific to the issue that uncovered this I've gone with an arrow function as an abstract factory to keep `this` in the proper scope and execute the factory I was originally attempting to pass. I've also started to restructure our service modules to be more wire-friendly down the road.
