### ISSUE TITLE
Ability to hide the date part and apply timezone attribute in the inline-edit mode for the lightning-datatable

### ISSUE THREAD

**Issue by KrutoiAlik** [salesforce/lwc#2288]
**Is your feature request related to a problem? Please describe.**
The lightning-datatable doesn't support time-only fields, but it supports **date** type with additional type attributes to show only the time part.
`type: "date",
                typeAttributes: {
                    hour: "2-digit",
                    minute: "2-digit",
                    timeZone: "UTC"
                }`
The problem is the time format doesn't work properly in the inline-edit mode as it shows the date with time, but not time only.
The view mode: 
![image](https://user-images.githubusercontent.com/28713787/113433924-c1ea8500-93e8-11eb-8a01-f97215a913a6.png)
The inline-edit mode: 
![image](https://user-images.githubusercontent.com/28713787/113433972-d464be80-93e8-11eb-9cf5-1871d002908d.png)
Also, it shows time part with user's locale, when the UTC is selected.

**Describe the solution you'd like**
It would be great to be able to hide the date part and apply UTC format when the inline-edit mode is turned on.

**Describe alternatives you've considered**
I have tried to make the custom data type with a time field within it but wasn't able to view the dropdown with time options. As a workaround, I removed a truncate in the cell, but the dropdown was within the cell with scroll down and it didn't overflow as I expected. If it is possible to achieve, it would be great to have an opportunity to make the dropdown with time options visible not inside the cell, but the datatable.

**Comment by jmsjtu** [comment]
Closing as this is an issue with Lightning Base Components, please open a Salesforce Stack Exchange question or Salesforce Case if you're still experiencing this issue.
