### ISSUE TITLE
Mechanism to retrieve the current active element within the shadow DOM context

### ISSUE THREAD

**Issue by Gr8Gatsby** [salesforce/lwc#229]
_SOMA#1005_

### Migrated issue

notes:

Retrieving `document.activeElement` will potentially cause issues once we move to the Shadow DOM context. As such we'll need a more accurate method to retrieve the active element within a component's Shadow DOM context.

**Comment by FollowingFawn** [comment]
Is there a method to access the activeElement within a component's shadow DOM? this.querySelector().activeElement nor this.template.querySelector().activeElement are working for me.

**Comment by pmdartus** [comment]
You can access the active element in the component shadow tree using `this.template.activeElement` getter.
