### ISSUE TITLE
pwa build fails

### ISSUE THREAD

**Issue by gmineropfdrive** [salesforce/lwc#2291]
### Description
unable to build pwa project after running create-lwc-app

#### Steps to Reproduce
build a pwa using:
`npx create-lwc-app my-app -t pwa --yes`
build fails with error: Conflict: Multiple assets emit different content to the same filename index.html

#### Expected Results
Build should not fail

#### Actual Results

⌛  Creating build configuration
🌟  Using custom configuration from webpack.config.js.
📦  Starting build process.
🆘  Conflict: Multiple assets emit different content to the same filename index.html
NPM logs:
13 verbose stack Error: lwcbuilder@0.0.1 build: `lwc-services build -m production -w scripts/webpack.config.js`
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14
### Browsers Affected
n/a
### Version
    "dependencies": {
        "compression": "^1.7.4",
        "express": "^4.17.1",
        "helmet": "^4.4.1"
    },
    "devDependencies": {
        "eslint": "^7.24.0",
        "husky": "^6.0.0",
        "lint-staged": "^10.5.4",
        "lwc-services": "^3.0.4",
        "prettier": "^2.2.1"
    },
    "engines": {
        "node": ">=10.13.0",
        "npm": ">=6.4.1",
        "yarn": ">=1.9.4"
    },
18 verbose node v14.15.4
19 verbose npm  v6.14.10

**Possible Solution**

modify webpack.config to fix conflict.
remove
` { from: 'src/index.html', to: 'dist/'}`, 
 fro m the lwc-services.config file.

modify the webpack config  as follows:
`// Custom webpack configuration file, provides generation of service worker
// More information: https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin
const { GenerateSW } = require('workbox-webpack-plugin');
const path = require('path');
module.exports = {
    entry: './src/index.js',
    output: {
        path: path.join(__dirname, '..', 'dist'),
        filename: '[name].js',
    },
    plugins: [new GenerateSW({ swDest: 'sw.js' })]
};`

**Comment by pmdartus** [comment]
Moved to the appropriate repository: https://github.com/muenzpraeger/create-lwc-app/issues/832
