### ISSUE TITLE
Creating form using dynamic json

### ISSUE THREAD

**Issue by ajay312** [salesforce/lwc#2340]
Hi Team ,

We have requirement of  creating forms using dynamic json ..Example ng-formely in angular.

Any feature in LWC using this pattern?

**Comment by pmdartus** [comment]
I am not aware if there is an existing library that can create dynamic forms from JSON. That said I don't see any major blocker to create such a library on top of LWC.

I will close this issue as is outside the scope of the LWC framework.

**Comment by ajay312** [comment]
@pmdartus 

How to create a new customization library and publish in npm ?
