### ISSUE TITLE
@rollup/plugin-node-resolve v13 throws "TypeError: The importee argument must be a valid LWC module name"

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#2354]
### Description

Between `@rollup/plugin-node-resolve` v11 and v13 (there is no v12), a change was introduced which causes an incompatibility with `@lwc/rollup-plugin`.

- [Non-working repro with v13](https://github.com/nolanlawson/lwc-barebone/commit/f510374c172b91809ac8fee0191f73da2d683762)
- [Working repro with v11](https://github.com/nolanlawson/lwc-barebone/commit/e58e18ab4204176f5d833ae5fc0ad74e61c6bfb2)

#### Steps to Reproduce

Run `yarn && yarn build` on the above commits.

#### Expected Results

No error

#### Actual Results

Error thrown:

```
[!] (plugin node-resolve) TypeError: The importee argument must be a valid LWC module name. Received "/Users/nlawson/workspace/lwc-barebone/src/modules/x/app/app.html"
TypeError: The importee argument must be a valid LWC module name. Received "/Users/nlawson/workspace/lwc-barebone/src/modules/x/app/app.html"
    at resolveModule (/Users/nlawson/workspace/lwc-barebone/node_modules/@lwc/module-resolver/dist/commonjs/resolve-module.js:116:15)
    at Object.resolveId (/Users/nlawson/workspace/lwc-barebone/node_modules/@lwc/rollup-plugin/src/index.js:74:28)
    at /Users/nlawson/workspace/lwc-barebone/node_modules/rollup/dist/shared/rollup.js:18863:25
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

### Version

Fails in LWC 2.2.0, also fails back to 1.16.x at least.

**Possible Solution**

In `rollup.config.js`, explicitly tell `@rollup/plugin-node-resolve` to only resolve `.js`/`.mjs` files, so that it skips LWC `.html` and `.css` files:

```diff
-    nodeResolve(),
+    nodeResolve({
+      resolveOnly: [/.*\.m?js$/]
+    }),
```

**Comment by pmdartus** [comment]
I was looking into this issue today and this comes from https://github.com/rollup/plugins/commit/3a543dfd9142f936b0157893580c25f4cb729b0f#diff-dbc8c6c4e7383a37fbae0c12d8e6d8901c93631bb7774f4bd1a2a88bbe1980a0.

The `@lwc/rollup-plugin` expects all the relative imports to start with `.`. However `@rollup-plugin/node-resolve` now normalizes the path so depending on the plugin order invocation path might or not be normalized. To fix this `@lwc/rollup-plugin` should handle the case where a relative path starts with a `/` as well.
