### ISSUE TITLE
Property 'querySelector' does not exist on type 'ShadowRootTheGoodPart'

### ISSUE THREAD

**Issue by peternhale** [salesforce/lwc#2359]
### Description
[Repost from forcedotcom/cli #1030](https://github.com/forcedotcom/cli/issues/1030)

Summary
When you enable the type check to validate your work with JS in lwc folder, any usage of querySelector / querySelectorAll causes such issue. It doesn't block deploying the code. Installing node modules (npm install) doesn't resolve it.

Steps To Reproduce:
Create SFDX project

Create an LWC component

In lwc folder, in eslintrc.json file add property:

{
  "compilerOptions": {
      "checkJs": true,
  }
}

use this.template.querySelector("div"); in JS code;

Expected result
No error is detected by VS Code, because LWC LightningElement and LWC LightningElement.template properties and methods are defined in the .sfdx/typings/lwc folder

Actual result
Problems tab in VS Code shows "Property 'querySelector' does not exist on type 'ShadowRootTheGoodPart'. ts(2339)" issue;

Additional information
As the solution, it would be possible to define the NodeSelector interface that ShadowRootTheGoodPart extends in the engine.d.ts file. Even if you install the node_modules, this interface is still not found there (at least automatically, and I didn't find it manually)

VS Code Version: April 2021 (version 1.56)

SFDX CLI Version: sfdx-cli/7.94.3-a4e7c7955b darwin-x64 node-v14.15.4

OS and version: macOS Big Sur version 11.2.3

**Comment by pmdartus** [comment]
This is already the case https://github.com/salesforce/lwc/pull/2067.
