### ISSUE TITLE
How to Create a LWC library  and deploy in Salesforce platform??

### ISSUE THREAD

**Issue by ajay312** [salesforce/lwc#2404]
Team,
We have requirement of creation of LWC library and publish it in salesforce platform?
Suggest any Examples?

Thank you!

**Comment by AllanOricil** [comment]
What do you mean LWC library? Is it going to wrap some lwc/salesforce apis? if not, you can write your library with any es spec and then bundle it with webpack, rollup or other bundler. And finally upload your lib as a static resource, or create a LWC to wrap your lib and expose the main entry to other LWC.

**Comment by ajay312** [comment]
No salesforce api is included ..We are creating common behaviour in some of lwc components and can create a library with in org so that my team members can import it

**Comment by AllanOricil** [comment]
You can create a LWC that only contains a `.js`. Inside of it you write your Javascript using the spec you want and then at the end you export what can be consumed elsewhere with the export keyword

````js
export {
     mySuperMethod1,
     mySuperMethod2,
     mySuperObject,
     myClass
}
```` 

then on the other LWCs that need to use your lib, just use import 

````js
import { mySuperMethod1 } from 'c/myAmazingLibrary';
````

**Comment by nolanlawson** [comment]
Thanks @AllanOricil, it looks like this question was answered. Please reopen if I've closed this issue in error.
