### ISSUE TITLE
LWC1112: @api get connection and @api set connection detected in class declaration. Only one of the two needs to be decorated with @api.

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2406]
### Description

`@api` can't be placed in the `set` when the `set` is before the `get`
![image](https://user-images.githubusercontent.com/55927613/125119332-52f78900-e0c7-11eb-9e81-bd98d8d5bdbd.png)

This is valid
![image](https://user-images.githubusercontent.com/55927613/125119248-365b5100-e0c7-11eb-8433-8671bbe39603.png)

It is only a error on the editor. ESLint does not catch this error. And this error is comming from `lwc`
Another thing is that this error is not blocking the deployment of the component.

#### Steps to Reproduce

Just write a `set`  followed by a `get`, and then add `@api` to the `set`. Then verify that this error message appears

#### Expected Results
the `@api` annotation should be valid in either `get` or `set`

#### Actual Results
the `@api` annotation displays an error messge when added to a `set` which is before the `get`

### Browsers Affected
N/A

### Version
N/A

**Possible Solution**

**Additional context/Screenshots**
N/A

**Comment by AllanOricil** [comment]
I also opened it on the LWC Eslint recommnended preset.  https://github.com/salesforce/eslint-config-lwc/issues/66
But later I noticed that it is not an ESLint error

**Comment by AllanOricil** [comment]
Apparently this is a regression

https://github.com/salesforce/lwc/issues/1113

**Comment by AllanOricil** [comment]
These are my `devDependencies`. Maybe I'm using an old package version?

````json
"devDependencies": {
        "@prettier/plugin-xml": "^0.12.0",
        "@salesforce/eslint-config-lwc": "^0.7.0",
        "@salesforce/eslint-plugin-aura": "^1.4.0",
        "@salesforce/sfdx-lwc-jest": "^0.14.0",
        "eslint": "^7.6.0",
        "eslint-config-prettier": "^6.11.0",
        "husky": "^4.2.1",
        "lint-staged": "^10.0.7",
        "prettier": "2.3.2",
        "prettier-plugin-apex": "1.10.0"
    },
````

**Comment by nolanlawson** [comment]
Related: https://github.com/salesforce/eslint-config-lwc/issues/66

**Comment by nolanlawson** [comment]
Which LWC version are you using? What is the error message?

It seems to be working for me: https://webcomponents.dev/edit/h4dvbbJVyVZXKXxjBACz

```js
import { LightningElement, api } from "lwc";

export default class extends LightningElement {
  _foo = 'foo'

  @api
  set foo (val) {
    this._foo = val
  }

  get foo () {
    return this._foo
  }

}

```

**Comment by AllanOricil** [comment]
@nolanlawson  Im on a sfdx project

**Comment by AllanOricil** [comment]
This component that Im seeing this error has the following `meta.xml` file. It is using `api 48.0` => Could it be a reason? I don't know, maybe the lwc compiler uses the api version declared in the xml?

````xml
<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>48.0</apiVersion>
    <runtimeNamespace>vlocity_cmt</runtimeNamespace>
    <isExposed>true</isExposed>
    <description>Vlocity OmniScript Auto-generated - a303N0000006YMqQAM</description>
    <masterLabel>Agent/AllFlowsNewIssue/English</masterLabel>
    <targets>
        <target>lightningCommunity__Page</target>
        <target>lightningCommunity__Default</target>
        <target>lightning__RecordPage</target>
        <target>lightning__AppPage</target>
        <target>lightning__HomePage</target>
    </targets>
    <targetConfigs>
        <targetConfig targets="lightning__AppPage, lightning__RecordPage">
            <property name="layout" type="String" datasource="lightning,newport"/>
            <property name="inline" type="boolean" default="false"/>
            <property name="inlineLabel" type="string" default="Launch Agent/AllFlowsNewIssue"/>
            <property name="inlineVariant" type="string" default="brand" datasource="brand,outline-brand,neutral,success,destructive,text-destructive,inverse,link"/>
            <property name="dir" type="string" default="ltr" datasource="ltr,rtl"/>
            <supportedFormFactors>
                <supportedFormFactor type="Large"/>
                <supportedFormFactor type="Small"/>
            </supportedFormFactors>
        </targetConfig>
        <targetConfig targets="lightning__HomePage">
            <property name="layout" type="String" datasource="lightning,newport"/>
            <property name="inline" type="boolean" default="false"/>
            <property name="inlineLabel" type="string" default="Launch Agent/AllFlowsNewIssue"/>
            <property name="inlineVariant" type="string" default="brand" datasource="brand,outline-brand,neutral,success,destructive,text-destructive,inverse,link"/>
            <property name="dir" type="string" default="ltr" datasource="ltr,rtl"/>
            <supportedFormFactors>
                <supportedFormFactor type="Large"/>
            </supportedFormFactors>
        </targetConfig>
        <targetConfig targets="lightningCommunity__Default">
            <property name="layout" type="String" datasource="lightning,newport"/>
            <property name="inline" type="boolean" default="false"/>
            <property name="inlineLabel" type="string" default="Launch Agent/AllFlowsNewIssue"/>
            <property name="inlineVariant" type="string" default="brand" datasource="brand,outline-brand,neutral,success,destructive,text-destructive,inverse,link"/>
            <property name="recordId" type="String" label="Record Id" description="Automatically bind the page's record id to the component variable" default="{!recordId}"/>
            <property name="dir" type="string" default="ltr" datasource="ltr,rtl"/>
        </targetConfig>
    </targetConfigs>
</LightningComponentBundle>
````

**Comment by pmdartus** [comment]
If this issue is reported in VSCode only, it means that it is a language server issue. I am not able to reproduce this issue locally after creating a brand new SFDX project and updating all the Salesforce VSCode extensions. I don't think it is a regression, there are tests in place for setter/getter and getter/setter: 

https://github.com/salesforce/lwc/blob/d93e2963d8d32b138ce9ed130d98e7bef84b3d74/packages/%40lwc/babel-plugin-component/src/__tests__/api-decorator.spec.js#L219-L232 

This issue should be reported against [forcedotcom/lightning-language-server](https://github.com/forcedotcom/lightning-language-server).

**Comment by ytiq** [comment]
found an example that fails it

```
import { LightningElement, api } from 'lwc';

export default class Testsdfsdf extends LightningElement {
    @api get b() {}
    @api set a(value) { }
    get a() {}
}
```

**Comment by AllanOricil** [comment]
@ytiq open an issue in this repo https://github.com/forcedotcom/lightning-language-server

**Comment by ytiq** [comment]
@AllanOricil seems like https://github.com/forcedotcom/lightning-language-server is not being maintained since there are no comments on issues since August

**Comment by AllanOricil** [comment]
@pmdartus @nolanlawson I confirm @ytiq isolated the problem correctly. It is not an issue related to vscode not loading the language server.



steps:

1 - create a lwc with the following code
````js
import { LightningElement, api } from 'lwc';

export default class Test extends LightningElement {

    _test;
    @api set test(value){}
}
````
2 - verify it does work and no language server error is present
3 - change the lwc code to this one
````js
import { LightningElement, api } from 'lwc';

export default class Test extends LightningElement {

    _test;
    @api set test(value){}
    @api get bla(){}
}
````
4 - verify that now you have the error from this issue

**Comment by geoffswift** [comment]
First of all, if we want to decorate both the getter and setter, then why not allow it?  This seems an unnecessary restriction.

It would also make more sense to actually require the opposite, i.e. both the getter / setter must be decorated.   Have a read of the proposal for decorators here https://github.com/tc39/proposal-decorators?tab=readme-ov-file#class-accessors...

Accessor decorators are applied separately to getters and setters. In the following example, @foo is applied only to get x() - set x() is undecorated:
```javascript
class C {
  @foo
  get x() {
    // ...
  }

  set x(val) {
    // ...
  }
}
```
