### ISSUE TITLE
Can't use DOMParser with lwc:dom="manual" - error = Error: Access denied: {"from":{"namespace":"c"}}

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2420]
#### Steps to Reproduce

1 - Create this component

````html
<template>
    <div class="container" lwc:dom="manual">
    </div>
    <button onclick={clickHandler}>Use Document Create Element</button>
    <button onclick={clickHandlerUsingDOMParser}>Use DOM Parser</button>
</template>
````

````js
import { LightningElement } from 'lwc';

export default class App extends LightningElement {
    
    clickHandler() {
        const container = this.template.querySelector('.container');
        container.appendChild(document.createElement('input'));
    }


    clickHandlerUsingDOMParser() {
        const input = new DOMParser().parseFromString("<input>", "text/html");
        const container = this.template.querySelector('.container');
        container.appendChild(input);
    }
}
````

2 - Click on `Use Document Create Element` button and verify that the Input element is added to the DOM with no problem. 

3 - Now, click on the `Use DOM Parser` and verify that it does not work, nor throw an exception, nor a warning (unless you add a break point to see the warning). 

![image](https://user-images.githubusercontent.com/55927613/125789427-d7f12f98-7f31-4736-9450-c01e4b99cc1b.png)

We have to render a dynamic component based on the content that is retrieved from an API as a HTML/XML string. We need to append this html string to the DOM. To do that, first we tried to use `innerHTML`, which worked without a problem, but ESLint complained about it because of this rule (https://github.com/salesforce/eslint-plugin-lwc/blob/master/docs/rules/no-inner-html.md). Then we decided to change to `appendChild` and it simply does not work. So, we need to go back to the first solution and ignore that eslint rule.

#### Expected Results

The input element created from a String using DOMParser should be added to the DOM when using lwc:dom="manual"

#### Actual Results

Elements created with DOMParser can't be added to the DOM, even when using lwc:dom="manual"

### Browsers Affected

Chrome. But I have not tested it on other browsers

### Version

- LWC: N/A

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by AllanOricil** [comment]
@lucoucie helped to find this problem

**Comment by manuel-jasso** [comment]
Hello @AllanOricil, sorry it took a long time for us to get back to this. This is an issue with Lightning Locker, which is our legacy UI security library, and I think you know we are starting to roll out LWS (Lightning Web Security) to replace it. LWS doesn't have this problem and Lightning Locker is in strict maintenance mode, so the best course of action is to do what you already described: to disable the `no-inner-html` eslint rule and use `innerHtml`.
