### ISSUE TITLE
`Node.getRootNode()` return incorrect value for light DOM elements with synthetic shadow

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#2424]
### Description

The `Node.prototype.getRootNode()` method returns an incorrect value when invoked on light DOM element slotted in synthetic shadow component. This is only observable when the light DOM component is the top-level component.

#### Steps to Reproduce

```html
<!-- x-light-container -->
<template lwc:render-mode="light">
    <x-consumer data-id="consumer">
        <p data-id="p">I am an assigned element.</p>
        I am an assigned text.
    </x-consumer>
</template>
```

```html
<!-- x-consumer -->
<template>
    <p>I am in the shadow</p>
    <slot data-id="slot"></slot>
</template>
```

```js
document.querySelector('p').getRootNode()
```

#### Expected Results
`document`

#### Actual Results
`ShadowRoot`

### Browsers Affected
All

### Version
- LWC: 2.2.8

**Comment by nolanlawson** [comment]
This issue as been Never'd to avoid breaking current synthetic shadow users.
