### ISSUE TITLE
Light DOM serialization is incorrect when mixed with synthetic shadow DOM

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#2425]
### Description

The following API report incorrect values when mixing light DOM with synthetic shadow DOM:
- `Node.prototype.textContent`
- `Element.prototype.innerHTML`
- `Element.prototype.outerHTML`

Failing test examples added via #2393

### Browsers Affected
All

### Version
- LWC: 2.2.8

**Comment by gregwhitworth** [comment]
@nolanlawson @abdulsattar while I haven't gotten any negative feedback is this bug close to landing because this seems like one we should probably ensure devs don't take a dependency on

**Comment by nolanlawson** [comment]
@gregwhitworth Yep I came to the same conclusion. Planning to merge soon: https://github.com/salesforce/lwc/pull/2549#issuecomment-1005032281

**Comment by nolanlawson** [comment]
We resolved not to make this change, to avoid breaking current users of synthetic shadow DOM.
