### ISSUE TITLE
Make `@lwc/template-compiler` produce a stable AST

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#2432]
## Back story

The LWC template compiler exposes a [parse](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/template-compiler/src/index.ts#L29-L33) method. This method returns the internal AST produced by the template compiler prior to code generation. This API was introduced to collect metadata about LWC templates, however the internal template compiler AST was never meant to be exposed.

The LWC template compiler AST has not been designed to be consumable outside the package as it leaks out compiler internal details (eg. parse5 AST nodes). Over time the AST has grown in complexity and new properties have been added without much maintenance consideration as it was always considered an internal data structure. Finally, the current LWC template AST suffers from the fact that it isn’t serializable as it contains circular references.

## Requirements

* All the AST nodes have a string type property representing the concrete type of the AST node. This makes it easier to walk the generated AST tree (eg. [estree-walker](https://github.com/Rich-Harris/estree-walker))
* All the AST nodes should have source location information. It is necessary for metadata collection and reference replacement in the original source code.
* The generated AST should be serializable using JSON.stringify. No cyclic reference is allowed.

## Proposed AST shape

<details>
<summary>Expand to see the proposed AST shape</summary>

### Utility AST nodes

```ts
export interface BaseNode {
    type: string;
    loc: SourceLocation;
}

export interface SourceLocation {
    startLine: number;
    startColumn: number;
    endLine: number;
    endColumn: number;
    start: number;
    end: number;
}

export interface Literal<Value = string | boolean> {
    type: 'Literal';
    value: Value;
}
```

### Expression  AST nodes

*Note:* As of today LWC template compiler only allows identifier and member expression. That said, we should keep the door open to allow more complex expression in the template. The proposed AST node shapes align with the estree AST shape, which will help if we ever decide to expand the supported syntax.

```ts
export interface Identifier extends BaseNode {
    type: 'Identifier';
    name: string;
}

export interface MemberExpression extends BaseNode {
    type: 'MemberExpression';
    object: Expression;
    property: Identifier;
}

export type Expression = Identifier | MemberExpression;
```

### HTML attributes and directives AST nodes

```ts
export interface Attribute extends BaseNode {
    type: 'Attribute';
    name: string;
    value: Literal | Expression;
}

export interface Property extends BaseNode {
    type: 'Property';
    name: string;
    value: Literal | Expression;
}

export interface EventListener extends BaseNode {
    type: 'EventListener';
    name: string;
    handler: Expression;
}

export interface Directive extends BaseNode {
    type: 'Directive';
    name: string;
    value: Expression | Literal;
}

export interface KeyDirective extends Directive {
    name: 'key';
    value: Expression;
}

export interface DynamicDirective extends Directive {
    name: 'dynamic';
    value: Expression;
}

export interface RenderModeDirective extends Directive {
    name: 'render-mode';
    value: Literal<'shadow'> | Literal<'light'>;
}

export interface PreserveCommentsDirective extends Directive {
    name: 'preserve-comments';
    value: Literal<boolean>;
}

export type ElementDirective = KeyDirective | KeyDirective;
export type RootDirective = RenderModeDirective | PreserveCommentsDirective;
```

### HTML nodes AST nodes

```ts
export interface Text extends BaseNode {
    type: 'Text';
    value: Literal | Expression;
}

export interface Comment extends BaseNode {
    type: 'Comment';
    value: string;
}

export interface BaseParentNode extends BaseNode {
    children: ChildNode[];
}

export interface Element extends BaseParentNode {
    type: 'Element';
    name: string;
    namespace?: string;
    attributes: Attribute[];
    listeners: EventListener[];
    directives?: ElementDirective[];
}

export interface Component extends BaseParentNode {
    type: 'Component';
    name: string;
    attributes: Attribute[];
    properties: Property[];
    listeners: EventListener[];
    directives?: ElementDirective[];
}

export interface IfBlock extends BaseParentNode {
    type: 'IfBlock';
    modifier: 'true' | 'false';
    condition: Expression;
}

export interface ForBlock extends BaseParentNode {
    type: 'ForBlock';
    expression: Expression;
    item?: Identifier;
    index?: Identifier;
}

export interface Slot extends Element {
    type: 'Slot';
    name: string;
}

export interface Root extends BaseParentNode {
    type: 'Root';
    directives?: RootDirective[];
}

export type ParentNode = ForBlock | IfBlock | Element | Component | Root;

export type ChildNode = ForBlock | IfBlock | Comment | Element | Component | Text;
```

</details>

## Prior work

Changing the template compiler AST shape is a breaking change. Since the feature is undocumented and still considered experimental it can be released as a minor change. However, we already have some code depending on the current AST, therefore I think it would be better to land all the changes in a single release to help the transition.

As state previously the template compiler code grew organically and it is quite complex to refactor the AST shape without touching some of the most brittle pieces of the template compiler code. The following clean up tasks should help with the refactor:
- [x] **Upgrade `parse5`:** Today the template compiler uses a [parse5 fork](https://github.com/HTMLParseErrorWG/parse5). The forked code has been merged a while back in the upstream repository. We don't need to keep this fork around anymore. #2433
- [x] **Remove the following fields from the `IRNode`s: `original`, `attrsList`:** Those properties won't be present in the new AST shape and are only used for internal bookkeeping. Instead of storing parse5 AST nodes on the LWC compiler AST nodes, those should be passed around in the parser. 
- [x] **Remove `parent` field from `IRNode`s:** The future AST nodes won't have parent back pointers (because it introduces circular dependencies). We can take a head start by changing the compiler code to keep track of the parent chain instead of relying on the information stored on the AST node.
- [x] **Replace the closure wrapping all the parser method:** The `parse` method creates a closure to avoid passing around different objects like `warnings` and `state` as arguments to the parsing method. Instead of this, it would be preferable to have to create a `Parser` class that could hold those objects and expose utility methods for warnings.
- [x] **Simplify diagnostic collection:** The template compiler is designed to be resilient to compilation errors. However, the compiler is permissive IMO. The compiler keeps processing a given element even if a compilation occurred compilation error occurred on the same element. This leads to complex flow control and cryptic errors messages. A more elegant approach would be to make the compiler panic when at the first compilation error and add a synchronization step to discard invalid subtrees ([example](https://craftinginterpreters.com/statements-and-state.html#parsing-variables)).

**Comment by nolanlawson** [comment]
This is fixed by #2518
