### ISSUE TITLE
It's unclear how to use getRecordUi when the mode is set to 'Create'

### ISSUE THREAD

**Issue by joeythomaschaske** [salesforce/lwc#2456]
The documentation for `getRecordUi` requires `recordIds` but also accepts a `Create` mode. 

What is supposed to be supplied to `recordIds` when the mode is set to `Create`?

**Comment by nolanlawson** [comment]
This looks like a question related to an external Salesforce API, [`getRecordUi`](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.reference_wire_adapters_record_ui).

Apologies for not getting to this earlier, but I hope you found an answer to your question. If not, you can reach out to the relevant Salesforce support channel. Please reopen if I've made a mistake closing this.
