### ISSUE TITLE
Add LWC to js-framework-benchmark

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2459]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
All other major js frameworks were added to https://github.com/krausest/js-framework-benchmark for performance comparison. It would be nice to see how lwc behave against them, and how it improves on each release.

**Describe alternatives you've considered**
Currently there is no official comparison

**Additional context**
N/A

**Comment by nolanlawson** [comment]
Opened a PR on `js-framework-benchmark`: https://github.com/krausest/js-framework-benchmark/pull/970

**Comment by AllanOricil** [comment]
> 

Looking forward to see the results and how lwc will improve in the next releases. Good job @nolanlawson

**Comment by nolanlawson** [comment]
LWC is now on the results page: https://krausest.github.io/js-framework-benchmark/current.html

**Comment by AllanOricil** [comment]
Nice results. Now this can serve as an additional kpi to measure how much lwc improves every each major/minor release. Good job
