### ISSUE TITLE
[Light DOM] template-compiler should throw error if <slot> has event listeners

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#2507]
In light DOM mode, the `<slot>` can be defined in the template, but it doesn't really exist in the DOM. This can lead to unexpected behavior for developers who are doing something like this:

```html
<slot onslotchange={handleSlotChange}></slot>
```

...or even:

```html
<slot onscroll={handleScroll}></slot>
```

The above works fine in shadow DOM, but not light DOM.

To ease the migration from shadow DOM to light DOM, we should throw an error (or a warning) when light DOM templates have any event listeners on the `<slot>` "element."

Arguably, the style compiler should also throw for attempts to style `<slot>`s in a light DOM template:

```css
slot {
  overflow-y: scroll;
}
```

...but I'm not sure we have enough information in the style compiler to do that.

**Comment by pmdartus** [comment]
@nolanlawson The template compile already checks if light DOM slots have attributes and reports an error ([check](https://github.com/salesforce/lwc/blob/master/packages/@lwc/template-compiler/src/parser/index.ts#L570-L581), [test](https://github.com/salesforce/lwc/blob/master/packages/@lwc/template-compiler/src/__tests__/fixtures/directive-render-mode/error-slots-attributes/metadata.json#L5)).

**Comment by nolanlawson** [comment]
Updated the description and made [a repro](https://github.com/nolanlawson/lwc-barebone/commit/76f6e220c2ceb02b7a50452a7e9156b2291d34b3). Looks like it only repros for event listeners, not other attributes.
