### ISSUE TITLE
SVG "path" balise => lwc1078: path has no matching closing tag.

### ISSUE THREAD

**Issue by MostafaACHRAF** [salesforce/lwc#2533]
### Description
When i try to deploy my lwc, i get this error: lwc1078: path has no matching closing tag.
I'm using SVG tags like this:

` <svg xmlns="http://www.w3.org/2000/svg" width="36" height="27.5" viewBox="0 0 36 27.5">
                                        <g transform="translate(-96.65 -317.5)" fill="none" stroke="currentColor" stroke-miterlimit="10">
                                            <path d="M97.179 344.754c0-1.754-.517-5.044 2.328-5.044s2.069 3.07 4.656 3.07h-....." />
                                            <circle cx="3.289" cy="3........./>
                                        </g>
</svg>`
#### Steps to Reproduce

When I use an explicit closing tag: <path></path>
The code compiles successfully!

https://webcomponents.dev/edit/X6AH4iI3YamzSdqkrTLP

### Version

- Node version v16.8.0

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nolanlawson** [comment]
Related: https://github.com/salesforce/lwc/issues/1781
