### ISSUE TITLE
Chrome SVG Fill URL not always loading images

### ISSUE THREAD

**Issue by redhatva** [salesforce/lwc#2568]
### Description
I have created a D3 LWC network / visualization graph and it is using static resources for images. On first load of any page it will render correctly in Chrome. However navigating to a new page (record) the LWC will partially render (less the icons from the static resource). In Safari this behavior does not exist. I do not believe it to be a D3 issue but cannot confirm.

#### Steps to Reproduce
https://jsfiddle.net/3gznL1ad/
https://stackoverflow.com/questions/69826608/d3-render-fill-image-refresh-browser-issue

https://webcomponents.dev/create/lwc

```js
const your => (code) => here;
```

### Version

- LWC: x.x.x

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nolanlawson** [comment]
Do you have screenshots to demonstrate the issue? What do you mean by "partial render"?

The JSFiddle link you posted doesn't seem to use LWC – does this JSFiddle repro the issue?

**Comment by redhatva** [comment]
@nolanlawson I have an lwc version... So the lines and text labels will render and so will a fill with color - but it appears that images will only load on first page opened with the LWC using D3. I can hit refresh in browser and it will load.
See https://stackoverflow.com/questions/69826608/d3-render-fill-image-refresh-browser-issue

![good-d3](https://user-images.githubusercontent.com/2695603/140324365-a82a4675-97b5-4cb7-a097-eb59d672e95a.png)
![bad-d3](https://user-images.githubusercontent.com/2695603/140324369-f679556b-69ff-4418-990d-6aec941caece.png

https://user-images.githubusercontent.com/2695603/140324421-b5aa8218-d7f0-4c4c-8c89-663491a52e1e.mov

)

**Comment by nolanlawson** [comment]
@redhatva Does this issue only happen when the Chrome DevTools are open? Do you have "Disable cache" checked in the Chrome DevTools?

**Comment by redhatva** [comment]
@nolanlawson cache has no bearing... I can actually see the images downloading in Chrome DevTools... Also shut off cacheing both in Chrome and Salesforce... This issue does not happen in Safari

**Comment by nolanlawson** [comment]
@redhatva I'm not 100% understanding the code pattern here, but I suspect this isn't an LWC issue but is rather related to the `<circle>`s having a style like `fill: url(#account);`, referencing a `<pattern>` by id (e.g. `<pattern id="account">`). These `<pattern>`s contain SVG `<image>`s.

As an alternative, could you try using `fill: url(https://example.com/full/path/to/image.png)`? (Or `background` instead of `fill`.) I'm not super familiar with SVG, but I suspect there's something subtle going on here with Chrome/Safari's SVG implementation.

**Comment by nolanlawson** [comment]
Closing old issues, please reopen if you have a reduced repro and this has been identified as an LWC issue. If not, please reach out to Salesforce support as necessary. Thank you! 🙂
