### ISSUE TITLE
Base components integration not working 

### ISSUE THREAD

**Issue by raukaute** [salesforce/lwc#2580]
### Description

Following the guide [here](https://developer.salesforce.com/blogs/2020/12/build-connected-apps-anywhere-using-lightning-base-components) components under the lightning namespace won't get styled. I assume this is something to do with the synthetic shadow. Using lwc-services v2 works however. 

#### Steps to Reproduce
Follow [these steps](https://developer.salesforce.com/blogs/2020/12/build-connected-apps-anywhere-using-lightning-base-components)

#### Expected Results
Intergrating base components should work as expected

#### Actual Results
Base components markup gets rendered but styles are not applied.

### Browsers Affected
All

### Version
Node v16
Project init with npx create-lwc-app 

Happy coding! :)

**Comment by nolanlawson** [comment]
Most likely the reason it's not working is that synthetic shadow is not active on the page. Can you open up the DevTools in the browser and confirm that you _don't_ see `#shadow-root (open)` anywhere? This will confirm that synthetic shadow DOM is loaded and working properly.

BTW `lwc-services` is a separate project, over at https://github.com/muenzpraeger/create-lwc-app . If it's working in `lwc-services` v2 but not v3 then I suspect it has something to do with how synthetic shadow is being injected onto the page.

**Comment by nolanlawson** [comment]
I tried the repro steps; the blog post is indeed out of date. I did manage to create [a working version](https://github.com/nolanlawson/sample-create-lwc-app) with a correctly-styled `<lightning-button>` though: 

![Screen Shot 2022-03-10 at 9 56 58 AM](https://user-images.githubusercontent.com/283842/157725908-01021f63-3649-4c38-8204-f7e5cb19c5ba.png)

I'll reach out to see if we can update the blog post. In the meantime, you should know that [`create-lwc-app` is deprecated](https://developer.salesforce.com/blogs/2022/02/its-time-to-say-goodbye-to-create-lwc-app). Please see that blog post for alternatives.

Closing this issue, hope that helps!
