### ISSUE TITLE
@api get recordId and @api set recordId detected in class declaration. Only one of the two needs to be decorated with @api.

### ISSUE THREAD

**Issue by ytiq** [salesforce/lwc#2590]
#### Steps to Reproduce

https://webcomponents.dev/edit/4TuiynUFc1ccniIlgo2L

```js
import { LightningElement, api } from 'lwc';

export default class Testsdfsdf extends LightningElement {
    @api get b() {}
    @api set a(value) { }
    get a() {}
}
```

#### Expected Results
No Error from ESLint is shown

#### Actual Results

@api get recordId and @api set recordId detected in class declaration. Only one of the two needs to be decorated with @api.

### Browsers Affected

VS Code latest, latest version of plugins

### Version

- LWC: x.x.x

**Possible Solution**

**Additional context/Screenshots**
If at any place in the project you have `@api get` in the component then adding `@api set` will give you an error

Seems related to #2406 
Also I duplicated it here https://github.com/forcedotcom/lightning-language-server/issues/464

**Comment by pmdartus** [comment]
> If at any place in the project you have `@api get` in the component then adding `@api set` will give you an error

This is the correct behavior. The `@api` decorator should only be applied a single time for a getter/setter pair. The compiler reports an error if it is used on both the getter and the setter.
