### ISSUE TITLE
Avoid reading innerHTML from an element in diffing algo

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#2603]
### Description

We should avoid comparing the real DOM with the virtual DOM here:

https://github.com/salesforce/lwc/blob/4420492dfb101693effcf6cf6e4b4a3430153c19/packages/%40lwc/engine-core/src/framework/api.ts#L206

Ideally the virtual DOM should do the heavy lifting of actually touching the DOM for us; we shouldn't be comparing DOM nodes to VNodes. There are also perf implications to reading `elm.innerHTML` (the browser has to serialize the whole innerHTML).

See more discussion here: https://github.com/salesforce/lwc/pull/2589/files#r766183112

**Comment by nolanlawson** [comment]
Although now that I take a second look at this, this only applies to `dom:manual`, and only during hydration.

https://github.com/salesforce/lwc/blob/4420492dfb101693effcf6cf6e4b4a3430153c19/packages/%40lwc/engine-core/src/framework/api.ts#L201-L215

**Comment by caridy** [comment]
As I said, I might be missing something here. Although CORE package should never assume that there is a DOM available.

**Comment by pmdartus** [comment]
> Although now that I take a second look at this, this only applies to `dom:manual`, and only during hydration.

This code path is executed during rehydration to recover from discrepancies between the server-side rendered content and the client-side state. If the engine detects a discrepancy it will automatically attempt to recover it. It is also something we are doing for [text](https://github.com/salesforce/lwc/blob/39a1d90172a54f0647fe0d9251fd7efee8836e0f/packages/%40lwc/engine-core/src/framework/api.ts#L103-L108), [comment](https://github.com/salesforce/lwc/blob/39a1d90172a54f0647fe0d9251fd7efee8836e0f/packages/%40lwc/engine-core/src/framework/api.ts#L138-L143), and the list goes on. 

> As I said, I might be missing something here. Although CORE package should never assume that there is a DOM available.

Agreed, it should always go through the renderer. 

The main takeaways for me here are:
- we rushed the merge of hydrate in the code base, we should have been a little more careful here during the review.
- TypeScript should have caught this issue. I haven't been able to completely remove all the DOM depend on types from `@lwc/engine-core` and this is the reason why TypeScript is fine using interfaces like `Element` or `Node` in this package today. Some work needs to be done to fully decouple the work.
- I would suggest refactoring the diffing algo code to make it easier to follow and resonate about. We are today mixing template invocation, diffing, and hydration. I would like to split the logic into multiple files with clearly defined boundaries. I have been following the vue-next project for a while now and I think we can really inspire ourselves from the way they split the [template](https://github.com/vuejs/vue-next/blob/a1167c57e5514be57505f4bce8d163aa1f92cf14/packages/runtime-core/src/vnode.ts), [renderer](https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/renderer.ts) and [hydration](https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/hydration.ts) logic.

**Comment by nolanlawson** [comment]
This is fixed now:

https://github.com/salesforce/lwc/blob/ee36ae984b46f1c16054e4ec24b035a5c3a304ad/packages/%40lwc/engine-core/src/framework/hydration.ts#L126
