### ISSUE TITLE
Template compiler removes whitespace before/after elements

### ISSUE THREAD

**Issue by stof** [salesforce/lwc#2607]
#### Steps to Reproduce

```html
<div>
    {author}
    <span
         class=""
    >{about}</span
    >
</div>
```

#### Expected Results
The final HTML has some spaces between the text rendered by the `author` variable and the span, as done in the source code. In an inline context, spaces are meaningful for the rendering of the page

#### Actual Results
The template compiler removes those spaces when compiling, which makes the 2 words become one.

### Version
- LWC: 2.2.11

**Possible Solution**

**Additional context/Screenshots**

**Comment by nolanlawson** [comment]
Thanks for the bug report. I found a minimal repro for this (https://github.com/nolanlawson/lwc-barebone/commit/3b953a72e2752c1c7fe90d91121d0bbe6867b6ee) and can confirm:

![Screen Shot 2021-12-16 at 1 24 25 PM](https://user-images.githubusercontent.com/283842/146451074-2ccc5f5c-8130-4f0b-aa92-aef6f3d9227a.png)

Repro:

```html
        {foo}
        <span>{bar}</span>
```

This also repros:

```html
        <span>{foo}</span>
        <span>{bar}</span>
```

In the meantime, the workaround is to insert a non-breaking space (`&nbsp;`) or ASCII-encoded whitespace (`&#32;`) between the two elements:

```patch
         {foo}
+        &#32;
         <span>{bar}</span>
```

I'll also note that [Svelte does preserve spaces](https://svelte.dev/repl/01e38c4eba7f46cf8bba9d87a4c20274?version=3.44.3), but some folks have been asking for the opposite behavior (https://github.com/sveltejs/svelte/issues/6540) – e.g. because it has performance implications (https://github.com/krausest/js-framework-benchmark/pull/937).

**Comment by nolanlawson** [comment]
In LWC's case, the least-destructive fix would probably be:

1. Whitespace between two elements is removed (`<span>{foo}</span> <span>{bar}</span>`)
2. But whitespace before or after a text node is preserved (`{foo} <span>{bar}</span>`)

**Comment by pmdartus** [comment]
I think the least disruptive approach here would be to add a new directive similar to the [`lwc:preserve-comments`](https://github.com/salesforce/lwc-rfcs/pull/47) one (eg. `lwc:preserve-whitespaces`) to clearly indicate the intent.

**Comment by nwcm** [comment]
Seeing issues with LWC whitespace which doesn't occur under normal HTML behaviors. 
These were noticed when implementing prettier with LWC parser.

LWC correctly displays single line, but if the markup is over multiple lines it can cause issues. `htmlWhitespaceSensitivity` as `strict` does not resolve these issues.

test config `.pretterrc.json`
```
{
  "trailingComma": "none",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": true,
  "overrides": [
    {
        "files": "**/lwc/**/*.html",
        "options": {
          "parser": "lwc",
          "printWidth": 30,
          "htmlWhitespaceSensitivity": "css"
        }
    }
  ]
}
 ```

1. 
    **Readable**
    ```<p><span>Test foo end</span></p>```
    Formatted (prettier)
    ```
    <p>
      <span
        >Test foo end</span
      >
    </p>
     ```
     Output
     `Test foo end`
2. 
    **Readable**
    ```<p><span>Test <strong>foo</strong> end</span></p>```
    Formatted (prettier)
    ```
    <p>
      <span
        >Test
        <strong>foo</strong>
        end</span
      >
    </p>
     ```
     Output
     `Testfooend`
3. 
    **Readable**
    ```<p><span>Test<strong> foo </strong>end</span></p>```
    Formatted (prettier)
    ```
    <p>
      <span
        >Test<strong>
          foo </strong
        >end</span
      >
    </p>
     ```
     Output
     `Testfoo end`
4. 
    **Readable**
    ```<p><span>Test <strong>foo </strong>end</span></p>```
    Formatted (prettier)
    ```
    <p>
      <span
        >Test
        <strong>foo </strong
        >end</span
      >
    </p>
     ```
     Output
     `Testfoo end`
5. 
    **Readable**
    ```<p><span>Test&nbsp;<strong>foo</strong>&nbsp;end</span></p>```
    Formatted (prettier)
    ```
    <p>
      <span
        >Test&nbsp;<strong>foo</strong>&nbsp;end</span
      >
    </p>
     ```
     Output
     `Test foo end`
6. 
    **Readable**
    ```<p><span>Test&#32;<strong>foo</strong>&#32;end</span></p>```
    Formatted (prettier)
    ```
    <p>
      <span
        >Test&#32;<strong>foo</strong>&#32;end</span
      >
    </p>
     ```
     Output
     `Test foo end`
 
 
The <strong> applied correctly, so ignore that it isn't reflected in the output





**full template example**

```
<template>
  <div>
    <p><span>Test foo end</span></p>
    <p><span>Test <strong>foo</strong> end</span></p>
    <p><span>Test<strong> foo </strong>end</span></p>
    <p><span>Test <strong>foo </strong>end</span></p>
    <p><span>Test&nbsp;<strong>foo</strong>&nbsp;end</span></p>
    <p><span>Test&#32;<strong>foo</strong>&#32;end</span></p>
    <p>
      <span
        >Test foo end</span
      >
    </p>
    <p>
      <span
        >Test
        <strong>foo</strong>
        end</span
      >
    </p>
    <p>
      <span
        >Test<strong>
          foo </strong
        >end</span
      >
    </p>
    <p>
      <span
        >Test
        <strong>foo </strong
        >end</span
      >
    </p>
    <p>
      <span
        >Test&nbsp;<strong>foo</strong>&nbsp;end</span
      >
    </p>
    <p>
      <span
        >Test&#32;<strong>foo</strong>&#32;end</span
      >
    </p>
  </div>
</template>
```
