### ISSUE TITLE
createRecord wire adapter should return the Id in the fields attribute

### ISSUE THREAD

**Issue by joeythomaschaske** [salesforce/lwc#2614]
**Is your feature request related to a problem? Please describe.**
It seems inconsistent that the newly created record's id is not in fields attribute and not obtainable by using `getFieldValue`. This makes for awkward code if you want to use `getFieldValue` to read other fields but need to access the id field directly for that one field.

**Describe the solution you'd like**
Id is returned in the fields attribute and readable with `getFieldValue`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pmdartus** [comment]
Thanks for opening this issue @joeythomaschaske. FYI @mburr-salesforce this might something you would be interested in.
I will have to close this issue as it is unrelated to the core LWC framework. In the future, I would recommend posting similar feature requests via [Idea Exchange](https://ideas.salesforce.com/s/about).

**Comment by mburr-salesforce** [comment]
@joeythomaschaske on the surface it does appear odd, but in this case `createRecord` is just repeating the information it received from the underlying UI API (https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_resources_records_create.htm). I expect you'll see similar behavior for other fields that are repeated as top-level properties in the `Record` structure.

Note that when reading record data (e.g. `getRecord`) you should be able to include `Id` in the set of requested fields to have the value included in `fields` attribute of the returned data. There is, unfortunately, no provision in the UI API to request the set of fields to be returned when creating a record.
