### ISSUE TITLE
Lightning Card slot footer not working with conditional rendering

### ISSUE THREAD

**Issue by ichizos** [salesforce/lwc#2637]
### Description
`<lightning-card>` slots are not working consistently with conditional rendering. On initial load both `slot="actions"` and `slot="footer"` loads properly using conditional rendering. After flipping the boolean with button both slots are hidden, but after flipping it again the `slot="footer"` is not appearing.

#### Steps to Reproduce
https://webcomponents.dev/edit/2POI9emMdB86ijjsJZqS

#### Expected Results
After clicking on button for the 2nd time `slot="footer"` should appear.

#### Actual Results
After `slot="footer"` being hidden there is no way to bring it back.

**Comment by nolanlawson** [comment]
Thanks for the bug report. This does not seem to repro [with synthetic shadow disabled](https://webcomponents.dev/edit/rzcHodALIExitEkT1x9G), so it looks like a synthetic shadow issue.

Before (synthetic shadow):

![Screen Shot 2022-01-13 at 1 58 59 PM](https://user-images.githubusercontent.com/283842/149415779-ed90271a-daa4-412f-9be5-6f1aa6268e9a.png)

After toggling twice (synthetic shadow):

![Screen Shot 2022-01-13 at 1 59 04 PM](https://user-images.githubusercontent.com/283842/149415800-7a5923bb-7669-4b38-a2f6-153d4ced8605.png)

Before and after toggling twice (native shadow, ignore the styling issues):

![Screen Shot 2022-01-13 at 2 01 12 PM](https://user-images.githubusercontent.com/283842/149415894-bf27aefe-8dfe-4eed-9daa-eab1f5731b5e.png)

**Comment by nolanlawson** [comment]
On second look, I [can't seem to repro](https://github.com/nolanlawson/lwc-barebone/commit/7344ac1e64137c1480ab41ba1137a8a969843f78) using a basic component with a slot. So now I'm wondering if this is actually a `<lightning-button>` issue.

There are well-known differences between synthetic and native shadow in terms of the timing of slot creation, so that may still be what triggers the bug.

**Comment by ichizos** [comment]
@nolanlawson It was giving me a headache today on my Salesforce project sandbox and I was able to replicate it on the webcomponents.dev site as you could see. 

Can confirm that I was only able to reproduce it for `slot="footer"` in `<lightning-card/>`. No matter if I gave the `slot` attribute to `<template>`, `<div>` or any other element the result was the same. 

My only guess is that there is an issue within `<lightning-card>` source code and how this specific `slot` is handled.

**Comment by jmsjtu** [comment]
This has been fixed by the Lightning Base Components team.
