### ISSUE TITLE
loadScript rejecting with empty exception, but the script is loaded

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2640]
### Description

when using loadScript with [yup](https://github.com/jquense/yup), an empty exception occurs and It goes inside the catch.

I tried a minified version and a build that I created from the source repo, and both had the same issue. Without knowing what is causing the exception I can't understand what is happening.

````js
loadScript(this, Yup + '/index.js')
            .then(() => {
                console.log('loaded');
            })
            .catch((e) => {
                console.log('error');
                console.log(e);
            });
````

in the image below you can see yup was loaded and the exception is empty.

![image](https://user-images.githubusercontent.com/55927613/149517483-e87b102b-7a44-4b7b-ae53-f6b6a0bf8d4c.png)

#### Steps to Reproduce

1 - add yup to your org as a static resource
2 - use loadScript to load index.js or index.esm.js
3 - verify the resource is loaded but catch is called with an undefined exception. Open the inspector and check the resource is there.

obs: I also ensured I cleaned the cache between tests.

#### Expected Results
If the script is loaded it should not go inside the catch when using loadScript

#### Actual Results
the script is loaded and the promise is rejected

### Browsers Affected
Chrome Version 97.0.4692.71 (Official Build) (arm64) but i did not test in other browsers

### Version

- LWC: the one that is running on a sandbox with api 53

**Possible Solution**
No idea

**Additional context/Screenshots**

**Comment by AllanOricil** [comment]
The same issue happens with ajv (https://cdnjs.cloudflare.com/ajax/libs/ajv/8.6.1/ajv7.min.js)

**Comment by nolanlawson** [comment]
Hi @AllanOricil just FYI, `loadScript` is [not part of this repo](https://github.com/salesforce/lwc/search?q=loadscript) and is instead part of the [Salesforce platform resource loader](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.js_third_party_library). So it seems unlikely to be an LWC bug per se.

Could you please try this:

1. Turn on [Lightning debug mode](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/aura_debug_mode.htm) (Profile in upper-right corner -> Settings -> Advanced User Details -> Edit -> Check "Debug mode" -> Refresh)
1. Set a breakpoint right before calling `loadScript`
2. Wait for the breakpoint to be hit
2. In Chrome DevTools, turn on [pause on exceptions](https://developers.google.com/web/updates/2015/05/automatically-pause-on-any-exception) as well as "pause on caught exceptions"
3. Press the Play button

This should pause on the actual exception that's being thrown. I'm not sure why ultimately it becomes an undefined error object.

**Comment by AllanOricil** [comment]
Im just not sure yet why ajv does not work. I got a version which people on stackoverflow say it works on the browser :/

Ajv throws this exception:
![image](https://user-images.githubusercontent.com/55927613/149620329-0479c882-254f-42a4-8faf-634c41097e77.png)

Aura_proddebug.js captures it and throws another exception:
![image](https://user-images.githubusercontent.com/55927613/149620343-947e4e84-068c-4942-addf-1804ea4663cf.png)

The load script callback rejects with an error that is undefined because "message" does not exist in the evt object:
![image](https://user-images.githubusercontent.com/55927613/149620422-f8cfbd5b-cd24-40dc-8bbf-d4ecb1d46993.png)

loadScript.catch(e) receives an undefined error:
![image](https://user-images.githubusercontent.com/55927613/149620445-792e7364-b789-4ee6-a8eb-13e4ebcb7039.png)

**Comment by AllanOricil** [comment]
I built ajv from the source and now everything loaded as expected. I was not luck with the cdn code. 

![image](https://user-images.githubusercontent.com/55927613/149620821-052c6f90-ef0b-493a-8061-aef0cc5072c3.png)

But it would be good to not reject that promise with an undefined error. Thank you @nolanlawson for the help 👍 
You can close this if you want to track it somewhere else.

**Comment by manuel-jasso** [comment]
Hi @AllanOricil and @nolanlawson for the detailed report, this is a known issue with `loadScript()` from Legacy Locker, but this is no longer a problem with `loadScript()` from LWS (Lightning Web Security, aka Locker vNext), meaning LWS properly rejects promises with a message.

Since Legacy Locker is in maintenance mode (only security issues will be fixed), most likely this issue will stay, but glad to see it's not critical.

Cc @caridy
