### ISSUE TITLE
Enter key is triggering a URL redirect on lightning-record-edit-form

### ISSUE THREAD

**Issue by milton-chen-ncino** [salesforce/lwc#2647]
### Description
This is about API version 54 which is for preview release of Summer 22.
I am not sure if this is the right place to raise this but I'll give it a try.
Basically when you have a date input picker inside a lightning-record-edit-form, and you hit enter, it will trigger a redirect of the URL.
My guess is that triggered a form submit and then went to the URL.

#### Steps to Reproduce
Create below input and pick a date. Hit enter key inside the input.

```js
      <lightning-record-edit-form object-api-name="Contact">
        <lightning-input-field field-name="Birthdate" type="Date"> </lightning-input-field>
      </lightning-record-edit-form>
```

#### Expected Results
No URL redirect. Date change has been accepted.

#### Actual Results
The page jumped to different URL.

### Browsers Affected

Chrome

### Version

- LWC: 54.0

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by pmdartus** [comment]
Thanks for opening this issue.

Unfortunately, I will have to close this issue as it is unrelated to the core LWC framework. In the future, I would recommend posting this issue on [Salesforce Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) or opening a [Salesforce case](https://help.salesforce.com/s/).
