### ISSUE TITLE
[Perf] Hoist static VNodes in template compiler

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#2688]
In #2559 we hoisted static objects/arrays in templates. A further optimization we can do is to hoist static VNodes. For instance:

```html
<template>
    <h1>I am static</h1>
    <div>I am <span>static</span> <span>too</span></div>
</template>
```

```js
function tmpl($api, $cmp, $slotset, $ctx) {
  const {t: api_text, h: api_element} = $api;
  return [api_element("h1", {
    key: 0
  }, [api_text("I am static")]), api_element("div", {
    key: 1
  }, [api_text("I am "), api_element("span", {
    key: 2
  }, [api_text("static")]), api_element("span", {
    key: 3
  }, [api_text("too")])])];
}
```

In this example, every VNode can be hoisted to a static `const` outside of `tmpl`.

There are several parts to this work:

- [ ] Remove the `owner` field from the `VNode` object (see below).
- [ ] Allow templates to access the `$api` from outside the `tmpl`. (Because we decoupled from the ACT Compiler (#2662), we no longer need to use the `$api` function param at all.)
- [ ] Hoist the VNodes, probably in [this routine](https://github.com/salesforce/lwc/blob/dbf80c5e769dc663c9c47e396a6447d183613876/packages/%40lwc/template-compiler/src/codegen/optimize.ts).
- [ ] Use TypeScript to mark all VNodes as `readonly`, and fix any places where we mutate the VNodes.
- [ ] Check that the diffing algo uses object equality (`===`) as a fast-path for diffing VNodes.

**Comment by pmdartus** [comment]
A pre-requisite for this work would be to remove the [`owner` field](https://github.com/salesforce/lwc/blob/890e6a0deb60f86688c584241d879c45e38ba3c0/packages/%40lwc/engine-core/src/framework/vnodes.ts#L29) from `VNode`. This field is set to the [currently rendered VM](https://github.com/salesforce/lwc/blob/890e6a0deb60f86688c584241d879c45e38ba3c0/packages/%40lwc/engine-core/src/framework/template.ts#L60-L66). If we were to hoist VNode creation outside the template, the current rendered VM will be `null` and would fail to diff at runtime.

As a side note, removing the `owner` reference would also require VNode slotting. 

I think the first step would be to push https://github.com/salesforce/lwc/pull/2677 through the finish line. This PR would make it easier to get rid of the `owner` reference. I won't have much time in the upcoming weeks, if you have some bandwidth @nolanlawson, I would be happy to hand it over to you.

**Comment by nolanlawson** [comment]
@pmdartus Thanks, this is good context. I've updated the steps above.

**Comment by nolanlawson** [comment]
> As a side note, removing the `owner` reference would also require VNode slotting.

@pmdartus Could you elaborate on what VNode slotting is?

BTW I checked, and even with your PR, there seem to be about a dozen usages of `vm.owner`. IIUC, to get rid of it, we would need to plumb the currently-rendered VM through every call in the rendering stack? Or just rely on `getVMBeingRendered()`?

**Comment by pmdartus** [comment]
> BTW I checked, and even with your PR, there seem to be about a dozen usages of `vm.owner`. IIUC, to get rid of it, we would need to plumb the currently-rendered VM through every call in the rendering stack?

I did this experiment on a branch locally unfortunately I don't have the code anymore. It would require passing around the `VM` to `patchChildren` function. This is pretty straightforward to do however it doesn't work for slotted elements in synthetic shadow DOM and light DOM. 

Today each VNode is associated with its owner VM when created. The owner VM is used among other things to link each element with the correct shadow tree via `linkNodeToShadow`. The VM that is currently patched is equal to the `vnode.owner` except for slotted VNodes. 

Slotted VNodes are currently passed from one VM to another using the `VM.aChildren`. If we want to remove the `VNode.owner` property we will need to change the `VM.aChildren` to capture both the list of slotted VNode and the owner VM for those slotted VNodes. 

I haven't tried to implement this, but I don't see any reason why it wouldn't be possible.

**Comment by nolanlawson** [comment]
Fixed by https://github.com/salesforce/lwc/pull/2781
