### ISSUE TITLE
[JS compiler] remove registerDecorators for non-LightningElement classes

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#2701]
### Description

The `@lwc/babel-plugin-component` generates `registerDecorators` even for non-LightningElement classes.

#### Steps to Reproduce

https://webcomponents.dev/edit/MYuFA04EubKHITYFNgQm

Input:

```js
class NotALightningElement {
  foo = 'foo'
}
```

Output:

```js
class NotALightningElement {
  constructor() {
    this.foo = 'foo';
  }
}

registerDecorators(NotALightningElement, {
  fields: ["foo"]
});
```

**Possible Solution**

Potentially we can detect a `class` without an `extends` (superclass) and avoid doing `registerDecorators` on that class.

**Comment by nolanlawson** [comment]
While we're at it, `registerComponent` is called for any module that does `export default`.

**Comment by pmdartus** [comment]
> Your first example should be `export default Foo`, right?

No, the first example should also be wrapped with `registerComponent`.

**Comment by nolanlawson** [comment]
For a convoluted set of reasons, this bug is blocking downstream `lightning-components` tests from upgrading LWC.

Basically any JS file with a `class` gets an LWC import, so if you use Jest to mock that `class` then you'll bring along an entire mocked copy of the LWC engine, which conflicts with the real one and causes:

    Unexpected tag name "lightning-datepicker". This name is a registered custom element, preventing LWC to upgrade the element.
