### ISSUE TITLE
Lightning Web Security does not Work with Vlocity or Communities/Experiences Sites

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#2714]
### Description

@manuel-jasso
When enabled, vlocity throws lots of exceptions when using the OS designer built with lwc.

![image](https://user-images.githubusercontent.com/55927613/155715992-47ca29d4-8c27-46fa-977f-670ec09af9cf.png)
![image](https://user-images.githubusercontent.com/55927613/155716008-04ff3c94-29ed-46d9-b097-8236f17951c1.png)

Since the lightning web security release notes say we shouldn't have any problems with lwc built with the lightning locker, and vlocity ui is built with lwc using the lightning locker, I believe something is not accurate about this new lightning web security being ready.

I know this ticket shouldn't be here, but you can share it the vlocity development team.

**Comment by manuel-jasso** [comment]
Hi @AllanOricil, thanks for the report, @nolanlawson kindly mentioned it in our internal channels and the @salesforce/ui-security team is aware. We'll probably need some details in order to reproduce it, someone from @salesforce/ui-security will get back to you. Thanks!

**Comment by AllanOricil** [comment]
I think events are not propagating correctly. There are some parts of vlocity that are not updating after they say it was updated. For instance, when I deactivate an OS, the top right button stays as "Deactivate" instead of becoming "Activate". Another example is when I try to see the OS's setup as a JSON, it does not load at all:

![image](https://user-images.githubusercontent.com/55927613/155989856-83cb3dc4-7c25-4824-82c0-31435b4e2602.png)

In both examples, no exception appears in the console

**Comment by AllanOricil** [comment]
I cant create an OS. When I click on the Save button nothing happens. I had to disable lightning web security, do a clean cache and hard refresh, to be able to create a new OS

**Comment by AllanOricil** [comment]
Another bug. I cant go into preview mode. This time this one produced an error in the console.
![Screen Recording 2022-03-01 at 20 32 54](https://user-images.githubusercontent.com/55927613/156266907-a3985993-ec81-4305-86c6-a5865137d57a.gif)

![image](https://user-images.githubusercontent.com/55927613/156266980-c7b9f1c4-3f83-4ce4-a49c-67f86165bc64.png)

**Comment by AllanOricil** [comment]
Another one.  After refreshing the page once, I can only click one one vlocity component in Design Mode. When I select another component it simply throws this error. When lightning web security is disabled, this does not happen.

![image](https://user-images.githubusercontent.com/55927613/156267353-3f4d4f64-fdd9-4545-9b7f-1729aa3310a6.png)

**Comment by AllanOricil** [comment]
Same bug I had the first time. But this time Im adding all the pictures in sequence
![image](https://user-images.githubusercontent.com/55927613/156268345-193d57fc-d31d-44d8-a152-795603d222cf.png)
![image](https://user-images.githubusercontent.com/55927613/156268357-1cf7112c-2fa2-4a0b-82f8-6a93b67b0ff4.png)
![image](https://user-images.githubusercontent.com/55927613/156268367-e923ed1a-cd9d-473c-a971-0584e423414c.png)
![image](https://user-images.githubusercontent.com/55927613/156268381-f4ad6bf9-0d4a-41e7-9c4f-b17185b81469.png)

**Comment by AllanOricil** [comment]
This Lightning Web Security is bugging Communities/Experience Sites. I have components that work fine and when I render them inside a Community page I get this error. This error goes away when disabling Lightning Web Security

![image](https://user-images.githubusercontent.com/55927613/157780349-5299288e-56ee-49f4-8576-48cc03fb98ef.png)

**Comment by manuel-jasso** [comment]
Hello @AllanOricil, thanks for the details. Again we need to analyze this in detail to be sure, but it looks like LWS is doing what it is supposed to do: it prevents data from namespace "foo" to be mutated by namespace "bar". If this is the issue here, we already have a fix that could address _this particular problem_, but I am not sure when this fix will be available to you. @garychangsf might have better insight regarding timelines.
