### ISSUE TITLE
[Rollup] Migrating to rollup generates decorator error

### ISSUE THREAD

**Issue by jsomhorst** [salesforce/lwc#2715]
Hi,

we are migrating our current LWC components, which use the lwc-creator to rollup. We almost to everything working except the following:

Whenever we do a "rollup -w -c rollup.config.js" we get the following error: 

(plugin rollup-plugin-lwc-compiler) Error: SyntaxError: C:\dev\acuity\acuity-core\src\modules\map\pageTemplate\pageTemplate.ts: LWC1104: "api" can only be used as a class decorator. 

Does anyone know how we can fix this? 

Rollup config: 

`import lwc from "@lwc/rollup-plugin";
import replace from "@rollup/plugin-replace";
import serve from 'rollup-plugin-serve';
import livereload from 'rollup-plugin-livereload'
import typescript from '@rollup/plugin-typescript';

export default {
    input: "src/index.js",

    output: {
        file: "dist/index.js",
        format: "esm",
    },

    plugins: [
        typescript(),
        replace({
            "process.env.NODE_ENV": JSON.stringify("development"),
        }),
        lwc(),
        serve({
            host:'development.server',
            port: 8080,
            contentBase: 'src'
        }),
        livereload(),
    ],
};`

tsconfig.json
{
    "compilerOptions": {
        "target": "ES6",
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "lib": ["ES2021.String","dom"]
    }
}

package.json
`{
    "name": "core",
    "description": "core components",
    "version": "0.0.1",
    "author": "Me",
    "dependencies": {
        "@lwc/synthetic-shadow": "^2.5.8",
        "@salesforce-ux/design-system": "^2.16.2",
        "compression": "^1.7.4",
        "express": "^4.17.1",
        "helmet": "^4.6.0",
        "lightning-base-components": "^1.13.7-alpha"
    },
    "devDependencies": {
        "@lwc/rollup-plugin": "^2.9.0",
        "@rollup/plugin-replace": "^4.0.0",
        "@rollup/plugin-typescript": "^8.3.1",
        "@types/jest": "^27.0.2",
        "eslint": "^8.1.0",
        "eslint-plugin-inclusive-language": "^2.1.1",
        "husky": "^7.0.4",
        "lwc": "^2.9.0",
        "prettier": "^2.4.1",
        "rollup": "^2.68.0",
        "rollup-plugin-livereload": "^2.0.5",
        "rollup-plugin-serve": "^1.1.0"
    },
    "engines": {
        "node": ">=10.13.0",
        "npm": ">=6.4.1",
        "yarn": ">=1.9.4"
    },
    "keywords": [
        "lwc"
    ],
    "license": "MIT",
    "repository": "Me",
    "scripts": {
        "lint": "eslint ./src/**/*.ts",
        "watch": "rollup -w -c rollup.config.js"
    }
}
`

**Comment by pmdartus** [comment]
I am suspecting the TypeScript compiler is transforming the LWC decorator. This is certainly the reason why the LWC compiler is complaining about the `api` decorator being misused. I would recommend using babel to strip off the TypeScript annotations and leave the decorators in place.

**Comment by jsomhorst** [comment]
I'm fairly new to all this so I just installed 
- "@rollup/plugin-babel": "^5.3.1",
- "@babel/preset-typescript": "^7.16.7",

and adding the following to rollup.config.js

babel({
            presets: ["@babel/preset-typescript"],
            extensions:['.ts']
        }),

but still the same error. 

LWC1104: "api" can only be used as a class decorator
   9 | }
  10 |
> 11 | __decorate([api], App.prototype, "name", void 0);
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

maybe i'm missing something?

**Comment by pmdartus** [comment]
Is it possible for you to share the entire repo, so I can look at the setup? If not could you share a minimal repo?

**Comment by jsomhorst** [comment]
I have created a minimum repo: 

https://github.com/jsomhorst/acuity-core-rollup

**Comment by nolanlawson** [comment]
@jsomhorst Could you set the visibility of the repo to public? I get a 404.

**Comment by jsomhorst** [comment]
@nolanlawson I just changed it into public. It is a simple hello world repo which has the same issue.

**Comment by nolanlawson** [comment]
@jsomhorst Looking through your code, it looks like @pmdartus is right, and you can get it to work by using Babel to strip TypeScript types and not using `@rollup/plugin-typescript`. Here is [a working example I made based on your repro](https://github.com/nolanlawson/acuity-core-rollup/commit/4530269ff2c7e829e27154a0de706edc05120932).

```diff
     plugins: [
+        lwc(),
         babel({
-            presets: ["@babel/preset-typescript"],
+            "plugins": [
+                ["@babel/plugin-transform-typescript"],
+                ["@babel/plugin-proposal-decorators", { "legacy": true }],
+            ],
             extensions:[".ts"]
         }),
-        typescript(),
+        // typescript(),
         replace({
             "process.env.NODE_ENV": JSON.stringify("development"),
         }),
-        lwc(),
     ],
-};
```

Note I also had to move the `lwc` plugin earlier. Also if you want actual typechecking, you will probably want to run TypeScript as part of your lint process (e.g. using `tsc --noEmit`).

We could definitely do a better job of documenting how to use LWC+TypeScript+Rollup, but this looks like an app configuration issues, so I'm going to close this for now. Let me know if that helps.

**Comment by jsomhorst** [comment]
Thanks, I just tested this example and it seems to work. I would like to see some more / better documentation regarding lwc typescript rollup scenario in the future :)
