### ISSUE TITLE
The CloseActionScreenEvent event constructor does not support EventInit object

### ISSUE THREAD

**Issue by Damecek** [salesforce/lwc#2722]
#### Steps to Reproduce

Here in the [RFC](https://rfcs.lwc.dev/rfcs/lbc-api/0000-lwc-custom-quick-actions-api#screen-action-component-and-events) you can read the following.

> The CloseActionScreenEvent event has a default event propagation settings (bubbles: false and composed: false). (...) If a developer wants to dispatch this event from a descendants components, they may want to override the event propagation settings by passing an EventInit object to the constructor.

Unfortunately, passing `EventInit` object to constructor will still dispatch a custom event with default propagation settings `bubbles: false` and `composed: false`. That means that if you use `lightning-quick-action-panel` in child component of quick action, you won't be able to close the panel from the child.

#### Steps to Reproduce

Create child component with `lightning-quick-action-panel` and parent component which will be exposed as quick action.

child.html
```
<template>
    <lightning-quick-action-panel header="header">
        <lightning-button name="button" label="button" onclick={handleCancel}></lightning-button>
    </lightning-quick-action-panel>
</template>
```

child.js
```
import {LightningElement} from 'lwc';
import {CloseActionScreenEvent} from "lightning/actions";

export default class Child extends LightningElement {
    handleCancel() {
        this.dispatchEvent(new CloseActionScreenEvent({bubbles: true, composed: true}));
    }
}
```

parent.html
```
<template>
    <c-child></c-child>
</template>
```

parent.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>52.0</apiVersion>
    <description>Parent</description>
    <isExposed>true</isExposed>
    <targets>
        <target>lightning__RecordAction</target>
    </targets>
    <targetConfigs>
        <targetConfig targets="lightning__RecordAction">
            <actionType>ScreenAction</actionType>
        </targetConfig>
    </targetConfigs>
    <masterLabel>Parent</masterLabel>
</LightningComponentBundle>
```

Then creating quick action with this child component. After clicking the button in the child component, the event will be dispatched, but the panel won't close.

#### Expected Results
After clicking the button, the panel will close.

#### Actual Results
Panel won't close.

**Possible Solution**
Dispatch custom event from child, handle that in parent and from there then dispatch `CloseActionScreenEvent`.

**Comment by pmdartus** [comment]
@KamilSzostak @asrinivas-a Could you please look into this.

**Comment by KamilSzostak** [comment]
The team will look into this in our next sprint. Thanks!

**Comment by KamilSzostak** [comment]
We scheduled a fix for 240. Depending on the complexity, we will consider backporting into 238.

**Comment by Goobles** [comment]
A workaround for this would be to just make a CustomEvent with CloseActionScreenEvent's event name:

this works from within the child component and does close the parent component modal: 
```
    this.dispatchEvent(new CustomEvent('lightning__actionsclosescreen', {bubbles:true, composed:true}))
```

**Comment by kevinv11n** [comment]
> A workaround for this would be to just make a CustomEvent with CloseActionScreenEvent's event name:

A major warning here: this is **not a supported path** so may break in various ways in the future. Eg the event name may change, not using the static import makes the dependency on the action and its listeners opaque to our system.

**Comment by npiland** [comment]
@pmdartus We've integrated the changes in the review you were listed on, the resolution should roll out in Winter '23.

**Comment by Damecek** [comment]
@pmdartus @npiland thanks guys for fixing, thou it works only in case you specify the `bubbless` and `composed` args. This should be documented, but I did not find it anywhere.
```
this.dispatchEvent(new CloseActionScreenEvent({ bubbles: true, composed: true }));
```
