### ISSUE TITLE
Markup no valid XML, how to parse in external tools.

### ISSUE THREAD

**Issue by rsoesemann** [salesforce/lwc#2749]
Disclaimer: I am the person who ported the static code analyser PMD to Salesforce and maintains it.

As detailed in https://github.com/pmd/pmd/issues/3849 security scanners like PMD are unable to check LWC markup as it is not valid XML.

What format is LWC Markup using and is there an open, reusable parser that could be used to provide such support in external tools?

**Comment by pmdartus** [comment]
LWC templates use [HTML5 syntax](https://html.spec.whatwg.org/multipage/syntax.html#syntax). The HTML syntax is a lot more forgiving than the XML syntax and attempts to recover from malformed content. 

The LWC compiler uses [parse5](https://github.com/inikulin/parse5) to parse HTML templates. As long as the parser you are using complies with the HTML5 specification, you should be able to parse LWC component templates. I am not an expert in Java, but [jsoup](https://github.com/jhy/jsoup) looks legit.

**Comment by rsoesemann** [comment]
Thank you @pmdartus
