### ISSUE TITLE
LWC not compatible with recent node.js

### ISSUE THREAD

**Issue by littlehoneybunnytuttifruttipumpkinpie** [salesforce/lwc#2756]
I'm new to trying to use LWC, but failing on 3 different computers, each one showing variety of warning and errors after running "npm install". Here is sample output:

```
npm install

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/asset-transformer@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <15' },
npm WARN EBADENGINE   current: { node: 'v16.14.2', npm: '8.5.0' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
npm ERR! code 1
npm ERR! path c:\Coding\lwrsite1\node_modules\node-zopfli-es
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.0
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.3 found at "C:\Python310\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.32228.343) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! (node:11092) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn C:\Python310\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'c:\\Coding\\lwrsite1\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'c:\\Coding\\lwrsite1\\node_modules\\node-zopfli-es\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'c:\\Coding\\lwrsite1\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\{User}\\AppData\\Local\\node-gyp\\Cache\\16.14.2\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\{User}\\AppData\\Local\\node-gyp\\Cache\\16.14.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=c:\\Coding\\lwrsite1\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\{User}\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.14.2\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=c:\\Coding\\lwrsite1\\node_modules\\node-zopfli-es',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'c:\\Coding\\lwrsite1\\node_modules\\node-zopfli-es\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: C:\Users\{User}\AppData\Local\node-gyp\Cache\16.14.2\common.gypi not found (cwd: c:\Coding\lwrsite1\node_modules\node-zopfli-es) while reading includes of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (c:\Coding\lwrsite1\node_modules\node-gyp\lib\configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\Coding\\lwrsite1\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd c:\Coding\lwrsite1\node_modules\node-zopfli-es
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v7.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{User}\AppData\Local\npm-cache\_logs\2022-03-23T18_03_41_468Z-debug-0.log

```

**Comment by nolanlawson** [comment]
It looks like the package `@lwrjs/asset-transformer` requires Node 14 or 15, not Node 16:

```
npm WARN EBADENGINE   package: '@lwrjs/asset-transformer@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <15' },
npm WARN EBADENGINE   current: { node: 'v16.14.2', npm: '8.5.0' }
npm WARN EBADENGINE }
```

Also I wonder if the fact that you're on Windows is contributing to the problem. Does it also fail for you on Windows Subsystem for Linux?

**Comment by nolanlawson** [comment]
Could you provide steps to reproduce? Did you create a new LWR project using [these steps](https://developer.salesforce.com/docs/platform/lwr/guide/lwr-get-started.html)?

**Comment by yungcheng** [comment]
addressed by https://github.com/salesforce/lwr/pull/1209

**Comment by littlehoneybunnytuttifruttipumpkinpie** [comment]
I only use Windows, but got these errors on multiple Windows machines. The steps to reproduce are those described at https://developer.salesforce.com/docs/platform/lwr/guide/lwr-get-started.html
Specifically when running "npm install"

**Comment by nolanlawson** [comment]
@littlehoneybunnytuttifruttipumpkinpie I just tried to repro and could not repro the error. I'm using Windows 10 21H2, Node 16.13.2, and npm 8.1.2. There is a warning about the Node version, but `npm install` completes successfully.

![Screenshot 2022-03-24 085624](https://user-images.githubusercontent.com/283842/159958846-195bc022-c895-40ed-add7-c4d7d90d6bfd.png)

From your error output, it looks like the [node-zopfli-es](https://www.npmjs.com/package/node-zopfli-es) native module is failing to install. Can you try `npm install -g node-zopfli-es` and see if it works? If not, you may need to install [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) or other native tooling for Node on Windows. Also, Windows Subsystem for Linux will probably work.

**Comment by nolanlawson** [comment]
@littlehoneybunnytuttifruttipumpkinpie 

> is it possible to use LWC without npm and without node, but just by linking directly to some LWC JS files

LWC components must be compiled by the LWC compiler before they can be run, so no, you cannot directly import LWC source files in the browser and use them in the browser. However, you can use the [`CustomElementConstructor`](https://lwc.dev/guide/install#use-lightning-web-components-as-native-web-components) API to import a compiled LWC component just like any other web component. [Here is a demo.](https://github.com/nolanlawson/lwc-barebone/commit/7e3662b7a86aa1f1ca2e0b39c2696057d3495519)

For the output you provide, it looks like another native Node dependency, `iltorb`, is failing to compile. Unfortunately this seems to be an environmental issue, and I'm not much of a Windows expert, but perhaps clearing `node_modules` and/or reinstalling the VS Build Tools will fix it.

**Comment by littlehoneybunnytuttifruttipumpkinpie** [comment]
I guess there may be some problems local to my environment, so I'll close this issue, but please keep it in mind in future tests and similar issue reports. Thanks for answering my other question!

**Comment by btfranklin** [comment]
I do not think this has anything to do with being on Windows. I'm on a Mac, and I get the same BADENGINE error. Previously, when I got this, I was able to address it by using nvm to change my node version to LTS. However, that doesn't appear to be working anymore since LTS is 16.14.2.

Here is my output:
npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/asset-transformer@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <15' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.4' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
npm ERR! code 1
npm ERR! path /Users/bt/Development/js/trek-stop/node_modules/node-zopfli-es
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.0
npm ERR! gyp info using node@16.14.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! (node:29881) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/bt/Development/js/trek-stop/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/trek-stop/node_modules/node-zopfli-es/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/trek-stop/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Library/Caches/node-gyp/16.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/bt/Library/Caches/node-gyp/16.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/bt/Development/js/trek-stop/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/bt/Library/Caches/node-gyp/16.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/bt/Development/js/trek-stop/node_modules/node-zopfli-es',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! env: python: No such file or directory
npm ERR! make: *** [Release/nothing.a] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/bt/Development/js/trek-stop/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/Users/bt/.nvm/versions/node/v16.14.0/bin/node" "/Users/bt/Development/js/trek-stop/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/bt/Development/js/trek-stop/node_modules/node-zopfli-es
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v7.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bt/.npm/_logs/2022-03-30T17_59_25_964Z-debug-0.log

**Comment by btfranklin** [comment]
My workaround for this (which is sub-optimal to say the least) was to use an older version of node this way:
nvm use 14.19.0

This definitely doesn't have anything to do with node_modules because I don't even have that folder yet in the project.

**Comment by nolanlawson** [comment]
@btfranklin The "bad engine" error is technically just a warning, due to `@lwrjs/asset-transformer` specifying its desired Node version as `>=14.15.4 <15`. The true error based on your stacktrace is `node-zopfli-es`, a native module, failing to compile.

FYI @yungcheng

**Comment by btfranklin** [comment]
Okay, fair enough. Nevertheless, unless I roll back my node version to 14.19.0, I am not able to initialize a project properly. If I update to the "latest npm" as the [docs instruct me to](https://developer.salesforce.com/docs/platform/lwr/guide/lwr-get-started.html), I get the following failure instead. I understand that in both cases the node-zopfli-es module is the underlying problem, but it seems strange that the same error is showing up until I use a version of nvm that falls within the specified range, especially in light of the fact that so many LWR items are reporting "unsupported engine".

npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'trek-stop@0.0.1',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/core@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/types@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/app-service@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/asset-registry@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/asset-transformer@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <15' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/base-template-engine@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/base-view-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/base-view-transformer@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/client-modules@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/compiler@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/diagnostics@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/fs-asset-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/html-view-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/loader@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/lwc-module-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/lwc-ssr@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/markdown-view-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/module-bundler@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/module-registry@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/npm-module-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/nunjucks-view-provider@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/o11y@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/resource-registry@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/router@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/server@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/shared-utils@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lwrjs/view-registry@0.6.2',
npm WARN EBADENGINE   required: { node: '>=14.15.4 <17' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
npm ERR! code 1
npm ERR! path /Users/bt/Development/js/trek-stop/node_modules/node-zopfli-es
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.0
npm ERR! gyp info using node@17.8.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v17.8.0/node-v17.8.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.8.0/node-v17.8.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v17.8.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.8.0/SHASUMS256.txt
npm ERR! (node:40522) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/bt/Development/js/trek-stop/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/trek-stop/node_modules/node-zopfli-es/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Development/js/trek-stop/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/bt/Library/Caches/node-gyp/17.8.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/bt/Library/Caches/node-gyp/17.8.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/bt/Development/js/trek-stop/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/bt/Library/Caches/node-gyp/17.8.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/bt/Development/js/trek-stop/node_modules/node-zopfli-es',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! env: python: No such file or directory
npm ERR! make: *** [Release/nothing.a] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/bt/Development/js/trek-stop/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/Users/bt/.nvm/versions/node/v17.8.0/bin/node" "/Users/bt/Development/js/trek-stop/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/bt/Development/js/trek-stop/node_modules/node-zopfli-es
npm ERR! gyp ERR! node -v v17.8.0
npm ERR! gyp ERR! node-gyp -v v7.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bt/.npm/_logs/2022-03-30T19_23_23_802Z-debug-0.log

**Comment by btfranklin** [comment]
According to the node-zopfli-es repo (https://github.com/jaeh/node-zopfli-es) that module is deprecated and is quite out of date. From what I can tell, the dependency upon it comes from shrink-ray-current (https://www.npmjs.com/package/shrink-ray-current) which itself is referenced by express. I'm not sure what the correct procedure is for excising something like this, as I'm a bit new to node-based development.

**Comment by btfranklin** [comment]
I think I have an answer. I suspect you will hear this same problem from others in the future.

If you look at the node-zopfli-es repo page, one of the prerequisites is "Python 2.7". Prior to now, this version was already pre-installed on macOS. As of macOS 12.3, which I am now running, [Python 2.7 has been removed](https://blog.kandji.io/apple-removing-python-2.7-what-admins-need-to-know-and-do). My system currently only has Python 3 on it.

Anybody with a Mac who upgrades to 12.3 and then tries to generate a project with node-zopfli-es in it is going to see this error, I suspect.

**Comment by btfranklin** [comment]
Sheesh. Installing Python 2.7 on macOS 12.3 is easier said than done. This is going to be a serious problem. Some of these dependencies just need to be updated, period.

**Comment by nolanlawson** [comment]
The team is looking into this; thanks for reporting. In the meantime, you might try using Yarn with [selective resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to replace `shrink-ray-current` with `compression`:

```json
"resolutions": {
  "shrink-ray-current": "npm:compression@1.7.4"
}
```
