### ISSUE TITLE
lightning-input checkbox inline variant not clickable

### ISSUE THREAD

**Issue by Damecek** [salesforce/lwc#2790]
### Description
When you use the `lable-inline` variant, the checkbox cannot be checked by clicking the box, you need to click the label instead. The `slds-text-align_right` is important.
```
<div class="slds-text-align_right">
    <lightning-input type="checkbox" label="Basic option" name="input1" variant="label-inline"></lightning-input>
</div>
```

#### Steps to Reproduce
create lwc component with `div` with text align and in it `<lightning-input type="checkbox" label="Basic option" name="input1" variant="label-inline"></lightning-input>`.

https://webcomponents.dev/edit/VJNJBYlqShZWh93rtuOH

#### Expected Results
checkbox can be checked clicking on the box.

#### Actual Results
you need to click on the label instead

### Browsers Affected
chrome definitely

**Additional context/Screenshots**
Applies to Salesforce flow debug also.
![image](https://user-images.githubusercontent.com/46635736/163035179-34aca6d4-f914-41eb-8f1f-58eb8ff668e6.png)

**Comment by nolanlawson** [comment]
Thanks for reporting. This issue should be fixed in Salesforce Summer '22 (238). Please reopen if I'm incorrect.

/cc @Templarian

**Comment by AllanOricil** [comment]
@nolanlawson @Templarian this is still happening

**Comment by Tounisiano** [comment]
this is still happening !
