### ISSUE TITLE
usage of WeakSet in context provider

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#2813]
### Description

`new WeakSet<EventTarget>()` is used in `context-provider.ts` in core. This poses the question of how this code works on IE11, which does not support WeakSet. Normally, we use a WeakMap instead with a dummy value, and only focus on the key part of it.

**Comment by nolanlawson** [comment]
I took a look at this. The answer seems to be that [es5-proxy-compat contains a WeakSet polyfill](https://unpkg.com/browse/es5-proxy-compat@0.22.4/polyfills.js). This polyfill is loaded both in our Karma tests and in core via `lwc-platform`.

Maybe there was some point in time when WeakSet didn't work in IE11 (via polyfills), but that's not the case anymore?

In any case, I think we can close this.
