### ISSUE TITLE
Falsy values not showing in draft lightning-datatable

### ISSUE THREAD

**Issue by puenteNicholas21** [salesforce/lwc#2839]
### Description
When i have a lightning-datatable and a given cell i edit is a boolean field and i change the value from true to false, the draft yellow background and new value isn't shown until i save it.  This doesn't happen when going from true to false.  The same bug exists when making a string empty '', i get no indication in the UI of the draft value cause its falsy is my guess.

what appears to be happening in the background is a check to see whether the draft value is populated and if so show the draft value and not current value, and potentially the check is looking for falsy outcomes regardless if that is allowed or expected. (not checking undefined)

#### Steps to Reproduce
using all the docs ive found on web to implement lightning data table.  no matter what attributes i try i still get this issue.

#### Expected Results
Falsy values should show in draft state.

#### Actual Results
Original values shown instead of falsy type values expected in draft view

Not sure why screenshots aren't loading but hopefully explanation is clear

**Comment by nolanlawson** [comment]
Thanks for creating the issue! This was fixed and released in next week’s patch release.

/cc @Templarian
