### ISSUE TITLE
Static fragments of `<td></td>` result in runtime error

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#2887]
### Description

I noticed that the static optimization (#2781) broke the js-framework-benchmark. It throws an error when trying to append elements.

The problem is that the compiled template ends up with this code:

```js
const $fragment2 = parseFragment`<td class="col-md-6${0}"${2}></td>`;
```

And eventually it tries to parse this html into a fragment using this function:

https://github.com/salesforce/lwc/blob/c828bfe0c481219e2f5406f9bcfada9b92b2a60c/packages/%40lwc/engine-dom/src/renderer.ts#L107-L109

But since the `<td>` is standalone, this function returns `null`:

![Screen Shot 2022-06-16 at 9 16 24 AM](https://user-images.githubusercontent.com/283842/174118128-4eb61ec5-e890-4c16-9cb3-fe9bb41dc762.png)

[Minimal repro](https://github.com/nolanlawson/lwc-barebone/commit/c80ac4149e7cf1caf5483684fab6da3c6a795c14):

```html
<template>
    <button onclick={add}>Create row</button>
    <table>
        <tbody>
            <template for:each={rows} for:item="row">
                <tr key={row.id}>
                    <td></td>
                </tr>
            </template>
        </tbody>
    </table>
</template>
```

```js
import { LightningElement, track } from 'lwc';

export default class extends LightningElement {
    @track rows = [];

    add() {
        this.rows.push({ id: 1 });
    }
}
```

**Comment by nolanlawson** [comment]
WI: [W-11308172](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000zNPk3YAG/view)

**Comment by caridy** [comment]
Yeah, more rules to limit what can be statically inserted. Luckily, that's well specified, let's just add more rules.

**Comment by nolanlawson** [comment]
Yeah we could potentially do some kind of workaround for static `<td>`s (e.g. wrapping them in another element before parsing), but I wonder if it's worth it. It might actually be a perf regression due to creating an extra element just to throw it away. Adding a rule is simpler.
