### ISSUE TITLE
npm install failure because Unsupported engine it asset-transformer 

### ISSUE THREAD

**Issue by Torsen** [salesforce/lwc#2889]
### Description
I got a Macbook Pro with M1 Chip. the first versión available for this arch is 15.0.

I'm trying to run a local project with LWR. when I try to run "npm install" in the project folder, I'm getting this error

<img width="411" alt="image" src="https://user-images.githubusercontent.com/2922027/174578316-db99a593-7db1-456b-afed-a74c7bb97bce.png">

#### Steps to Reproduce
1.- Install node last version. In my case 16.14.2
2.- npm init lwr (create a project)
3.- change to project dir
4.- npm install

https://webcomponents.dev/create/lwc

```js
const your => (code) => here;
```

#### Expected Results
Installed dependencies in the project folder

#### Actual Results

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2922027/174579472-7f9d4b78-5542-4fa6-86b5-193c76a930c1.png">

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/2922027/174579348-43e83c15-d66e-49b7-aa7f-281200c12abd.png">

### Version

package.json {
  "name": "locallwr",
  "version": "0.0.1",
  "license": "MIT",
  "private": true,
  "type": "module",
  "scripts": {
    "clean": "rm -rf __lwr_cache__",
    "dev": "lwr serve",
    "start": "lwr serve --mode prod",
    "start:compat": "lwr serve --mode compat",
    "start:prod-compat": "lwr serve --mode prod-compat"
  },
  "dependencies": {
    "lwc": "2.5.8",
    "lwr": "0.6.5"
  },
  "engines": {
    "node": ">=14.15.4 <17"
  }
}

Node version : 16.14.2
NPM version: 8.5.0

**Possible Solution**

I don't have anyone

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by pmdartus** [comment]
The engine version mismatch is only a warning, `npm install` should be able to proceed. This warning will be removed in the next minor version of LWR. You can either downgrade to Node@14 or install the [latest LWR alpha version](https://github.com/salesforce/lwr/releases/tag/v0.7.0-alpha.17).

That said the install failed because NPM wasn't able to compile the native dependencies. Could you please re-run `npm install --verbose` and share the entire log please?

**Comment by Torsen** [comment]
I cannot install Node@14 because I have a Macbookpro M1, and it's available for that CPU architecture 

There is the log
[2022-06-20T14_16_19_154Z-debug-0.log](https://github.com/salesforce/lwc/files/8941378/2022-06-20T14_16_19_154Z-debug-0.log)

**Comment by kmbauer** [comment]
This has been addressed in the lwr 0.7 main branch.  For example `npm init lwr@0.7.0-alpha.17` will work with node 16.  We plan to release a 0.7 npm package as latest sometime this week.

**Comment by nolanlawson** [comment]
This issue can be closed. The `node-zopfli-es` compilation error should also be addressed in lwr 0.7: https://github.com/salesforce/lwc/issues/2788 https://github.com/salesforce/lwc/issues/2756

**Comment by Torsen** [comment]
It works, thanks @kmbauer for you help 👏
