### ISSUE TITLE
lightning-datatable displays blank rows if the bufferSize is greater than number of lines

### ISSUE THREAD

**Issue by Damecek** [salesforce/lwc#2912]
### Description
We can now use render-mode and render-config on the lightning-table (https://developer.salesforce.com/docs/component-library/bundle/lightning-datatable/specification, https://help.salesforce.com/s/articleView?id=release-notes.rn_lc_datatable.htm&type=5&release=238).
The issue is when the datatable should display fewer lines than is the defined bufferSize, it displays just blank lines.

#### Steps to Reproduce

https://studio.webcomponents.dev/edit/WRhsJw3Ga1Qkja8s10Lv

#### Expected Results
all lines will be rendered regardless of the bufferSize

#### Actual Results
lines are not rendered if they are fewer than the bufferSize

**Comment by Templarian** [comment]
@Damecek We've filed an internal bug track this issue. Thanks!

Note: This feature was not meant to roll out in 238 and is being removed from the documentation, so a fix will not be going into 238. Please continue using `table` until we're ready to roll this out in 240.

**Comment by gopinathperumal-eaton** [comment]
Did this issue get fixed in v240? I am still facing this issue
