### ISSUE TITLE
CSS file for all templates in a component (rather than one-per template)

### ISSUE THREAD

**Issue by aheber** [salesforce/lwc#2917]
**Is your feature request related to a problem? Please describe.**
In some components we use many template files in a single component (20+ SVG templates is an example). If we want CSS to be correctly applied to each of those templates in the file we have to create CSS files paired with each template and maintain the same exact CSS in each of those files.

**Describe the solution you'd like**
I would like to have a way to declare a CSS file that is applied to all templates on a component, or can be set in the Javascript. I realize some of this could be achieved with Shared CSS components but that feels like a step too far when the CSS will not be used outside of this component and it creates a weird disconnect to where I manage the CSS for a given component.

**Describe alternatives you've considered**
* Shared CSS component
* Creating my own primary CSS file and having a script that distributes the changes to all subordinates
* We have used the private `stylesheets` and as of Summer '22 now having to set the `stylesheetToken` values of the template. (https://github.com/salesforce/lwc/issues/2826) which we didn't realize were private APIs until recently.

**Additional context**
This is a quality of life and planning for maintenance kind of issue. The idea of adding a bunch of CSS files that hold the exact same values feels like a problem, code smell, and not ideal. It isn't going to break us if we have to do it but it sure feels like something that could be prevented/supported better.

**Comment by nolanlawson** [comment]
Thanks for raising this issue. Please take a look at the [programmatic style injection RFC](https://github.com/salesforce/lwc-rfcs/pull/56) which should hopefully solve this issue in the future. (Or let us know if it doesn't. 🙂)

**Comment by aheber** [comment]
@nolanlawson, thank you. I hadn't found that in my searching.

I do believe that would cover all my uses at this time.

To add a thought for implementation, as my use case diverges from the present examples. At this time, if a template doesn't have a paired `css` file then it doesn't receive a `stylesheetToken`. To leverage the "common" stylesheet applied via the component's stylesheet property each template will still need to have a token, or one would need to be generated when processing the aggregate stylesheets.
(If it would help, I could add this message to the RFC also)

**Comment by nolanlawson** [comment]
@aheber You're right, this would need to be handled correctly. I think it's an implementation detail, though – we would have to apply the `stylesheetToken` correctly in that case so that programmatic style injection works properly. (The only reason we remove it is a small perf improvement: #2670.
