### ISSUE TITLE
Option to disable hydration mismatch warnings

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#2939]
https://github.com/salesforce/lwc/pull/2929 fixed an issue with hydrating components during custom element upgrades. However it's not a perfect solution in some cases.

Let's say you have some pre-existing HTML like this:

```html
<my-component></my-component>
```

...and you would like this to automatically upgrade to a custom element when registered via:

```js
customElements.define("my-component", MyComponent.CustomElementConstructor)
```

Unfortunately this results in a console warning:

```
[LWC error]: Hydration mismatch: incorrect number of rendered nodes. Client produced more nodes than the server.
```

The reason is that the component as rendered by the server has no children, whereas the component rendered on the client does.

This might not be a standard usecase for SSR, but it does exist – we use this pattern in [lwc-docs](https://github.com/salesforce/lwc-docs). It would be great to support this scenario without having ugly console errors (even if just in dev mode).

![Screen Shot 2022-07-20 at 3 26 34 PM](https://user-images.githubusercontent.com/283842/180093106-5a3508d6-9cb9-4479-82cc-28ebd54c8451.png)

One could argue that `lwc-docs` should just have the right number of children in the HTML, but some folks may like to use LWC components purely as "progressive enhancement" with no server-side HTML children.

**Comment by nolanlawson** [comment]
@pmdartus That solution makes sense to me, since the main use-case for the bare `<x-foo></x-foo>` is something like the `lwc-docs` case, e.g. putting HTML tags in markdown. The only downside I can think of for `lwc:ssr` is that it's a lot of bloat to add it to every single component in the HTML. On the other hand, it's a more explicit signal about which components should be hydrated, and maybe it would even be necessary in a multi-framework world, where there may be non-LWC custom elements in the markup.

So yeah, LGTM. 👍

**Comment by nolanlawson** [comment]
**Workarounds**

Currently there are three workarounds:

1. Ignore the error. It's just a `console.error`, not a thrown `Error`.
2. Don't use dev mode. The error only shows in dev mode, not prod mode.
3. Use `renderComponent` from `@lwc/engine-server` to render the full HTML of the component.

**Comment by nolanlawson** [comment]
Alternatively, we could disable hydration for `CustomElementConstructor` entirely.

**Comment by bthompsf** [comment]
> **Workarounds**
> 
> 2. Don't use dev mode. The error only shows in dev mode, not prod mode.

Is this only partially accurate? There still seems to be a `[LWC error]: Hydration completed with errors.` error logged in production mode, which essentially bubbles up from a hydration mismatch. Is there any way to disable that one?

**Comment by nolanlawson** [comment]
You are right, this one runs in all modes:

https://github.com/salesforce/lwc/blob/beae209801201e22b8bb3043badcd361b9f06376/packages/%40lwc/engine-core/src/framework/hydration.ts#L72-L74

I think it'd be reasonable to silence this in prod mode.

**Comment by nolanlawson** [comment]
I think we can close this now that #3591 is in. This shouldn't really be necessary anymore.
