### ISSUE TITLE
Icons are not showing up when used with lwr static sites

### ISSUE THREAD

**Issue by rahulgawale** [salesforce/lwc#2981]
### Description
I am getting the below warning on the console.

> lightning_primitiveIcon.js:48 <lightning-primitive-icon> failed to dynamically import icon templates for utility: Failed to fetch > dynamically imported module: http://localhost:3000/1/module/esm/0/l/en-US/mi/lightning%2FiconSvgTemplatesUtility%2Fv%2F1_15_4-alpha/latest/lightning_iconSvgTemplatesUtility.js

#### Steps to Reproduce
**Note:**  I am using npm.

1. run `npm init lwr`
2. Go to the project folder and run the blow commands
3. `cd StaticSite`
4. `npm install`
5. `npm run dev`
4. Add the SLDS dependencies to the project as described on [this link](https://developer.salesforce.com/docs/platform/lwr/guide/lwr-slds.html).
5. Add the base components dependencies as per [this article](https://developer.salesforce.com/docs/platform/lwr/guide/lwr-lwc.html).
6. add `lightning-icon` component in the app component with any icon.
7. Then run `npm run build` 
8. Run `npm run start`.
9. Open the link in the browser `http://localhost:3000/`.
10. You can see the lightning icon is not visible.
11. See the error on the console.
12. 
![image](https://user-images.githubusercontent.com/16396279/182889939-05edbfab-1c3c-4079-a849-20d056b5e35f.png)

#### Expected Results
The icon should be visible

#### Actual Results
The icon is not visible. Getting error on console.

### Version
Here is my package.json

```
{
	"name": "lwr-admin-tools",
	"version": "0.0.1",
	"license": "MIT",
	"private": true,
	"type": "module",
	"scripts": {
		"build": "node ./scripts/copy-slds.mjs",
		"clean": "rm -rf __lwr_cache__",
		"dev": "lwr serve",
		"start": "lwr serve --mode prod",
		"start:compat": "lwr serve --mode compat",
		"start:prod-compat": "lwr serve --mode prod-compat"
	},
	"dependencies": {
		"lwc": "2.22.0",
		"lwr": "0.7.3"
	},
	"engines": {
		"node": ">=14.15.4 <19"
	},
	"devDependencies": {
		"lightning-base-components": "^1.15.4-alpha",
		"@salesforce-ux/design-system": "^2.18.1",
		"fs-extra": "^10.1.0",
		"path": "^0.12.7"
	}
}
```

**Additional context/Screenshots**
Here is my `lwr.config.json file`.
```
{
	"lwc": {
		"modules": [
			{
				"dir": "$rootDir/src/modules"
			},
			{"npm": "@salesforce-ux/design-system"},
			{"npm": "lightning-base-components"}
		]
	},
	"assets": [
		{
			"alias": "assetsDir",
			"dir": "$rootDir/src/assets",
			"urlPath": "/assets"
		},

		{
			"file": "$rootDir/src/assets/utilitySprite.svg",
			"urlPath": "/lightning.utilitySprite"
		}
	],
	"routes": [
		{
			"id": "my-app",
			"path": "/",
			"rootComponent": "c/app",
			"layoutTemplate": "$layoutsDir/main.html",
			"bootstrap": {
				"syntheticShadow": true
			}
		},
		{
			"id": "Contact",
			"path": "/contact",
			"contentTemplate": "$contentDir/home.md",
			"layoutTemplate": "$layoutsDir/main_layout.njk"
		},
		{
			"id": "About",
			"path": "/about",
			"contentTemplate": "$contentDir/about.md",
			"layoutTemplate": "$layoutsDir/main_layout.njk"
		}
	]
}

```

### App component
**app.html**
```
<template>
    This is app home page.
    <lightning-button
        variant="Brand"
        label="Label"
        title="Button"
        onclick={handleClick}
    ></lightning-button>
    <lightning-icon
        icon-name="utility:add"
        alternative-text="Doc image"
    ></lightning-icon>
</template>
```

**app.js**
```
import {LightningElement /* api, track*/} from "lwc";
export default class App extends LightningElement {
	handleClick() {
		console.log("Clicked");
	}
}

```

**Comment by khangsfdc** [comment]
@rahulgawale, can try the following to see if the issue goes away?

1. add WARMUP=true to start command: `WARMUP=true npm run start`.  This primes the module registry at server startup, so that we can rule out timeouts requesting the module at runtime.
2. If the above fails, also try running prod mode which enables bundling.  

There is a [known LBC issue](https://github.com/salesforce/lightning-base-components/issues/121) in the packaging of this LBC that causes perf issues when running in LWR.

**Comment by rahulgawale** [comment]
@khangsfdc Thank you for your response! I tried adding `WARMUP=true` to `npm run start` command but that did not help. Also, I tried running it in `start:prod-compat` and `start:compat` respectively, but none of them helped. Also looks like the issue link you shared is not on the public git repo.

This is the console log after adding warmup=true.

```

> lwr-admin-tools@0.0.1 start
> lwr serve --mode prod WARMUP=true

LOG_LEVEL: info
(node:11832) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Running LWR v0.7.3 at: http://localhost:3000 | mode: prod
Error: Could not load lightning/iconSvgTemplatesUtilityRtl: Transform failed with 1 error:
    }
  ],  warnings: [],
  code: 'PLUGIN_ERROR',
  plugin: 'bundle-plugin',
  hook: 'load',  watchFiles: [ 'lightning/iconSvgTemplatesUtilityRtl' ]
}
```

Thanks!

**Comment by caridy** [comment]
cc @garychangsf @manuel-jasso

**Comment by khangsfdc** [comment]
@rahulgawale ok I will try repro to debug as soon as I have the chance.

**Comment by khangsfdc** [comment]
I attempted repro with same LWR (0.7.3)and LWC (2.22.0) version, and node version (14.15.4), and it is working for me.  Can you confirm if you are using windows/linux?

<img width="280" alt="image" src="https://user-images.githubusercontent.com/49442382/183231763-f73ee4c5-d83f-4d62-b950-e20a7a9d21b0.png">

**Comment by rahulgawale** [comment]
I am using windows

**Comment by rahulgawale** [comment]
@khangsfdc. Also, I am using node version `16.15.1` is that a problem? Also, I possible can you please share the project repo?

**Comment by rahulgawale** [comment]
**Update:** Tried downgrading the Node version to `14.15.4` but that did not work either. Also, this is an issue is specific to LWR only. I smell that this is an issue with Windows OS only.

**Comment by nolanlawson** [comment]
@rahulgawale Does it work in Windows Subsystem for Linux?

**Comment by rahulgawale** [comment]
@nolanlawson I haven't tried it before, but I will give it a try.

**Comment by rahulgawale** [comment]
@nolanlawson It is working with Windows Subsystem for Linux(WSL) and **yarn** (did not work with **npm**, still figuring out!), thank you very much for your help.

So Here are the steps if you are using `yarn`.
1. Install the Windows Subsystem for Linux using the command `wsl --install`  as mentioned in [this doc](https://docs.microsoft.com/en-us/windows/wsl/install#install-wsl-command).
2. Install [nvm, node.js, and npm](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm) in WSL 
3. Remove yarn cache and run `yarn add`.
4. Run `yarn start`.


I will close the issue, once I get it working with npm. Thanks again!

**Comment by rahulgawale** [comment]
**Update:** I am able to use npm as well. The trick was that the project should be in the root folder of the Linux(WSL). Putting the project folder inside `~/` resolves the access issues.

**Comment by DougMidgley** [comment]
Linking this is using only WSL is a little extreme. Is there any fix for using it properly without WSL in windows? given its the enterprise standard, its important to be supported.
Specifially the error i am getting is 
`<lightning-primitive-icon> failed to dynamically import icon templates for utility: Invalid Unicode escape sequence`
when we try to load icons for lightning-base-components lib

**Comment by rahulgawale** [comment]
@DougMidgley  Yeah it's a big deal, maybe the dev team didn't even think about Windows machines for development. Also, there are some limitations with WLS, and not very convenient to set up.

**Comment by junaid-md** [comment]
@rahulgawale - Did you find any work around for this?

**Comment by rahulgawale** [comment]
Yes @junaid-md you need to install WSL on windows.
