### ISSUE TITLE
[Pivots] Support "extends" key in customElements.define()

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#2983]
### Description

With custom element registry pivots (#2724), using the `extends` key is not supported:

```js
customElements.define('my-button', Button, { extends: 'button' });
```

The above code will throw an error:

    NotSupportedError: "extends" key in customElements.define() options is not supported

Note: Safari [does not support this keyword](https://caniuse.com/custom-elementsv1) ([WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=182671)).

**Comment by nolanlawson** [comment]
Tricky parts about supporting this:

1. Multiple elements with the same tag name probably can't extend different built-in elements – we only get one chance to call the real `customElements.define()`
2. The standard pattern is to register `class MyButton extends HTMLButtonElement {}`, and in the polyfill we only patch the global `window.HTMLElement`. Do we need to patch all the other ones too? (`HTMLButtonElement`, `HTMLLIElement`, etc.)

**Comment by nolanlawson** [comment]
Pivots were dropped in #3310

**Comment by caridy** [comment]
@rwaldron this is one of those things that we will never support. Probably we should document it somewhere in locker.
