### ISSUE TITLE
Unify compiler and engine packages

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#2996]
In many frameworks, it is common to `npm install name-of-framework` and import everything from that one package. For LWC, this would avoid the problem where a consumer of LWC has multiple `@lwc/*` / `lwc` packages with conflicting versions.

In short, this would mean making sure that `npm install lwc` gives you everything you need to run LWC. There would be no need to install a separate `@lwc/compiler` package.

**Comment by nolanlawson** [comment]
One (simple) way we could solve this would be to just add files like the following to the `lwc` package:

```js
// compiler.js
module.exports = require('@lwc/compiler')
```

```js
// engine-server.js
module.exports = require('@lwc/engine-server')
```

```js
// rollup-plugin.js
module.exports = require('@lwc/rollup-plugin')
```

... and then we would add `@lwc/compiler`, `@lwc/engine-server`, and `@lwc/rollup-plugin` (etc.) to the `dependencies` of `lwc`. So consumers could do:

```js
import compiler from 'lwc/compiler'
import { renderComponent } from 'lwc/engine-server'
import plugin from 'lwc/rollup-plugin'
```

Some advantages of this approach:

- `lwc` is guaranteed to install the correct version of `@lwc/compiler` as its `dependency`.
- No breaking changes. You can continue to use `@lwc/compiler` or `lwc/compiler` – both work. (If there are multiple conflicting versions installed, then well, you were going to have a bad time anyway.)
- We don't have to worry about tree-shaking problems (which would arise from cramming everything into a single `index.js` file) – everything is neatly separated into different files

**Comment by nolanlawson** [comment]
We could do this in a backwards-compatible way, but it may make more sense to start with a clean slate:

1. Using [Node.js package exports](https://nodejs.org/api/packages.html#exports)
2. Dropping CommonJS support
3. Removing [`lwc/index.js`](https://github.com/salesforce/lwc/blob/8f3d5c95cc3438f3482f816c2b9ce2ffdaea3050/packages/lwc/index.js) and [`lwc/types.d.ts`](https://github.com/salesforce/lwc/blob/8f3d5c95cc3438f3482f816c2b9ce2ffdaea3050/packages/lwc/types.d.ts), which don't seem necessary if `lwc` is just exporting other packages

**Comment by pmdartus** [comment]
I really like this plan!

**Comment by nolanlawson** [comment]
We can also do https://github.com/salesforce/lwc/issues/2430 while we're at it.

OTOH, https://github.com/salesforce/lwc/issues/2765 and https://github.com/salesforce/lwc/issues/3017 may be a lot harder to accomplish; there are ecosystem issues: https://github.com/salesforce/lwc/issues/3445#issuecomment-1504121029

**Comment by nolanlawson** [comment]
We should probably also make the default export of `lwc` something like:

```js
module.exports = require('@lwc/engine-dom');
```

It's kind of weird to have `import { LightningElement } from 'lwc'`, and yet `lwc` [doesn't actually export that](https://unpkg.com/browse/lwc@2.45.2/index.js)…

**Comment by attilah** [comment]
@nolanlawson would you consider exporting the mutation tracker and membrane functionality as well? That would make it much easier under Salesforce environment to integrate custom more complex state management on top of the existing one if we've have access to membranes and their get/set/subscribe functionality. As I checked [framework/main.ts](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine-core/src/framework/main.ts) does not export anything useful regarding membranes.

**Comment by nolanlawson** [comment]
@attilah Mutation tracker / observable-membrane area. bit special in that they get directly bundled into `engine-dom`/`engine-server`. In other words, they aren't dependencies, but rather devDependencies.

What is your use case for importing observable-membrane on its own?
