### ISSUE TITLE
[Pivots] Support form-associate custom element (FACE) callbacks

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#3000]
### Description

As seen in [Polymer's implementation](https://github.com/webcomponents/polyfills/blob/b266e8a926ec2d0c43a38383defa0f2d5a2f9aa7/packages/scoped-custom-element-registry/src/scoped-custom-element-registry.js#L276-L303), pivots (#2724) should support [FACE callbacks](https://web.dev/more-capable-form-controls/#lifecycle-callbacks) such as `formAssociatedCallback` and `formDisabledCallback`.

**Comment by nolanlawson** [comment]
I started implementing this, but there is an interesting wrinkle: FACE [assumes](https://web.dev/more-capable-form-controls/#defining-a-form-associated-custom-element) you add `static formAssociated = true` to your custom element class, similar to how `static observedAttributes` work.

So you only get one chance to make an element form-associated. This is a problem if we have class A which is registered first and _not_ form-associated, and then class B which is registered second and _is_ form-associated. A few possibilities:

1. Set `static formAssociated = true` for every `PivotCtor`, just in case someone wants to be form-associated. If the callback is invoked by the browser on a non-form-associated element, just ignore it.
2. Avoid setting `static formAssociated = true` for class A, and then implement some kind of polyfill for class B.

Both options make me nervous. FWIW Polymer's polyfill [seems](https://github.com/webcomponents/polyfills/blob/b266e8a926ec2d0c43a38383defa0f2d5a2f9aa7/packages/scoped-custom-element-registry/src/scoped-custom-element-registry.js#L218-L220) to go for option #<span>1</span> but not bother to ignore FACE callbacks for non-FACE elements.

**Comment by caridy** [comment]
At this point name collision should not be a thing... so we should be fine to use formAssociated if the Ctor has it at the time of declaration of the upgradable class.

**Comment by nolanlawson** [comment]
Pivots were dropped in #3310

**Comment by caridy** [comment]
@rwaldron do we need this in locker?
