### ISSUE TITLE
LWC template compiler warns about `part` attribute

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#3016]
### Description

The template compiler warns if you use the [part](https://developer.mozilla.org/en-US/docs/Web/API/Element/part) attribute.

#### Steps to Reproduce

```html
<template>
    <div part="foo"></div>
</template>
```

Result:

```
(!) Plugin rollup-plugin-lwc-compiler: @lwc/rollup-plugin: LWC1057: part is not valid attribute for div.
For more information refer to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div
```

Note this is just a warning, not an error.

**Comment by nolanlawson** [comment]
We should probably switch to something like [html-element-attributes](https://www.npmjs.com/package/html-element-attributes) and [svg-element-attributes](https://www.npmjs.com/package/svg-element-attributes) so we don't have to maintain this list ourselves. But in the short term we could just add `part`.

**Comment by cvharris** [comment]
Is there no way to silence these warnings? We use a styling library which styles attributes as opposed to classes, in order to follow CSS Component style guides. These attributes would be non-standard and also would be found on more than just LWC components.

**Comment by nolanlawson** [comment]
@cvharris Currently no, there is no way to disable the console message.

IIUC the library you're using does something like this:

```css
div[column] {
  display: flex;
}
```

So you do this in your LWC template:

```html
<div column></div>
```

...and `column` is not a valid property on a `<div>` or a known HTML attribute, hence LWC logs the warning.

Maybe there is a case for allowing people to provide a list of strings or something of known custom attributes, to silence the warning. Please feel free to fie a new bug, since this one is specifically about `part`.
