### ISSUE TITLE
Winter '23 does not invoke LWC disconnectedCallback lifecycle hook

### ISSUE THREAD

**Issue by sirephil** [salesforce/lwc#3035]
### Description

We have some LWCs that rely on processing being performed in the LWC disconnectedCallback lifecycle hook. This has worked for a good couple of years since we introduced this functionality.

However, we have noticed that, on an org that is running the Salesforce Winter '23 platform version, these LWCs fail to function correctly causing errors in the relevant user experiences and preventing the user from completing their task if they use the feature more than once without manually refreshing the whole browser tab.

#### Steps to Reproduce

1. Create an LWC that relies on disconnectedCallback.
2. Insert that LWC into a screen flow, for example.
3. Cause that screen flow to be invoked on a Winter '23 org page (e.g. by setting it in a flow-based quick action and invoking that action).
4. "Finish" the flow to cause the LWC to be "disconnected".

**Component**

Javascript:

```js
import {LightningElement} from 'lwc';

export default class TestDisCb extends LightningElement {

	disconnectedCallback() {
		throw 'disconnectedCallback was called as expected.';
	}
}
```

Template:

```html
<template>
    <p>My component</p>
</template>
```

Metadata:

```xml
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>50.0</apiVersion>
    <description>Test Dis Cb</description>
    <isExposed>true</isExposed>
    <masterLabel>Test Dis Cb</masterLabel>
    <targets>
        <target>lightning__AppPage</target>
        <target>lightning__HomePage</target>
        <target>lightning__RecordPage</target>
        <target>lightning__UtilityBar</target>
        <target>lightning__FlowScreen</target>
        <target>lightning__Tab</target>
        <target>lightning__Inbox</target>
        <target>lightningCommunity__Page</target>
        <target>lightningCommunity__Default</target>
        <target>lightningSnapin__ChatMessage</target>
    </targets>
</LightningComponentBundle>
```

#### Expected Results
The disconnectedCallback is invoked an a "Component Error" is shown to the user when the flow is finished.

#### Actual Results
The error is shown when using this on a Summer '22 org but not on a Winter '23 org (since the callback isn't invoked).

### Browsers Affected

All.

### Version

N/A

**Additional context/Screenshots**

This is what you see on a Summer '22 org:

![image](https://user-images.githubusercontent.com/57453324/189301569-d3ae833e-79d5-4d9c-9a02-254bf7a2a93a.png)

This error doesn't appear on a Winter '23 org even though it should.

**Comment by rui-rayqiu** [comment]
This issue cannot be repro'ed on a Winter'23 sandbox org (LWC v2.20.5) for a simple screen flow so it should not be a lifecycle hook regression at framework level. 
Please feel free to contact Salesforce support for further help if needed.

**Comment by sirephil** [comment]
@rui-rayqiu just to verify - when trying to reproduce this issue, if you use this code, you did see the "Component Error" message, right? Seeing the error indicates successful invocation of the lifecycle hook. NOT seeing it shows that the lifecycle hook was not called...

**Comment by rui-rayqiu** [comment]
@sirephil Yes. The error message does show and the lifecycle hook is invoked.
<img width="2108" alt="Screen Shot" src="https://user-images.githubusercontent.com/14824597/190264312-a19cd5cb-80c7-4cb0-b1a3-de50b40193d6.png">

**Comment by sirephil** [comment]
We re-tested after you reported this and the issue has gone away. Perhaps there was a Winter '23 patch already?

Thanks for looking into this. Greatly appreciated.
