### ISSUE TITLE
example_app.js is not a valid string

### ISSUE THREAD

**Issue by Zokor** [salesforce/lwc#3061]
Tried in both latest stable version and also on latest Alpha, same problem

![image](https://user-images.githubusercontent.com/5063752/191951051-3b18c8cb-588a-4bda-acd3-f687e44e90b6.png)

![image](https://user-images.githubusercontent.com/5063752/191950943-9b128470-096a-466a-9173-8c36b03d90bb.png)

![image](https://user-images.githubusercontent.com/5063752/191950996-c95855d8-bbf2-41ba-b6c6-ae62cd8bf18f.png)

**Comment by nrkruk** [comment]
@Zokor can you please include the full error stack trace and a link to your GitHub repository/branch?

**Comment by Zokor** [comment]
@nrkruk i just started a new project through

npm init lwr 
npm install
npm run dev

created a variable, i've putted the string and it blows. if you cancel the server and start again it will boot up fine without that string error. only happens in the hot reload.

Tried with Typescript and also a new project.

I'm with node 16.14.2, Mac Mini M1

**Comment by nrkruk** [comment]
Ok - I understand your scenario now and was able to reproduce. We've got an issue open to track in LWR

**Comment by nolanlawson** [comment]
This is being tracked in another repo (internally). Thanks for opening!
