### ISSUE TITLE
Support LWR OSS Custom Server Side Routes including POST/PATCH

### ISSUE THREAD

**Issue by DougMidgley** [salesforce/lwc#3170]
**Is your feature request related to a problem? Please describe.**
Currently LWR is a great solution for building a website, but when we need to handle server side requests (for example oauth response redirects or form submits) if we want to use it for broader purposes.

**Describe the solution you'd like**
Extend "routeHandler" to support non-get methods.

**Describe alternatives you've considered**
Running a secondary server to handle backend requests. This is always an option but running two servers seems counter-intuitive and increases complexity for even the most basic web functionality.

**Comment by kmbauer** [comment]
One means would be to use custom middleware for these routes -> https://salesforce.stackexchange.com/questions/384117/how-to-add-a-proxy-middleware-in-the-lwr-server

**Comment by DougMidgley** [comment]
thanks @kmbauer ! exactly what i was looking for :)
