### ISSUE TITLE
[Pivots] Support `toggleAttribute` and `attributes`

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#3173]
### Description

Pivot classes currently handle `setAttribute` and `removeAttribute`, but not `toggleAttribute` or `attributes`:

https://github.com/salesforce/lwc/blob/d5bf91e4a70f3daf83507b6181565f6f9451467f/packages/%40lwc/engine-dom/src/custom-elements/create-scoped-registry.ts#L296-L333

Related: #2994

**Comment by nolanlawson** [comment]
Pivots were dropped in #3310

**Comment by caridy** [comment]
@rwaldron do we need this in locker?
