### ISSUE TITLE
`dispatchEvent` using `LightningModal` does not work

### ISSUE THREAD

**Issue by rgalanakis** [salesforce/lwc#3235]
### Description

Following the instructions on this page: https://developer.salesforce.com/docs/component-library/bundle/lightning-modal/documentation
and using the "Modal Events" instructions, results in an error because the modal cannot dispatch the event: ` [Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.]`

#### Steps to Reproduce

```js
// app component
import BugtestModal from "c/bugtestModal"
// In some handler
BugtestModal.open({
    label: 'Modal Title',
    size: 'large',
    description: 'Modal Title with brief description',
});
```

```js
// modal
import { api } from 'lwc';
import LightningModal from 'lightning/modal';

export default class MyModal extends LightningModal {
    @api content;

    handleOkay() {
        this.dispatchEvent(new CustomEvent('select', {detail: {id: 42}}));
    }
}
```

```html
<template>
    <lightning-modal-header label="My Modal Heading"></lightning-modal-header>
    <lightning-modal-body> Content: {content} </lightning-modal-body>
    <lightning-modal-footer>
        <lightning-button label="OK" onclick={handleOkay}></lightning-button>
    </lightning-modal-footer>
</template>
```

#### Expected Results

No error is thrown.

#### Actual Results

` [Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.]`

### Browsers Affected

All.

### Version

Salesforce.com Enterprise Web Services API Version 56.0

**Additional context/Screenshots**

This seems potentially related: https://github.com/salesforce/lwc/issues/1666
However it seems that should be related to user-land components, this is extending `lightning/modal`, which, as per the documentation, should be supported.

**Comment by msrivastav13** [comment]
This known issue is logged as a bug with the lightning base components team. 

The issue appears to happen for orgs with LWS disabled. So if it is possible to have your org with the LWS [setting](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.security_lwsec_enable) enabled, then enabling it will solve it.

For orgs unable to have the LWS setting enabled and needing more time, we have a workaround for now while R&D fixes this. Follow this [answer](https://salesforce.stackexchange.com/questions/387924/lightning-modal-custom-event-not-working-in-winter-23-release/388903#388903) on the StackExchange for a temporary workaround.

**Comment by rgalanakis** [comment]
Thanks, I would suggest updating the documentation in the meantime, since what's published simply does not work.

**Comment by Bartheleway** [comment]
Just to add an extra piece of information, I also run into this today and I discover that in my case I could do :
```
document.dispatchEvent(new CustomEvent('my_event'))
```
in place of the traditional
```
this.dispatchEvent(new CustomEvent('my_event'))
```

I'm just wondering if the DOM tree gets traversed the same way ...

**Comment by nolanlawson** [comment]
@Bartheleway Rather than dispatching events at the global level, you may prefer using `composed: true, bubbles: true`. Some details: https://pm.dartus.fr/blog/a-complete-guide-on-shadow-dom-and-event-propagation/

**Comment by Bartheleway** [comment]
@nolanlawson  Thanks but no thanks. My event (even if not specified in my previous comment) is already using `composed: true, bubbles: true`.
If your answer is a way to tell me that DOM tree is not traversed the same way because of shadow DOM vs real DOM differences, then thanks, answer wasn't really clear about that.

As this topic mention extending a LWC other than `LightningElement` is generating the following error `[Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.]`. This is the topic of the thread. In my case I am extending `BasePrechat` which is a standard element I must extend, so workaround of "not extending" but copying source code is not an option.
The ecosystem seems to have an issue for a while that Salesforce seems not finding solution (or not wanting to ?) so I'm just sharing the workaround I'm using in my context.
@msrivastav13 say that migrating to LWS fix the issue. Some people (in stackoverflow) seems to still have the issue after migrating. In my case I cannot migrate to LWS as I still have Aura component that cannot be migrated thanks to Salesforce not providing same possibilities in LWC.

We can debate wether the "dummy button" solution is better than "dispatching at global level" solution. In my case I need the event to be listen outside of LWC framework so dispatching at global level seems fine and once issue fixed, I will only have to replace `document` by `this` instead of changing template, removing dummy component.

**Comment by nolanlawson** [comment]
@Bartheleway Thanks for the clarification. I found the internal bug for this (W-12557963), and it is indeed an issue with legacy Lightning Locker and Lightning Base Components. There is already work underway to update the documentation for Lightning Modal.

Those changes seem not live yet, so I'll summarize them here:

- Enabling Lightning Web Security should fix this. Lightning Web Security (LWS) is gradually replacing legacy Lightning Locker.
- If you can't enable LWS, a workaround is to wrap the code that calls `dispatchEvent` in a child component that extends `LightningElement`, then use the wrapper component as a child of one of the modal components in the modal template.

I'll close this issue, as this is not an issue in the open-source LWC framework. If you have any further issues, please follow up on [Salesforce Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) or by opening a [Salesforce case](https://help.salesforce.com/s/). Thank you!

**Comment by jsmithdev** [comment]
I hit this while extending LightningCheckboxGroup to make a new lwc "CheckboxGroupHorizontal". The only work around that worked for me was creating a new LWC called eventPasser:

eventPasser.js
```js
// WORK AROUND for issue with LWC extending and legacy Lightning Locker (not LWS)
// https://github.com/salesforce/lwc/issues/3235 
import { api, LightningElement } from 'lwc';

export default class EventPasser extends LightningElement {

	@api 
	passEvent(event) {
		this.dispatchEvent(event);
	}
}
```
eventPasser.html
```html
<template></template>
```

I use it by adding it to the troubled lwc's html and replacing typical `this.dispatchEvent` js:
```html
<c-event-passer></c-event-passer>
```

```js
const passer = this.template.querySelector('c-event-passer');
passer.passEvent(new CustomEvent('change', {
	bubbles: true,
	composed: true,
	detail,
}));
```

**Comment by Shahhmeeer** [comment]
Hey, I recently have gotten the same issue. I am extending lightning modal, and before closing it, I want to show a toast event either for success or an error. I have read the above thread, but I can't seem to understand as to why is this happening. Any help would be appreciated. Thanks in advance

Here is my code for better clarity:

This is where I am calling my showToast method:
```
else if (this.selectedGateway === "Braintree and Stripe") {
      try {
        await this.processBraintreeAndStripe();
        // this.showToast("Registered!", "Braintree and Stripe Token Registered", "success");
        this.isLoading = false;
        this.handleClose();
      } catch (error) {
        console.log("there was an error: ", error);
        // this.showToast("Oops! Error", `There was an error ${error}`, "error");
        this.isLoading = false;
      }
    }
```

### My Toast Mehtod
```
showToast(title, message, variant) {
    this.dispatchEvent(
      new ShowToastEvent({
        title,
        message,
        variant
      })
    );
  }
```

i am getting this continously:

```
there was an error:  TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at s (aura_prod.js:51:47725)
    at ce.dispatchEvent (aura_prod.js:51:13159)
    at ce.showToast (paymentConsoleModal.js:1:8380)
    at ce.handleRegistry (paymentConsoleModal.js:1:7497)
```

**Comment by Shahhmeeer** [comment]
> LightningCheckboxGroup

### Update, Enabling Lightning Web Security (LWS) solved the issue. Cheers
