### ISSUE TITLE
(template-compiler) Using multiple if:true|false directives on same tag passes compilation but fails at runtime.

### ISSUE THREAD

**Issue by ravijayaramappa** [salesforce/lwc#3277]
### Description
Using `if:true` `if:false` directives on the same tag passes compilation but fails at runtime.

Use case 1:
```
    <template if:true={foo} if:false={bar}>
        <p>1</p>
    </template>
```
The second condition is ignored in the compiled output

Use case 2:
```
<div if:true={foo} if:false={bar}></div>
```
The second `if` directive is treated as an attribute. It sets the same attribute on the element at runtime.

Use case 3:
```
<x-child if:true={foo} if:false={bar}></x-child>
```
The second `if:false` is treated as a public property of x-child. And it logs an error at runtime and fails to render the component.

#### Steps to Reproduce

```html
<template>
    <template if:true={foo} if:false={bar}>
        <p>1</p>
    </template>
    <div if:true={foo} if:false={bar}></div>
    <x-child if:true={foo} if:false={bar}></x-child>
</template>
```

```js
import { LightningElement} from 'lwc';


export default class App extends LightningElement {
  foo = true;
  bar = false;
}

```

Compiled template
```
import _xChild from "x/child";
import { parseFragment, registerTemplate } from "lwc";
const $fragment1 = parseFragment`<p${3}>1</p>`;
function tmpl($api, $cmp, $slotset, $ctx) {
  const {
    st: api_static_fragment,
    h: api_element,
    c: api_custom_element,
  } = $api;
  return [
    $cmp.foo ? api_static_fragment($fragment1(), 1) : null,
    $cmp.foo
      ? api_element("div", {
          attrs: {
            "if:false": $cmp.bar,
          },
          key: 2,
        })
      : null,
    $cmp.foo
      ? api_custom_element("x-child", _xChild, {
          props: {
            "if:false": $cmp.bar,
          },
          key: 3,
        })
      : null,
  ];
  /*LWC compiler vX.X.X*/
}
export default registerTemplate(tmpl);
tmpl.stylesheets = [];

```

#### Actual Results

```
Uncaught Error: Unknown public property "if:false" of element <X-CHILD>. This is likely a typo on the corresponding attribute "if:false".
```

**Comment by AndrewHuffman** [comment]
Following, we'd like to stay on top of this in terms of how it'd affect the metadata.

**Comment by nolanlawson** [comment]
For posterity: I cannot reproduce issue #<span></span>2 or #<span></span>3, either with or without the static content optimization enabled. The first one still repros for me though.

[Repro](https://stackblitz.com/edit/salesforce-lwc-jx2rdwdz?file=src%2Fmodules%2Fx%2Fapp%2Fapp.html,src%2Fmodules%2Fx%2Fapp%2Fapp.js,rollup.config.js&title=LWC%20playground)
