### ISSUE TITLE
generalize syntactic sugar

### ISSUE THREAD

**Issue by Gr8Gatsby** [salesforce/lwc#328]
_SOMA#998_

### Migrated issue

notes:

We've discussed adding syntactic sugar to HTML to simplify access of external items, including removing the need for Javascript for such access which enables HTML-only components. This needs:
- generalized developer ergonomics
- pluggable providers so we can support additional types, particularly on force.com

The canonical example is for labels:

```
<template>
    <h1 i18n:key="@label/globalSection/paramName1"></h1>
    <h2 i18n:key="@label/globalSection/paramName2">list of elements</h2>
    <h3 i18n:key="@label/globalSection/paramName3">you have {x} elements</h3>
</template>
```

which is equivalent to:

```
import paramName1 from '@label/globalSection/paramName1'
import paramName2 from '@label/globalSection/paramName2';
import paramName3 from '@label/globalSection/paramName3'
```

Another example is to reference Visualforce:

```
<template>
    <lightning-vf-page vf:page-name="MyPage" />
</template>
```

which is equivalent to:

```
import MyPage from '@vf/MyPage';
```

There are a few big questions to be answered, but I will do my best to answer them here:

* can a custom directive (or is it an attribute namespace?) be bound to a computed value? It seems that the answer to this question is "NO".
* how can the compiler extra all these metadata so it can be used for other optimizations? it seems that any custom directive (even those that are unknown to the compiler) can be extracted and exposed via the regular compiler metadata.
* will the compiler apply any sort of validation? access checks? It seems that it will not, it will just delegate this to the ref-integrity check in the secondary pass.

In general, I see two big avenues to pursue this:

* make this very restrictive, with no runtime code, just transformations from directive to import statements, and if there is a need for any runtime (like the VF example above), then create a component that can accept such namespace attributes.
* make this less restrictive, with a runtime initialization for the piece that handles the provided value accordingly as part of the lifecycle of the component. (more similar to VUE custom directives).

One comment: VF can be a static transformation like label is. The example I gave shows this.

**Comment by jmsjtu** [comment]
We discussed internally and this is an interesting concept but should go through the official RFC process.
