### ISSUE TITLE
SVGs not styled correctly in synthetic shadow with static optimization

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#3311]
### Description

In certain cases, synthetic shadow styling tokens are not applied correctly to SVGs. The necessary conditions are:

1. Component with uppercase letters (e.g. `x/componentLikeThis`)
2. Synthetic shadow
3. Style applied to element in the SVG namespace
4. Firefox

#### Steps to Reproduce

[Minimal repro](https://stackblitz.com/edit/salesforce-lwc-mjcqrw?file=src%2Fmodules%2Fx%2FappLiCaTiOn%2FappLiCaTiOn.html,src%2Fmodules%2Fx%2FappLiCaTiOn%2FappLiCaTiOn.css&title=LWC%20playground)

Chrome on left, Firefox on right. Firefox is case-sensitive here; Chrome is not.

![Screen Shot 2023-01-23 at 2 59 06 PM](https://user-images.githubusercontent.com/283842/214172841-32c6cf25-0b11-4830-ab63-d182af9fef03.png)

Renders:

```html
<x-application x-application_application-host="">
  <svg x-appLiCaTiOn_appLiCaTiOn="" viewBox="0 0 240 80" data-dynamic="foo">
    <text x="20" y="35" x-application_application="">I should not be visible</text>
  </svg>
  <div x-application_application="">Above SVG should not be visible</div>
</x-application>
```

With CSS:

```css
text[x-appLiCaTiOn_appLiCaTiOn] {display: none;}
```

Note the casing. Chrome ignores the case difference between the CSS and HTML, whereas Firefox does not.

**Comment by nolanlawson** [comment]
[Repro of how it worked in an older version of LWC](https://github.com/nolanlawson/lwc-barebone/commit/2312109c91220a4999b8be4167fe398d4fa5bb43).

In the older version, the attribute was not lowercased when applied to the SVG element. So it worked in Firefox.

![Screen Shot 2023-01-23 at 3 29 50 PM](https://user-images.githubusercontent.com/283842/214175533-3fe56d00-a1a7-438a-8749-864c5a9eb5c3.png)

**Comment by nolanlawson** [comment]
Interestingly, Vue [does not have this problem ](https://sfc.vuejs.org/#eNp1kT1PwzAQhv/KyUtBoklUQEIhRSoLYkZi8pLE19ZVYlu2kzaK8t85xyl0wYM/7u59fB8j2xmT9B2ynBUeW9OUHt+4Aihcf4Be4vldX7acZZDB5imDl4wzEKUv12JQZSvr7bjXepolcRHm4iFoNiF2oMvjM2c3EWF9gjvqrhGgtIcK6ScnqwZvMGngLKoipWxiWkL2i3FX6R7h6/vjf1SRxvAA+62tcH5oEFytDYqZNWc8RqqQjgKHnGgKX4NtCvpZM4trK03MCy9GWw8C92XX/AGoOXf31xeARd9ZBSNQn3JY0b4KyOCig/uIj1T2wGQboOu2NMnJaUVzmUl8cTjO8iubMxpceHN29N64PE3dvg7TPLlE20NKt8R2yssWE3TturL67NASmLOlsolNPyHFpbE=) because their style tokens are always lowercase.

![Screen Shot 2023-01-23 at 4 01 54 PM](https://user-images.githubusercontent.com/283842/214179606-614b1b99-018b-4e29-8bc8-38091bb3f6db.png)

**Comment by rsoesemann** [comment]
Will Salesforce actually fix this in their own LWC implementation? Still seeing this behavior.

**Comment by ravijayaramappa** [comment]
@rsoesemann This issue was fixed on 2/1. What is the behavior you are noticing? Can also please include information on which salesforce instance you are on?

**Comment by nolanlawson** [comment]
Note: https://github.com/salesforce/lwc/issues/3313 would have fixed this
