### ISSUE TITLE
"Magic comment" for native-shadow-only CSS

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#3321]
In https://github.com/salesforce/lwc/pull/3229#issuecomment-1380823099 I describe a solution for reducing duplication in the compiled JS output for CSS files.

CSS files are currently compiled to a function that returns a string. This function takes different arguments depending on whether it needs to be rendered in synthetic or native mode.

E.g. for the input:

```css
:host([data-foo="bar"][data-baz="quux"]) [data-haha="toto"] {
  color: blue;
}
```

… we get the output:

```js
function stylesheet(token, useActualHostSelector, useNativeDirPseudoclass) {
  var shadowSelector = token ? "[" + token + "]" : "";
  var hostSelector = token ? "[" + token + "-host]" : "";
  return (
    (useActualHostSelector
      ? ':host([data-foo="bar"][data-baz="quux"]) [data-haha="toto"]'
      : hostSelector + '[data-baz="quux"][data-foo="bar"] [data-haha="toto"]') +
    shadowSelector +
    " {color: blue;}"
  );
}

```

In https://github.com/salesforce/lwc/pull/3229 we added the `disableSyntheticShadowSupport` option to the compiler which vastly simplifies this compiled output by removing synthetic-shadow-related code. However, this doesn't work for projects with mixed CSS files that support both synthetic and native.

Some projects, though, have specific CSS files that are designed to only target native shadow. The selectors in these CSS files are not designed to be run in synthetic shadow components.

So we can implement a "magic comment" system to mark CSS files are native-shadow-only:

```css
/* lwc-disable-synthetic-shadow-support */
```

This comment, if it appears anywhere in the CSS file, does the same thing for that CSS file as the `disableSyntheticShadowSupport` option.

Note the following limitations:

1. This will only work for non-scoped styles. Scoped styles have to be flexible enough to take arguments to their function.
2. If a CSS file uses this magic comment and then is rendered in a synthetic shadow component, the framework should (probably) render no styles at all. (And log a warning? Maybe?)

**Comment by nolanlawson** [comment]
Downside to this proposal: it may be impossible to un-ship this due to observable changes.

E.g. if a component uses a CSS file:

```css
/* lwc-disable-synthetic-shadow-support */
:host {
  color: red;
} 
```

… and if this is rendered in a synthetic shadow components, it will either 1) do nothing, or 2) get hoisted to the `<head>` where, again, it does nothing because `:host` is meaningless outside of a shadow root.

However, if we un-ship this feature, then suddenly the `:host` selector will start working in synthetic shadow.

So component authors could take a dependency on the behavior of the magic comment, and we would be unable to un-ship it.

That said, we _would_ be able to un-ship the magic comment if we drop support for synthetic shadow entirely.

**Comment by nolanlawson** [comment]
Alternatively, we could make these native-shadow-only CSS files throw an error when rendered in a synthetic shadow component. This would force developers to use [programmatic styles](https://lwc.dev/guide/css#associate-css-stylesheets-to-a-component-programmatically), e.g. with a mixin.

This would make it more possible to remove this feature in the future, since the error would prevent developers from relying on the behavior of native-only-styles-loaded-in-synthetic.

**Comment by jye-sf** [comment]
>If a CSS file uses this magic comment and then is rendered in a synthetic shadow component, the framework should (probably) render no styles at all. (And log a warning? Maybe?)

>Alternatively, we could make these native-shadow-only CSS files throw an error when rendered in a synthetic shadow component.

I like throwing a warning/error (or having some other explicit behavior for native-styles-in-synthetic) better than just letting it happen to do nothing due to other side effects. It forces developers to be more intentional and guards against relying on the undefined/unintended behavior.

How would we detect this on the framework if the magic comment is stripped out during minification? Is there a different indicator we'd be using?

**Comment by nolanlawson** [comment]
> How would we detect this on the framework if the magic comment is stripped out during minification? Is there a different indicator we'd be using?

Developers would be responsible for not running minification before passing the CSS to the LWC compiler. Or otherwise configuring their minifier not to strip comments.

(Interestingly, we don't have a way in LWC itself to minify CSS before turning it into a JS function... could be an interesting feature.)

**Comment by jye-sf** [comment]
>Developers would be responsible for not running minification before passing the CSS to the LWC compiler.

Sorry if I'm missing something basic. By framework I meant the runtime engine on the client during rendering, and the minification referred to what our Terser would do on the compiled JS function, not any minification the developer might do on the CSS file.

Looking at https://github.com/salesforce/lwc/pull/3229, I was under the impression that this magic comment would be added to or propagated into the generated `stylesheet` function in JS, similar to how we stamp the `LWC compiler version` comment in. That would then get stripped out by Terser in prod, similar to how the compiler version comment is removed, and the rendering engine would never get to see it.

I guess taking a step back, were you thinking we would throw any errors from the compiler, not the runtime engine?

**Comment by nolanlawson** [comment]
Sorry, I was not clear about the design. In my mind, the magic comments goes in the CSS, and this compiles to JS something like this:

```js
function stylesheet() {
  return ":host { color: red }" // optimized CSS string
}

stylesheet.$disableSynthetic$ = true // similar to $scoped$ = true
```

So nothing gets stripped out during Terser minification. The engine can use the `$disableSynthetic$` expando as a hint to throw an error if the stylesheet is rendered in synthetic mode.

**Comment by vbhargavmbis** [comment]
Agree that throwing a warn/error would be useful so that devs are aware that something is not be working and for what reason.
> … and if this is rendered in a synthetic shadow components, it will either 1) do nothing, or 2) get hoisted to the `<head>`
from here: https://github.com/salesforce/lwc/issues/3321#issuecomment-1405394635

Is it possible that (2) may have other impact based on the selectors other than `host`? For example, if a CSS file overrides a particular slds utility class for the component and if that is hoisted to the `<head>` it may override existing CSS across all components, right?


>(from the description) 2.  If a CSS file uses this magic comment and then is rendered in a synthetic shadow component, the framework should (probably) render no styles at all. 

Let's say `mycmp` is expected to work in both synthetic and native shadow/mixed modes.
If the component is structured like this:
```
my-cmp
  |___ mycmp.css
  |___ nativeshadowstyles.css
  |___ mycmp.html
  |___ mycmp.js
```
with `mycmp.css` containing:
```css
@import './nativeshadowstyles.css'

my-synthetic-only-styles {
  ..
}
```

**Question:** The recommendation with this proposal is that the magic comment is set in the `nativeshadowstyles.css` right? 
Or would that have the same issue as point #1 where it won't work for `*.scoped.css`?

The aim is to allow `mycmp` to render the synthetic-only styles in synthetic mode despite adding the magic comment.

**Comment by nolanlawson** [comment]
> Is it possible that (2) may have other impact based on the selectors other than host?

Yes, you're right; we don't want to hoist `div { color: red }` to the `<head>`. We can't do this.

> Question: The recommendation with this proposal is that the magic comment is set in the `nativeshadowstyles.css` right?

Correct, but your example would still break in synthetic shadow, assuming we throw the runtime error. The reason it would break is because `nativeshadowstyles.css` are still rendered by `mycmp.css`.

Instead, you would need to use [programmatic stylesheets](https://lwc.dev/guide/css#associate-css-stylesheets-to-a-component-programmatically) to ensure that only synthetic stylesheets are rendered for synthetic components, and vice versa.

Although now that I think about it, it would be quite awkward to implement, since `stylesheets` are a static property, and `this.template.synthetic` is not static. You would effectively need a wrapper class to check `this.template.stylesheet` and then either render a synthetic or a native child based on that. You could also just use `render()`, but then you would need to duplicate the HTML files, which duplicates the compiled `template` function.

Maybe this proposal is not really feasible after all.

**Comment by nolanlawson** [comment]
Related: [dynamic stylesheet replacement RFC](https://github.com/salesforce/lwc-rfcs/pull/76)

**Comment by vbhargavmbis** [comment]
> Yes, you're right; we don't want to hoist div { color: red } to the <head>. We can't do this.

Yeah overriding `div` is a much more severe issue! However, we could get around this by simply making this a no-op + console warn/error right? Or is there a need to hoist it to the `<head>`?

Your [dynamic stylesheet proposal](https://github.com/salesforce/lwc-rfcs/pull/76) looks interesting and seems like it would solve the problem at first glance! But as you mentioned in the RFC, there would be several ways to 'do dynamic styles'. I wanted to think through any other possibilities to incorporate the solution to this into an existing pattern. Here are a couple of initial thoughts for your consideration:
1. Is it possible to wire the magic comment in a way that it works only when the component is in mixed/native shadow mode? I'm guessing this isn't possible since the CSS is compiled at an earlier stage without the knowledge of whether the component is being rendered in synthetic or mixed mode. Is that correct?
    -   The alternative to this would be to conditionally set the stylesheet based on the component's render mode which in effect is the dynamic stylesheet proposal.

3. This addresses one of the downsides of the programmatic stylesheets so it has probably been considered but wanted to know for my understanding: Could we not conditionally set the `static stylesheets` variable like so:
```js
import syntheticstyles from './syntheticstyles.css';
import nativeshadowstyles from './nativeshadowstyles.css';

export default class extends LightningElement {
    static stylesheets =  getStylesheet();
    ...
    getStylesheet() {
        return this.template.synthetic ? syntheticstyles : nativeshadowstyles;
    }
}
```
This would use the `static` variable but still conditionally set the stylesheet.

**Comment by nolanlawson** [comment]
> I'm guessing this isn't possible since the CSS is compiled at an earlier stage without the knowledge of whether the component is being rendered in synthetic or mixed mode. Is that correct?

Correct.

> Could we not conditionally set the `static stylesheets` variable like so

No, that would not work. `static` properties do not have access to `this`. If you try to do something [like this](https://codepen.io/nolanlawson-the-selector/pen/bGjxYvG?editors=1010), you get a JS syntax error.

**Comment by andrew-gomez-sfdc** [comment]
Is there a strong argument for unshipping this feature before removing support for synthetic shadow?

**Comment by nolanlawson** [comment]
@andrew-gomez-sfdc The goal of `disableSyntheticShadowSupport` was to give a compiler option for environments that don't use synthetic shadow at all (e.g. off-core LWR).

> Is there a strong argument for unshipping this feature before removing support for synthetic shadow?

No. It can be unshipped when synthetic unships. But my concern right now is effectively adding another "feature" to synthetic shadow, i.e. a way to have code run in native but not synthetic. This would have to live as long as synthetic (or something like it) lives.

**Comment by andrew-gomez-sfdc** [comment]
In my opinion it seems like a typical feature to aid in migrating things to native shadow, eg. allowing LWC to run within Aura containers is not different conceptually right? 

To me the benefits for perf and flexibility to component authors seem huge, though I'm not suggesting there isn't another path to get to the same result

**Comment by nolanlawson** [comment]
I see two options for implementing this right now:

1. Implement this with error behavior when the native-only styles are loaded in synthetic.
2. Implement this with no-op behavior in that case instead.

The upside of #<span>1</span> is less maintenance cost for LWC because the feature can be removed at any time without breaking anyone. The downside is that it's not very useful without [dynamic stylesheet replacement](https://github.com/salesforce/lwc-rfcs/pull/76).

The downside of #<span>1</span> is maintenance cost – it will need to live for as long as synthetic shadow lives. The upside is that it's very useful for component authors to have native-only styles that are no-op in synthetic shadow.

In both cases, there would be a perf benefit due to the smaller compiled output.

**Comment by nolanlawson** [comment]
This is no longer planned
