### ISSUE TITLE
The error "The `insertBefore` method is available only on elements that use the `lwc:dom="manual"` directive" popup even though I have added lwc-dom=manual to my empty <canvas> tags which am using with chart.js and d3 libraries

### ISSUE THREAD

**Issue by junaid-md** [salesforce/lwc#3328]
**Am using LWR here**
`<canvas class="barChart" lwc:dom="manual"></canvas>   `

.js file:
```
renderedCallback() {
        if (this.isChartJsInitialized) {
            return;
        }
        this.isChartJsInitialized = true;
        this.loadChartJs();
    }

    loadChartJs() {
        const ctx = this.template.querySelector('canvas.barChart').getContext('2d');
        this.chart = new Chart(ctx, JSON.parse(JSON.stringify(this.gaugeChartData)));
    }
```

**Comment by junaid-md** [comment]
Am using LWR here
`<canvas class="barChart" lwc:dom="manual"></canvas>   `

.js file:
```
renderedCallback() {
        if (this.isChartJsInitialized) {
            return;
        }
        this.isChartJsInitialized = true;
        this.loadChartJs();
    }

    loadChartJs() {
        const ctx = this.template.querySelector('canvas.barChart').getContext('2d');
        this.chart = new Chart(ctx, JSON.parse(JSON.stringify(this.gaugeChartData)));
    }
```

**Comment by abdulsattar** [comment]
Can you provide a repro on lwc.studio for this? I'm successfully able to load Chart.js here: https://app.lwc.studio/edit/d0LymGHfZmEpson6CMVw/src/app.js?p=stories

**Comment by junaid-md** [comment]
@abdulsattar  - Its loading chart.js but there is still error on the console which is a little annoying to see it popping on every page where am using chart.js or d3.js

<img width="667" alt="image" src="https://user-images.githubusercontent.com/13597993/217004260-9ecb8f5d-3fbd-4d95-ab37-877de1908687.png">

**Comment by abdulsattar** [comment]
I don't see any errors in the code that I have https://stackblitz.com/edit/salesforce-lwc-bfnbck?file=src/modules/x/app/app.js here. Can you create a repro on stackblitz and share it here?

**Comment by junaid-md** [comment]
@abdulsattar - Seems like its an issue with the legacy version we are using in our project for chart.js (v 2.8.0).
I just updated the chartjs version and couldn't find any errors in the console.

Thanks for the help!
