### ISSUE TITLE
[integration] CLI to create integration tests 

### ISSUE THREAD

**Issue by Gr8Gatsby** [salesforce/lwc#335]
_SOMA#663_

### Migrated issue

notes:

CLI tool to automate creating integration tests. The goal of this is to automate creating integration tests, and to use existing repro cases from playground to build our test cases. This script would live in `compat-tests` project.

## PROPOSED FUNCTIONALITY
- New npm script: `create-integration` (We can bikeshed on name if need)

- prompt for
  - Github issue number (required)
  - Existing fiddle that reproduces the bug (optional)
- New folder added to `./src/components` that starts with the GitHub issue number: `./src/components/123`
- If fiddle id was provided and resolves, populates new folder with content from fiddle.
- Creates `spec.js` file inside of new folder
  - `spec.js` file has a single `describe` block populated with `Issue Number - Issue Title`

**Comment by pmdartus** [comment]
This is not needed anymore. Most of the tests have been moved from Webdriverio over to Karma.
