### ISSUE TITLE
Property delete does not work on component class properties

### ISSUE THREAD

**Issue by brianmfear** [salesforce/lwc#3353]
According to this [post](https://salesforce.stackexchange.com/q/396345/2984), the author claims that the `delete` keyword is broken in LWC. My response was that this appears to be some kind of protection to prevent breaking the LWR. I tried finding some sort of documentation on this, and even built a [demo](https://app.lwc.studio/edit/9Hcl2yzoUGyqjRVrYxLr/src/app.js?p=stories) that shows that "normal" classes that aren't used as a LightningElement controller do, in fact, behave as they should, which leads me to believe that this is an intentional design choice. Either way, I'm just looking to confirm if this is a bug or WAD, and relevant documentation if so. This is as much for my own edification as it is the original author's.

**Comment by nolanlawson** [comment]
Thanks for reporting. By any chance do you have a demo using https://playground.lwc.dev/ ? (I'm a little hesitant to give LWC Studio access to my GitHub.)

Also, I assume you're talking about `delete`ing a `@track`ed property in a `LightningElement`, and the fact that this is not tracked in the same way that `this[prop] = undefined` is?

**Comment by brianmfear** [comment]
@nolanlawson I had my demo from the link above. Didn't realize you had to authorize to view? Anyways, it was a quick copy-paste over into the link you've requested. Here's the [link](https://stackblitz.com/edit/salesforce-lwc-mv3xoa?file=src/modules/x/app/app.html).

**Comment by nolanlawson** [comment]
Interesting, I understand the issue now. [Minimal repro](https://stackblitz.com/edit/salesforce-lwc-ylj1i6?file=src%2Fmodules%2Fx%2Fapp%2Fapp.html,src%2Fmodules%2Fx%2Fapp%2Fapp.js&title=LWC%20playground):

```js
export default class extends LightningElement {
  foo = ''
  connectedCallback() {
    console.log(Object.hasOwn(this, 'foo'))
    delete this.foo
    console.log(Object.hasOwn(this, 'foo'))
  }
}
```

You would expect this to log `true` then `false`, but instead it logs `false` then `false`.

There may have been a reason for this design decision, but I'm not sure. @pmdartus or @caridy might know.

**Comment by pmdartus** [comment]
> I suspect it could be because that all properties are now reactive by default, making the former decoration unnecessary for primitives.

You are right this is related to reactivity. To track class fields mutation, the LWC engine attaches a set of getter / setter. This observation is applicable to all the class fields (standard, tracked, and public).

Let's take the following example where `CustomCmp` with a single `foo` class property.

```js
export default class CustomCmp extends LightningElement {
  foo = '';
}
```

The `CustomCmp` component would be interpreted at runtime as:

```js
export default class CustomCmp extends LightningElement {
  _foo = '';
  
  get foo() { 
    // Some mutation tracking logic [...]
    return this._foo; 
  }
  set foo(value) { 
    // Some mutation tracking logic [...]
    this._foo = value; 
  }
}
```

The class field mutation tracking logic can be found [here](https://github.com/salesforce/lwc/blob/ae6f4b2ffd2ba61c8ed1bb6686781fe3750631b9/packages/%40lwc/engine-core/src/framework/observed-fields.ts#L12).

It's important to call out that the LWC engine does some internal manipulation to the component class, which might be surprising to experienced JavaScript developers. According to the JavaScript specification, class fields should be assigned to the class instance itself. This isn't the case for LWC components, where class fields are applied to the prototype. 

This is the reason why in @nolanlawson's [previous example](https://github.com/salesforce/lwc/issues/3353#issuecomment-1435413264),  `Object.hasOwn(this, 'foo')` returns `false` on the first invocation (prior to deleting the property). This is a performance optimization, that we decided to add early on in LWC's development, to avoid the runtime overhead of re-creating those getters and setters on every component instance. That said it is something that we will likely change for LWC to adopt the latest [JavaScript decorator proposal](https://github.com/tc39/proposal-decorators). 

Going back to the original question posted on Stack Exchange:
* the `delete` keyword should work as expected on all JavaScript object
* LWC doesn't some internal mutation to the LWC component class to enable class field properties reactivity with a low runtime overhead
* using the `delete` keyword to remove a property an object is usually a code smell (in LWC but also in any JavaScript code). I would recommend staying away from it.

**Comment by bdovh** [comment]
```
Going back to the original question posted on Stack Exchange:

the delete keyword should work as expected on all JavaScript object
LWC doesn't some internal mutation to the LWC component class to enable class field properties reactivity with a low runtime overhead
using the delete keyword to remove a property an object is usually a code smell (in LWC but also in any JavaScript code). I would recommend staying away from it.
```

This sounds a little bit confusing do me.
@pmdartus ,
when say that `delete` keyword should work as expected, do you mean that it should delete the property and unset its value to `undefined`?
why do you say `LWC doesn't some internal mutation to the LWC component class`? In fact LWC Engine does mutation to LWC component class, like you explained in the previous comments, correct?

Can you provide some article or some documentation that explains why using the delete keyword is a code smell?
I have tried to google it and I have found so far this article
https://dev.to/smeijer/don-t-stop-mutating-3gj7
where it is stated that using `delete` is not a code smell.

I agree with this article in these conclusions:

```
I wish people to stopped banning half the language, simply because they:

find it hard to grasp
think it's prone to bugs
think the new way is better
```

**Comment by pmdartus** [comment]
> when say that `delete` keyword should work as expected, do you mean that it should delete the property and unset its value to `undefined`?

LWC doesn't change the semantics of the `delete` keyword. The `delete` keyword should work according to the specification. The keyword would effectively delete the owned property from the object, not replace it with `undefined`. 

> why do you say `LWC doesn't some internal mutation to the LWC component class`? In fact LWC Engine does mutation to LWC component class, like you explained in the previous comments, correct?

Good catch, it meant to say that it *does* and not *doesn't*. I updated the original comment as well.

> Can you provide some article or some documentation that explains why using the delete keyword is a code smell?

My main concern with the `delete` keyword is the unpredictable aspect it introduces. I fully agree that the usage of the `delete` keyword makes sense in this example shared in the blog post. That said it is a different story if you are considering a more complex system where objects are shared. In this case, I would highly recommend using an immutable approach when possible. When immutability isn't possible, I would recommend setting fields to `undefined` isn't of deleting them.

Performance is also another concern, but only if you are working on a highly performance-sensitive code. The usage of the `delete` keyword (or any other mutation to the internal shape of an object) can negatively impact performance. Here is an interesting [blog post](https://v8.dev/blog/fast-properties) about how properties are implemented in V8.

Don't get me wrong, I don't think the `delete` keyword should be banned from the language. But I think there is a case to be made about object mutations in general in complex and/or performance-sensitive projects.
