### ISSUE TITLE
Salesforce Developers: Component Reference LWC Examples are broken

### ISSUE THREAD

**Issue by lukethacoder** [salesforce/lwc#3499]
### Description

The developers.salesforce.com Component Reference site is not rendering LWC example components. Aura Components look to be rendering without any issues.

https://developer.salesforce.com/docs/component-library/overview/components

#### Steps to Reproduce

- go to [lightning-accordion - example - Salesforce Lightning Component Library](https://developer.salesforce.com/docs/component-library/bundle/lightning-accordion/example) (or any example)

#### Expected Results

LWC Component examples load without errors

#### Actual Results

`TypeError: Failed to fetch` is displayed where the component should be loaded.

Developer console is lit up red. Referencing a dead heroku app api?

![image](https://github.com/salesforce/lwc/assets/13529535/d5c3b55d-462c-4285-910c-18a8f55657fc)

### Browsers Affected

- Chrome: 113.0.5672.93
- Edge: 112.0.1722.64
- Firefox Developer Edition: 114.0b4
- ... presumably all browsers

### Version

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nolanlawson** [comment]
The Component Library team has restored the examples playground. Thank you again for letting us know.
