### ISSUE TITLE
Could "block virtual dom" benefit LWC?

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#3565]
https://million.dev/blog/virtual-dom

**Comment by AllanOricil** [comment]
I forgot lwc uses shadow dom

**Comment by nolanlawson** [comment]
I have not looked deeply into MillionJS, but I think there are two optimizations here that LWC could take advantage of:

1. Static analysis – we already do this (https://github.com/salesforce/lwc/pull/2781). See also [Vue static hoisting](https://vuejs.org/guide/extras/rendering-mechanism.html#static-hoisting) and [Marko static subtrees](https://markojs.com/docs/why-is-marko-fast/#compile-time-optimization-of-static-sub-trees).
2. Dirty checking – AFAICT this is a kind of fine-grained reactivity, i.e. diff the state and then only update subtrees that have changed, not the entire component. We could potentially do this with some kind of compile-time analysis.

In any case, this is worth looking into more deeply, so I'll leave this issue open for now. Thanks for opening!

**Comment by nolanlawson** [comment]
After reflection, I think this is covered by #3624. To implement fine-grained reactivity, we would very likely use a "block vdom" approach or something similar.
