### ISSUE TITLE
LightningElement missing refs definition from types.d.ts

### ISSUE THREAD

**Issue by attilah** [salesforce/lwc#3597]
### Description

Missing `refs` definition in [here](https://github.com/salesforce/lwc/blob/master/packages/lwc/types.d.ts#L178)

#### Steps to Reproduce

N/A

#### Expected Results

IDE and TSC should not give error to `this.refs` in component code.

#### Actual Results

Compiler gives: `TS2339: Property 'refs' does not exist on type 'foo'.` error

### Version

- LWC: 2.50.0

**Possible Solution**

Include `readonly refs: Record<string, HTMLElement>` definition

**Comment by nolanlawson** [comment]
Thanks for opening this issue. This should go away once #2996 is fixed.

**Comment by attilah** [comment]
That's good news, I hope it happens soon!

**Comment by nolanlawson** [comment]
Actually I'm wrong, it won't solve it. We'll have to solve this manually for now.
