### ISSUE TITLE
createContextProvider does not update components when using @lwrjs/router and client-side routing

### ISSUE THREAD

**Issue by jonshipman** [salesforce/lwc#3632]
### Description

When using the `createContextProvider` export from `lwc` and `createRouter` from `@lwrjs/router` the context fails to update subscribers when run with `npm run stage`.

#### Steps to Reproduce

See this sample project here: https://github.com/jonshipman/lwc-context-issue

1. `git clone https://github.com/jonshipman/lwc-context-issue.git`
2. `cd lwc-context-issue`
3. `npm install`
4. `npm run dev`
5. Open `http://localhost:3000` in your web browser

These steps run correctly. You should see the happy bear cooking blocks with a 1 second setInterval running. There should also be a button that will increment from the same context.

6. `npm run stage`
7. Refresh your web browser

When running a build version of the same code, the interval no longer updates the context. The context is unpopulated by the thrown error when clicking the increment button.

`npm run stage`: https://stackblitz.com/edit/salesforce-lwc-gy5yj2
`npm run dev`: https://stackblitz.com/edit/salesforce-lwc-f7fe9v

#### Expected Results
Dev and Build should exhibit the same behavior, they currently do not.

#### Actual Results
When building, setting the context does not update the subscribers.

### Version
 "@lwrjs/app-service": "^0.10.0",
 "@lwrjs/lwc-module-provider": "^0.10.0",
 "@lwrjs/npm-module-provider": "^0.10.0",
 "@lwrjs/router": "^0.10.0",
 "lwc": "3.0.0",
 "lwr": "0.10.0"

**Comment by nolanlawson** [comment]
Thanks for the repro and bug.

To summarize: `npm run dev` works fine, but `npm run stage` reproduces the bug, which indicates that there is some difference between the two that is causing this result.

I'm not sure exactly what's happening, but I do see that the `consumers` Set has size 2 for `npm run dev`, and size 0 for `npm run stage`. So in `stage`, there are no consumers to notify.

![Screenshot 2023-07-18 at 4 05 44 PM](https://github.com/salesforce/lwc/assets/283842/36593e92-9f1c-4504-a468-af329cb57e09)
![Screenshot 2023-07-18 at 4 06 28 PM](https://github.com/salesforce/lwc/assets/283842/2f9efee7-50f8-457d-8340-f9572f63f7ad)

**Comment by jonshipman** [comment]
Another discovery, running `npm run build:prod-compat` does work. Points to a problem with building ESM or scope issue (for example, converting `() => {}` to `function() {}`)

**Comment by khangiskhan** [comment]
@jonshipman the reason this breaks in `prod` mode (bundled ESM) is due to [singletons being bundled](https://developer.salesforce.com/docs/platform/lwr/guide/lwr-configure-project.html) in your code. The fix for this is to exclude that module from bundling via config:

Add this property in your `lwr.config.json`:
```json
"bundleConfig": {
   "exclude": ["app/context"]
}
```

As you astutely observed, this doesn't break in `prod-compat` mode (bundled AMD) because bundling works a bit differently there which avoids the singleton problem.

**Comment by jonshipman** [comment]
Thanks for that @khangiskhan 

Closing the issue.
