### ISSUE TITLE
[CustomElementConstructor] Support slots for top level components

### ISSUE THREAD

**Issue by ccwilson-us-ibm-com** [salesforce/lwc#3639]
**Is your feature request related to a problem? Please describe.**
Hi. This request is in response to this PR: https://github.com/salesforce/lwc/pull/3591

A little background.  I'm on a team at IBM that develops a library of LWC components for other IBM teams to use.  We document our components using Storybook.  You can check it out here: https://carbon-for-salesforce.nnuka7gjzia.us-east.codeengine.appdomain.cloud/?path=/story/getting-started-welcome--page

A number of our components use slots to provide child elements.  Examples include our Accordion, Data Table and Modal components.  And when rendering within Storybook, we render those components as the top level initial component.  The change it that PR breaks our rendering of those components within storybook.  Adding a wrapper component around these would obscure how our component is structured and used including attribute and element names.  We would also be creating wrapper components that are not intended for production and would need to be filtered out of our Salesforce packaging process.

This change breaks our ability to document and allow our users play with our components within Storybook.

**Describe the solution you'd like**
At minimum we'd like to revert the `clearNode(this)` call if there are any child nodes in `buildCustomElementConstructor`.  Or we could also use a flag to allow us to skip that check as mentioned in one of the review comments:  https://github.com/salesforce/lwc/pull/3591#discussion_r1242872317

We would also be curious to know what it would take for 'Using slots on a top level component' to be considered a fully supported feature and would be willing to contribute to the project to make that happen.

**Describe alternatives you've considered**
If this change remains we have the following options:
- Remove the use of slots in our components.  This would be a lot of effort and seems counter-intuitive for a framework based on Web Components/Custom Elements.  We also have a set of users that use the Salesforce Site Builder tool, and removing slots would remove their ability to drag and drop and individually configure a number of components into their pages.
- Dump storybook as our documentation tool. We do not know of a viable alternative documentation tool that also would work properly without the use of slots in the top level element.
- We could try to remain at version 2.50 of LWC, but that would deny us future bug fixes, features.
- We could also setup our project to remove the code discussed here during the packaging and deployment step.  But that is incredibly hacky and not really a viable long term solution

We welcome any other ideas.

**Additional context**
Here are a few additional links to some of our components that use a slot at the top level within our storybook documentation:
https://carbon-for-salesforce.nnuka7gjzia.us-east.codeengine.appdomain.cloud/?path=/story/carbon-components-modal--default
https://carbon-for-salesforce.nnuka7gjzia.us-east.codeengine.appdomain.cloud/?path=/story/carbon-components-progress-indicator--default
https://carbon-for-salesforce.nnuka7gjzia.us-east.codeengine.appdomain.cloud/?path=/story/carbon-components-structured-list--simple
https://carbon-for-salesforce.nnuka7gjzia.us-east.codeengine.appdomain.cloud/?path=/story/carbon-components-accordion--default

Thank you for the consideration.

**Comment by nolanlawson** [comment]
Thanks for opening the issue. To summarize, it sounds like you're asking for slots to work in `CustomElementConstructor` components at the top level. So basically, this would work:

```html
<x-foo>hello world</x-foo>
```

(Today, the `hello world` would be cleared after custom element upgrade.)

Obviously this would only work for native shadow DOM components; light DOM and synthetic shadow use synthetic slots.

So the one thing we _would_ still clear would be declarative shadow DOM (DSD):

```html
<x-foo>
  <template shadowroot="open">hello</template> <!-- cleared upon upgrade -->
</x-foo>
```

This seems reasonable to me, since it's a pretty common use case for custom elements to accept slotted content, whereas DSD is pretty new and mostly used for explicit hydration. @abdulsattar WDYT?

**Comment by nolanlawson** [comment]
And to clarify: do you need this _only_ in the LWC open-source project published on npm, or do you need this working in a Salesforce environment? (I'm not able to view your [GitHub project page](https://github.ibm.com/carbon-for-salesforce/carbon-for-salesforce).)

**Comment by ccwilson-us-ibm-com** [comment]
Just commenting to confirm that: Yes. I am asking for slots to work in `CustomElementConstructor` components at the top level.

Thanks.

**Comment by nolanlawson** [comment]
@ccwilson-us-ibm-com Your Storybook use case is not using synthetic shadow, right? I'm not sure we can support this use case for synthetic shadow components, since they don't use real `<slot>`s.

**Comment by ccwilson-us-ibm-com** [comment]
Confirming; our Storybook use case is **not** using synthetic shadow.
