### ISSUE TITLE
Warn in dev mode for methods/props missing an `@api`

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#3641]
```js
export default class extends LightningElement {
  get foo () { return 'foo' }
}
```

```js
console.log(elm.foo) // undefined
```

This logs `undefined` because the class is missing an `@api` on the `get foo()`. It would be great to have a dev-only warning to provide a hint that the component author has forgotten to add an `@api`.

**Comment by yashpatel1998** [comment]
@nolanlawson Can I grab this issue for fixing?

**Comment by nolanlawson** [comment]
@yashpatel1998 Sure thing! 😀

**Comment by AllanOricil** [comment]
@yashpatel1998 I tried this one because it is in the list I asked https://github.com/salesforce/lwc/issues/3700
