### ISSUE TITLE
lightning-base-component no longer supports synthetic shadow

### ISSUE THREAD

**Issue by DougMidgley** [salesforce/lwc#3646]
#### Steps to Reproduce
When moving from 1.18.6-alpha to 1.18.7-alpha, any styling at page level is not being applied to the components. Looking at the diff - 
https://diff.intrinsic.com/lightning-base-components/1.18.6-alpha/1.18.7-alpha#file-package.json - it seems this is because of a breaking change, but since lightning-base-component is only very vaguely documented it is a little unclear what action can be taken to move to anything above 1.18.6.

I used the following as a base
https://codesandbox.io/s/lwc-standalone-playground-d4nkf 

with the followup updated
`{
  "name": "lwc-standalone-playground",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "node ./src/server.js --ignore ./public",
    "build": "rollup -c",
    "copyAssets": "node scripts/copyAssets.js",
    "postinstall": "yarn copyAssets"
  },
  "dependencies": {
		"@lwc/compiler": "3.1.1",
		"@lwc/engine-dom": "3.1.1",
		"@lwc/eslint-plugin-lwc": "^1.6.3",
		"@lwc/rollup-plugin": "3.1.1",
		"@lwc/synthetic-shadow": "3.1.1",
		"@lwc/wire-service": "3.1.1",
    "@salesforce-ux/design-system": "^2.21.5",
    "express": "4.18.2",
    "lightning-base-components": "1.18.7-alpha",
    "rollup": "3.27.0",
    "rollup-plugin-replace": "2.2.0"
  },
  "license": "MIT",
  "keywords": [],
  "devDependencies": {
    "fs-extra": "^11.1.1"
  }
}
`
#### Expected Results
Buttons are styled

#### Actual Results
Buttons do not get global styling

### Browsers Affected
edge/chrome

### Version
see above

**Possible Solution**
document usage/release notes of lightning-base-components which would at least help understand any issues. 

**Additional context/Screenshots**

**Comment by nolanlawson** [comment]
Thanks for reporting, an internal WI was filed for this: W-13867378

**Comment by Templarian** [comment]
@DougMidgley Are you seeing the same with `1.19.1-alpha` latest?

**Comment by DougMidgley** [comment]
yes, indeed, i tried going down from that until it worked :)

**Comment by Templarian** [comment]
@DougMidgley I just tried with latest `1.19.1-alpha` with `"bootstrap": { "syntheticShadow": true }` with latest LWR init project.

![Image 8-2-23 at 3 06 PM](https://github.com/salesforce/lwc/assets/338885/4f0f4c8f-82ef-4986-91a9-65ae7e20360b)

Please ensure you've configured the correct properties for `lwr.config.json`. In a default new project:

```json
    "routes": [
        {
            "id": "example",
            "path": "/",
            "rootComponent": "example/app",
            "layoutTemplate": "$layoutsDir/index.html",
            "bootstrap": {
                "syntheticShadow": true
            }
        }
    ],
    "assets": [
        ...,
        {
            "alias": "sldsDir",
            "dir": "$rootDir/node_modules/@salesforce-ux/design-system/assets",
            "urlPath": "/slds"
        }
    ]
```

Example `layouts/index.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My LWR App</title>
  <link rel="stylesheet" href="$sldsDir/styles/salesforce-lightning-design-system.min.css" />
</head>
<body>
  <!-- triple braces prevents HTML escaping -->
  {{{body}}} {{{lwr_resources}}}
</body>
</html>
```

**Comment by nolanlawson** [comment]
Closing based on above discussion, please reopen if I've closed in error.
