### ISSUE TITLE
Template compiler fails to inject custom renderer for `lwc:spread`

### ISSUE THREAD

**Issue by ekashida** [salesforce/lwc#3663]
### Description

This should be pretty much the same fix as for [lwc:external](https://github.com/salesforce/lwc/pull/3559). We have logic that excludes custom elements by default so we need to make an exception for `lwc:spread`.

#### Steps to Reproduce

```
<template>
  <foo-bar lwc:spread={values}></foo-bar>
</template>
```

#### Expected Results

Template compiler injects a custom renderer.

#### Actual Results

Template compiler does not inject a custom renderer.

**Comment by nolanlawson** [comment]
Does this apply to `<div lwc:spread={values}>` too?

**Comment by ekashida** [comment]
@nolanlawson after looking into this further, it looks like custom elements using `lwc:spread` are not considered risky. The existing implementation to mark standard elements as risky is correct.
