### ISSUE TITLE
TypeScript Support  - LWC

### ISSUE THREAD

**Issue by SaurabhMulay999** [salesforce/lwc#3699]
I am not sure whether LWC directly or indirectly supports writing typescript in project. And How easy it would be to set up?  

If we setup with TS  is it org agnostic code? It must smoothly work through diff orgs.

**Comment by SaurabhMulay999** [comment]
@nolanlawson Thanks for the confirmation.

**Comment by icukovic** [comment]
@SaurabhMulay999 I know it might not be the answer you want but I suggest using JSDoc for LWCs.

**Comment by SaurabhMulay999** [comment]
@icukovic Thanks, I'll check it once.
