### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#3700]
@nolanlawson is there a really simple issue I could try to fix in order to learn how the project work?

- I want to get better at algorithms
- do something that would grant me some respect
- get better at js

**Comment by jmsjtu** [comment]
Hi @AllanOricil thanks for your interest!  Any of the issues labeled `Up for grabs` are good first issues to start with.

Please also take a look at our [contributioning guide](https://github.com/salesforce/lwc/blob/master/CONTRIBUTING.md) once you're ready to submit a PR.

Here are a few options:
- https://github.com/salesforce/lwc/issues/3641
- https://github.com/salesforce/lwc/issues/3659
- https://github.com/salesforce/lwc/issues/3693
- https://github.com/salesforce/lwc/issues/2869

**Comment by nolanlawson** [comment]
Closing as this is a question and @jmsjtu did a great job answering! And thanks a lot for your interest @AllanOricil 😁
