### ISSUE TITLE
Safari custom element becomes focusable when formAssociated=true

### ISSUE THREAD

**Issue by jmsjtu** [salesforce/lwc#3724]
### Description
There is a [bug](https://bugs.webkit.org/show_bug.cgi?id=261621) in Safari that causes non-focusable custom elements to become focusable when `formAssocaited=true`.

#### Steps to Reproduce

```html
<!DOCTYPE html>
<html>
    <x-foo></x-foo>
    <script>
        customElements.define(
            'x-foo',
            class Foo extends HTMLElement {
                static formAssociated = true;
            }
        );
        const foo = document.querySelector('x-foo');
        foo.focus();
        console.log(document.activeElement);
    </script>
</html>
````

The important bit:

```js
class Foo extends HTMLElement {
    static formAssociated = true;
}
...
foo.focus();
console.log(document.activeElement);
```
In both Chrome and Firefox, `document.activeElement` point to `<body>` while Safari points to `<x-foo>`.

**Comment by AllanOricil** [comment]
@jmsjtu is there a way to tell the browser which custom elements are focusable and which are not?

**Comment by jmsjtu** [comment]
@AllanOricil it's possible to overwrite the `focus` method but we're trying to avoid monkey patching DOM APIs as much as possible.

We don't anticipate this to have a large impact on our users but let's see once the `formAssociated` PR is merged.

The Safari bug also looks like it's been updated a few times, they might fix it before we need to do anything 🤞 .

**Comment by Aakriti1110** [comment]
If you need to set formAssociated=true on a custom element that is not explicitly focusable, you can use 
x-foo {
  pointer-events: none;
}

**Comment by Darcside9** [comment]
What if you remove the `formAssociated` property like this.

```
<!DOCTYPE html>
<html>
    <x-foo></x-foo>
    <script>
        customElements.define(
            'x-foo',
            class Foo extends HTMLElement {
                // Remove the formAssociated property
            }
        );
        const foo = document.querySelector('x-foo');
        foo.focus();
        console.log(document.activeElement);
    </script>
</html>
```

**Comment by nolanlawson** [comment]
This is fixed in Safari Technology Preview, so this issue can be closed.
