### ISSUE TITLE
Unable to create hello world with LWC Open Source

### ISSUE THREAD

**Issue by wimvelzeboer** [salesforce/lwc#3780]
I am trying to get a hello-world going with LWC (open source!!!), to run it as a stand-a-lone webpage/website, so that I can embed it in an existing website (running on Apache + PHP)

I followed this guide: [https://lwc.dev/guide/install](https://lwc.dev/guide/install)

```
npm init lwr        # Follow the on-screen instructions
                    # Select the "Single Page App" project
                    # Select the "LWC" variant
cd YourProjectName
npm install
npm run start      
```
The npm run start, works fine and the "Hello World" page is work at http://localhost:3000

Then I went to the #WebPack section installed the webpack and packages,
```
npm install --save-dev webpack webpack-cli lwc-webpack-plugin lwc @lwc/module-resolver
```
 created the config files, added the demo app, but got the following error when I ran `npx webpack build`:

```
user@work lwr-final]$ npx webpack build
[webpack-cli] Failed to load '/home/user/Projects/lwc/lwr-final/webpack.config.js' config
[webpack-cli] ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/user/Projects/lwc/lwr-final/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/user/Projects/lwc/lwr-final/webpack.config.js:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```
I went through the install guide a number of times with each time a fresh/clean install, but every time the same error. (Running on Fedora linux v38)

Does anyone know what the issue might be?
Am I doing something wrong or is the setup-guide missing a few steps?

[This is a link to the source](https://github.com/wimvelzeboer/lwc-boilerplate-not-working)

**Comment by nolanlawson** [comment]
Using Webpack is actually a totally different setup than using LWR. LWR by itself does not rely on Webpack at all.

If you want to use Webpack, then you would have to configure your project yourself without any scaffolding. The best guide in this case would be the [lwc-webpack-plugin guide](https://github.com/salesforce/lwc-webpack-plugin). For a scaffold, you might start with a "hello world" Webpack app, e.g. [this](https://webpack.js.org/guides/getting-started/).

Sorry you have a bad experience, and sorry that the guides are unclear about this!

**Comment by nolanlawson** [comment]
Out of curiosity, why did you want to use Webpack with LWR? Or were you just trying to use Webpack alone?

**Comment by wimvelzeboer** [comment]
Well, I was trying to see if I could use LWC in a non-Node environment. Like if I can use it on a web-hosting location that runs Apache+PhP+MySQL. 

I thought the Webpack was supposed to be able to convert a Node-package to something that can run in just a browser, without Node-backend.

But then also out of curiosity, for what reason is that Webpack listed on the [setup guide](https://lwc.dev/guide/install) in the first place?
I was following the exact descriptions of the guide, but can't complete it, even though it might have not been something for my use-case...

I will go through that setup-guide you suggested!
