### ISSUE TITLE
`errorCallback` swallows SSR error

### ISSUE THREAD

**Issue by khangiskhan** [salesforce/lwc#3788]
### Description

When SSR (via `renderComponent`) fails to SSR, e.g. due to non-portable code, the error is swallowed if the component contains an `errorCallback`.  Via debugging, I noticed when the error is swallowed, the `errorCallback` is called which is why the error gets swallowed instead of propagated.

It also looks like this only happens when using `<slot>` (see repro below with and without slot).

#### Steps to Reproduce

See https://github.com/salesforce-experience-platform-emu/lwr/compare/khang/repro/lwc_ssr_bug

#### Expected Results

Error is thrown when `renderComponent` fails

#### Actual Results

Error is swallowed

### Version

- LWC: 3.6.0

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nolanlawson** [comment]
Fixed by #3793
