### ISSUE TITLE
Light Dom slots don't trigger `disconnectedCallback` in synthetic lifecycle

### ISSUE THREAD

**Issue by jmsjtu** [salesforce/lwc#3823]
### Description

Now that light DOM slots use fragments (#3649), they don't trigger `disconnectedCallback` when `ENABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE` is not set.

#### Steps to Reproduce

Repro:

https://stackblitz.com/edit/salesforce-lwc-fcxo47?file=src%2Fmain.js

In the above example, the `disconnectedCallback` should be invoked when swapping between the if conditions.

**Comment by nolanlawson** [comment]
Does this affect scoped slots as well? And `lwc:if`/`elseif`/`else`? Those all use VFragments as well.

**Comment by jmsjtu** [comment]
> Does this affect scoped slots as well? And lwc:if/elseif/else? Those all use VFragments as well.

@nolanlawson I did some more investigation related to this question and posted a new issue #3827 

I think we can keep this one scoped to just the Light DOM slots and bring it to parity with the behavior from LWC 3.x.x.
