### ISSUE TITLE
[Post LWC v6] Add friendly error message when ElementInternals is not available due to lower API version

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#3929]
To use ElementInternals, you'll need to be on the latest API version. We should have a friendly error message like "You cannot use `static formAssociated` or `attachInternals` because your `apiVersion` is X and it should be at least Y."

Related: https://github.com/salesforce/lwc/pull/3904

**Comment by jmsjtu** [comment]
Based on @nolanlawson's [comment](https://github.com/salesforce/lwc/pull/4035#discussion_r1516570472), we should consider defaulting the `formAssociated` value to `false` if `useNativeLifecycle` is also `false`.

We should also log a dev warning to let the component author know the issue.

One thing to note is that we apply `formAssociated` on-demand now and the first component to register with the tag name will determine the value.

If it's possible to switch the `useNativeLifecycle` flag at runtime, we may end up in a situation where the `formAssociated` value is `true` on the class but still registers as `false` on the host element.

This might not be a real issue but could be something we want to consider testing.
