### ISSUE TITLE
Preserve comments for Third Party Web Components

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce/lwc#3959]
**Is your feature request related to a problem? Please describe.**
I'm having a look to Third Party Web Components in LWC, and tried with @nolanlawson's [emoji picker](https://github.com/nolanlawson/emoji-picker-element). It didn't work and after digging I think it's because it makes use of HTML comments, and these are removed, I assume by LWC.

I explain below the way I see it, but I'm not familiar about the internal of the framework, so I may just be totally wrong. Hopefully I won't be wasting your time 😅🤞

Code is pretty basic:
```
<template lwc:preserve-comments>
    <!-- My Comment -->
    <lightning-card title="Hello">
        <lightning-button label="New" slot="actions"></lightning-button>
        <p class="slds-p-horizontal_small">
            My Custom Component
            <emoji-picker lwc:external></emoji-picker>
        </p>
        <p slot="footer">Card Footer</p>
    </lightning-card>
</template>
```

On Salesforce side I tried both with a Static Resource with `lightning/platformResourceLoader` and via an LWC Module, both behave the same.
 
**Describe the solution you'd like**
Maybe be able to add a directive to the custom element itself to keep the Third Party's component code untouched:
`<emoji-picker lwc:external lwc:preserve-comments></emoji-picker>`

**Describe alternatives you've considered**
Use another WC that doesn't make use of comments.
I also naively tried to add `template.setAttribute('lwc:preserve-comments', '');` to the component code but of course that doesn't work 😁

**Additional context**
I can see on Salesforce that at some point the template of the WC doesn't have any comment:
<img width="751" alt="salesforce" src="https://github.com/salesforce/lwc/assets/2465122/d5e70bc2-f439-4968-be54-fc1f996ec38e">

While when using the WC directly on a regular HTML page it's there:
<img width="756" alt="oss" src="https://github.com/salesforce/lwc/assets/2465122/ad4447a7-d1e5-47b3-92c6-d7abf4ae5b16">

Adding `lwc:preserve-comments` does change the HTML but not the comments removal (which makes sense that it's not evaluated, but not sure why the comments are also removed from the Third Party WC even with `lwc:external`):
<img width="747" alt="preserve" src="https://github.com/salesforce/lwc/assets/2465122/5e3e26eb-434e-4c6d-8d99-99e8502ebaa9">

**Comment by nolanlawson** [comment]
Thanks for reporting. This is actually an issue with Lightning Web Security and is being internally tracked as W-14748180.

The minimal repro is:

```js
const template = document.createElement('template')
template.innerHTML = '<div><!-- foo --></div>'
console.log(template.content.firstChild.outerHTML)
```

LWS currently strips HTML comments from `<template>`s. This can be confirmed in the [LWS console](https://developer.salesforce.com/docs/component-library/tools/lws-console).

**Comment by ekashida** [comment]
This issue was resolved by @rwaldron (thanks!)
