### ISSUE TITLE
`UpgradableConstructor` should only apply `formAssociated` on-demand and throw in case of conflicts

### ISSUE THREAD

**Issue by jmsjtu** [salesforce/lwc#3983]
### Description
The introduction of `formAssociated` on the `UpgradeableConstructor` in #3695 has introduced unintended observable changes to custom elements.

This is causing the browser to identify LWC components as form-associated elements. This is an issue for components that contain form inputs, as secondary clicks [for labels](https://html.spec.whatwg.org/multipage/forms.html#the-label-element) are now dispatched on the label-associated host element instead of any internal form inputs (e.g., input).

A repro can be found [here](https://codepen.io/nolanlawson-the-selector/pen/mdojvQo).

Click the `label` element ("awesome checkbox" text) to observe the differences in behavior when `formAssociated` is `true` vs `false`.

The checkbox will check when the `label` is clicked with `formAssociated=false` but will not when `formAssociated=true`.

**Comment by nolanlawson** [comment]
New design, which aligns with LWS:

- The first definition of a component (e.g. `<x-foo>`) gets to set the class's `formAssociated`-ness to either `false` or `true`.
- The following definitions are subject to a check:
  - If there is an existing definition for the tag name (e.g. `<x-foo>`) and the existing definition's `formAssociated` value does _not_ equal the new definition's `formAssociated` value, throw an exception with clear explanation.
  - E.g.: `<x-foo> was already registered with formAssociated=true. It cannot be re-registered with formAssociated=false. Please rename your component to have a different name than <x-foo> (link to lwc.dev documentation)`
