### ISSUE TITLE
Normalize whitespace for attributes (breaking change)

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#4124]
For HTML templates containing static `style`/`class` attributes such as this:

```html
<div class=" foo bar     baz "></div>
<div style=" color  :  red ! important  "></div>
```

... we are inconsistent about how this is actually serialized to the DOM. For static-optimized nodes, the attributes are kept as-is. For non-static-optimized nodes, the whitespace/semicolons are normalized:

```html
<div class="foo bar baz"></div>
<div style="color: red !important;"></div>
```

This also applies to the case of blank vs missing attributes. For example:

```html
<div class=""></div>
<div style=" "></div>
```

In the static-optimized case, these attributes are kept as-is. For the non-static-optimized case, the attributes are removed entirely:

```html
<div></div>
<div></div>
```

This doesn't _really_ matter unless the developer is doing something zany (e.g. `querySelector('[class="foo bar baz"]')` rather than `querySelector('.foo.bar.baz')`), but we should at least be consistent about it.

We have also [warned developers](https://developer.salesforce.com/docs/platform/lwc/guide/create-components-css-antipatterns.html#anti-pattern-queryselector-with-exact-attribute-string-match) about this in the past, but not every developer follows these guidelines.

This would be a potentially breaking change.

**Comment by HermanBide** [comment]
can i work on this ?

**Comment by nolanlawson** [comment]
@HermanBide I would recommend against taking this one, since it is a breaking change and so we will have to be careful about it.
