### ISSUE TITLE
Lightning datatable admits only 100 records (or something lower than 150, idk)

### ISSUE THREAD

**Issue by davidf9265** [salesforce/lwc#4206]
### Description
I've been trying to load more than 100 records with the component, but the component crashes if i try it on load and stays loading forever if I try the infinite scroll feature

#### Steps to Reproduce
Create a LWC datatable component.
Try to use it with more than 100 records.

https://playground.lwc.dev

```js
const your => (code) => here;
```

### Version

-   LWC: x.x.x

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ekashida** [comment]
@davidf9265 This is an issue with Lightning Base Components and not the LWC framework (different teams). To resolve your issue, I recommend opening a [Salesforce Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) question or a [Salesforce case](https://help.salesforce.com/s/).

**Comment by davidf9265** [comment]
@ekashida Thanks, i will close this issue then and try addressing it there.
