### ISSUE TITLE
Version mismatch warning should warn for patch version differences as well

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#4211]
Here:

https://github.com/salesforce/lwc/blob/c7bd1b76051b1b117ca341945cd4e59993b177e9/packages/%40lwc/engine-core/src/framework/check-version-mismatch.ts#L43-L44

We check if the LWC compiler major/minor version differs from the engine major/minor version. Really we should just check if the versions are exactly the same or not, since we are just following basic semver from now on and make no guarantees about ABI compatibility between the engine and compiler for different versions.

**Comment by SaurabhMulay999** [comment]
Hey @nolanlawson ,
 I have raised a PR for this issue.

**Comment by nolanlawson** [comment]
Fixed by https://github.com/salesforce/lwc/pull/4216
