### ISSUE TITLE
Hydration validation incorrectly fails for statically optimized content

### ISSUE THREAD

**Issue by jmsjtu** [salesforce/lwc#4270]
### Description

Statically optimized content fails [hydration validation](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine-core/src/framework/hydration.ts#L828-L830) when static and dynamic attributes are mixed on the same element.

#### Steps to Reproduce

```html
<template lwc:render-mode="light">
    <div class="wrapper" style={computedWrapperStyle}>
    </div>
</template>
```

The above will fail hydration validation because each static part always validates the attributes, styles and class names against the element.

Since `class` is static it will be assigned when the fragment is created by the browser and does not have an associated static part.

#### Expected Results

Hydration validation should not fail.

#### Actual Results

Hydration validation failing.

**Possible Solution**

We should opt out of validating against `style` or `class` if it's not present on the static part. 

The purpose of the hydration validation is to ensure that hydration occurred successfully, in this case hydration does not occur for the static values.

**Comment by HermanBide** [comment]
has this issue been fixed if not can i try to work on it?

**Comment by jmsjtu** [comment]
@HermanBide thanks for your interest! 

We're already working on a fix that should be ready later today.

If you'd like to contribute, we have other issues under the ["Up for grabs"](https://github.com/salesforce/lwc/labels/Up%20for%20grabs) label.
