### ISSUE TITLE
Ignore hydration mismatches during SSR rendering as well as `connectedCallback`

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#4500]
As of https://github.com/salesforce/lwc/pull/4358, `validationOptOut` is now a no-op and we attempt to detect host mutations during SSR `connectedCallback`.

Unfortunately this doesn't cover the case of host mutation during normal rendering, e.g. via a getter/setter:

```html
<template>
  <div title={title}></div>
</template>
```

```js
get title() {
  this.classList.add('titled')
  return 'foo'
}
```

The most common case for this is setter rather than getters (e.g. a parent passing a prop in to a child), but either setters or getters can be invoked during SSR rendering (`renderedCallback` cannot). You could also do this in `render()`.

Arguably we should detect such host mutations and append the `data-lwc-host-mutated` attribute in that case as well, and then ignore hydration mismatches.

**Comment by jhefferman-sfdc** [comment]
Related GUS bug: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001zWGceYAG/view

**Comment by nolanlawson** [comment]
It occurred to me that this might not cover the case of one component manipulating another one's host during rendering... perhaps the simpler solution to this problem is to just bring back `validationOptOut` and make it not a no-op anymore.

So basically if you mutate during `connectedCallback`, then it's automatically ignored, but otherwise you would need to add `validationOptOut` like we required before.
