### ISSUE TITLE
Add ability to hide date format and help text element shown inline beneath the lightning-input field

### ISSUE THREAD

**Issue by Paul-Kalynyn** [salesforce/lwc#4512]
**Is your feature request related to a problem? Please describe.**
It breaks existing UI for LWCs with layout that have aligned input items to bottom. So, with Winter 25, Datepickers now aligned higher, then other inputs.
![image](https://github.com/user-attachments/assets/c16ace29-880a-4488-8576-b635809d52b9)
Additionally, I have noticed that other input elements like combobox also have this unexpected margin at the bottom
![image](https://github.com/user-attachments/assets/2bbeb968-41c0-4128-a9f4-e67a7b5678ce)
**Describe the solution you'd like**
Add attribute for `lightning-input` and `lightning-combobox` that will allow to hide this text under Datepicker. Similar to existing attribute `variant` with `label-hidden` value.

**Comment by nolanlawson** [comment]
This appears to be an issue with the Lightning Base Components. This repo is for the open-source Lightning Web Components framework only.

To resolve your issue, I would recommend opening a [Salesforce Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) question or a [Salesforce case](https://help.salesforce.com/s/).

**Comment by Templarian** [comment]
A fix is rolling out in `252.7` to only show this formatting text message when the date field is focused.

@Paul-Kalynyn For the UX in the screenshot the elements are aligned to the bottom. Instead align to the top and add spacing/padding above. The extra space below inputs in general should also be fixed shortly also.

@nolanlawson We can close this issue as these will be addressed before R1 (release when boxes begin migrating to the new release).
