### ISSUE TITLE
SecureWindow instance does not support opening blob files?

### ISSUE THREAD

**Issue by SourabhMulay** [salesforce/lwc#4608]
I'm encountering an error that states: "SecureWindow.open supports http:, https:, mailto: schemes, and relative URLs."

I attempted to create a Blob instance with the type "octet-stream" and open it using window.open(URI), but this resulted in the aforementioned error. I suspect that the restrictions imposed by Lightning Locker and strict Content Security Policies (CSP) are preventing the use of Blobs. Is there any way to disable the Locker Service without compromising the code API versions?

In current repo which code contribute functionality of lightning locker? Just wanted to know more about it!!

**Comment by nolanlawson** [comment]
Hi, this looks like an issue in Locker Service / Lightning Web Security. Could you please confirm whether you have Lightning Web Security enabled or not?

Also I would recommend opening a [Salesforce Stack Exchange](https://salesforce.stackexchange.com/questions/tagged/lightning-web-components) question or a [Salesforce case](https://help.salesforce.com/s/). In this repo, we can only resolve issues with the LWC open-source JavaScript framework.

**Comment by SourabhMulay** [comment]
Web security has enabled already! But, No Problem @nolanlawson! For now you can mark this as close. I will investigate further on it! If i found any abnormal behaviour I will let you know via comments.
