### ISSUE TITLE
[SSR] default-export the `generateMarkup` function

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#4719]
To render a component using `engine-server`, you do:

```js
import { renderComponent } from '@lwc/engine-server'
import Component from 'x/component'

renderComponent('x-cmp', Component, props)
```

Whereas in `ssr-runtime`, you do:

```js
import { renderComponent } from '@lwc/ssr-runtime'
import { generateMarkup } from 'x/component' // <-- This is different

renderComponent('x-cmp', generateMarkup, props)
```

The reason you have to import the `generateMarkup` function is because the exports of an SSR-compiled component look like this:

```js
class DefaultComponentName extends LightningElement {}
async function* generateMarkup(tagName, props, attrs, slotted) { /* ... */ }
const tagName = 'x-cmp'

export { DefaultComponentName as default, generateMarkup, tagName };
```

This is awkward for a few reasons:

- You have to import different things using `engine-server` vs `ssr-runtime`
- The `DefaultComponentName` above is essentially useless for consumers of the component. It doesn't make much sense to export it as `default`.

Instead, we should not export the component constructor at all, and should make `generateMarkup` the `default`. Bonus points if we somehow make `generateMarkup` opaque, since consumers aren't expected to call it directly.

**Comment by nolanlawson** [comment]
FYI @lpomerleau

**Comment by lpomerleau** [comment]
So the default export will no longer be the `LightningElement`? This is an abridged version of what we have right now, since we'll be supporting both versions of the SSR API for a few releases using a "gate":

```
// get a versioned specifier for the LWC runtime/engine
const engineServerSpecifier = getSpecifier({
    specifier: getFeatureFlags().SSR_COMPILER_ENABLED ? '@lwc/ssr-runtime' : '@lwc/engine-server',
    version: lwcVersion,
});

// loader.load returns { specifier: string; module: the LWC-compiled module }
const lwcEngine = await loader.load(engineServerSpecifier);
const component = await loader.load(cmpSpecifier);

 const html = getFeatureFlags().SSR_COMPILER_ENABLED
    ? await engine.renderComponent(
        elementName,
        component.module.generateMarkup,
        props,
        'sync',
    )
: engine.renderComponent(elementName, component.module.default, props);
```

So instead of `component.module.generateMarkup` we'll use `component.module.default`. 

This is a long-winded way of saying that since we already have a handle on the component's module, we have flexibility.

**Comment by nolanlawson** [comment]
@lpomerleau Right, you'll have to change line 14 to use `default` instead.

Hopefully this won't be a huge breaking change. For us, this would vastly simplify the benchmark code, which is why I was looking into this.

**Comment by nolanlawson** [comment]
I mean, we could _also_ still export `generateMarkup` while also exporting it as `default`. Looks like you're not using the `default` export anyway.

**Comment by lpomerleau** [comment]
> For us, this would vastly simplify the benchmark code, which is why I was looking into this.

Go for it and make changes now before all the API shapes are locked in and the gate is turned on.
