### ISSUE TITLE
[SSR v2] Consolidate mechanisms that validate identifier/field names

### ISSUE THREAD

**Issue by divmain** [salesforce/lwc#4826]
The new SSR compiler includes an [`isValidIdentifier`](https://github.com/salesforce/lwc/blob/0aa8026c0843adf5480ba5cef87ce8cbb481a7f3/packages/@lwc/ssr-compiler/src/shared.ts#L73) helper function, which determines whether a given string is a valid JavaScript identifier. However, there exists something similar in [`babel-plugin-component`](https://github.com/salesforce/lwc/blob/4845840a8f11a0f0334a7fb50dd82b4f7c2cbe22/packages/%40lwc/babel-plugin-component/src/decorators/wire/transform.ts#L61-L63). These should probably be consolidated onto the `babel-plugin-component` implementation for backwards compatibility reasons.

**Comment by nolanlawson** [comment]
[Details here](https://github.com/salesforce/lwc/pull/4807#discussion_r1835128698)
