### ISSUE TITLE
[SSR v2] add support for wire-decorated getters

### ISSUE THREAD

**Issue by divmain** [salesforce/lwc#4828]
See [this thread](https://github.com/salesforce/lwc/pull/4807#discussion_r1835165390). #4807 included support for wire-decorated getter/setter combos, wire-decorated methods, and wire-decorated properties. However, it does not include explicit support or tests for wire-decorated getters as seen here:

https://github.com/salesforce/lwc/blob/4845840a8f11a0f0334a7fb50dd82b4f7c2cbe22/packages/%40lwc/integration-types/src/decorators/wire.ts#L235-L239

This needs to be addressed in a follow-up PR.

**Comment by nolanlawson** [comment]
Closed by #4986
