### ISSUE TITLE
Create a lwc-types package with common interfaces (.d.ts)

### ISSUE THREAD

**Issue by apapko** [salesforce/lwc#503]
**Purpose:** minimize redundancy and standardize common types by creating a shared lwc-types package

**Existing Issue:**  some type definitions are consumed across multiple packages. For example, types like Location can be found in open source compiler,  platform compiler, babel-plugin-transform-lwc-class, and more. To minimize the redundancy of the type definitions and to standardize the interface across dependant packages, we should create a separate lwc-types package which will contain the common types.

Here is a great example of a bad _type_ usage from a dependent project that could benefit from the shared lwc-types packages - [link](https://git.soma.salesforce.com/lwc/lwc-platform/blob/master/packages/sfdc-lwc-compiler/src/compile.ts#L7
 ). 

We can be more granular and create more specialized types, like @lwc-types/compiler

**Comment by caridy** [comment]
@apapko I don't think this is needed anymore... can you confirm?

**Comment by apapko** [comment]
Yes, this can be closed now.
