### ISSUE TITLE
Engine should warn when using firstChild or lastChild on the shadowRoot

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#518]
**Is your feature request related to a problem? Please describe.**

The shadowRoot today exposes the both `firstChild` and `lastChild` properties. We reserve ourselves the right to add HTML elements that are not defined in the template. For example, when native shadow DOM is enabled each component with a stylesheet will inject a style tag in their shadow tree.

We need to communicate to the developers that `firstChild` and `lastChild` might not be the expected element.

**Describe the solution you'd like**

Option 1 - Disallowed of `firstChild` and `lastChild` properties from shadowRoot.
* 👍 Simple
* 👎 Too strict? (What would be a valid use case for accessing `firstChild` or `lastChild`?)

Option 2 - Add a warning in dev mode.
* 👍 Flexible
* 👎 Console logs get polluted with warnings (What would be a valid use case for accessing `firstChild` or `lastChild`?)
* 👎 No way to disable the warning

Option 3 - Add a section in the documentation to explain the behavior of `firstChild` and `lastChild`.
* 👍 Non-intrusive
* 👎 Developer need to read the doc

Until someone comes with a valid use case for `firstChild` and `lastChild`, I would favor option 1

**Comment by caridy** [comment]
@ekashida can you confirm that this error is now removed and this can be closed?

**Comment by ekashida** [comment]
@caridy I believe this issue is about potentially adding an error message to warn the user that the first/last child might not be what they have in their template.

**Comment by caridy** [comment]
yes, but we realized that this is not very important because they should just simply not rely on that ever.

**Comment by ekashida** [comment]
Given that I don't think any error was ever implemented (after checking 220) I'm closing this issue.
