### ISSUE TITLE
Improve version bump and package release flow

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#523]
The release flow has been greatly overlooked, there is today a lot of things that can go wrong when running `yarn release`. This issue contains a list of the things that we can improve to make the release flow more robust:

* The release script should update the local `peerDependencies` versions to avoid version mismatch after a minor release.
* The release script should ensure that the local repository doesn't contain uncommitted changes in git.
* The release script should do a full clean and build (today only build) before publishing the package. This would prevent the release of old generated artifacts.
* The release script should be able to bump the version and update the changelog in a single commit. Today we are doing it in 2 commits (db0276ea9380d52859aacbcbdc075e1a5e7338fa, be91d20d97ab828b6ec906e245d44566e0fbe5d7).

**Comment by caridy** [comment]
@diervo I think the work you did solved most of the problems here. Can you confirm and close this? @ekashida can you also confirm?

**Comment by ekashida** [comment]
We've been using a combination of lerna and CI for our releases for a while now.
