### ISSUE TITLE
Publish typescript declaration (.d.ts) files for lwc-wire-service

### ISSUE THREAD

**Issue by wpeter-sfdc** [salesforce/lwc#607]
**Is your feature request related to a problem? Please describe.**
I am writing a typescript library consuming the lwc-wire-service and it would be nice if the lwc-wire-service package included the declaration files.

**Describe the solution you'd like**
Include the .d.ts files in the lwc-wire-service package.

**Describe alternatives you've considered**
Uhh, not having typings is one alternative, but a world without types is no world for me.

**Additional context**

**Comment by caridy** [comment]
This is now in place. All `@lwc` packages have the `types/` folder.
