### ISSUE TITLE
[alignment with standards] refactor AOM properties to be surfaced via ElementInternals

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#717]
### Description

Today, we are exposing AOM properties via `this.template`, this is changing in the spec, and it now will be exposed via `createdCallback`, who receives an argument `internals` (instance of `ElementInternals`). Changes are fairly simple in LWC, but there are some users using AOM properties from template that might get affected by this. Maybe we can keep both references for now, until this settles after 218.

Additionally, the introduction of the new hook is also important, which means that they now have the ability to do things right after the constructor finishes. I'm not entirely sure about the semantics of this hook.

**Comment by nolanlawson** [comment]
@caridy What is left to do here? Is this just about implementing `attachInternals()` and the various [FACE callbacks](https://web.dev/more-capable-form-controls/#lifecycle-callbacks) now?

Related: https://github.com/salesforce/lwc/issues/3000

**Comment by nolanlawson** [comment]
Related: https://github.com/salesforce/lwc/issues/1023
