### ISSUE TITLE
querySelector() on slot element should return null to match native shadow dom behavior

### ISSUE THREAD

**Issue by ravijayaramappa** [salesforce/lwc#766]
### Description
Calling querySelector() and querySelectorAll() on a <slot> element should not return any nodes. assignedNodes() should be the only way to get to the slot content.

#### Steps to Reproduce
https://playground.lwcjs.org/projects/6SzgOH86p/4/edit

```xml
<!-- x-parent -->
<template>
    <c-child>
        <span slot='my-slot'>
            Non-Default Named Slot Text
        </span>
        <div slot='my-slot'></div>
        <div slot='my-slot'></div>
        <div slot='my-slot'></div>
    </c-child>
</template>
```

```xml
<!-- c-child -->
<template>
        <slot class='named-slot' name='my-slot'>
        </slot>
        <button onclick={clickHandler}>Query for slot content</button>
</template>

import { LightningElement } from 'lwc';
export default class Child extends LightningElement {
    // Compare this behavior with native shadow dom https://code.sololearn.com/WcfmdS96rnTj/#js
    clickHandler() {
        let secureSlotElement = this.template.querySelector('.named-slot');
        secureSlotElement.assignedNodes(); // returns span and 3 divs
        secureSlotElement.querySelectorAll('div'); // returns 3 divs, expecting empty nodelist
        secureSlotElement.querySelector('div'); // returns a div, expecting null
    }
}
```

#### Expected Results
querySelector() should return null and querySelectorAll should return an empty nodelist
Try the same scenario in native shadow dom: https://code.sololearn.com/WcfmdS96rnTj/#js

### Version
- LWC: 0.30.2

**Comment by AllanOricil** [comment]
@caridy 

Without being able to access the slot elements, I can't create a dynamic component for dragging and drop. I want to be able to iterate over all the elements of a slot and add css classes and drag and drop event listeners to these elements.

//wrapper to show the way I want to make a list of something that all items on it should be draggable.
````html
<c-drag-n-drop>
        <template for:each={_entries} for:item="entry" for:index="entryIndex">
            <anything-to-be-draggable key={entryIndex}></anything-to-be-draggable>
        </template>
</c-drag-n-drop>
````

//c-drag-n-drop
````html
<template>
    <div class={containerClass}>
        <slot></slot>
    </div>
</template>
````
