### ISSUE TITLE
swapping rows in lightning-datatable invoke render twice for the row goes down

### ISSUE THREAD

**Issue by reiniergs** [salesforce/lwc#803]
### Description
When we swap two rows in lightning datatable is invoke the render of the row is being move down, the second time the render is called props have the previous values. I assume is trying to reuse the same node.

#### Steps to reproduce in the playground
https://playground.lwcjs.org/projects/iJaIlF27S/4/edit

#### Steps to Reproduce in lgc
1. In lightning components repo start the standalone app by running `yarn app:start` inside of ui-lightning-suite folder
2. in https://github.com/salesforce/lightning-components/blob/master/ui-lightning-suite/src/main/modules/demo/app/app.html file insert 
```html
<demo-datatable-app-ex-example></demo-datatable-app-ex-example>
```
after line 4
3. click in the down arrow that swap the first column with the second column

You are going to see the second row keep the up arrow disabled even if we update the data to make the arrow enable after the swap
![bug-swap](https://user-images.githubusercontent.com/3241179/48032320-08e6ca00-e10c-11e8-9e63-717c31092aa3.gif)

**Comment by wimvanerp** [comment]
I am not able to see the playground or the code in github, could you tell me how this demo-datatable-app-ex-example exactly looks like? I am making something similar.
