### ISSUE TITLE
lwc:dom="manual" sets shadowToken attribute twice

### ISSUE THREAD

**Issue by davidturissini** [salesforce/lwc#873]
### Description

When using `lwc:dom="manual"`, the engine attempts to set the css token twice because the mutation observer fires its callback for the first time the css token attribute is set. Nothing is broken, but is perhaps a gap we want to close

**Comment by caridy** [comment]
@ravijayaramappa can you close this?

**Comment by ravijayaramappa** [comment]
Verified that [shadow token](https://github.com/salesforce/lwc/blob/master/packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-token.ts#L15-L17) is set only once per node.
