### ISSUE TITLE
Incorrect Compat sourcemaps

### ISSUE THREAD

**Issue by jodarove** [salesforce/lwc#883]
### Description
Sourcemaps for compat compilated code is incorrect, this is due a bug on rollup/babel (https://github.com/rollup/rollup/issues/2592)

Basically when you have 2 rollup plugins (lwc and compat in our case) and each one does a babel transformation. despite each partial sourcemaps being correct, the whole transformation sourcemap is shifted. 

#### Steps to Reproduce

generate sourcemaps for compat in a rollup config, similar to:

```js
module.exports = {
    external: function(id) {
        return id in globalModules;
    },
    input: path.resolve('src/main/lwc-app-main.js'),
    output: {
        sourcemap: true,
        file: path.resolve('build/lwc-app/main.js'),
        format: 'iife',
        globals: globalModules,
    },
    plugins: [
        // ...
        lwcCompiler({
            mode,
            mapNamespaceFromPath: true,
            resolveFromPackages: true,
            sourcemap: true,
        }),
        isCompat && rollupCompatPlugin({ polyfills: false, downgrade: false, sourcemap: true }),
        // ...
    ],
};
```
Once you open it in the browser, with sourcemaps enabled, you will notice that for compat, the sourcemaps are shifted.

#### Expected Results
Correct sourcemaps, like the generated for es2017.

#### Actual Results
Incorrect sourcemaps for compat compiled code.

### Browsers Affected
ie11.

**Comment by nolanlawson** [comment]
Compat mode will be removed eventually, so closing this as not planned
