### ISSUE TITLE
Component with unnamed slot unable to find elements inside slot of slotted component

### ISSUE THREAD

**Issue by saw** [salesforce/lwc#901]
### Description

If a component has an unnamed slot, and a second component with an unnamed slot is slotted inside it, querySelector/querySelectorAll are unable to find elements inside the slotted component's slot

#### Steps to Reproduce

https://playground.lwcjs.org/projects/9wDHj3gDp/11/edit

#### Expected Results

All elements matching the query are found, even if they are in the slots of slotted elements

#### Actual Results
only elements inside the slot, not the slots of slotted components are returned

### Browsers Affected

All

### Version

- LWC: 0.33.25

**Comment by dancolq** [comment]
There seems to be an issue when an the slotted component is re-rendered i.e. closed and opened up again.  The querySelectorAll picks the previous closed version of the component.  I confirmed this by generating a random number attribute on the slotted lwc component type,   I open up the container component and copy the random number generated by the slotted lwc cmp.  I close the component (i.e. cancel button) and repopen a new slotted item with a new random number is generated (renderd in the UI).   However if I call this.querySelectorAll(), it returns the original 'closed/destroyed' slotted lwc which is confirmed by reading the random number that was generated against it.

**Comment by ekashida** [comment]
@dancolq Do you mind creating a repro case for us using the [playground](https://developer.salesforce.com/docs/component-library/tools/playground)?

**Comment by dancolq** [comment]
> @dancolq Do you mind creating a repro case for us using the [playground](https://developer.salesforce.com/docs/component-library/tools/playground)?

Yes - I will create a scratch org ASAP, however I need to circumvent using - this.template.querySelector, this.template.querySelectorAll,  this.querySelector and this.querySelectorAll  as it they are picking up components that should have been previously destroyed from an earlier access via QuickAction, or Tab within an Aura Cmp Wrapper.   When I applied my fix,  I will create a SF scratch org that demonstrates this issue as the playground cannot in act the 'destroying' .   The only way I can think of fixing this issue communicating via the messageChannel,
