### ISSUE TITLE
Rendering raw HTML

### ISSUE THREAD

**Issue by priandsf** [salesforce/lwc#909]
SSR
Provide a way to render inner HTML in the component template, similar to React dangerouslySetInnerHTML. As of today, rendering HTML requires some DOM manipulation in renderedCallback, which might not be enabled for SSR.
It is up to the developer to sanitize the JS before injecting it.

**Comment by nolanlawson** [comment]
We have the `lwc:inner-html` directive now. https://lwc.dev/guide/reference#lwc%3Ainner-html%3D%7Bhtmlcontent%7D
