### ISSUE TITLE
Provide a SSR version of the lwc-engine

### ISSUE THREAD

**Issue by priandsf** [salesforce/lwc#910]
SSR
We need a version of the engine that is specific to SSR (lwc-engine-ssr). In particular, it should execute the component lifecycle from its creation to its rendering (asynchronous), being as close as possible from the browser one. Ideally, the exact same features and APIs should be available. Some pieces of the existing client engine, like the LightningComponent class, should be isolated and shared by the two engines.
The rendering engine should also be extensible so a rendering cache can be provided . For example, the markup and the data for a product tile component can be cached, thus avoiding the same rendering over and over for the same data.

**Comment by nolanlawson** [comment]
This is fixed; we have `@lwc/engine-server` now.
