### ISSUE TITLE
Compiler is omitting comments in templates

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#927]
### Description

One of the premises of the template in LWC is that what you see in the template is what you get in the DOM. That invariant does not hold true in part because regular html comments are completely ignored in the compiler as today, even though the engine supports them just fine via `api.p()`.

In a conversation with @diervo yesterday, we debated whether or not that should be the case, and we both agree that comments should be placed because it preserves the `childNodes` order, and other things that are important from the DX perspective.

We also debated whether or not in production it should have an empty comment or the real comment, and we both agree that since this value cannot be defined dynamically, it should be fine to have the real comment.

In the past, we have issues in Aura with the comments being wiped out, and people complaining about it.

**Comment by Bartheleway** [comment]
Comments in the production code is completely useless:
- Make the code heavier for no feature => performance impact
- Can provide spoiler about future feature
- Can help attacker to penetrate the code

For all those reasons I think comments should be stripped from production code. Probably not in debug mode though.

Relying on `childNodes` doesn't feel right in my mind, what use case does it serve ?

**Comment by ekashida** [comment]
Support for template comments was added in #2263
