### ISSUE TITLE
Elements insert manually in lwc:dom="manual" are not patched with synthetic shadow polyfill

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#971]
#### Steps to Reproduce

Node inserted manually in elements `lwc:dom="manual"` are not patched with the synthetic shadow polyfill. For example the `Node.getRootNode()` always return the `document` instead of the `ShadowRoot`

### Version
- LWC: 0.35.1

**Comment by caridy** [comment]
@ravijayaramappa I think this is covered by the mutation observer on portal elements, can you close this?

**Comment by ravijayaramappa** [comment]
Yea, moving the polyfill to global patch has fixed this issue.
https://playground.lwcjs.org/projects/S3BQ53clR/4/edit
