### ISSUE TITLE
ShadowRoot.delegatesFocus is not supported across browsers

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#985]
### Description

Gecko is the only engine that doesn't implement `delegatesFocus` on `ShadowRoot`. This property needs to be polyfilled if is not present when the native shadow is turned on.

```js
const elm = createElement('x-test', { is: Test, fallback: false });
document.body.appendChild(elm);

console.log('delegatesFocus' in elm.shadowRoot)
// Actual: false
// Expected: true
```

### Browsers Affected
- Firefox 64

### Version
- LWC: 0.35.4

**Comment by ekashida** [comment]
Updated this issue to reflect that fact that Webkit now implements delegatesFocus.

**Comment by nolanlawson** [comment]
[Tracking bug for Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1413836)

**Comment by nolanlawson** [comment]
`delegatesFocus` is now implemented in Firefox 94: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/94#dom

**Comment by nolanlawson** [comment]
[Safari doesn't support this until v15](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus#browser_compatibility) and SauceLabs still has v14 as the "latest" Safari, so reopening this issue for now.

**Comment by nolanlawson** [comment]
SauceLabs now has Safari v15, and delegatesFocus has [wide browser support](https://caniuse.com/mdn-api_shadowroot_delegatesfocus). I'd say we close this.
