### ISSUE TITLE
Node.isConnected return false on Nodes in shadow tree on IE11

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#987]
### Description

`Node.isConnected` returns `false` instead of `true` on IE11 for Nodes part of the shadow tree.

```js
const elm = createElement('x-test', { is: Test });
document.body.appendChild(elm);

expect(elm.shadowRoot.querySelector('div').isConnected).toBe(true);
// Actual: false (IE11)
// Expected: true
```

### Browsers Affected
- IE11

### Version
- LWC: 0.35.4

**Comment by caridy** [comment]
@ravijayaramappa I think you were working on the polyfill for `isConnected` as part of the node-reactions. Can you confirm, and get this one fixed?

**Comment by caridy** [comment]
this is in fact a duplicate of https://github.com/salesforce/lwc/issues/1029, which shows the polyfill code as well.
