### ISSUE TITLE
Missing setter for innerHTML and outerHTML on various interfaces

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#991]
### Description

While the engine is patching most of the Nodes with `innerHTML` and `outerHTML` getters. Setters are missing on some of them. When invoking the setter instead of throwing an error with an explicit message, it throws a `TypeError` with the following error message:

```
Cannot set property innerHTML of [object ShadowRoot] which has only a getter
```

It would be nice if the engine could throw an error with the following message.

```
Invalid attempt to set innerHTML on ShadowRoot.
```

The following properties don't have a setter associated with a getter:
- `ShadowRoot.innerHTML`
- `<Host Element>.outerHTML`
- ~`ShadoRoot.outerHTML`~
- `<Element in Shadow Tree>.outerHTML`

### Version
- LWC: 0.35.4

----

### Edit

`outerHTML` is not implemented by `ShadowRoot`.

**Comment by caridy** [comment]
validated.
